### ISSUE TITLE
Bluetooth does not allow search or setup including pairing [Solved]

### ISSUE THREAD

**Issue by beardedragon2** [blueman-project/blueman#1000]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.  Also see:
https://forum.manjaro.org/t/testing-update-2019-03-27-kernels-gnome-libreoffice-mesa-budgie-browsers-qt/80693/50?u=beardedragon

[bob@Manjaro-Stable ~]$ blueman-applet --loglevel debug
blueman-applet version 2.0.8 starting
Stale PID, overwriting
_________
Load (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:60)
['DiscvManager', 'StandardItems', 'ExitItem', 'PowerManager', 'AuthAgent', 'GameControllerWakelock', 'PPPSupport', 'ShowConnected', 'NetUsage', 'Headset', 'TransferService', 'DhcpClient', 'SerialManager', 'KillSwitch', 'DBusService', 'Networking', 'RecentConns', 'StatusIcon', 'Menu', 'NMDUNSupport', 'NMPANSupport', 'AppIndicator'] 
_________
get_interface_version (/usr/lib/python3.7/site-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 5 
_________
Load (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:60)
Unable to load plugin module AppIndicator
cannot import name AppIndicator3, introspection typelib not found 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Menu.Menu'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'> 
_________
update_menuitems (/usr/lib/python3.7/site-packages/blueman/plugins/applet/DiscvManager.py:123)
warning: Adapter is None 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ExitItem.ExitItem'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DBusService.DBusService'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
Not loading PPPSupport because it's conflict has higher priority 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Headset.Headset'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.TransferService.TransferService'> 
_________
get_interface_version (/usr/lib/python3.7/site-packages/blueman/bluez/obex/Base.py:20)
Detected BlueZ integrated obexd 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
Not loading DhcpClient because it's conflict has higher priority 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Networking.Networking'> 
_________
load_nap_settings (/usr/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py:36)
Loading NAP settings 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NMPANSupport.NMPANSupport'> 
_________
io_event (/usr/lib/python3.7/site-packages/blueman/plugins/applet/KillSwitch.py:71)
killswitch registered 0 
_________
io_event (/usr/lib/python3.7/site-packages/blueman/plugins/applet/KillSwitch.py:71)
State: True 
_________
UpdatePowerState (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:159)
off False 
foff False 
on True 
current state True 
new state True 
_________
_on_obex_owner_changed (/usr/lib/python3.7/site-packages/blueman/plugins/applet/TransferService.py:172)
obex owner changed: :1.41 
_________
on_dbus_name_owner_change (/usr/bin/blueman-applet:95)
org.bluez owner changed to :1.2 
_________
update_menuitems (/usr/lib/python3.7/site-packages/blueman/plugins/applet/DiscvManager.py:123)
warning: Adapter is None 
_________
set_nap (/usr/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py:65)
set nap False 
_________
initialize (/usr/lib/python3.7/site-packages/blueman/plugins/applet/RecentConns.py:144)
rebuilding menu 
_________
enumerate_connections (/usr/lib/python3.7/site-packages/blueman/plugins/applet/ShowConnected.py:53)
Found 0 existing connections 
_________
on_registered (/usr/lib/python3.7/site-packages/blueman/bluez/obex/AgentManager.py:18)
/org/blueman/obex_agent 
_________
RequestPowerState (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:131)
Requesting True 
_________
on_power_state_change_requested (/usr/lib/python3.7/site-packages/blueman/plugins/applet/KillSwitch.py:118)
True 
_________
UpdatePowerState (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:159)
off True 
foff False 
on True 
current state True 
new state False 
_________
UpdatePowerState (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:159)
Signalling False 
_________
check (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:119)
callbacks done 
_________
set_adapter_state (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:90)
True 

[bob@Manjaro-Stable ~]$ bluez-test-adapter list
bash: bluez-test-adapter: command not found
[bob@Manjaro-Stable ~]$ sudo bluez-test-adapter list
[sudo] password for bob: 
sudo: bluez-test-adapter: command not found
[bob@Manjaro-Stable ~]$ bluetoothctl list
bash: bluetoothctl: command not found
[bob@Manjaro-Stable ~]$ lsusb
Bus 004 Device 002: ID 8087:8000 Intel Corp. 
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8008 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 005: ID 1058:25a2 Western Digital Technologies, Inc. Elements 25A2
Bus 002 Device 004: ID 04b8:1121 Seiko Epson Corp. 
Bus 002 Device 003: ID 17ef:602d Lenovo 
Bus 002 Device 007: ID 0bda:0821 Realtek Semiconductor Corp. 
Bus 002 Device 006: ID 05e3:0722 Genesys Logic, Inc. SD/MMC card reader
Bus 002 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[bob@Manjaro-Stable ~]$

**Comment by cschramm** [comment]
What are your results or where do you need help with https://github.com/blueman-project/blueman/wiki/Troubleshooting#no-adapter-or-not-able-to-turn-on-bluetooth?

**Comment by beardedragon2** [comment]
Does this help?
[bob@Manjaro-Stable ~]$ systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-03-31 19:08:38 CDT; 10min ago
     Docs: man:bluetoothd(8)
 Main PID: 464 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4915)
   Memory: 2.2M
   CGroup: /system.slice/bluetooth.service
           └─464 /usr/lib/bluetooth/bluetoothd

Mar 31 19:08:37 Manjaro-Stable systemd[1]: Starting Bluetooth service...
Mar 31 19:08:37 Manjaro-Stable bluetoothd[464]: Bluetooth daemon 5.50
Mar 31 19:08:38 Manjaro-Stable bluetoothd[464]: Starting SDP server
Mar 31 19:08:38 Manjaro-Stable systemd[1]: Started Bluetooth service.
Mar 31 19:08:38 Manjaro-Stable bluetoothd[464]: Bluetooth management interface 1.14 initialized

**Comment by beardedragon2** [comment]
Desperate times calls for desperate measures.  Installed Debian based xubuntu in place of Arch based manjaro with the thought it has a different blueman version 2.0.5.  Sadly to no avail.   Still does not work.  I am wondering now if this is not a case of buetooth part gone bad in my computer.   I need it for my hearing aids.  Anyway I ordered a USB dongle to try that out, keep in touch.

**Comment by beardedragon2** [comment]
Seems I am not the only one, see this link:
https://forum.manjaro.org/t/bluetooth-woes-no-default-controller-available/81228?u=beardedragon

**Comment by beardedragon2** [comment]
Stillworking on trying to find the problem:

[bob@Manjaro ~]$ dmesg

8.611356] Bluetooth: Core ver 2.22
[    8.611368] NET: Registered protocol family 31
[    8.611369] Bluetooth: HCI device and connection manager initialized
[    8.611372] Bluetooth: HCI socket layer initialized
[    8.611373] Bluetooth: L2CAP socket layer initialized
[    8.611377] Bluetooth: SCO socket layer initialized

[10.906103] Bluetooth: hci0: command 0x1001 tx timeout

12.815885] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   12.815886] Bluetooth: BNEP filters: protocol multicast
[   12.815889] Bluetooth: BNEP socket layer initialized

18.799407] Bluetooth: hci0: RTL: HCI_OP_READ_LOCAL_VERSION failed (-110)

**Comment by beardedragon2** [comment]
> What are your results or where do you need help with https://github.com/blueman-project/blueman/wiki/Troubleshooting#no-adapter-or-not-able-to-turn-on-bluetooth?

See edited first entry.

**Comment by cschramm** [comment]
Seems like you're using some PCI Realtek hardware and might be missing firmware. Check `dmesg | grep firmware`. On Ubuntu firmware-realtek might help. I don't know about Manjaro.

**Comment by beardedragon2** [comment]
FYI I decided to use Debian Xfce, it is a fine operating system and I am familiar with it.  Same as xubuntu, but, better and more up to date.

**Comment by beardedragon2** [comment]
Solved !!!!!!
Bought bluetooth dongle then installed the following drivers and firmware
bluez-firmware
broadcom-sta-common
broadcom-sta-source

**Comment by beardedragon2** [comment]
One last item you might like to know.  I reinstalled Manjaro and it already had the drivers for the dongle because it looks at the hardware when you install it.  It was the bluetooth hardware all along, thanks for the time and effort you put in.
