### ISSUE TITLE
mini bluetooth keyboard; cant enter pair code

### ISSUE THREAD

**Issue by kekinkekistan** [blueman-project/blueman#1005]
so i have this little bluetooth keyboard,, thoght it was neet, so i bought this bluetooth adapter for my desktop. but i cant enter the pairin code.. isnt there a way to skip that and just auto connect when need be?

blueman:
BlueZ:
Distribution:
Desktop environment: manjaro

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
The procedure depends on the device. It might - and in case of a keyboard most probably does - require pairing before it allows you to connect.

If you describe your problem and provide the fundamental data, we might be able to help.
