### ISSUE TITLE
Bluetooth not working in HP 15r-006TU

### ISSUE THREAD

**Issue by anuedassery123** [blueman-project/blueman#1007]
blueman: installed
BlueZ: installed
Distribution: Manjaro 18.1
Desktop environment: xfce

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Bluetooth adapter is missing. Please help me to fix it. 
Thanks

**Comment by cschramm** [comment]
See https://github.com/blueman-project/blueman/wiki/Troubleshooting#no-adapter-or-not-able-to-turn-on-bluetooth
