### ISSUE TITLE
Set incoming file directory using $XDG_DOWNLOAD_DIR

### ISSUE THREAD

**Issue by clbarnes** [blueman-project/blueman#1011]
blueman: 2.0.5
Distribution: Ubuntu
Desktop environment: XFCE

Blueman does not set its incoming file directory using `XDG_DOWNLOAD_DIR` (when not manually set); it assumes that this will be at `$HOME/Downloads`.

**Comment by cschramm** [comment]
That's not the case. blueman uses GLib and GLib uses XDG special user directories. https://github.com/blueman-project/blueman/blob/master/blueman/plugins/applet/TransferService.py#L150

**Comment by infirit** [comment]
Duplicate, see https://github.com/blueman-project/blueman/issues/496#issuecomment-480927333. If you want to contribute to the discussion go to #998
