### ISSUE TITLE
Bluetooth Hands free not connected in HP-15ac098Tu 

### ISSUE THREAD

**Issue by hasanalikharodiya** [blueman-project/blueman#1029]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
I think you are looking for HFP/HSP support which is available through ofono. See https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Bluetooth/#index5h2

next time though do provide at least the basic info we ask for in the issue template :disappointed:
