### ISSUE TITLE
Connection Failed: The name org.freedesktop.NetworkManager was not provided by any .service files

### ISSUE THREAD

**Issue by sohasanl** [blueman-project/blueman#1032]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Please see the troubleshooting page for instructions on how to submit information.

**Comment by infirit** [comment]
Blueman uses NetworkManager to provide nap/dun support but we can't hope to provide any assistance if not even the most basic information is provided.

**Comment by Zeioth** [comment]
I can reproduce:

**Distro**: Antergos (latest)
**Log**: [here](https://pastebin.com/raw/mUWz3YYH)

Please provide me more info so I can test possible solutions. Cheers.

**Comment by cschramm** [comment]
@Zeioth the issue in your log seems unrelated and should be fixed in recent versions (try 2.1.beta1).

**Comment by Zeioth** [comment]
@cschramm I did:

    yaourt -S blueman-git
    sudo rm -rf /var/lib/bluetooth
    sudo systemctl enable blueman-mechanism.service 

It works now, thank you.
