### ISSUE TITLE
Add manager window accelerators

### ISSUE THREAD

**Issue by matthiasbeyer** [blueman-project/blueman#1045]
blueman: 2.0.8
BlueZ: (How to find out / is this relevant?)
Distribution: NixOS
Desktop environment: Sway (Wayland)

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow: No, because not an technical issue but a user-experience-issue.

---

I would like to be able to quit blueman-manager with Cltr-Q, could you please add this feature?

**Comment by infirit** [comment]
Most window manager have shortcuts to close a window, usually ctrl+f4.

Other than that blueman-manager does not have keyboard shortcuts which could be added if someone cares enough. Changed title and added enhancement.

**Comment by matthiasbeyer** [comment]
Well, in other applications Ctrl-Q works for me,... so I'm not sure whether the window manager is actually responsible here.

Either way: Thanks for not simply closing this!

**Comment by cschramm** [comment]
Can you please try #1406? :slightly_smiling_face:

**Comment by matthiasbeyer** [comment]
I do not use wayland anymore, so I cannot test, sorry.

Feel free to close this issue.
