### ISSUE TITLE
blueman-manager 2.1: no adapters found, while bluetooth is working properly

### ISSUE THREAD

**Issue by st-a** [blueman-project/blueman#1058]
blueman: 2.1
BlueZ: 5.50
Distribution: Arch Linux
Desktop environment: XFCE

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

------

hey, I have encountered some problems after upgrading `blueman` to 2.1. All my bluetooth devices are working properly, I'm typing this on my bluetooth keyboard right now. But `blueman-manager` is refusing to start. The first one is the error message right after the update, while the second one is with an additional reboot done.

```
blueman-manager version 2.1 starting
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/blueman/main/Manager.py", line 112, in on_dbus_name_appeared
    lambda: Gtk.main_quit())
  File "/usr/lib/python3.7/site-packages/blueman/Functions.py", line 71, in check_bluetooth_status
    if "PowerManager" not in applet.QueryPlugins():
  File "/usr/lib/python3.7/site-packages/gi/overrides/Gio.py", line 354, in call
    None)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Method "QueryPlugins" with signature "" on interface "org.blueman.Applet" doesn't exist
 (41)
```

```
blueman-manager version 2.1 starting
blueman-manager 13.14.52 ERROR    Manager:117 on_dbus_name_appeared: No bluetooth adapter(s) found.
```

`blueman-adapters` is working as expected and showing the onboard bluetooth device. Scanning and piring using `bluetoothctl` is also working without problems.  Downgrading `blueman` to 2.0.8 does solve the issue.

**Comment by cschramm** [comment]
Thanks for the report. The first issue sounds like a packing bug to me. Most probably an old blueman-applet process was still running after the upgrade.

The second issue is similar to #1050. @infirit is working on it and has patches for 2.1 in #1055.
