### ISSUE TITLE
Cannot connect to device via applet RecentConns plugin

### ISSUE THREAD

**Issue by atk91** [blueman-project/blueman#1059]
blueman: 2.1-1
BlueZ: 5.50-6
Distribution: Arch Linux
Desktop environment: None, i3 window manager

[*] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Logs: 
https://gist.github.com/atk91/2ace87a5d7a4c393acbee8882d0a5239

This happens when you right-click on icon in tray, then choose recent connections and choose 'Auto connect profiles on ...'
Connecting via blueman-manager gui works fine.

**Comment by cschramm** [comment]
Thanks for the report. I prepared a fix in #1060.
