### ISSUE TITLE
No bluetooth adapters detected, despite other bluetooth managers working

### ISSUE THREAD

**Issue by CCF100** [blueman-project/blueman#1074]
blueman: 2.1-1
BlueZ: 5.50-6
Distribution: Arch Linux
Desktop environment: Cinnamon
Blueberry is successfully able to control the bluetooth adapter, but not blueman...
https://gist.github.com/CCF100/e50ef31a7115a9ffc4b692b383b287d1
* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
@infirit That issue should be fixed in 2.1.1, correct?

**Comment by infirit** [comment]
Sounds like the bug I introduced and fixed with 16a147262a9beccbded533b1cf788d01aefbeab4
