### ISSUE TITLE
Apple Airpods not connecting to Dell XPS (9380)

### ISSUE THREAD

**Issue by mikachoow21** [blueman-project/blueman#1083]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
Yeah, lets ignore the issue template and provide none of the requested :disappointed:. Until you read through  https://github.com/blueman-project/blueman/wiki/Troubleshooting and provide the info requested in the issue template there is nothing we can do to help.

**Comment by mikachoow21** [comment]
Sorry about this, I found a solution by changing the bluetooth config
