### ISSUE TITLE
 No audio on Bluetooth Device

### ISSUE THREAD

**Issue by ajeeshissac** [blueman-project/blueman#1090]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->
I am using Blueman on my Linux Mint laptop. My Laptop is HP. while connecting to bluetooth speaker and headset its connecting but no audio only some noises. some times there is problem with connecting also. Bluetooth audio device is Philips. Hoping for a replay.
Thanks and Regards
Ajeesh Issac

**Comment by infirit** [comment]
https://github.com/blueman-project/blueman/wiki/Troubleshooting
