### ISSUE TITLE
blueman-applet did not change state if bluetoothctl power off

### ISSUE THREAD

**Issue by RazuvaevDD** [blueman-project/blueman#1098]
blueman: blueman-git 2.1.alpha3.r5.g088da0c7-1
BlueZ: bluez-5.50-7
Distribution: Arch Linux
Desktop environment: Awesome WM

**Commands:**
_`$ bluetoothctl power on`
`$ blueman-applet &`
`$ bluetoothctl power off`_

**Expected:**
  blueman-applet will change its state to inactive

**Presently:**
  blueman-applet did not change its state to inactive

**Comment by infirit** [comment]
Can you post the blueman-applet log as described in https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging

I can however reproduce and the relevant bit from my log is below.

```
blueman-applet 10.01.51 DEBUG    Base:74 do_g_properties_changed: /org/bluez/hci0 {'Powered': False, 'Discovering': False, 'Class': 0}
blueman-applet 10.01.51 INFO     PowerManager:172 update_power_state: off False | foff False | on True | current state True | new state True
blueman-applet 10.01.51 DEBUG    DiscvManager:82 on_adapter_property_changed: prop Powered False
blueman-applet 10.01.51 INFO     DiscvManager:99 on_adapter_property_changed: Stop
blueman-applet 10.01.51 DEBUG    DiscvManager:82 on_adapter_property_changed: prop Discovering False
blueman-applet 10.01.51 DEBUG    DiscvManager:82 on_adapter_property_changed: prop Class 0
```

**Comment by cschramm** [comment]
It looks like the PowerManager plugin just does not updates the known adapter state correctly on property change. Can you test the fix in #1102?

**Comment by RazuvaevDD** [comment]
blueman-git-2.1.r32.gae2be5a7-1 in Arch repository don't work correctly.

**Comment by cschramm** [comment]
What did you download exactly? To test the fix branch you need to download https://github.com/cschramm/blueman/tree/power-fix.

**Comment by RazuvaevDD** [comment]
i download thus package from your link, but it's not work -_-
![изображение](https://user-images.githubusercontent.com/15276724/66317777-ab559180-e909-11e9-820e-404490739987.png)

**Comment by cschramm** [comment]
From your screenshot I'm not sure if you replaced the running applet instance. You need to exit or koll it and then run the version of `blueman-applet` you just installed.
