### ISSUE TITLE
Notification for incoming file flashes too fast on screen

### ISSUE THREAD

**Issue by Frodoobe** [blueman-project/blueman#1105]
When transferring a file from my device to my computer the notification of file transfer (accept\decline) flashes on the screen rather than appearing and waiting for a response. It happens so quickly that unless I position my cursor in the exact spot where the notification appears I am unable to select a choice.

**Comment by cschramm** [comment]
What notification daemon do you use?

Please provide
```
dbus-send --session --print-reply --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.GetServerInformation
```
and
```
dbus-send --session --print-reply --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.GetCapabilities
```

**Comment by troisiemetype** [comment]
Hello,

I have the exact same issue. The notification for accepting a file transfer displays for less than one second. Other notifications (for accepting or notifying connection status, etc.) are displayed until clicked or for a reasonable time.

I have the following results for the two `dbus` requests you asked for above : 

```
method return time=1769948637.607236 sender=:1.25 -> destination=:1.889 serial=1255 reply_serial=2
   string "lxqt-notificationd"
   string "lxqt.org"
   string "1.4.0"
   string "1.2"
```
```
method return time=1769948647.985257 sender=:1.25 -> destination=:1.890 serial=1256 reply_serial=2
   array [
      string "actions"
      string "body"
      string "body-hyperlinks"
      string "body-images"
      string "body-markup"
      string "persistence"
   ]
```
