### ISSUE TITLE
Daemon/Recent Connections... list empty after suspension and restart

### ISSUE THREAD

**Issue by antondubrovski** [blueman-project/blueman#1131]
blueman: 2.0.5
BlueZ: 
Distribution: Ubuntu 19.04
Desktop environment: GNOME 3.32.1

Hello! I am used to connecting my JBL and AirPods through Daemon's "Recent Connections...". However, after suspending and subsequent restarting of my laptop the list goes empty, and I have 
to open the "Devices..." window and connect my devices from there. It is in no way much of a drag nor is it a big issue, but surely there's a way to get rid of this problem. Thanks in advance!

* [ yep ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
For us 2.0.5 is more than 2 years old 😨 but lets see what we can figure out as it may be a proper bug which may exist in the current stable 2.1 releases. Can you confirm this only happens with suspend/resume or does a proper restart also clear it out?

The juicy bits are in blueman-applet console output so can you:
1. kill the blueman-applet
2. run blueman-applet in a terminal
3. Attempt to connect to at least one device
4. Suspend and resume
5. Paste the complete output to a gist and post the link here
