### ISSUE TITLE
Blueman isn't connecting to my headset like it once did. What gives!

### ISSUE THREAD

**Issue by nobleexperiment** [blueman-project/blueman#1136]
blueman:2.04
BlueZ: 
Distribution: ubuntu 16.04 lts
Desktop environment: yes

My Bluetooth headset is listed on recent connections (hard to screenshot the actual menu that's not visibly showin it) on the app but it's not connecting. I've done the linux lsusb, sudo service bluetooth restart blah blah everything and it's not working. My alsa stuff was even force-rebooted. I had to reinstall pulseaudio in hopes it would work again as it previously did. Now i'm stuck and exhausted all options. How can I have the blueman connect to my headset like it previously did?

link to screenshot: [https://imgur.com/dueKkHO](https://imgur.com/dueKkHO)

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Check `dmesg` and find the hardware ID of your controller.

**Comment by nobleexperiment** [comment]
[   19.393047] audit: type=1400 audit(1572888834.649:39): apparmor="DENIED" operation="open" profile="snap.pulseaudio.pulseaudio" name="/sys/devices/virtual/dmi/id/board_vendor" pid=1576 comm="pulseaudio" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[   19.790843] audit: type=1400 audit(1572888835.045:40): apparmor="DENIED" operation="open" profile="snap.pulseaudio.pulseaudio" name="/sys/devices/virtual/dmi/id/board_vendor" pid=1576 comm="pulseaudio" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[   19.844117] audit: type=1400 audit(1572888835.101:41): apparmor="DENIED" operation="open" profile="snap.pulseaudio.pulseaudio" name="/sys/devices/virtual/dmi/id/board_vendor" pid=1576 comm="pulseaudio" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[   21.507014] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   21.507016] Bluetooth: BNEP filters: protocol multicast
[   21.507022] Bluetooth: BNEP socket layer initialized

**Comment by cschramm** [comment]
So you're having some issue with your pulseaudio installation. Is your user in the `audio` group?

**Comment by nobleexperiment** [comment]
nope. I type in groups audio and it spits back:~$ groups audio
groups: ‘audio’: no such user

**Comment by cschramm** [comment]
That's not how to use the `groups` command.

You usually need to be in the `audio` group to be allowed to use pulseaudio.

**Comment by nobleexperiment** [comment]
my user is not in the audio group. I do have pulseaudio working, but only when i use the terminal to type in Pulseaudio -D.

**Comment by cschramm** [comment]
Please catch up on reading our troubleshooting page and provide the blueman-applet logs with the connection attempt.
