### ISSUE TITLE
Raspberry pi4 bluetooth problem

### ISSUE THREAD

**Issue by antojuve** [blueman-project/blueman#1145]
Hello, Im new on ubuntu and raspberry, I install ubuntu following a youtube tutorial on my new raspberry pi4 4gb, I want to add my bluetooth keyboard and mouse but I cant. I install blueman following a youtube video but I cant add any device.

When I run Bluetooth manager (Blueman) the options "Adapter" and "Device" are blocked and I cant put my raspberry as visible for the others devices.

Can help me pleaseeee

blueman:
BlueZ:
Distribution:
Desktop environment: ubuntu 19.10 64bits

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
See https://github.com/blueman-project/blueman/wiki/Troubleshooting#no-adapter-or-not-able-to-turn-on-bluetooth

If you need further help go to the top of above link and give it a proper read :wink:
