### ISSUE TITLE
Automatically connect headphones after pairing and trust.

### ISSUE THREAD

**Issue by lavaed** [blueman-project/blueman#1147]
blueman: 2
BlueZ: 5.52
Distribution: ubuntu 18 kernel 4.15
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.
 After successfully connecting and using the headphones on the computer, I disconnect the headphones, and after that I want them to connect to the computer themselves, as it was on ubuntu 14. Bluetoothd connects the headphones automatically, and immediately disconnected them.
 When the headphones try to connect to the computer, bluetoothd writes the following to the logs.

 [ bluetoothd[2932]: src/adapter.c:connected_callback() hci0 device 90:00:00:00:A5:B9 connected eir_len 5
bluetoothd[2932]: src/adapter.c:dev_disconnected() Device 90:00:00:00:A5:B9 disconnected, reason 3
bluetoothd[2932]: src/adapter.c:adapter_remove_connection()
bluetoothd[2932]: plugins/policy.c:disconnect_cb() reason 3
bluetoothd[2932]: src/adapter.c:bonding_attempt_complete() hci0 bdaddr 90:00:00:00:A5:B9 type 0 status 0xe
bluetoothd[2932]: src/device.c:device_bonding_complete() bonding (nil) status 0x0e
bluetoothd[2932]: src/device.c:device_bonding_failed() status 14
bluetoothd[2932]: src/adapter.c:resume_discovery()
] 
 Upon successful connection from the computer, the logs begin like this.

 [bluetoothd[2932]: src/device.c:connect_profiles() /org/bluez/hci0/dev_90_00_00_00_A5_B9 (all), client :1.146
bluetoothd[2932]: src/service.c:btd_service_ref() 0x562ea8e71460: ref=2
bluetoothd[2932]: src/service.c:change_state() 0x562ea8e71460: device 90:00:00:00:A5:B9 profile Headset Voice gateway sta
bluetoothd[2932]: src/adapter.c:connected_callback() hci0 device 90:00:00:00:A5:B9 connected eir_len 9
bluetoothd[2932]: src/profile.c:ext_connect() Headset Voice gateway connected to 90:00:00:00:A5:B9
bluetoothd[2932]: src/service.c:change_state() 0x562ea8e71460: device 90:00:00:00:A5:B9 profile Headset Voice gateway sta
bluetoothd[2932]: src/device.c:device_profile_connected() Headset Voice gateway Success (0) ] 

- 

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Problem solved?
