### ISSUE TITLE
blueman

### ISSUE THREAD

**Issue by mohdzain98** [blueman-project/blueman#1153]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

Blueman is unable to search for a device.
Search button is disabled and also adapter is also disabled

->

**Comment by infirit** [comment]
There is not enough information here, see https://github.com/blueman-project/blueman/wiki/Troubleshooting
