### ISSUE TITLE
mon clavier bluetooth 1by one n'est pas reconnu et ne s'appaire pas

### ISSUE THREAD

**Issue by kurtcuis** [blueman-project/blueman#1155]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by ruediste** [comment]
Title in english: My bluetooth keyboard "1by one" is not recognized and does not appear
