### ISSUE TITLE
Bluetooth cannot search for a device or add a device

### ISSUE THREAD

**Issue by iobami** [blueman-project/blueman#1164]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by mlk71075** [comment]
Confirm. Ubuntu Focal, blueman-manager 2.1.1, scanning can't see any new device.
ii  blueman                              2.1.1-1                           amd64        Graphical bluetooth manager
ii  libbluetooth3:amd64                  5.52-0ubuntu2                     amd64        Library to use the BlueZ Linux Bluetooth stack
ii  libgnome-bluetooth13:amd64           3.34.0-1                          amd64        GNOME Bluetooth tools - support library
ii  pulseaudio-module-bluetooth          1:13.0-3ubuntu1                   amd64        Bluetooth module for PulseAudio sound server

**Comment by cschramm** [comment]
@mlk71075: Are you sure that you do have the same issue as @iobami? You seem to be able to search for devices, @iobami does not.

Check https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging-blueman regarding a blueman-applet debug log of the scan. Also check if devices show up in bluetoothctl. If yes, this is not a blueman issue but something more fundamental in your in Bluetooth stack.

**Comment by mlk71075** [comment]
I am sure. I did both, no device appeared.
However on another machine, I could successfully scan for devices. Same
Ubuntu version, both updated before I wrote the comment.

W dniu niedz., 26.01.2020 o 10:08 Christopher Schramm <
notifications@github.com> napisał(a):

**Comment by franzever** [comment]
tengo el mismo problema.
soy nuevo en el mundo de linux ubuntu acabo de instalarlo y el dispositivo de bluetooth no logra identificar a otros cuando los busca. 
busque por la web configuraciones posibles soluciones con blueman y bluez pero hasta ahora nada, no detecta dispositivos moviles, tabletas o equipos de audio.
alguien podria ayudarme..
