### ISSUE TITLE
Philips BT50 Speaker error

### ISSUE THREAD

**Issue by bertoeric34** [blueman-project/blueman#1175]
blueman:
BlueZ:
Distribution: Lubuntu
Desktop environment:
LXQT 0141
No connection to my Philips BT50
Info:
FC:58:FA:A0:4B:B5
public
Philips BT50
Philips BT50
0x260404
0x0000
audio-card
oui
oui
non
non
non
00001101-0000-1000-8000-00805f9b34fb Serial Port
00001108-0000-1000-8000-00805f9b34fb Headset
0000110b-0000-1000-8000-00805f9b34fb Synchronie audio
0000110c-0000-1000-8000-00805f9b34fb Remote Control Target
0000110e-0000-1000-8000-00805f9b34fb Remote Control
0000111e-0000-1000-8000-00805f9b34fb Handsfree
/org/bluez/hci0
Blue devil ne le detecte pas

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
This is the blueman project, so you will not find support for bluedevil here...
