### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by vtolentino** [blueman-project/blueman#1176]
help help
![image](https://user-images.githubusercontent.com/38164483/74048218-c9a6c900-499f-11ea-9aa1-4e933bb9c8da.png)

**Comment by cschramm** [comment]
Please see https://github.com/blueman-project/blueman/wiki/Troubleshooting for basic information when asking for help.

Try `rfcomm(1)` to see if it's a blueman issue or - probably - something else.
