### ISSUE TITLE
Tray icon disappears for a second when bluetooth turned on

### ISSUE THREAD

**Issue by Mau-G** [blueman-project/blueman#1182]
blueman: 2.1.2
BlueZ: 5.52
Distribution: openSUSE Tumbleweed
Desktop environment: Xfce

With rfkill plugin enabled, when turning on bluetoogh the tray applet would disappear for a second. During this time if open the tray contextual menu the applet and menu would freeze the entire systray.

![image](https://user-images.githubusercontent.com/44322817/74600113-7f23fb80-50c7-11ea-8a21-cb32f32b1c4f.png)

1. make sure bluetooth is off
2. turn on bluetooth via applet
3. icon disappears for a second and reappears

Could be related to this error:
```
blueman-manager version 2.1.2 starting
Failed to enable bluetooth
blueman-manager 14.23.56 ERROR    Manager:118 on_dbus_name_appeared: Default adapter not found, trying first available.
blueman-manager 14.23.56 ERROR    Manager:122 on_dbus_name_appeared: No adapter(s) found, exiting
```

**Comment by cschramm** [comment]
Sorry for not getting back earlier.

I cannot replicate the issue. Neither does the icon disappear for me, nor do I have a clue how to cause the freeze you mention.
