### ISSUE TITLE
Incorrect German translation detail

### ISSUE THREAD

**Issue by geos-github** [blueman-project/blueman#1186]
blueman: 2.05
BlueZ:
Distribution: Xubuntu 18.04 LTS 32bit
Desktop environment:

blueman-manager lists the types of devices it can see. For the German localization, a desktop computer is labelled "Schreibtisch". While this word literally means "Desktop", Desktop Computers are not called that way (sounds as wierd as e.g. speaking of "Microsoft Fenster"). Please correct that translation mistake. My suggestion is to use the term "Desktop-Computer" or "Desktop" to refer to  a desktop computer in German. c.f. https://de.wikipedia.org/wiki/Desktop-Computer

**Comment by infirit** [comment]
I have corrected it on the weblate translation tool. If you have further suggestions please feel free to do so on link below.

https://hosted.weblate.org/projects/blueman/blueman/de/
