### ISSUE TITLE
bluetooth worked once after random combo of terminal commands and GUI selections 

### ISSUE THREAD

**Issue by Darrell-Turner** [blueman-project/blueman#1187]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
There isn't enough information to even start a conversation. See
https://github.com/blueman-project/blueman/wiki/Troubleshooting

At the very minimum we need version numbers and blueman-applet log. Ideally
you provide the steps you done and what you tried before.
