### ISSUE TITLE
Bluetooth setup assistant has control with missing borders

### ISSUE THREAD

**Issue by philipzae** [blueman-project/blueman#1188]
blueman: 2.1.2
BlueZ: 5.53
Distribution: Xubuntu 20.04
Desktop environment: XFCE

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

The bluetooth assistant has a steps control on the left but unfortunately only 1 of the 4 borders appear.

![xubuntu-ermine-bt-works](https://user-images.githubusercontent.com/4412114/75869903-adbe0800-5e23-11ea-8d8d-125aeba244e7.png)

Also filed at launchpad
https://bugs.launchpad.net/ubuntu/+source/blueman/+bug/1866028

**Comment by infirit** [comment]
Can you reproduce this with the gtk default theme adwaita? If not then it
is most likely a problem with the theme. If it does we'll have to check if
I see the same

**Comment by philipzae** [comment]
Yes its there with adwaita.

![blueman adwaita](https://user-images.githubusercontent.com/4412114/76059028-3f9a5200-5f97-11ea-92fa-aff08793279a.png)

**Comment by cschramm** [comment]
I think that's just what [GtkAssistant](https://developer.gnome.org/gtk3/stable/GtkAssistant.html) does when using defaults (`use-header-bar` `FALSE` and `has-padding` `TRUE`).

**Comment by infirit** [comment]
>
> I think that's just what GtkAssistant
> <https://developer.gnome.org/gtk3/stable/GtkAssistant.html> does when
> using defaults (use-header-bar FALSE and has-padding TRUE
>
It is probably how GtkAssistant is designed and not much we can do about it
then. I'll poke at some properties to see if it makes a difference.

>

**Comment by philipzae** [comment]
@infirit any progress with this issue?

**Comment by infirit** [comment]
Yes, this is how it looks. Nothing we can do about this.
