### ISSUE TITLE
turn off permanently on aarch64

### ISSUE THREAD

**Issue by ng0177** [blueman-project/blueman#1191]
Sorry, there seems to be no way of doing so. Ideas? Thanks.

**Comment by cschramm** [comment]
I don't think there's anything specific to aarch64. There are a couple of mechanism that might be auto-powering your adapters, e.g. udev rules, BlueZ' `AutoEnable`, blueman's `auto-power-on`...

**Comment by ng0177** [comment]
I tried `tlp` but it seems to have no effect. How test on cli, if bluetooth is really on or off?

**Comment by cschramm** [comment]
`hciconfig` will either show `UP` or `DOWN` for the controllers.

**Comment by ng0177** [comment]
```
Building bluez-hciconfig...
==> ERROR: bluez-hciconfig is not available for the 'aarch64' architecture.
```

**Comment by cschramm** [comment]
BlueZ' D-Bus interface would be what I'd use then, e.g.
```
dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0 org.freedesktop.DBus.Properties.Get string:org.bluez.Adapter1 string:Powered
```
in case `dbus-send` is available. :smile: Some other tool otherwise...

**Comment by ng0177** [comment]
```
method return time=1584263958.358546 sender=:1.18 -> destination=:1.212 serial=138 reply_serial=2
   variant       boolean true
```
works like a charm :-) Can `send-bus` also be used to turn it on and off?

**Comment by cschramm** [comment]
```
dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0 org.freedesktop.DBus.Properties.Set string:org.bluez.Adapter1 string:Powered variant:boolean:false
```

**Comment by ng0177** [comment]
Problem solved. Thanks for the swift responses!
