### ISSUE TITLE
The Bluetooth work fine but somes times have lag

### ISSUE THREAD

**Issue by xatusbetazx17** [blueman-project/blueman#1201]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by Phil171** [comment]
Xubuntu 20.04
Blueman : blueman-manager 2.1.2
Souris BT freeze ou s'arrête de fonctionner, impossible de l'enlever dans blueman-manager ou de la réinstaller.
Obligation de redémarrer l'ordinateur.

**Comment by Phil171** [comment]
Xubuntu 20.04
Blueman: blueman-manager 2.1.2
Souris BT freeze or stops working, cannot remove it in blueman-manager or reinstall it.
Obligation to restart the computer.
