### ISSUE TITLE
Unable to run blueman-manager

### ISSUE THREAD

**Issue by xXBannedXx** [blueman-project/blueman#1219]
blueman: latest
BlueZ: latest
Distribution: Kali
Desktop environment: Kali Linux

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

Whenever I try to run the command to open the manager I get the error “***stack smashing detected***: <unknown> terminated Aborted”

**Comment by Yannik** [comment]
@xXBannedXx run like this: `blueman-manager --loglevel DEBUG`

**Comment by xXBannedXx** [comment]
blueman-manager 21.15.56 INFO     PluginManager:85 load_plugin: ['Notes', 'Services', 'PulseAudioProfile', 'Info']
blueman-manager 21.15.56 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.manager.Notes.Notes'>
blueman-manager 21.15.56 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.manager.Services.Services'>
blueman-manager 21.15.56 INFO     PluginManager:156 __load_plugin: loading <class 'blueman.plugins.manager.PulseAudioProfile.PulseAudioProfile'>
*** stack smashing detected ***: <unknown> terminated
Aborted

**Comment by cschramm** [comment]
Some binary, either our C library or your Python interpreter in general trips over a GCC protection mechanism there. How do you build blueman?

**Comment by xXBannedXx** [comment]
I use the default build that comes with kali Linux. Usually an apt-get update/upgrade will update it from kalis servers.

**Comment by cschramm** [comment]
I'd expect that to be some Kali specific issue, not related to blueman (as they just import blueman from Debian without changes). Please report it to the Kali Linux bug tracker.
