### ISSUE TITLE
How to activate BLUETOOTH 5.0 on RASPBERRY 4 Model B. It really works with XUBUNTU 18.04.04 ?

### ISSUE THREAD

**Issue by MrOnionPI** [blueman-project/blueman#1220]
blueman:
BlueZ:
Distribution:
Desktop environment:
Recently I've purchased the RASPBERRY LABSTS KIT, after the configuration I've installed XUBUNTU 18.04.04. I've noticed that with this HW + SW configuration it is not possible to connect any bluetooth device to the RASPBERRY 4 MODULE B, although from the XUBUNTU Desktop menu the BLUETOOTH functionality seems activated. The product that I've purchased state that supports both features: Wireless connectivity: wifi 2.4 GHz and 5GHz IEEE 802.11ac and Bluetooth 5.0 BLE ???? Can you suggest to me how to really activate the BLUETOOTH functionality on the product I've purchased?

Thank you
Vincenzo
Apri in Google Traduttore	
Feedba

**Comment by fabian727** [comment]
after starting bluetoothctl in bash, can you see your device with typing in "list"?

e.g.:
`user@compuer:/home/user# bluetoothctl 
Agent registered
[bluetooth]# list
Controller 01:23:45:67:89:AB computer [default]
[bluetooth]# 
`

if so, your bluetooth adapter is recognized and it is a configuration problem, else I think it is not a problem of the bluetoothctl/ blueZ, but rather Xubuntu/ raspberry.
I know that you can run raspbi-config under raspbian. Is the module enabled? You can also verify the identification for searching of the directory "/var/lib/bluetooth/01:23:45:67:89:AB"
