### ISSUE TITLE
iMac 2010 Bluetooth Manager refuses to work after sleep

### ISSUE THREAD

**Issue by tmanok** [blueman-project/blueman#1244]
blueman: community/blueman 2.1.2-1 [installed]
Distribution: Manjaro
Desktop environment: Cinnamon

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

GitHub Gist (Good Suggestion): https://gist.github.com/tmanok/4af34117c3136e06e6b796d9ebbeefe3

Basically here's what has occurred: I setup Bluetooth on a fresh install of Manjaro Cinnamon on a 2010 27" iMac for my Apple Magic Mouse. The mouse worked fine both using the liveCD (USB) and post installation. However after running out to do an errand, the bluetooth stopped working post-login. This was a pain but my keyboard shortcut skills are reasonable so I started by pressing SUPER and typing Bluetooth to launch blueman-manager, which then asked me to enable bluetooth (something I had done on initial setup). After pressing [TAB] then [ENTER] to select the Enable Bluetooth GUI button, the application closed leaving me without a mouse! 

So since then I've been mouseless (~1hour) with a fresh install of Manjaro. Not terrible though, I managed to install chromium and sign into it so I could access my GitHub and submit this issue (wicked keyboard skills lol). Any help is appreciated, see my terminal output in the GIST using suggested debug commands, I'll try further debug when I return from a car appointment.

**Comment by cschramm** [comment]
What does `bluetoothctl list` in a terminal give you?
