### ISSUE TITLE
[RPMLint] Program is likely to break with new gcc

### ISSUE THREAD

**Issue by posophe** [blueman-project/blueman#125]
This is the output of blueman building on OBS. GCC version is 4.8/4.8+

I: Program is likely to break with new gcc. Try -fno-strict-aliasing.
W: blueman strict-aliasing-punning _blueman.c:4439
W: blueman strict-aliasing-punning libblueman.c:130

**Comment by cschramm** [comment]
I cannot get any of those warnings with GCC 4.9 and -Wall. How exactly do you produce them?

I see what it means in libblueman.c:130 and that's in fact our code. What's in your _blueman.c:4439? That's not directly our code, but generated by Cython.

**Comment by posophe** [comment]
I don't know. It's generated from blueman.c. I can't tell you exactly what is broken, as rpmlint doesn't give so much details.

**Comment by infirit** [comment]
No warnings with gcc 4.9.2 and cython 0.22 on Gentoo. As @cschramm mentioned this file is generated by cython so the version of cython used perhaps is older and generates the wrong c.

Also do post (pastebin/gist please) the whole build log as the rpmlint output is not sufficient to figure this out.

**Comment by posophe** [comment]
libblueman.c: In function '_create_bridge':
libblueman.c:130:9: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          ((unsigned long *)(&ifr.ifr_data))[0] = (unsigned long)args;
          ^
_blueman.c:4848:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 __pyx_t_1 = __Pyx_PyBool_FromLong((!(!__pyx_t_2))); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 459; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    ^
 _blueman.c:4848:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 _blueman.c: In function '__pyx_pf_8_blueman_24get_special_dir':

That's it for the log

**Comment by infirit** [comment]
That is not the whole __build__ log, I mean from rpm start of the build till the end :wink: 

However searching the interwebs I found that we must pass ```-fno-strict-aliasing``` for cython, see this [post](https://mail.python.org/pipermail/cython-devel/2013-July/003732.html). I'll add this to the CFLAGS when building.

**Comment by posophe** [comment]
But I gave you the punning functions which break blueman. I pass -fno-stric-aliasing too but I think it should be fixed.

**Comment by cschramm** [comment]
Concerning cython I guess it cannot be fixed on our side. Our libblueman.c could, yeah...

**Comment by infirit** [comment]
>Our libblueman.c could, yeah...

Ah, missed that file was pure c, reopening.

>But I gave you the punning functions which break blueman.

@posophe, come on now, you know very well how this works as a maintainer. It contains all the information on your build environment like versions numbers and the CFLAGS/LDFLAGS used. And the latter is very relevant in reproducing this warning.

**Comment by posophe** [comment]
The cython lib is generated from libblueman.c so fixing libblueman.c fix the cython lib :-)

**Comment by posophe** [comment]
@infirit : I have some troubles with cython 0.22, about the tests. I'm trying to fix it but cython is kind of... more complex than classic python libraries.

**Comment by cschramm** [comment]
> The cython lib is generated from libblueman.c so fixing libblueman.c fix the cython lib :-)

No. It's generated from _blueman.pyx. We could possibly fix it with a change in that file, but not necessarily.

**Comment by infirit** [comment]
```get_special_dir``` is no more in master so we can ignore that. We are left with ``_create_bridge``` in ```libblueman.c``` which is called from ```create_bridge``` in ```_blueman.pyx```.

**Comment by infirit** [comment]
>[((unsigned long *)(&ifr.ifr_data))[0] = (unsigned long)args;](https://github.com/blueman-project/blueman/blob/master/module/libblueman.c#L130)

Is the offending line, but I am not sure how to fix this :disappointed:

**Comment by cschramm** [comment]
Weird construct. I think it should just be `ifr.ifr_data = (char *) &args;` :smile:

**Comment by posophe** [comment]
I meant because _blueman.pyx is calling libblueman.c

**Comment by infirit** [comment]
I put the change in https://github.com/blueman-project/blueman/pull/257 for testing. It compiles but have not tried running.

**Comment by cschramm** [comment]
rpmlint should be free of warnings now with and without -fno-strict-aliasing, is it?

**Comment by infirit** [comment]
Portage checks for this but I never saw the warning so I was hoping @posophe would confirm the commit fixes the problem with rpmlint.

**Comment by posophe** [comment]
Fixed for libblueman. Thanks

**Comment by infirit** [comment]
Commit 1493fc0e538c1f93db8823cc08977dc9662271e6 reverted and closing.
