### ISSUE TITLE
not detecting my bluetooth devices

### ISSUE THREAD

**Issue by karthik1786** [blueman-project/blueman#1264]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by karthik1786** [comment]
i have installed blueman and enabled started service, but still the devices is not detected, kindly advice me in this

**Comment by cschramm** [comment]
https://github.com/blueman-project/blueman/wiki/Troubleshooting
