### ISSUE TITLE
Paired but failed to connect

### ISSUE THREAD

**Issue by Baptistouta** [blueman-project/blueman#1266]
blueman:2.0.5
BlueZ:5
Distribution:lubuntu 18.04
Desktop environment:lxde

I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

My audio devices are paired but I cannot connect them. When I make synchronie audio blueman gives me 
> blueman.bluez.errors.DBusFailedError: Protocol not available... 

I used blueman-applet, please find what [it returned](https://pastebin.com/TfYRpfyM) 
Futhermore, I tried to follow https://github.com/blueman-project/blueman/wiki/Troubleshooting 
> A2DP audio device PAIRED but fails to connect.

Finally I couldn't because with LXDE, the directory /var/lib/gdm doesn't exist. It seems to be replaced by lightdm , but we are not allowed to execute or read or write this directory.

Thank You for helping me

<!--

: 
ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
`pulseaudio-module-bluetooth` installed?

**Comment by Baptistouta** [comment]
No, it wasn't. I installed and it solved my problem. Thank you very much.
