### ISSUE TITLE
not detecting my bluetooth devices

### ISSUE THREAD

**Issue by amitgit12** [blueman-project/blueman#1267]
Below is the log.

killall blueman-applet
blueman-applet > bt_logfile

blueman-applet version 2.0.5 starting
Stale PID, overwriting
_________
^[[1mLoad^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:60)
['RecentConns', 'StatusIcon', 'StandardItems', 'AuthAgent', 'Headset', 'Menu', 'SerialManager', 'NetUsage', 'NMDUNSupport', 'DiscvManager', 'ShowConnected', 'TransferService', 'AppIndicator', 'PowerManager', 'ExitItem', 'KillSwitch', 'PPPSupport', 'GameControllerWakelock', 'DhcpClient', 'NMPANSupport', 'DBusService', 'Networking']
_________
^[[1mget_interface_version^[[0m (/usr/lib/python3/dist-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 5
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Menu.Menu'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Headset.Headset'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'>
_________
^[[1mupdate_menuitems^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:123)
warning: Adapter is None
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.TransferService.TransferService'>
_________
^[[1mget_interface_version^[[0m (/usr/lib/python3/dist-packages/blueman/bluez/obex/Base.py:20)
Detected BlueZ integrated obexd
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AppIndicator.AppIndicator'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ExitItem.ExitItem'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DBusService.DBusService'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.PPPSupport.PPPSupport'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'>
_________
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DhcpClient.DhcpClient'>
^[[1m__load_plugin^[[0m (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Networking.Networking'>
_________
^[[1mload_nap_settings^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py:36)
Loading NAP settings
_________
^[[1mio_event^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
killswitch registered 2
_________
^[[1mio_event^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
State: True
_________
^[[1mUpdatePowerState^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False
foff False
on True
current state True
new state True
_________
^[[1m_on_obex_owner_changed^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/TransferService.py:172)
obex owner changed: :1.82
_________
^[[1mon_dbus_name_owner_change^[[0m (/usr/bin/blueman-applet:95)
org.bluez owner changed to :1.7
_________
^[[1minitialize^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:144)
rebuilding menu
_________
^[[1mregister_agent^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/AuthAgent.py:63)
Registering agent
^[[1mset_nap^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py:65)
set nap False
_________
^[[1menumerate_connections^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/ShowConnected.py:53)
Found 0 existing connections
_________
^[[1mon_registered^[[0m (/usr/lib/python3/dist-packages/blueman/bluez/obex/AgentManager.py:18)
/org/blueman/obex_agent
_________
^[[1mRequestPowerState^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:131)
Requesting True
_________
^[[1mon_power_state_change_requested^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:118)
True
_________
^[[1mUpdatePowerState^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False
foff False
on True
current state True
new state True
_________
^[[1mcheck^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:119)
callbacks done
_________
^[[1mset_adapter_state^[[0m (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:90)
True

blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
There's not even a discovery visible in the logs.
