### ISSUE TITLE
Bluetooth does not add any device, wether audio device or my samsung galaxy J7

### ISSUE THREAD

**Issue by descholar-ceo** [blueman-project/blueman#1275]
blueman: 2.0.5
BlueZ: 5.47-4 
Distribution: Linux mint 19.3 Tricia
Desktop environment: Cinnamon desktop

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

I would like to get help because it refuses to connect to any device, I even formatted and reinstalled Linux mint 19.3 Tricia but still it doesn't work

**Comment by cschramm** [comment]
Please provide output from `blueman-applet` (see the troubleshooting page) of the failing process.

**Comment by descholar-ceo** [comment]
@cschramm It keeps searching and it cannot find any bluetooth device

**Comment by cschramm** [comment]
Did you try searching in `bluetoothctl`? If nothing shows up but there are discoverable devices, that's probably an issue with the driver / firmware / controller.

**Comment by descholar-ceo** [comment]
This is what I get when I run `show`
![Screenshot from 2020-06-12 08-11-08](https://user-images.githubusercontent.com/56886064/84470763-4f0af480-ac84-11ea-9f33-21435f712ab2.png)


and when I run `scan on` I get this
![Screenshot from 2020-06-12 08-10-02](https://user-images.githubusercontent.com/56886064/84470720-36024380-ac84-11ea-9458-997ab10c360f.png)


When I run `devices` It shows nothing

===>It seems like I am not getting any device, (I have my samsung galaxy J7 bluetooth on and visible to all near by devices on) and is able to be paired.

**Comment by cschramm** [comment]
That pretty much confirms "driver / firmware / controller". Nothing we can do from the blueman side.

Check your system logs for errors on start and when searching. The driver or bluetoothd might give some hint. Also find your chipset with `lsusb` or `lspci` and see if you can find similar issues with it on the Internets.
