### ISSUE TITLE
Disconnecting headset "No adapter found"

### ISSUE THREAD

**Issue by callegula** [blueman-project/blueman#1281]
(probably) closed.

After remove device reboot and restart systemctl bluez and search new device - it works. :)

___________________________________________
blueman:2.1.3
BlueZ:
Distribution: fedora 
Desktop environment: i3
versions as of june17 2020

blueman-manager 21.06.35 ERROR    Manager:118 on_dbus_name_appeared: Default adapter not found, trying first available.
blueman-manager 21.06.35 ERROR    Manager:122 on_dbus_name_appeared: No adapter(s) found, exiting

Happens time and time again.

Disconnecting headset

**Comment by cschramm** [comment]
How do you disconnect? On your computer or from the device itself?

If I get you right, it's unpredictable when it happens, correct?

**Comment by callegula** [comment]
Hi 

I disconnect 90% by powering of the headphones. 

Regards 

On 2020-06-18 08:24, Christopher Schramm wrote:

> How do you disconnect? On your computer or from the device itself? 
> 
> If I get you right, it's unpredictable when it happens, correct? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/blueman-project/blueman/issues/1281#issuecomment-645805682
[2]

**Comment by BraveJero** [comment]
The same happens to me. Random disconnects
