### ISSUE TITLE
the text cannot display properly

### ISSUE THREAD

**Issue by felixthian** [blueman-project/blueman#1285]
blueman:2.1.3
BlueZ:
Distribution:Parrot OS
Desktop environment: kde plasma 5.17.5

![image](https://user-images.githubusercontent.com/33191745/85946921-43cbf000-b937-11ea-9d61-e5b2881aef07.png)

Help, the text cannot display properly.

**Comment by cschramm** [comment]
🧐 Does Parrot OS use the original Debian package (version 2.1.3-2 signed by me) or use custom build a?

**Comment by felixthian** [comment]
Thanks, i solved it by reinstall the whole os.
