### ISSUE TITLE
Transfer to remote device doesn't notify when finished

### ISSUE THREAD

**Issue by rworkman** [blueman-project/blueman#129]
I just transferred a file to my phone, and the transfer completed successfully, but blueman did not notify when it was finished - it appeared to still be sending.

**Comment by cschramm** [comment]
Unfortunately I cannot reproduce this with neither a recent version of obexd nor 0.46.

Does it persist for you? If so, please open blueman/bluez/obex/Session.py and remove the props parameter from the reply_handler function definition around line 27 to see if that fixes the problem. In case it does, the first question is why. Does your obexd package contain the doc directory and a obex-client-api.txt in it? If so, please show me the prototype for SendFile from it.

**Comment by rworkman** [comment]
Behavior still persists. Removing props from reply_handler results in no change at all (file is still successfully sent, but still not notification - the window just stays open indefinitely). Here are all three API docs from obexd-0.48: http://slackware.com/~rworkman/obexd_docs/

Interestingly enough, either with or without the "props" change, I don't see any of the tracebacks that I was seeing when I originally reported this.

**Comment by cschramm** [comment]
If you're able to interactively debug or add some debugging statements to the Python code (you can use dprint for output), please try to trace the following things in the Session class:

* The send_file method (around line 26) gets called
* It calls the SendFile dbus method (around line 44)
* The supplied reply_handler (around line 27) gets called
* It calls the add_signal_receiver method on the bus (around line 36 for your obexd version)

Points 1 and 2 obviously succeed because otherwise the transfer would not happen. The exception pointed at a failure at point 3.

**Comment by rworkman** [comment]
Okay, I added a dprint right after ```self.__interface.SendFile``` and now with "props" left in there, this occurs right after SendFile is called:
```Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
TypeError: reply_handler() takes exactly 2 arguments (1 given)```

If I remove the "props" then this happens right after SendFile is called:
```Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/lib64/python2.7/site-packages/blueman/bluez/obex/Session.py", line 35, in reply_handler
    for prop, func in handlers:
ValueError: too many values to unpack```

I even downgraded obexd to 0.46 since that's working for you :/

**Comment by cschramm** [comment]
Nice, we got our exception back! :laughing: We can work with that.

The ValueError is my fault. I fixed that in https://github.com/blueman-project/blueman/commit/c03fdb4ede7760c07d9fd5c0ab063c9c80d1bc4e. I still have no idea why your obexd does not provide the props arguments as absolutely every documentation for the SendFile method I can find says it does, but I've added a fallback in https://github.com/blueman-project/blueman/commit/ae66cb849a7939848a7dd103b11d9e81e15340f8. Please test with the 129 branch.

**Comment by rworkman** [comment]
Re package or source, both - I'm building it from git. Basically, I change the version string in configure.ac to reflect the git hash, autogen.sh, make dist, and then build a package from that tarball. No patches (aside from those needed for a particular test, e.g. the ones in branch 129 this time).
Testing with 129, still no completion confirmation and there's this:
```Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/lib64/python2.7/site-packages/blueman/bluez/obex/Session.py", line 38, in reply_handler
    transfer_path)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 148, in add_signal_receiver
    path, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 414, in add_signal_receiver
    signal_name, handler_function, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 78, in __init__
    validate_object_path(object_path)
TypeError: must be string, not dbus.Struct```

**Comment by rworkman** [comment]
As an aside, in lines 36 and 37 of Session.py, should those two instances of "prop" be "props" instead?
In case it's not clear, python is not my native language :)

**Comment by cschramm** [comment]
No, that's correct. The `for prop, func in handlers.items()` takes each of the items of `handlers` and extracts them into the local `prop` and `func` variables, so `prop` can be each of the keywords in `handlers`.

Looks like the single argument your `reply_handler` gets is not the `transfer_path`, but a dbus struct which probably contains both `transfer_path` and the `props`. Then https://github.com/blueman-project/blueman/commit/b4dad178cda5aa04c61a07bf0c6aa8f06104e28a should print the struct including path and properties and then initialize `transfer_path` and `props` correctly.

I have no idea why this could happen. Maybe it's a problem with your dbus-python, but I'd expect more issues at other location then... :confused: 

(I've added the [bug fix](https://github.com/blueman-project/blueman/commit/b6e0546a11ea5339d7a00d188a0a8a2962db1117) to master)

**Comment by cschramm** [comment]
@rworkman 

> Then b4dad17 should print the struct including path and properties and then initialize transfer_path and props correctly.

Can you try that commit?

**Comment by rworkman** [comment]
Sorry for the delay - this got pushed down on my TODO list for various real life reasons. However, I am happy to report that it does indeed work as expected.

**Comment by cschramm** [comment]
OK, now I know what's going on in your case. I'm curious why that . I will prepare a test script to find that out if you're fine with getting a little deeper into this.

**Comment by rworkman** [comment]
Sure, I can do that.

**Comment by cschramm** [comment]
OK, I've prepared a test script to see on which abstraction layers - if any - the reply looks as expected and on which we see the dbus struct object.

Run it like `python2 script.py <sourceaddr> <destaddr> <file>` where `<sourceaddr>` is the hardware address (with colons) of your adapter and `<destaddr>` is the one of the destination device.

You should not get any errors, no matter what the replies are. So if it fails there's probably something wrong with the connection or my code.

````python
#! /usr/bin/python2

import dbus
from dbus.lowlevel import MethodCallMessage
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import Gtk
import sys
import os.path

if len(sys.argv) != 4:
    raise Exception("No source adapter, target device, and / or file specified")

adapter = sys.argv[1]
device = sys.argv[2]
filepath = os.path.abspath(sys.argv[3])

print("Adapter: " + adapter)
print("Device: " + device)
print("File: " + filepath)

legacy = True

if legacy:
    bus_name = 'org.bluez.obex.client'
    object_path = '/'
    client_interface_name = 'org.bluez.obex.Client'
    object_push_interface_name = 'org.bluez.obex.ObjectPush'
else:
    bus_name = 'org.bluez.obex'
    object_path = '/org/bluez/obex'
    client_interface_name = 'org.bluez.obex.Client1'
    object_push_interface_name = 'org.bluez.obex.ObjectPush1'

DBusGMainLoop(set_as_default=True)

client_interface = dbus.Interface(dbus.SessionBus().get_object(bus_name, object_path), client_interface_name)

session_path = client_interface.CreateSession(device, {'Source': adapter, 'Target': 'opp'})

session_interface = dbus.Interface(dbus.SessionBus().get_object(bus_name, session_path), object_push_interface_name)

def handler_func(message, next_test):
    def handler(*args):
        print(message, args)
        try:
            next_test()
        except Exception as e:
            print(e)
            exit(1)
    return handler

def msg_reply_handler(message):
    print('msg reply', message.get_args_list())
    exit()

def test_proxy():
    print('Testing proxy object...')
    session_interface.SendFile(filepath, reply_handler=handler_func('proxy reply', test_call_async), error_handler=handler_func('proxy error', test_call_async), timeout=30)

def test_call_async():
    print('Testing call_async...')
    dbus.SessionBus().call_async(bus_name, session_path, object_push_interface_name, 'SendFile', 's', [filepath], handler_func('call_async reply', test_send_message_with_reply), handler_func('call_async error', test_send_message_with_reply), 30)

def test_send_message_with_reply():
    print('Testing send_message_with_reply...')
    message = MethodCallMessage(destination=bus_name, path=session_path, interface=object_push_interface_name, method='SendFile')
    message.append(filepath, signature='s')
    dbus.SessionBus().send_message_with_reply(message, msg_reply_handler, 30)

test_proxy()

Gtk.main()
````

**Comment by cschramm** [comment]
:slot_machine:

**Comment by cschramm** [comment]
:moon:

**Comment by rworkman** [comment]
Crap, I just now saw this - the notification that I had a new message just now appeared. Odd. Sorry; I'll test this asap - hopefully tomorrow. In the meantime, I've updated to dbus-glib-0.104 and the NEWS file shows this, which is possibly related: 
• Don't trip a libdbus fatal warning if a Unix fd or other unsupported type is encountered in a message (fd.o #80557, Alban Crequy)

**Comment by rworkman** [comment]
It's simple enough, so let's do it now :-)
'''
[rworkman@liberty ~]$ ./blueman-test 00:16:CE:EB:9C:3A D0:DF:C7:4E:3E:6E /home/rworkman/MAILBOX-VANDALS 
Adapter: 00:16:CE:EB:9C:3A
Device: D0:DF:C7:4E:3E:6E
File: /home/rworkman/MAILBOX-VANDALS
Testing proxy object...
('proxy reply', (dbus.Struct((dbus.ObjectPath('/org/bluez/obex/session1/transfer3'), dbus.Dictionary({dbus.String(u'Filename'): dbus.String(u'/home/rworkman/MAILBOX-VANDALS', variant_level=1), dbus.String(u'Name'): dbus.String(u'MAILBOX-VANDALS', variant_level=1), dbus.String(u'Size'): dbus.UInt64(1598L, variant_level=1)}, signature=dbus.Signature('sv'))), signature=None),))
Testing call_async...
('call_async reply', (dbus.Struct((dbus.ObjectPath('/org/bluez/obex/session1/transfer4'), dbus.Dictionary({dbus.String(u'Filename'): dbus.String(u'/home/rworkman/MAILBOX-VANDALS', variant_level=1), dbus.String(u'Name'): dbus.String(u'MAILBOX-VANDALS', variant_level=1), dbus.String(u'Size'): dbus.UInt64(1598L, variant_level=1)}, signature=dbus.Signature('sv'))), signature=None),))
Testing send_message_with_reply...
('msg reply', [dbus.Struct((dbus.ObjectPath('/org/bluez/obex/session1/transfer5'), dbus.Dictionary({dbus.String(u'Filename'): dbus.String(u'/home/rworkman/MAILBOX-VANDALS', variant_level=1), dbus.String(u'Name'): dbus.String(u'MAILBOX-VANDALS', variant_level=1), dbus.String(u'Size'): dbus.UInt64(1598L, variant_level=1)}, signature=dbus.Signature('sv'))), signature=None)])
'''

**Comment by cschramm** [comment]
So you have the wrapping struct around the arguments on all levels. Looking at the source of obexd 0.48 (and 0.47) this is actually what I would expect and my statement that I cannot reproduce it with 0.46 is actually complete bullshit as it has a completely different interface and cannot work at all.

I added a generic handling for that in #196. Can you please test it (still branch 129)?

**Comment by rworkman** [comment]
Yep, it seems perfect now. Progress bar shows up and fills as the transfer takes place, disappears when it finishes, and Stop works as expected.  Thanks!
