### ISSUE TITLE
Bluetooth headset device - No battery indicator/status

### ISSUE THREAD

**Issue by kred-jon** [blueman-project/blueman#1291]
blueman: Version 5.53
BlueZ: 5.53-0ubuntu3
Distribution: Ubuntu 20.04
Desktop environment: Gnome

* [ *] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
See #947
