### ISSUE TITLE
My speaker doesn't autoconnect

### ISSUE THREAD

**Issue by mynameismisterbig** [blueman-project/blueman#1295]
blueman: 2.0.5
BlueZ: 5.48-0ubuntu3.4
Distribution: Bodhi Linux 5
Desktop environment: Moksha

* [X ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

My JBL speaker works fine, but doesn't autoconnect when I login, I have to select it from Recent Connections->Audio Sink to get my music to play! The "AutoEnable" is set to true in  /etc/bluetooth/main.conf as stated on your page.

**Comment by cschramm** [comment]
There is nothing that would make it auto-connect (apart from the speaker itself). An auto-connect feature is planned for blueman 2.2 and the functionality itself is already available in master but the UI parts are missing, see https://github.com/blueman-project/blueman/issues/239.
