### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by silocoder** [blueman-project/blueman#1297]
Linuxmint 20
blueman-applet 2.1.2

The bluetooth icon in tray keeps hiding and re-appearing when there is a scan for devices. Very annoying.

**Comment by cschramm** [comment]
Do you use the AppIndicator plugin? Is it the same if you disable it? What do you mean with "there is a scan for devices"? Running the discovery from blueman-manager?

Please provide the blueman-applet output of that process. Also, a short screencast might be helpful.

**Comment by silocoder** [comment]
I think there may have been a conflict with the other bluetooth applet that comes with Linuxmint.  I removed it and don't seem to have that problem. I will see. Thanks
