### ISSUE TITLE
Clicking 'Devices' in the tray kills blueman-manager if it's already open

### ISSUE THREAD

**Issue by j-piecuch** [blueman-project/blueman#1302]
blueman: revision [8b0a563c5d2305da712ef57ae2ffe627121d884a](https://github.com/blueman-project/blueman/tree/8b0a563c5d2305da712ef57ae2ffe627121d884a)
BlueZ: 5.53
Distribution: Ubuntu 20.04
Desktop environment: GNOME 3.3

On current master, as well as the blueman version in Ubuntu repositories (2.1.2), the following behavior can be observed:
![Screencast from 22 07 2020 11 23 49](https://user-images.githubusercontent.com/17250100/88162036-14946000-cc11-11ea-99ba-87db196d007f.gif)

I'm not sure this is intended. The culprit is here: https://github.com/blueman-project/blueman/blob/8b0a563c5d2305da712ef57ae2ffe627121d884a/blueman/plugins/applet/StandardItems.py#L76-L80
`on_devices()` kills the running instance of blueman-manager without spawning another one.
A fix would be to simply launch blueman-manager unconditionally, and let `check_single_instance()` do the job.
I can submit a PR with the change, just let me know if this is indeed a bug.

**Comment by infirit** [comment]
This is how it is intended to work, not a bug 😃
