### ISSUE TITLE
Auto-receive files from trusted devices is broken

### ISSUE THREAD

**Issue by piotrgazda75** [blueman-project/blueman#1310]
blueman: 2.1.2-1
BlueZ: 5.53-0ubuntu3
Distribution: Mint 20 amd64
Desktop environment: MATE 1.24.0

Hello!

I have my HUAWEI P20 Pro paired and trusted and every time I send to my MSI GP73 laptop one or few files I have to click "Accept" for EVERY single file. This is definitely not right :-(

Best regards
Peter

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
There should be an "Always accept" option next to "Accept" that enables such an "auto-receive". Trusting a device has nothing to do with that.

**Comment by piotrgazda75** [comment]
Hello!

Looks like they forgot about it. Please, check the screenshot in
attachment. There are only "Accept" and "Reject" options. I think
MATE's devs should be informed.

Best regards
Piotr Gazda

**Comment by cschramm** [comment]
![No screenshot](https://media0.giphy.com/media/VIQfHC9jAZbt6ojTdo/giphy.gif?cid=82a1493blqygei13tebcjxugzakwjzd4yvdn9vw0srmut8tt&rid=giphy.gif)

Might be a shortcoming of your notification daemon. Not sure right now. Will check the code.

**Comment by cschramm** [comment]
Looks like I was completely wrong about this, sorry. ("Always accept" exists for incoming service connections, not for incoming files, and sets the device to trusted.) There is a configuration to make it work as you expect. From the tray icon's context menu open "Local Services", and tick "Accept files from trusted devices" for the "Transfer" service.
