### ISSUE TITLE
Sap driver initialization failed

### ISSUE THREAD

**Issue by souviksenapati** [blueman-project/blueman#1313]
root@kali:~# service bluetooth status
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2020-07-31 20:43:08 IST; 14min ago
       Docs: man:bluetoothd(8)
   Main PID: 23454 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 4539)
     Memory: 1.1M
     CGroup: /system.slice/bluetooth.service
             └─23454 /usr/lib/bluetooth/bluetoothd

Jul 31 20:53:38 kali bluetoothd[23454]: Sap driver initialization failed.
Jul 31 20:53:38 kali bluetoothd[23454]: sap-server: Operation not permitted (1)
Jul 31 20:53:38 kali bluetoothd[23454]: Endpoint registered: sender=:1.57 path=/MediaEndpoint/A2DPSink/sbc
Jul 31 20:53:38 kali bluetoothd[23454]: Endpoint registered: sender=:1.57 path=/MediaEndpoint/A2DPSource/sbc
Jul 31 20:53:55 kali bluetoothd[23454]: Endpoint unregistered: sender=:1.57 path=/MediaEndpoint/A2DPSink/sbc
Jul 31 20:53:55 kali bluetoothd[23454]: Endpoint unregistered: sender=:1.57 path=/MediaEndpoint/A2DPSource/sbc
Jul 31 20:54:01 kali bluetoothd[23454]: Sap driver initialization failed.
Jul 31 20:54:01 kali bluetoothd[23454]: sap-server: Operation not permitted (1)
Jul 31 20:54:01 kali bluetoothd[23454]: Endpoint registered: sender=:1.57 path=/MediaEndpoint/A2DPSink/sbc
Jul 31 20:54:01 kali bluetoothd[23454]: Endpoint registered: sender=:1.57 path=/MediaEndpoint/A2DPSource/sbc

**Comment by cschramm** [comment]
First of, this is the blueman project, offering a BlueZ GUI. See http://www.bluez.org/contact/ for BlueZ itself.

Those SAP errors are harmless and make sense as you have SAP enabled but most probably no hardware for it. You can disable that BlueZ functionality by starting `bluetoothd` with `--noplugin=sap`.
