### ISSUE TITLE
Discover other BT services than AP, Headset, and Audio Source

### ISSUE THREAD

**Issue by NHerreroReder** [blueman-project/blueman#1331]
blueman: 2.0.8-1
BlueZ: 5.50-1.2~deb10u1
Distribution: Linux version 4.19.0-10-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.132-1 (2020-07-24)
Desktop environment: XFCE

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

(Mouse Right Button)). I don't know if it is a Blueman limitation or I must do anything more.
Can Blueman, also, discover BT mouse or joystick services? Thanks in advance. Regards.

**Comment by cschramm** [comment]
Just like audio services, HID services get connected with the generic connect entry in that device menu.
