### ISSUE TITLE
Remember last profile ?

### ISSUE THREAD

**Issue by joakim-tjernlund** [blueman-project/blueman#1372]
blueman: master 11/08/20
BlueZ: master
Distribution: Gentoo
Desktop environment: MATE

* [ X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

blueman usually select an A2DP profile when I reconnect. It would be nice if blueman could remember the profile I had before.

BTW, time for a new 2.1.x release?

**Comment by cschramm** [comment]
The profile selection blueman offer's is just an interface to pulseaudio. You can add `set-card-profile` statements to `/etc/pulse/default.pa` to set a default profile.
