### ISSUE TITLE
Feature Request: desktop notifications for connect / disconnect

### ISSUE THREAD

**Issue by hissssst** [blueman-project/blueman#1374]
First of all, thank you for this awesome software

I'd like to open discussion about desktop notifications with blueman.
It would be nice to have notifications sent when device connects/disconnects

**Comment by infirit** [comment]
I am not against adding a notification but not without a proper use case. Can you be more specific in which situation this may be useful and how it would help you?

**Comment by hissssst** [comment]
I would like to receive notifications when device connects/disconnects. It's useful because I am connected to multiple bt-headsets at one time and some of them can disconnect when they are out of battery.

It would be nice to receive notification like `Device Headset Pro (12:34:56:78:ab:cd) disconnected`

**Comment by cschramm** [comment]
Makes perfect sense to me. Usually you do not need it as the status icon change is sufficient if you use just one device at a time but you lack that feedback if you use multiple.
