### ISSUE TITLE
Bluetooth manager cant detect devices - Ubuntu OS

### ISSUE THREAD

**Issue by rdprabhu2167** [blueman-project/blueman#1385]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I am new to Ubuntu and Github (but have n years of experience working in the Unix environment..so its all coming back to me!! My problem is ..my laptop bluetooth manager refuses to detect any bluetooth devices around. I tried one solution ..i.e copying the missing *.hcd file and copying it in the said location ..rebooting the system. Didnt work ..any suggestions ?
the solution I tried was found here : 
https://askubuntu.com/questions/1091888/bluetooth-not-finding-any-devices-ubuntu-18-04

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Most probably a firmware issue, yes, but could you please provide basic information and output of such a discovery process from blueman-applet so that we can take a look?

**Comment by ellitrym1** [comment]
Similar issue,
It was working fine but now whenever i search for a bluetooth device, nothing shows up even tho the device is visible. Plus after hitting the search button, the button becomes unclickable unless you restart the app itself.

**Comment by cschramm** [comment]
@ellitrym1: Similar issue => same information required.

**Comment by Tanmay-Chavan** [comment]
the same issue, the only difference being I tried to install aptX support, and it got messed up the same as above.

**Comment by cschramm** [comment]
@Tanmay-Chavan: As you demonstrated it with bluetoothctl, it's clearly not an issue with blueman.

**Comment by Tanmay-Chavan** [comment]
Oh okay, thanks. I know this is tangential to the original point, but can you suggest any fix?

**Comment by cschramm** [comment]
@Tanmay-Chavan: In generals it's probably related to kernel / driver / firmware. Apart from checking the syslog, I'd look up the chip you're using and commit a web search on others' experience with it and Linux (Ubuntu 20.04 I guess). From your specific description, it sounds like it used to work, then you tried to install aptX support, and then it did not work anymore. That sounds like overlooked some effect of your aptX adventures that you did not and still should revert to get it back working.
