### ISSUE TITLE
Connection Problem on Raspbian

### ISSUE THREAD

**Issue by MartinsMaker** [blueman-project/blueman#1386]
Good evening everyone ,I'm trying to connect my headphones (speaker/microphone) to a raspberry pi 3, but when I try to connect them 
     I receive this error "connection failed:blueman.bluez.errors.DBusFailedError: input/output error", so I tried also with another device but I get the same error.
     What can I do ?
      Someone had the same problem as me?
      I want to use my headphones to do some speech recognition tests so I need to use the built-in microphone.

**Comment by cschramm** [comment]
input/output error hints at some driver issue. Did you try a more recent kernel?
