### ISSUE TITLE
Implementing "Reset"  in code 

### ISSUE THREAD

**Issue by JulyJim** [blueman-project/blueman#1388]
blueman: 2.0.4 
BlueZ:  ??
Distribution: Ubuntu 16 04 
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.
I am developing bluetooth C++ application.
I can successfully originally “scan for nearby devices” , No problem. 
however, I am unable to  successfully repeat the discovery UNTIL I “Remove”  found devices using “Bluetooth Manager”.  I am not connecting / paring / communicating  – just what to make sure I can reliably , repeatably “scan for nearby devices” . I am not sure how OS , Bluetooth Manager and my application interacts, however until I resolve that  - HOW / WHERE can I find “Bluetooth Manager “ code to implement “Remove” ? It would help immensely during my code development.  ( assuming it is not trade secret , but Open source )   
Thanks 
->

**Comment by JulyJim** [comment]
OK , I got here 

blueman/blueman/bluez/Adapter.py 

Is that a start ?  I am not that versed in Python, but will this lead to "blueZ"  ? I prefer to eliminate "high" level wrappers  if possible.

**Comment by cschramm** [comment]
I have no idea what this ticket is about. 🤷‍♂️

**Comment by JulyJim** [comment]
Per your site instructions I can as for assistance, But if you do not get it , just let somebody else reply. 

    On Friday, September 25, 2020, 12:26:34 PM CDT, Christopher Schramm <notifications@github.com> wrote:  
 
 


I have no idea what this ticket is about. 🤷‍♂️

**Comment by infirit** [comment]
> But if you do not get it , just let somebody else reply.

There are 2 of us, @cschramm and me and I also do not understand what this is about..

**Comment by JulyJim** [comment]
On Friday, September 25, 2020, 7:26:45 PM CDT, Sander Sweers <notifications@github.com> wrote:  
 OK, I need to know how  is "Remove"  implemented in " Bluetooth Manager " any references to actual code hopefully leading to "blueZ" source code.  
 



But if you do not get it , just let somebody else reply.


There are 2 of us, @cschramm and me and I also do not understand what this is about..

**Comment by cschramm** [comment]
It's a DBus call to `org.bluez`, interface `org.bluez.Adapter1` on the respective adapter's object path, method `RemoveDevice`.

**Comment by infirit** [comment]
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt

**Comment by JulyJim** [comment]
BluetoothManager FYI 

Ido not know the sequence of replies I have received. 

Hereare my thoughts, in no particular order. 

Thelink referenced apparently makes no distinction between “adapter”and “device”.

However,it implies that “stopping the scan” will erase something – I amnot sure if Qt will work that way. 

Frommy research so far it looks that Qt will NOT perform physical searchAFTER the API is used first time. So my “hack” will be to NOTuse Qt for “scan for nearby devices”. 

Icannot prove it now , but I think “Bluetooth Manager” works sameway – it will enable “Scan” only once up front. Perhaps thedesigner logic was – why scan second time…things do not change (?) ... 


 Asfar as arbitrary closingmypost– it must be more important to maintaing clean slate instead ofresolving issues and letting the customer know.

Thisgives an impression you , owner of the site, do not give a hoot aboutcustomer – and do not care to receive feedback. ( So disregard whatI just posted ).
CASE CLOSED no reply necessary 





    On Saturday, September 26, 2020, 6:37:54 AM CDT, Sander Sweers <notifications@github.com> wrote:  
 
 


https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt

**Comment by cschramm** [comment]
I honestly still don't have the slightest idea what your wish is. Ticket is closed as it seemed to be to know what blueman does when you click "Remove" and we provided the simple answer.

We're not owners of this site (GitHub) and do not have customers (if you're willing to pay for our volunteer work, you're welcome to beta-test our halfway set up Open Collective https://opencollective.com/blueman).

**Comment by infirit** [comment]
I think you are seriously confused what blueman is and how it interacts with the underlying kernel bluetooth subsystem.

**Comment by JulyJim** [comment]
Well, thanks for the offer, but I am not interested in being insulted ( ",,,you are confused ...")  nor working with a group who cannot read  - I asked HOW  is "Reset"  implemented in "Bluetooth Manager" - simple as that .
Have a swell day. 


    On Saturday, September 26, 2020, 10:48:35 AM CDT, Christopher Schramm <notifications@github.com> wrote:  
 
 


I honestly still don't have the slightest idea what your wish is. Ticket is closed as it seemed to be to know what blueman does when you click "Remove" and we provided the simple answer.

We're not owners of this site (GitHub) and do not have customers (if you're willing to pay for our volunteer work, you're welcome to beta-test our halfway set up Open Collective https://opencollective.com/blueman).

**Comment by JulyJim** [comment]
Yes, I am seriously confused.Please enlighten  me 
How does this complicated process works ? 

1. Open Bluetooth Manager.2. Push "scan" to "Scan for nearby devices" . 
3. Bluetooth Manager shows , after noticeable delays as expected - THREE discovered devices. 
4. UNPLUG ONE OF THE DISCOVERED DEVICES!5. Push "scan" AGAIN to "Scan for nearby devices" . 
6. Bluetooth Manager IMMEDIATELY , STILL  shows THREE discovered devices. 

Magic?  
Perhaps special feature  " interacting the underlying kernel bluetooth subsystem "  ? 

BUG ! 

Don't bother to fix it, you could get hurt using your voluntary  brain. 

Cheers 


    On Saturday, September 26, 2020, 3:09:28 PM CDT, Sander Sweers <notifications@github.com> wrote:  
 
 


I think you are seriously confused what blueman is and how it interacts with the underlying kernel bluetooth subsystem.

**Comment by cschramm** [comment]
Not eager to talk to insulting, confusing people, but let's try one more time.

> 1. Open Bluetooth Manager.
> 2. Push "scan" to "Scan for nearby devices" .
> 3. Bluetooth Manager shows , after noticeable delays as expected - THREE discovered devices.
> 4. UNPLUG ONE OF THE DISCOVERED DEVICES!

Unplug WHAT from WHERE? (Sorry for the caps, I'm just trying to adapt a little bit.)

> 5. Push "scan" AGAIN to "Scan for nearby devices" .
> 6. Bluetooth Manager IMMEDIATELY , STILL  shows THREE discovered devices.

blueman-manager ALWAYS shows ALL devices currently provided by BlueZ. Unless you REMOVED one, AWAITED THE TIMEOUT after which BlueZ removes temporary devices automatically (should be three minutes, see https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/src/adapter.c?id=36441825004c70c81ff72915c51e0e60b30d91ff#n77), or DISCOVERED A NEW ONE during the second scan, it is more than expected behavior of BlueZ that nothing changed. If you want to tell people over there, that that's a bug, please see http://www.bluez.org/contact/, but consider that you might just insult and confuse them.

**Comment by JulyJim** [comment]
How irrelevant can you get ?CAN YOU READ ?Please STOP replying with nonsense.Have a great day . 


    On Monday, September 28, 2020, 2:12:57 AM CDT, Christopher Schramm <notifications@github.com> wrote:  
 
 


Not eager to talk to insulting, confusing people, but let's try one more time.

   
   - Open Bluetooth Manager.
   - Push "scan" to "Scan for nearby devices" .
   - Bluetooth Manager shows , after noticeable delays as expected - THREE discovered devices.
   - UNPLUG ONE OF THE DISCOVERED DEVICES!


Unplug WHAT from WHERE? (Sorry for the caps, I'm just trying to adapt a little bit.)

   
   - Push "scan" AGAIN to "Scan for nearby devices" .
   - Bluetooth Manager IMMEDIATELY , STILL shows THREE discovered devices.


blueman-manager ALWAYS shows ALL devices currently provided by BlueZ. Unless you REMOVED one, AWAITED THE TIMEOUT after which BlueZ removes temporary devices automatically (should be three minutes, see https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/src/adapter.c?id=36441825004c70c81ff72915c51e0e60b30d91ff#n77), or DISCOVERED A NEW ONE during the second scan, it is more than expected behavior of BlueZ that nothing changed. If you want to tell people over there, that that's a bug, please see http://www.bluez.org/contact/, but consider that you might just insult and confuse them.
