### ISSUE TITLE
Bluetooth worked first day, now not able to connect

### ISSUE THREAD

**Issue by tadsn3w** [blueman-project/blueman#1397]
blueman: 2.1.2
BlueZ:
Distribution: Linux Mint 20
Desktop environment: Cinamon

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

Install ASUS Dual Band 802.11AC Wireless-AC2100 PCI-e Bluetooth 5 Gigabit WiFi Adapter, 160MHz Support (PCE-AC58BT) and it worked the first day (sort of)
Watching a video worked.  I stopped the video for 5 minues,and I couldn't hear any sound after that.
I tried everything, killall process, etc. restarting sound, etc. nothing.
I had to reboot and it worked again, until I stopped the video for more than 5 minutes.
Today next day, I couldn't connect at all.  Blueman shows my headset, but I got a message (Not able to connect. Resource not ready).  I logged out and reboot nothing.
->

**Comment by cschramm** [comment]
Please check the troubleshooting page and provide a log from blueman-applet that shows the failing connection attempt.
