### ISSUE TITLE
error connecting bluetooth in mx linux

### ISSUE THREAD

**Issue by Caeliiaa** [blueman-project/blueman#1401]
hello,

I have mx linux installed as the operating system on my laptop, but I have tried to connect with my cell phone by bluetooth and it does not recognize any device, I have even tried with other devices.

system information:

> $ inxi -Fxz
System:    Host: mx Kernel: 5.8.0-0.bpo.2-amd64 x86_64 bits: 64 compiler: N/A 
           Desktop: Xfce 4.14.2 Distro: MX-19.2_x64 patito feo May 31  2020 
           base: Debian GNU/Linux 10 (buster) 
Machine:   Type: Laptop System: Hewlett-Packard product: HP 245 G7 Notebook PC v: N/A 
           serial: <filter> 
           Mobo: Hewlett-Packard model: 8560 v: 83.44 serial: <filter> UEFI: AMI v: F.53 
           date: 12/27/2019 
Battery:   ID-1: BAT0 charge: 38.8 Wh condition: 41.0/41.0 Wh (100%) 
           model: Hewlett-Packard Primary status: Charging 
CPU:       Topology: Dual Core model: AMD E2-9000e RADEON R2 4 COMPUTE CORES 2C+2G bits: 64 
           type: MCP arch: Excavator L2 cache: 1024 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 5988 
           Speed: 1091 MHz min/max: 1100/1500 MHz Core speeds (MHz): 1: 1093 2: 1090 
Graphics:  Device-1: AMD Stoney [Radeon R2/R3/R4/R5 Graphics] vendor: Hewlett-Packard 
           driver: amdgpu v: kernel bus ID: 00:01.0 
           Display: x11 server: X.Org 1.20.4 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: AMD STONEY (DRM 3.38.0 5.8.0-0.bpo.2-amd64 LLVM 7.0.1) 
           v: 4.5 Mesa 18.3.6 direct render: Yes 
Audio:     Device-1: AMD vendor: Hewlett-Packard driver: snd_hda_intel v: kernel bus ID: 00:01.1 
           Device-2: AMD Family 15h Audio vendor: Hewlett-Packard driver: snd_hda_intel 
           v: kernel bus ID: 00:09.2 
           Sound Server: ALSA v: k5.8.0-0.bpo.2-amd64 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
           vendor: Hewlett-Packard driver: r8169 v: kernel port: e000 bus ID: 02:00.0 
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Realtek RTL8723DE 802.11b/g/n PCIe Adapter vendor: Hewlett-Packard 
           driver: N/A port: d000 bus ID: 03:00.0 
Drives:    Local Storage: total: 465.76 GiB used: 12.08 GiB (2.6%) 
           ID-1: /dev/sda vendor: Toshiba model: MQ01ACF050 size: 465.76 GiB temp: 44 C 
Partition: ID-1: / size: 86.01 GiB used: 12.03 GiB (14.0%) fs: ext4 dev: /dev/sda4 
Sensors:   System Temperatures: cpu: 54.1 C mobo: N/A gpu: amdgpu temp: 0 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 215 Uptime: 42m Memory: 3.31 GiB used: 1.46 GiB (44.1%) Init: SysVinit 
           runlevel: 5 Compilers: gcc: 8.3.0 Shell: bash v: 5.0.3 inxi: 3.0.36 

I do not know if it will be an error of mx linux, but I can not connect by wifi either.
I have dualboot installed with windows, and if I start windows the wifi works perfectly

**Comment by cschramm** [comment]
Please provide output of the attempted device discovery from `blueman-applet --loglevel debug` and check `dmesg` for errors while running it.
