### ISSUE TITLE
Annoying things - Blue Tooth Beeps.

### ISSUE THREAD

**Issue by Phuxxi** [blueman-project/blueman#1408]
The only device I have that does this is the Mint OS on a laptop.

When the bluetooth speaker is running a signal from an active video or audio player.... it just runs and it's fine.

But when I stop the video / audio - the blue tooth software in the laptop, sends a beep every two minutes to remind me that the blue tooth sender is idle.

I do not need a beep every two minutes to remind me that I have paused the audio (or the program producing the audio).

Now I HAVE looked in the power settings, the bluetooth settings and the sound settings , looking for a way to turn this annoying unhelpful "deedoo" sound off, but I have not as yet found it.

It's unnecessary and annoying and needs to be deleted from the OS / software.

Does anyone have any experience in killing off this idiot "reminder" function, because if you can help me, both to get rid of it and have it eliminated from the OS / software, it would be really appreciated.

**Comment by cschramm** [comment]
Hi, I've never heard of such a thing. Why do you think it's the laptop? It rather sounds like a "feature" of the speaker to me.
