### ISSUE TITLE
obexd cannot be started under Debian with latest bluez-obexd (5.55-1) 

### ISSUE THREAD

**Issue by akoun** [blueman-project/blueman#1430]
blueman: 2.3.1
BlueZ: 5.55-1
Distribution: Debian GNU/Linux bullseye/sid
Desktop environment: XFCE

with version bluez-obexd (5.55-1) under Debian Bullseye the obexd daemon cannot start when I enable the transfer plugin and I get the following error in /var/log/daemon.log
**dbus-daemon[2739]: [session uid=1000 pid=2737] Activated service 'org.bluez.obex' failed: Failed to execute program org.bluez.obex: No such file or directory**

consequently no file transfer is possible via bluetooth.

BUT when I downgrade to bluez-obexd (5.50-1.2~deb10u1) everything works fine!
thank you
<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
I cannot confirm that.

`systemctl status --user dbus-org.bluez.obex.service`?

**Comment by akoun** [comment]
> systemctl status --user dbus-org.bluez.obex.service
> Unit dbus-org.bluez.obex.service could not be found.

I think the following is relevant as well
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972070

**Comment by cschramm** [comment]
Sounds like an issue with that Debian package then. Definitely not blueman specific as the reporter uses bluedevil. Also, I'm using Debian and bluez-obexd 5.55-1 works for me, so it is not a generic issue.
