### ISSUE TITLE
I want a driver for my device bluetooth. the lubuntu do not work. that do not connect this bluetooth for earphone.

### ISSUE THREAD

**Issue by anestis12** [blueman-project/blueman#1435]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Drivers are not in the scope of the blueman project.
