### ISSUE TITLE
problems with connection

### ISSUE THREAD

**Issue by plynpool** [blueman-project/blueman#1438]
blueman:
BlueZ:
Distribution:
Desktop environment:
I am not sure what the problem is but the program was working at first but now for some it will not. I have tried removing my device and reinstalling it but still the device will not work. I am using a Bose Sound Link bluetooth speaker. Thanks in advance for any help offered. 
* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by Geoniboy** [comment]
Hello, I think I have the same problem?
I have found something that seems to (usually) work?
In a terminal type; 

sudo rfkill unblock bluetooth

Enter your password

Re-start your computer

This is the only thing that seems to get a result for me?
Not an actual fix, but hopefully somebody more knowledgeable will be able to come up with an actual fix?

Cheers! Best of luck!

jw.
