### ISSUE TITLE
Cant pair MX keys from Logitech

### ISSUE THREAD

**Issue by jpstijn** [blueman-project/blueman#1449]
blueman: 2.1.2-1ubuntu0.2
BlueZ:
Distribution:
Desktop environment: Ubuntu 20.04.1 LTS

I am using the blueman bluetooth manager to connect a MS Anywhere 2 mouse en MX keys Logitech keyboard but i cant pair my MS keys. 

![image](https://user-images.githubusercontent.com/24881734/100648782-bb1c0a80-3341-11eb-88ce-353d16f4291a.png)

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by cschramm** [comment]
Don't you mean MX Keys? Then I guess you're missing some firmware, see #1412. I'm really puzzled why some missing firmware doesn't keep the adapter from functioning but from handling the pairing process for that one specific device... 😄

**Comment by infirit** [comment]
>I'm really puzzled why some missing firmware doesn't keep the adapter from functioning but from handling the pairing process for that one specific device...

This is what happens with my old BCM20702A1 dongle. If I remember correctly the firmware unlocks Bluetooth 4 functionality. So pairing will work but the moment I tried to use any of the Bluetooth 4 functionality it fails.

**Comment by cschramm** [comment]
@infirit What seems to be failing here and in #1412 is pairing the MX Keys and it does not even result in an obvious error (there might be something in the bluetoothd logs, of course), just not show the passkey, but, yes, an existing (fallback) driver / firmware not handling forwarding a certain event, could be the explanation. :thinking:

**Comment by jpstijn** [comment]
> Don't you mean MX Keys? Then I guess you're missing some firmware, see #1412. I'm really puzzled why some missing firmware doesn't keep the adapter from functioning but from handling the pairing process for that one specific device... 😄

Yes i did mean MX keys

**Comment by jpstijn** [comment]
Its indeed some sort of the same issue i do not get prompt for a key and i just says it failed.
