### ISSUE TITLE
Please store bluetooth device settings permanently

### ISSUE THREAD

**Issue by Greenbear59** [blueman-project/blueman#1452]
blueman: 2.1.2
BlueZ: 5.53-0ubuntu3
Distribution: Ubuntu 20.04.1
Desktop environment: Xfce

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Every i connect my headset (freeVoice Space FBT650BTS) i have first tell the system that this is a headset rather than a listen only device (Audio Profile) which is annoying.
⇒ Please store these settings permanently

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
See #1167 #1372
