### ISSUE TITLE
Bulid and install on Raspberry 4B failed

### ISSUE THREAD

**Issue by lixunhui** [blueman-project/blueman#1463]
PyGObject 3.38.0
![image](https://user-images.githubusercontent.com/4917509/101733604-185e4b80-3afa-11eb-9bc8-81ec46584241.png)
`./autogen.sh`
![image](https://user-images.githubusercontent.com/4917509/101733465-e51bbc80-3af9-11eb-8adc-1085ce1a1804.png)

**Comment by cschramm** [comment]
That does not look like a version mismatch, but your `pkg-config` does not seem to have `pygobject-3.0` at all.

**Comment by infirit** [comment]
Distribution, blueman version?
