### ISSUE TITLE
"Disconnect <device>" tray option remains after turning off bluetooth by suspending the system.

### ISSUE THREAD

**Issue by j-piecuch** [blueman-project/blueman#1464]
blueman: `2.1.r422.ged861d1c` (`blueman-git` from AUR)
BlueZ: 5.55-1
Distribution: Manjaro
Desktop environment: i3

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

## Description:
On my laptop, if I suspend (e.g. by closing the lid) while my bluetooth headphones are connected, they are disconnected properly. After resuming, the "Disconnect &lt;device&gt;" option remains in the tray, even though the device was disconnected and bluetooth is turned off.

Screenshot:
![blueman](https://user-images.githubusercontent.com/17250100/101806893-cbd43980-3b14-11eb-8ea5-53629f94d5b0.png)

## Steps to reproduce:
- Connect to a device
- Suspend the system (e.g. `systemctl suspend`)
- Resume the system
- The "Disconnect &lt;device&gt;" option will still be visible in the tray.

**Comment by cschramm** [comment]
Thanks for reporting. Fixed.
