### ISSUE TITLE
blueman-applet 12.23.31 ERROR    PluginManager:91 load_plugin: Unable to load plugin module KillSwitch

### ISSUE THREAD

**Issue by Midigich** [blueman-project/blueman#1492]
blueman-applet 12.23.31 ERROR    PluginManager:91 load_plugin: Unable to load plugin module KillSwitch
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 89, in load_plugin
    importlib.import_module(self.module_path.__name__ + ".%s" % plugin)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py", line 23, in <module>
    raise ImportError('Hardware kill switch not found')
ImportError: Hardware kill switch not found
blueman-applet 12.23.32 WARNING  PluginManager:148 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-tray version 2.1.4 starting
blueman-tray version 2.1.4 starting
There is an instance already running
Exiting due to channel error.

###!!! [Parent][MessageChannel] Error: (msgtype=0x39000A,name=PContent::Msg_InitProfiler) Channel error: cannot send/recv

[Parent 124, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-esr-mwtdDv/firefox-esr-78.6.1esr/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19

###!!! [Parent][MessageChannel] Error: (msgtype=0x390060,name=PContent::Msg_SetPermissionsWithKey) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39005C,name=PContent::Msg_GMPsChanged) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390073,name=PContent::Msg_RegisterBrowsingContextGroup) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390002,name=PContent::Msg_ConstructBrowser) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012C,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2100A4,name=PBrowser::Msg_SetWidgetNativeData) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012C,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006B,name=PBrowser::Msg_InitRendering) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21009C,name=PBrowser::Msg_SafeAreaInsetsChanged) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210067,name=PBrowser::Msg_Show) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210095,name=PBrowser::Msg_SetDocShellIsActive) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006F,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv

Exiting due to channel error.
blueman-applet 12.23.39 ERROR    BasePlugin:76 _load     : Error calling StartServiceByName for org.blueman.Mechanism: Launch helper exited with unknown return code 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 36, in __init__
    self.init()
gi.repository.GLib.GError: g-dbus-error-quark: Error calling StartServiceByName for org.blueman.Mechanism: Launch helper exited with unknown return code 1 (25)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 24, in on_load
    self.load_nap_settings()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 45, in load_nap_settings
    m = Mechanism()
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 15, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 43, in __init__
    super().__init__(name='org.blueman.Mechanism', interface_name='org.blueman.Mechanism',
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 38, in __init__
    raise DBusProxyFailed(e.message)
blueman.main.DBusProxies.DBusProxyFailed: Error calling StartServiceByName for org.blueman.Mechanism: Launch helper exited with unknown return code 1
blueman-applet 12.23.39 ERROR    PluginManager:162 __load_plugin: Failed to load Networking
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 36, in __init__
    self.init()
gi.repository.GLib.GError: g-dbus-error-quark: Error calling StartServiceByName for org.blueman.Mechanism: Launch helper exited with unknown return code 1 (25)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 160, in __load_plugin
    inst._load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/AppletPlugin.py", line 57, in _load
    super()._load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 24, in on_load
    self.load_nap_settings()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 45, in load_nap_settings
    m = Mechanism()
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 15, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 43, in __init__
    super().__init__(name='org.blueman.Mechanism', interface_name='org.blueman.Mechanism',
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 38, in __init__
    raise DBusProxyFailed(e.message)
blueman.main.DBusProxies.DBusProxyFailed: Error calling StartServiceByName for org.blueman.Mechanism: Launch helper exited with unknown return code 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 36, in __init__
    self.init()
gi.repository.GLib.Error: g-dbus-error-quark: Error calling StartServiceByName for org.blueman.Mechanism: Launch helper exited with unknown return code 1 (25)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/blueman-applet", line 42, in <module>
    BluemanApplet()
  File "/usr/lib/python3/dist-packages/blueman/main/Applet.py", line 34, in __init__
    self.Plugins.load_plugin()
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 122, in load_plugin
    self.__load_plugin(cls)
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 160, in __load_plugin
    inst._load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/AppletPlugin.py", line 57, in _load
    super()._load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 24, in on_load
    self.load_nap_settings()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 45, in load_nap_settings
    m = Mechanism()
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 15, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 43, in __init__
    super().__init__(name='org.blueman.Mechanism', interface_name='org.blueman.Mechanism',
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 38, in __init__
    raise DBusProxyFailed(e.message)
blueman.main.DBusProxies.DBusProxyFailed: Error calling StartServiceByName for org.blueman.Mechanism: Launch helper exited with unknown return code 1

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006B,name=PBrowser::Msg_InitRendering) Channel error: cannot send/recv

Exiting due to channel error.

###!!! [Parent][MessageChannel] Error: (msgtype=0x21009C,name=PBrowser::Msg_SafeAreaInsetsChanged) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210067,name=PBrowser::Msg_Show) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006D,name=PBrowser::Msg_LoadURL) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390073,name=PContent::Msg_RegisterBrowsingContextGroup) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390002,name=PContent::Msg_ConstructBrowser) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012C,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012C,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006B,name=PBrowser::Msg_InitRendering) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21009C,name=PBrowser::Msg_SafeAreaInsetsChanged) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210067,name=PBrowser::Msg_Show) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006D,name=PBrowser::Msg_LoadURL) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390073,name=PContent::Msg_RegisterBrowsingContextGroup) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390002,name=PContent::Msg_ConstructBrowser) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012C,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012C,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006B,name=PBrowser::Msg_InitRendering) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21009C,name=PBrowser::Msg_SafeAreaInsetsChanged) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210067,name=PBrowser::Msg_Show) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006D,name=PBrowser::Msg_LoadURL) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390073,name=PContent::Msg_RegisterBrowsingContextGroup) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390002,name=PContent::Msg_ConstructBrowser) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012C,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012C,name=PContent::Msg_CommitBrowsingContextTransaction) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006B,name=PBrowser::Msg_InitRendering) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21009C,name=PBrowser::Msg_SafeAreaInsetsChanged) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210067,name=PBrowser::Msg_Show) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006D,name=PBrowser::Msg_LoadURL) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210001,name=PBrowser::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390074,name=PContent::Msg_LoadURI) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210001,name=PBrowser::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390074,name=PContent::Msg_LoadURI) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210001,name=PBrowser::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390074,name=PContent::Msg_LoadURI) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210093,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210001,name=PBrowser::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390074,name=PContent::Msg_LoadURI) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006F,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006F,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006F,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21006F,name=PBrowser::Msg_UpdateDimensions) Channel error: cannot send/recv

Exiting due to channel error.

###!!! [Parent][MessageChannel] Error: (msgtype=0x21004D,name=PBrowser::Msg_FlushTabState) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210001,name=PBrowser::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x21004D,name=PBrowser::Msg_FlushTabState) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x210094,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39001D,name=PContent::Msg_RegisterChromeItem) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x39012D,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390024,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x390036,name=PContent::Msg_UpdateSharedData) Channel error: cannot send/recv

[Parent 124, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-esr-mwtdDv/firefox-esr-78.6.1esr/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19
[Parent 124, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-esr-mwtdDv/firefox-esr-78.6.1esr/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19
[Parent 124, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-esr-mwtdDv/firefox-esr-78.6.1esr/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19
[Parent 124, Main Thread] WARNING: FileDescriptorSet destroyed with unconsumed descriptors: file /build/firefox-esr-mwtdDv/firefox-esr-78.6.1esr/ipc/chromium/src/chrome/common/file_descriptor_set_posix.cc, line 19
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 36, in __init__
    self.init()
gi.repository.GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.blueman.Applet: Timeout was reached (24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/blueman-tray", line 40, in <module>
    BluemanTray()
  File "/usr/lib/python3/dist-packages/blueman/main/Tray.py", line 16, in __init__
    applet = AppletService()
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 15, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 49, in __init__
    super().__init__(name='org.blueman.Applet', interface_name='org.blueman.Applet',
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 38, in __init__
    raise DBusProxyFailed(e.message)
blueman.main.DBusProxies.DBusProxyFailed: Error calling StartServiceByName for org.blueman.Applet: Timeout was reached

(tracker-miner-fs:270): Tracker-CRITICAL **: 12:24:01.976:   (Sparql buffer) Error in array-update: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

(tracker-miner-fs:270): Tracker-CRITICAL **: 12:24:01.978: Could not execute sparql: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

(tracker-miner-fs:270): Tracker-CRITICAL **: 12:24:01.982: Could not remove files in volumes: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

(tracker-miner-fs:270): Tracker-CRITICAL **: 12:24:01.985: Could not remove files in volumes: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

(tracker-miner-fs:270): Tracker-CRITICAL **: 12:24:01.986: Could not initialize currently active mount points: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

(tracker-miner-fs:270): Tracker-WARNING **: 12:24:01.988: Parent 'file:///root' not indexed yet

(tracker-miner-fs:270): Tracker-WARNING **: 12:24:02.201: Parent 'file:///usr/share/applications' not indexed yet

(tracker-miner-fs:270): Tracker-WARNING **: 13:17:43.843: Parent 'file:///root' not indexed yet

**Comment by cschramm** [comment]
This is expected as you do not have a hardware killswitch registered.
