### ISSUE TITLE
failed to run script: Failed to execute child process “/usr/bin/pm-is-supported”

### ISSUE THREAD

**Issue by Midigich** [blueman-project/blueman#1494]
No window manager registered on screen 0. To start the xfdesktop without this check, run with --disable-wm-check.

(xfce4-panel:5203): garcon-CRITICAL **: 16:52:49.912: garcon_gtk_menu_get_desktop_actions_menu: assertion 'actions != NULL' failed

(wrapper-2.0:5220): GLib-GIO-CRITICAL **: 16:52:50.591: g_file_new_for_path: assertion 'path != NULL' failed

** (wrapper-2.0:5221): WARNING **: 16:52:50.597: No outputs have backlight property

(wrapper-2.0:5220): GLib-GIO-CRITICAL **: 16:52:50.599: g_file_monitor_file: assertion 'G_IS_FILE (file)' failed

(wrapper-2.0:5220): GLib-GObject-WARNING **: 16:52:50.638: invalid (NULL) pointer instance

** (xfce4-power-manager:5231): WARNING **: 16:52:50.652: Failed to get name owner: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.xfce.PowerManager': no such name

(wrapper-2.0:5220): GLib-GObject-CRITICAL **: 16:52:50.654: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (xfce4-power-manager:5231): WARNING **: 16:52:50.666: Failed to get name owner: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.PowerManagement': no such name

(wrapper-2.0:5220): Gtk-WARNING **: 16:52:50.668: Attempting to add a widget with type GtkToggleButton to a container of type XfcePanelPlugin, but the widget is already inside a container of type XfcePanelPlugin, please remove the widget from its existing container first.
Xfce power manager is not running
Xlib:  extension "DPMS" missing on display "0:0".

(xfce4-power-manager:5231): xfce4-power-manager-WARNING **: 16:52:50.788: Monitor is not DPMS capable

(wrapper-2.0:5220): Gtk-WARNING **: 16:52:50.887: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)

** (wrapper-2.0:5219): WARNING **: 16:52:50.939: Binding 'XF86AudioMicMute' failed!

(wrapper-2.0:5219): pulseaudio-plugin-WARNING **: 16:52:51.037: Could not have grabbed volume control keys. Is another volume control application (xfce4-volumed) running?
shared memfd open() failed: Function not implemented
Tracker-Message: 16:52:51.281: Set scheduler policy to SCHED_IDLE
Connection failure: Connection refused
Tracker-Message: 16:52:51.363: Set scheduler policy to SCHED_IDLE
shared memfd open() failed: Function not implemented
Tracker-Message: 16:52:51.407: Setting priority nice level to 19
pa_context_connect() failed: Connection refused
Tracker-Message: 16:52:51.528: Setting priority nice level to 19

(wrapper-2.0:5221): Gtk-WARNING **: 16:52:51.919: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner PowerManagerButton)

** (light-locker:5290): ERROR **: 16:52:51.938: session_id is not set, is /proc mounted with hidepid>0?

(polkit-gnome-authentication-agent-1:5302): polkit-gnome-1-WARNING **: 16:52:52.098: Unable to determine the session we are in: No session for pid 5302
Xfce Power Manager: Another power manager is already running

(xfce4-session:5137): xfce4-session-WARNING **: 16:52:52.265: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

** (xiccd:5355): WARNING **: 16:52:52.273: EDID is empty
blueman-applet version 2.1.4 starting
Stale PID, overwriting
blueman-applet 16.52.52 ERROR    PluginManager:91 load_plugin: Unable to load plugin module KillSwitch
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 89, in load_plugin
    importlib.import_module(self.module_path.__name__ + ".%s" % plugin)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py", line 23, in <module>
    raise ImportError('Hardware kill switch not found')
ImportError: Hardware kill switch not found

(xfce4-session:5137): xfce4-session-WARNING **: 16:52:52.640: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

** (xiccd:5355): CRITICAL **: 16:52:52.743: unable to connect to profile: Failed to connect to missing profile /org/freedesktop/ColorManager/profiles/icc_2d5203fc6fb7c3ce0daa797ea32f8fb2
Terminated
Error creating proxy: Error calling StartServiceByName for org.gtk.vfs.GPhoto2VolumeMonitor: The connection is closed (g-io-error-quark, 18)

(tracker-miner-fs:5328): GVFS-RemoteVolumeMonitor-[1;33mWARNING[0m **: [34m16:52:52.786[0m: invoking List() failed for type GProxyVolumeMonitorGPhoto2: The connection is closed (g-io-error-quark, 18)

(xfce4-power-manager:5231): libnotify-[1;33mWARNING[0m **: [34m16:52:52.791[0m: Failed to connect to proxy

**Comment by cschramm** [comment]
I'm not sure what I'm looking at here. That message does not even seem to relate to blueman.
