### ISSUE TITLE
Blueman applet can't be triggered from command line

### ISSUE THREAD

**Issue by fctorial** [blueman-project/blueman#1500]
It isn't possible to trigger blueman devices window to come up without using a mouse (clicking on system tray icon). So you can't connect to a bluetooth mouse without a usb mouse.

**Comment by cschramm** [comment]
Regarding the tray icon: I'd say that depends on the desktop environment. If it does not allow to put focus on it, you cannot open the menu without a click. That is correct but not specific to blueman, is it?

Regarding opening the manager: Just run `blueman-manager` directly. You don't need the tray icon for it.

Regarding using the GUI without a pointer device: If it is about regularly connecting to one specific mouse, you're better off with a respective `bluetoothctl connect` command. There is no point in using the blueman GUI for that task.

**Comment by fctorial** [comment]
blueman-manager is what I needed.
