### ISSUE TITLE
Blueman does not show 2nd adapter

### ISSUE THREAD

**Issue by SCCOBN** [blueman-project/blueman#1501]
blueman: 2.1.4
BlueZ: 5.55
Distribution: arch
Desktop environment: xfce 4.16

Here is the problem -- previously my laptop had Ubuntu 18 LTS and blueman (yes I removed blueberry and installed blueman) showed both bluetooth adapters. One adapter comes as part of my Wifi card and the other is on a separate card connected to mobo via internal USB. Now fast forward, I installed Arch and now noticed this problem. Blueman only shows 1 bluetooth adapter. I search google all over and couldn't find a solution. I even uninstalled blueman and installed blueberry, same thing. So now it's back to blueman and more troubleshooting.

lsusb -- https://i.imgur.com/qBhm2dg.png

rfkill list -- https://i.imgur.com/pXu0aIs.png

bluetoothctl list -- https://i.imgur.com/Lpb2zIK.png

Which way do I look to find me a solution?

**Comment by cschramm** [comment]
Looks like the Atheros adapter 13d3:3362 is missing. Should be supported by `ath3k`. Is it even loaded? Also check `dmesg` for `Bluetooth` and `ath3k` (and `usbcore`) messages.
