### ISSUE TITLE
Connecting to A2DP Fails

### ISSUE THREAD

**Issue by nunyafukkinbizness** [blueman-project/blueman#1504]
blueman:
BlueZ:
Distribution:
Desktop environment:Ubuntu Cinnamon

Sometimes have trouble connecting a2dp mode. Have to turn off bluetooth and turn back on, reconnect device. Sometimes I have to delete device, pair it again, then connect, and finally try to switch from from HSFP to A2DP I'm about to give up on bluetooth on a Linux computer!

**Comment by infirit** [comment]
If it works sometimes there is likely nothing we can do about it in blueman. Have you raised this on the Ubuntu forums?

Blueman is just a front-end to bluez (Bluetooth) and pulseaudio (soundserver). We don't directly hande either.
