### ISSUE TITLE
blueman-applet freezes & battery level not showing with master branch

### ISSUE THREAD

**Issue by souravdas142** [blueman-project/blueman#1509]
blueman: master =  1cf77b268dff784b30e70b97acfadaa424e469da
BlueZ: 5.56
Distribution: Arch-linux
Desktop environment: i3wm

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**There is 2 issue** 

1.  I am getting `(blueman-tray:43216): Gdk-CRITICAL **: 20:02:59.234: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0'` failed while running blueman-applet

2.  There is no battery level displaying while connecting my headphone. (and not with "gatt" menu from bluetoothctl)

here is my [journalLogblueman.log](https://github.com/blueman-project/blueman/files/6142128/journalLogblueman.log)

**Comment by cschramm** [comment]
With "blueman-applet freezes" you mean that the tray icon becomes unresponsive? That is most probably connected to that error message. I would not assume that blueman-applet itself freezes, though. What kernel do you have?

With "battery level not showing" you mean that the notification introduced with #1418 does not show up? Please provide the blueman-applet output and the info from the device's context menu.

**Comment by souravdas142** [comment]
for the first question , Yeah tray-icon became unresponsive sometimes. using 
kernel 5.11.6
pipewire 0.3.23

for the second question, yes. Notification doesn't show up, I can't see battery level of my bluetooth headphone.
here is my [blueman-applet.log](https://github.com/blueman-project/blueman/files/6147415/blueman-applet.log) and [btDeviceinfo.log](https://github.com/blueman-project/blueman/files/6147426/btDeviceinfo.log)

**Comment by cschramm** [comment]
If you're able to replicate the freezes, please try commenting out the line with `self.indicator.set_title('blueman')` in your `/usr/lib/python3.?/site-packages/blueman/main/indicators/GtkStatusIcon.py` (probably line 64) and see if that helps.

Regarding the battery level, I have to inform you that your device does not provide a battery service. :smile:

**Comment by souravdas142** [comment]
**sorry for the late reply.** I built again the master branch yesterday and works fine, no freezes occurred till now.


**Regarding the battery level -**

> Regarding the battery level, I have to inform you that your device does not provide a battery service. 😄

If this is so, then how Android and Windows shows battery level? Can you explain? giving you screenshots of both devices.

![image](https://user-images.githubusercontent.com/24272753/117470210-2f537d80-af74-11eb-8616-48128ca92c07.png)
**This is from Windows 10 20H2**

![screenshot](https://user-images.githubusercontent.com/24272753/117471810-dbe22f00-af75-11eb-8284-dcebe2f6cea5.jpg)


**And this is from Xiaomi redmi 5a**.

🔥 @cschramm  **Please fix it, Its a very long time  and overwhelmed feature request**

**Comment by cschramm** [comment]
Our implementation only supports the standard battery GATT service. There are older battery level implementations that operate inside HID and HFP but as far as I'm aware BlueZ does not have support for them as well (without an external battery provider). You could check if it provides a `org.bluez.Battery1` interface on the device, though, e.g. with `d-feet`, `org.bluez` on system bus, object `/org/bluez/hci0/dev_48_D8_45_1E_E2_03`.

**Comment by souravdas142** [comment]
No GATT service doesn't print anything. By the way if bluez doesn't provide this feature thats mean  "my issue" is not related this project. 

> There are older battery level implementations that operate inside HID and HFP but as far as I'm aware BlueZ does not have support for them as well (without an external battery provider).

Though This feature should be added in bluez as a fallback :smile: I am closing it now. Thank you btw.
