### ISSUE TITLE
DELL XPS 13 bluethoot doesn't scan devices

### ISSUE THREAD

**Issue by ichasco-heytrade** [blueman-project/blueman#1514]
blueman: 2.1.4-1
BlueZ: 5.56-1
Distribution: Manjaro 21.0
Desktop environment: XFCE
Laptop: XPS 13 9310 (0991)
BIOS version:  2.0.0

Hi, I get errors using the bluethoot. It doesn't scan any devices 

```
mar 24 10:56:56 XXX systemd[1]: Starting Bluetooth service...
mar 24 10:56:56 XXX bluetoothd[1005]: Bluetooth daemon 5.56
mar 24 10:56:56 XXX systemd[1]: Started Bluetooth service.
mar 24 10:56:56 XXX bluetoothd[1005]: Starting SDP server
mar 24 10:56:56 XXX bluetoothd[1005]: Bluetooth management interface 1.19 initialized
mar 24 10:56:58 XXX bluetoothd[1005]: Loading LTKs timed out for hci0
mar 24 10:57:03 XXX bluetoothd[1005]: Endpoint registered: sender=:1.38 path=/MediaEndpoint/A2DPSink/sbc
mar 24 10:57:03 XXX bluetoothd[1005]: Endpoint registered: sender=:1.38 path=/MediaEndpoint/A2DPSource/sbc
mar 24 10:57:06 XXX bluetoothd[1005]: Failed to set mode: Failed (0x03)
mar 24 10:59:39 XXX bluetoothd[1005]: Failed to set mode: Failed (0x03)
```

I have also tried to restart it. And when the laptop boots, the bluethoot is disabled. I also tried with:

/etc/bluetooth/main.conf
```
AutoEnable=true
```

Thanks!

**Comment by cschramm** [comment]
This is the blueman project.

From a quick Google search, https://arcolinuxforum.com/viewtopic.php?p=916&sid=4a32f6475f677cda9c99d95abb01b56f#p916 (i.e. tinkering with BlueZ' `FastConnectable` and `Cache` settings) sounds promising.
