### ISSUE TITLE
RPI4 Bluez Update

### ISSUE THREAD

**Issue by whizps** [blueman-project/blueman#1527]
blueman:
BlueZ: 5.4
Distribution: Raspbian GNU/Linux 10 (buster)
Desktop environment: Raspberry Pi

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Hi! So it's not much of an issue but i see that the RPI4s are using bluez for it's bluetooth, do you possibly have a guide on how to update to the latest working version of Bluez on the RPI4 ?

**Comment by cschramm** [comment]
I did not get your question. What do you mean with "latest working version"?

If your system is based on Debian buster, it should have BlueZ 5.50. [buster-backports](https://packages.debian.org/buster-backports/bluez) currently provides 5.54 and [bullseye](https://packages.debian.org/bullseye/bluez) 5.55. [Upstream](http://www.bluez.org/) is at 5.58.
