### ISSUE TITLE
blueman does not auto connect

### ISSUE THREAD

**Issue by Geoniboy** [blueman-project/blueman#1539]
blueman: 2.1.2
BlueZ: 
Distribution: Linux Mint
Desktop environment: X-Cinnamon

Hello folks, 

I have really tried as many things as possible and spent a heap of time on this, I'm not a power user, so I have hit the wall of my knowledge and ability...

I can get my Altec Lansing H20 Jacket BT speaker to work on my Toshiba Satellite Pro L650 laptop to work, but when I boot up, I seem to always have a problem connecting? It seems that my system does recognize that I would like to auto connect to the speaker? 

From my understanding, if my speaker is turned on and then I boot my laptop, it should recognize the trusted device and auto connect to it?

This function seems to have dropped off Linux Mint quite a while ago? Possibly even 2 years ago?
For all this time I have tried to find the setting that will permanently save and recognize the speaker and auto connect on boot up?

Up to now, I have had to enable and disable repeatedly until "default controller' appears and then I could reconnect.

I downloaded BlueZ KDE and it asked me if I wanted to always trust the speaker, which I selected yes.
But no go.
When I restarted my laptop, it seemed to have forgotten everything and I had to manually reconnect?

Thanks in advance for your help!

Cheers!

* [Y ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Most of those questions do not seem like they should be questions but I'll try answering as much as I can.

> when I boot up, I seem to always have a problem connecting?

You mentioned you have to "enable and disable repeatedly until "default controller' appears". That very much sounds like a problem yes, but I do not really get what and why you're doing there.

> It seems that my system does recognize that I would like to auto connect to the speaker?

Why is that? It would surprise me.

> From my understanding, if my speaker is turned on and then I boot my laptop, it should recognize the trusted device and auto connect to it?

No.

> This function seems to have dropped off Linux Mint quite a while ago? Possibly even 2 years ago?

Well, I remember there has been some auto-connect going on in BlueZ 4. That's a thing of the past for nearly 9 years now. Even Linux Mint has BlueZ 5 for nearly 5 years.

> For all this time I have tried to find the setting that will permanently save and recognize the speaker and auto connect on boot up?

I guess you have. No longer. blueman 2.2 will have an auto-connect feature for you.

> When I restarted my laptop, it seemed to have forgotten everything and I had to manually reconnect?

No. There is no auto-connect setting it could forget about.
