### ISSUE TITLE
Bluetooth Headphone resists to connect.

### ISSUE THREAD

**Issue by him4nshug4ur** [blueman-project/blueman#1540]
blueman: 2.1.4
BlueZ:
Distribution: manjaro
Desktop environment: XFCE

1. The Bluetooth Headphone, once connected and marked as trusted, will work fine for few minutes (10 mins on average) and will eventually disconnect. Once it disconnects, it resists reconnecting and often it affects WiFi too.
2. Once connected, sometimes it switches profile for the BT Headphone (Profile switches from A2DP Sink to HSP/HFP). I would always want it to be at A2DP Sink.

* [yes] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

1. The Bluetooth Headphone, once connected and marked as trusted, will work fine for few minutes (10 mins on average) and will eventually disconnect. Once it disconnects, it resists reconnecting and often it affects WiFi too.
2. Once connected, sometimes it switches profile for the BT Headphone (Profile switches from A2DP Sink to HSP/HFP). I would always want it to be at A2DP Sink.

**Comment by cschramm** [comment]
To look into the first point, we'd need at least the output of `blueman-applet --loglevel debug` of when it disconnects and when you're trying to reconnect. Most probably we will not see a reason there, though, and you're better of looking at bluetoothd logs to look into what's going on.

Second point is about pulseaudio and you might want `set-card-profile` in its `default.pa`, see #1167.
