### ISSUE TITLE
[Feature Request] Adding a toggle for Connect / Disconnect

### ISSUE THREAD

**Issue by satomst** [blueman-project/blueman#1542]
blueman: 2.1.2
Distribution: Linux Mint
Desktop environment: Cinnamon

Hello, could you perhaps add a toggle for Connect / Disconnect?
Currently it's Right click > Connect / Disconnect, and I do this a lot so I was wondering if this shortcut can be implemented.

Thank you! 

![image](https://user-images.githubusercontent.com/84996300/120045502-03e90f00-bfc5-11eb-9dc5-23ac41959c9e.png)

![image](https://user-images.githubusercontent.com/84996300/120045630-4e6a8b80-bfc5-11eb-8441-5ec457bc2d8b.png)

**Comment by cschramm** [comment]
Blueman 2.2 supports double-clicking to connect / disconnect.
