### ISSUE TITLE
Minor UI Bug

### ISSUE THREAD

**Issue by Sov-trotter** [blueman-project/blueman#1552]
blueman:2.1.4-1
Distribution:Manjaro Linux
Desktop environment: xfce

Apologies for the picture from phone.
![image](https://user-images.githubusercontent.com/43717431/120511812-60469700-c3e8-11eb-9955-8adae1036d01.png)

**Comment by cschramm** [comment]
There's a native StatusNotifierItem implementation in #1382 that replaces the AppIndicator implementation and should not have that issue.

**Comment by saija** [comment]
Hi guys

Same UI issue here:

Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
![blueman UI tooltip issue](https://user-images.githubusercontent.com/84354945/120879808-9e2ff080-c58b-11eb-9ad3-d9c938f326f8.png)

Desktop environment: KDE Plasma

**Comment by cschramm** [comment]
Same solution. As far as I remember the issue is due to libappindicator and independent of the tray. It seems to be fine with our own StatusNotifierItem implementation in #1382 (some trays render the part bold, some just strip the tags).
