### ISSUE TITLE
Just a simple UI "bug"?

### ISSUE THREAD

**Issue by TheOncomingStorm** [blueman-project/blueman#1561]
blueman: 2.1.4
BlueZ:(not sure)
Distribution: Arch
Desktop environment: KDE Plasma

This is really just a thing you might want to correct in the UI, assuming it's not just something in the DE on my machine causing it. In the popup when I mouse over the task tray icon I get the text below with the html "bold" markup.. 

![image](https://user-images.githubusercontent.com/400942/123836698-ff6f8900-d8d7-11eb-8cb5-a5933cf1d3ea.png)

**Comment by cschramm** [comment]
An issue with libappindicator, see #1552.
