### ISSUE TITLE
Input/Output Error while connecting to BT headset

### ISSUE THREAD

**Issue by Pranjalmet** [blueman-project/blueman#1566]
blueman: 2.1.4
BlueZ: 5.60
Distribution: Arch
Desktop environment: DWM

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

blueman-applet logs
https://pastebin.com/Rdz504tz

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

**Comment by Pranjalmet** [comment]
[Blueman-applet logs](https://pastebin.com/Rdz504tz)

**Comment by cschramm** [comment]
The bluetoothd logs should have some indication what's failing.

**Comment by Pranjalmet** [comment]
[This is log of process of pairing and connecting](https://pastebin.com/PkbPCzzy)
it connects and disconnects after few seconds, in blueman-manager it says Input/Output error that's it

**Comment by cschramm** [comment]
blueman only fowards the error reported by bluetoothd (BlueZ). Its logs typically show some more details on what went wrong. It's not about blueman, so do not look in blueman logs.
