### ISSUE TITLE
Enable/disable connect/disconnect notification windows

### ISSUE THREAD

**Issue by themidnightfox** [blueman-project/blueman#1570]
blueman: 2.2.1-1
BlueZ: 5.60-1
Distribution: archlinux
Desktop environment: i3
Notification daemon: none

Is there a way I can disable the connect/disconnect popup windows (for a specific device)? I only use bluetooth for a bluetooth speaker, so I get all the feedback on connection status I need in an audible way.

**Comment by cschramm** [comment]
You can disable the ConnectionNotifier plugin. You cannot target specific devices.

**Comment by themidnightfox** [comment]
That does the trick, thanks!
