### ISSUE TITLE
Not working in Ubuntu 20.4

### ISSUE THREAD

**Issue by Nagendra1811** [blueman-project/blueman#1571]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by PeterDaveHello** [comment]
If you mean Ubuntu 20.04, blueman-manager v2.1.2 seems to work for me, not sure if it's the environment caused the problem? Here's the version I installed:

```sh
$ apt-cache policy blueman 
blueman:
  Installed: 2.1.2-1ubuntu0.2
  Candidate: 2.1.2-1ubuntu0.2
  Version table:
 *** 2.1.2-1ubuntu0.2 500
        500 http://ftp.ubuntu-tw.net/ubuntu focal-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages
        100 /var/lib/dpkg/status
```
