### ISSUE TITLE
how to bluetoothctl (blueman-manager Device Connect To: Audio Sink)

### ISSUE THREAD

**Issue by fabyouless** [blueman-project/blueman#1574]
blueman: 2.0.4
BlueZ: 5.43
Distribution: BunsenLabs Helium
Desktop environment: Openbox

What is the bluetoothctl command that is the equivalent of opening blueman-manager, highlighting the desired device, and selectiong Audio Sink from the Device >> Connect To: menu?

I want to execute this via my laptop and ssh, instead of having to switch over to my linux box on my TV every time.

Thanks,

fabyouless

**Comment by cschramm** [comment]
Just the generic `connect` command. It connects audio and input services alike, as exposed by the BlueZ 5 API.
