### ISSUE TITLE
Ubuntu 18.04: /dev/rfcommx cannot open due to device file permission

### ISSUE THREAD

**Issue by cpuwolf** [blueman-project/blueman#1575]
blueman:Blueman-manager 2.0.5
BlueZ:
Distribution:Ubuntu 18.04
Desktop environment:GNOME

solution:

cd /etc/udev/rules.d
sudo vim 97-bt-rfcomm.rules

KERNEL=="rfcomm*", SUBSYSTEM=="tty", MODE="0666"

**Comment by cschramm** [comment]
It's not blueman that provides the device file. I'm not sure what you're asking for.
