### ISSUE TITLE
changes to Bluetooth Devices window?

### ISSUE THREAD

**Issue by mrsteve0924** [blueman-project/blueman#1577]
blueman: 2.2.1-1
BlueZ: 5.60-1
Distribution: archlinux
Desktop environment: xfce

after last update to 2.2.1-1 i no longer see all the link icons for a connected device.  also, when i trust the device the trust icon turned yellow. now it doesn't.  audio does work though.

![blueman](https://user-images.githubusercontent.com/37476191/127052172-ec18ba4a-f273-4b36-a29b-d47e56463195.png)

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Should be fixed by #1563.
