### ISSUE TITLE
HP Bluetooth Mouse X4000b Connection Failed: Input/output error

### ISSUE THREAD

**Issue by kzoli429** [blueman-project/blueman#1579]
blueman: 2.2.1-1
BlueZ: 5.60-1
Distribution: Arch Linux latest (Linux asus-x530 5.13.5-arch1-1 #1 SMP PREEMPT Sun, 25 Jul 2021 18:02:58 +0000 x86_64 GNU/Linux
Desktop environment: XFCE

Although it has been working before, it stopped working a few week ago (appr. 2 month).
It has been coherently working from Asus Vivobook S15 built-in adapter earlier.
Now it works only from USB plugin Bt adapter.

Logs:
https://gist.github.com/kzoli429/f5daaa14237c03fcddcfa3c90f9ce645

**Comment by cschramm** [comment]
Clearly not a blueman issue, but I can try to help with tracing it down.

> no device found although HP Bluetooth Mouse X4000b available

`bluetoothctl list` does not show devices. `bluetoothctl devices` does.

> profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info

This is definitely concerning. You can find `Can't get HIDP connection info` on the Internets, mostly referring to issues with specific kernel versions, so it might be worth downgrading your kernel.

Did you try to just remove the device completely and re-add it? If it doesn't help you can also try wiping data from `/var/lib/bluetooth`. (A backup before removing anything could enable us to find the problem afterward if it helped).
