### ISSUE TITLE
AD2P device added, but failed to connect

### ISSUE THREAD

**Issue by azazar** [blueman-project/blueman#158]
Unable to connect bluetooth headset:

![ad2p problem](https://cloud.githubusercontent.com/assets/2816075/5515953/5db15208-88a5-11e4-8f56-13e452726646.png)
![ad2p problem 2](https://cloud.githubusercontent.com/assets/2816075/5515957/7c8e2cdc-88a5-11e4-93c1-f9a8d39d7274.png)

```text
# uname -a
Linux portable 3.16.0-28-generic #38-Ubuntu SMP Fri Dec 12 17:37:40 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

# dpkg -s blueman|grep Version
Version: 1.23-git201406261335-deb-1ubuntu1
# dpkg -s bluez|grep Version
Version: 4.101-0ubuntu20

# cat /etc/bluetooth/audio.conf 
# Configuration file for the audio service

# This section contains options which are not specific to any
# particular interface
[General]

# Switch to master role for incoming connections (defaults to true)
#Master=true

# If we want to disable support for specific services
# Defaults to supporting all implemented services
#Disable=Gateway,Source,Socket
Disable=Socket

# SCO routing. Either PCM or HCI (in which case audio is routed to/from ALSA)
# Defaults to HCI
#SCORouting=PCM

# Automatically connect both A2DP and HFP/HSP profiles for incoming
# connections. Some headsets that support both profiles will only connect the
# other one automatically so the default setting of true is usually a good
# idea.
AutoConnect=true

# Headset interface specific options (i.e. options which affect how the audio
# service interacts with remote headset devices)
[Headset]

# Set to true to support HFP, false means only HSP is supported
# Defaults to true
#HFP=true
HFP=false

# Maximum number of connected HSP/HFP devices per adapter. Defaults to 1
MaxConnected=5

# Set to true to enable use of fast connectable mode (faster page scanning)
# for HFP when incoming call starts. Default settings are restored after
# call is answered or rejected. Page scan interval is much shorter and page
# scan type changed to interlaced. Such allows faster connection initiated
# by a headset.
FastConnectable=false

# Just an example of potential config options for the other interfaces
#[A2DP]
SBCSources=1
MPEG12Sources=0
```

**Comment by azazar** [comment]
That problem suddenly disappeared without any obvious cause.

**Comment by lispeaking** [comment]
Similar problem here (Xubuntu 15.04/14.10/14.04).
When I try to connect to the audio sink of a Belkin Songstream BT it says
"Connection Failed: Stream setup failed"

same error with lubuntu.

but

BT sound works OK with Ubuntu GNOME, Kubuntu, an Ubuntu

**Comment by bigteejay** [comment]
Anyone find a solution to this? I'm having the same problem with my Altec Lansing "Life Jacket 2" bluetooth speaker.  The hardware doesnt even show up in the sound applet or the pavucontrol applet,

`user@:~$ uname -a
Linux user-mobl 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:43:30 UTC 2015 i686 i686 i686 GNU/Linux`

**Comment by bigteejay** [comment]
This resolved it!

```
user@:~$ pactl list modules | grep blue
	Name: module-bluetooth-policy
		module.description = "When a bluetooth sink or source is added, load module-loopback"
```

"module-bluetooth-discover" missing even though the device confirmed it was paired.  I ran...
```
user@:~$ pactl load-module module-bluetooth-discover
23
```

Now it appears in the applets as a hardware device and the module shows that it is loaded...

```
user@:~$ pactl list modules | grep blue
	Name: module-bluetooth-policy
		module.description = "When a bluetooth sink or source is added, load module-loopback"
	Name: module-bluetooth-discover
		module.description = "Detect available bluetooth audio devices and load bluetooth audio drivers"
	Name: module-bluetooth-device
	Argument: address="40:EF:4C:FF:E1:8A" path="/org/bluez/755/hci0/dev_40_EF_4C_FF_E1_8A"
```

**Comment by bigteejay** [comment]
Though the device appeared, it didn't play audio until I adjusted the "mode" to "High Fidelity Playback (A2DP)"
![screenshot from 2015-09-24 12 26 31](https://cloud.githubusercontent.com/assets/14826513/10084435/4e010f54-62b8-11e5-93ff-e6b837d715cd.png)

**Comment by bigteejay** [comment]
Also, commented out the "if" in the check for the module (odd that the check fails apparently, but requesting it be loaded works).  Seems to support the odd behavior that azazar encountered.

Adding edit for completeness/google/others.   In /etc/pulse/default.sa...
```
# Commented out to enable audio playback via Bluetooth upon startup
#.ifexists module-bluetooth-discover.so
load-module module-bluetooth-discover
#.endif
```

**Comment by cschramm** [comment]
Side note: You should be able to switch the device's mode in its context menu in blueman as well. That's the only user interaction that should be required and actually the only pulseaudio related feature that blueman still provides. Everything else is done by pulseaudio now - if it works. :wink:

**Comment by jmanne** [comment]
Thank you guys for working out the solution to this problem. It resolved the problem
I was having very effectively.

**Comment by mauriciojost** [comment]
It helped me fix my issue too! Thanks!

**Comment by dminca** [comment]
1. `sudo apt-get install pulseaudio-module-bluetooth`
2. `pactl load-module module-bluetooth-discover`
3. Delete the device from bluetooth devices and pair it again.

Also integrated in an [Ansible provisioning script][1]

[1]: https://github.com/WizDevOps/containerschiff/blob/master/roles/packages/tasks/main.yml#L53

**Comment by coreybruce** [comment]
I fixed this issue, download bluez from there website and compile it http://www.bluez.org/download/

you will need to install libreadline-dev libical-dev before compiling, read the readme.md for instractions and now I can use my bluetooth sony headphone with high Fidelity playback

**Comment by parkerlreed** [comment]
Also you may run into this while using GDM. GDM uses it's own pulseaudio instance and takes up the A2DP module before the user process can access it. 

Placing https://aur.archlinux.org/cgit/aur.git/plain/default.pa?h=pulseaudio-bluetooth-a2dp-gdm-fix at `/var/lib/gdm/.config/puls/default.pa` to free up A2DP for the user.

**Comment by SalahAdDin** [comment]
@dminca What's about in `Arch Linux`?

**Comment by coreybruce** [comment]
This isn't about Arch so why ask? anyways problem is solved by simply compiling BlueZ

**Comment by SalahAdDin** [comment]
@dminca what's about `Arch Linux`?

**Comment by parkerlreed** [comment]
@SalahAdDin If you're using GDM use the fix above. Otherwise you shouldn't be having this issue on Arch.

**Comment by SalahAdDin** [comment]
I'm using `deepin-startdde-manager` or some like that.
