### ISSUE TITLE
Connect does not pair and connect

### ISSUE THREAD

**Issue by ChristFollower3** [blueman-project/blueman#1585]
blueman:
BlueZ:
Distribution:
Desktop environment:

When you click connect it does not pair and connect.  You have to pair first, then connect.  Either disable connect until paired or make connect pair first and then connect.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Paring and connecting are different things. The services that you can connect to with the connect action might not even need pairing. The devices' manuals should give directions what to do.

**Comment by Byzantine-1** [comment]
Good day, 
For some reason, my devices show up on blueman, but won't pair or connect. I will attach the code I am receiving. Thank you.
![DeepinScreenshot_select-area_20210909123702](https://user-images.githubusercontent.com/85775394/132726769-6f4b9536-35be-43db-be4c-288dfcbd5b72.png)

**Comment by cschramm** [comment]
@Byzantine-1: That does not seem related at all. Please open a separate issue and provide all the basic information that we ask for in the template.
