### ISSUE TITLE
Doesn't show active devices 

### ISSUE THREAD

**Issue by saugatsn** [blueman-project/blueman#1586]
The bluetooth adater seems to be working correctly but it doesn't show active bluetooth devices. So, I cannot connect to my device. How do I fix this?
blueman:
BlueZ:
Distribution:
Desktop environment: Parrot OS

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by tomazza** [comment]
Hi.

I've been having the same problems on three different installations, with Blueman 2.2.2-1 on Bluez 5.60-1. It is on three different Arch based distributions as well, Manjaro, Arco Linux and Arch Linux itself. 

I solved it by open bluetoothctl in terminal and and typed the command "scan on", without the quotes. When it had detected the device i wanted to connect, it was also detected in Blueman and I could connect to it. After that, I had no further issues connecting additional devices directly through Blueman.

**Comment by cschramm** [comment]
So the search action in blueman did not work?

**Comment by tomazza** [comment]
No not until I started the search through bluetoothctl. After that it worked just fine in Blueman.
________________________________

**Comment by cschramm** [comment]
When you hit the search button in blueman-manager, you should see `Discovering: yes` for the adapter in bluetoothctl and then devices showing up. If that does not work, please start blueman-applet with `--loglevel debug` and then blueman-manager with the same argument and provide the output starting where you hit the button.
