### ISSUE TITLE
1More colorbuds won't connect to Kubuntu PC.  Android and Windows connect fine.  

### ISSUE THREAD

**Issue by catalyst1987** [blueman-project/blueman#1597]
blueman: 2.1.2
BlueZ: 5.53
Distribution: Kubuntu 20.04.3
Desktop environment: Plasma

I have a pair of 1More colorbuds that I am trying to connect to my Kubuntu PC.  The earbuds connect fine to my Android Phone and my work laptop which is running Windows 10.  Sometimes they will connect when I put the earbuds into its case and leave the case open.  But as soon as I pull them out and put them into my ears, the device disconnects and cannot reconnect.  When trying to reconnect via the blueman manager I get a "host is down" error.  Removing and re-adding the device in blueman doesn't seem to help.  Any guidance would be greatly appreciated.  

Blueman applet debug log:  https://pastebin.com/za5tBCYS
Bluetoothd log: https://pastebin.com/2m5BfDzQ

Results of bluetoothctl list

`Controller C8:FF:28:0D:EB:2C Thor [default]`

Results of lsusb

`Bus 004 Device 002: ID 05e3:0616 Genesys Logic, Inc. hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 0b05:1825 ASUSTek Computer, Inc. Qualcomm Bluetooth 4.1
Bus 001 Device 009: ID 0557:222e ATEN International Co., Ltd
Bus 001 Device 008: ID 0557:8021 ATEN International Co., Ltd Hub
Bus 001 Device 006: ID 0424:2744 Microchip Technology, Inc. (formerly SMSC) Hub
Bus 001 Device 004: ID 0557:5411 ATEN International Co., Ltd 4-Port USB 2.0 Hub
Bus 001 Device 010: ID 046d:082d Logitech, Inc. HD Pro Webcam C920
Bus 001 Device 002: ID 17a0:0001 Samson Technologies Corp. C01U condenser microphone
Bus 001 Device 007: ID 28de:1142 Valve Software Wireless Steam Controller
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

Many Thanks.

**Comment by cschramm** [comment]
I don't think I can provide much help here.

The blueman log does not seem to show a connection at all. The bluetoothd log looks like the audio stream gets established and then the device closes it (`profiles/audio/avdtp.c:avdtp_parse_cmd() Received CLOSE_CMD`).
