### ISSUE TITLE
keyboard Connect Disconnect problem after rebooting

### ISSUE THREAD

**Issue by no-1imit** [blueman-project/blueman#1599]
blueman: 2.2.2
BlueZ:
Distribution: Manjaro
Desktop environment: xfce

Hi, I connect to my keyboard and everything is okay, but when I restart my computer I see 'Connect' 'Disconnect' notifications and cannot connect to my keyboard, I have to remove my keyboard from blueman devices and then reconnect to it.
I have already set my keyboard as trusted device in blueman.

**Comment by cschramm** [comment]
Please provide the blueman-applet log of when you try to connect to the device after restarting.
