### ISSUE TITLE
Port to obexd

### ISSUE THREAD

**Issue by cschramm** [blueman-project/blueman#16]

**Comment by cschramm** [comment]
I have a strange dbus issue in the obexd branch that currently blocks the obexd server implementation.

In [blueman/bluez/obex/Agent.py:24](https://github.com/blueman-project/blueman/blob/12875cc37a3e0489613f6c97e949bf6e3a4a230c/blueman/bluez/obex/Agent.py#L24) I register an object with path /org/blueman/obex_agent (from [blueman/plugins/applet/TransferService.py:25](https://github.com/blueman-project/blueman/blob/12875cc37a3e0489613f6c97e949bf6e3a4a230c/blueman/plugins/applet/TransferService.py#L25)) on the system bus, but when obexd tries to call the AuthorizePush dbus method, it gets org.freedesktop.DBus.Error.UnknownObject. Accordingly, the agent's _message_cb python method is never called, meaning it never gets a message from dbus.

The same thing works for our BlueZ agent (see [blueman/bluez/Agent.py:51](https://github.com/blueman-project/blueman/blob/12875cc37a3e0489613f6c97e949bf6e3a4a230c/blueman/bluez/Agent.py#L51); the path is usually /org/blueman/agent/global from [blueman/main/applet/BluezAgent.py:265](https://github.com/blueman-project/blueman/blob/12875cc37a3e0489613f6c97e949bf6e3a4a230c/blueman/main/applet/BluezAgent.py#L265) in case of BlueZ 5), so I'm puzzled what might be wrong and I'm out of ideas how to get behind it. :cry: The only way I can think of is debugging the dbus service to see what goes on during registration and dispatching, but that seems like overkill.

**Comment by infirit** [comment]
I tried the obexd branch, the problem I see is that there is no object ```org.bluez.obex.Agent1``` for me.

When looking at the obex objects with ``d-feet`` I see it indeed does not exist, I do have ```AgentManager1``` and ```Client1```.

journal entry below.
```
apr 14 12:46:31 infirit obexd[17528]: Agent replied with an error: org.freedesktop.DBus.Error.UnknownObject, Method "AuthorizePush" with signature "o" on interface "org.bluez.obex.Agent1" doesn't exist
```

**Comment by cschramm** [comment]
org.bluez.obex.Agent1 is an interface that should be provided by our registered /org/blueman/obex_agent object just as out /org/blueman/agent/global provides methods on org.bluez.Agent1. So obexd (BlueZ) expects us to provide it, not the other way around.

In dbus we have buses with objects implementing interfaces with methods. When you call the AuthorizePush method of the org.bluez.obex.Agent1 interface on the object /org/blueman/obex_agent on the system bus, dbus will send a message to the object containing the interface and the method names. That's where python-dbus's _message_cb method gets called, independent of the interface and method. So it does not have to do with those names, but dbus does not find the /org/blueman/obex_agent object on the system bus I'm registering... The error name "UnknownObject" clearly indicates that while the message is a generic one for all failing method calls and completely misleading.

Unfortunately you cannot inspect either of the agents as you're not allowed to send the Inspect method call; I'm not sure why bluez / obexd can.

Typing this I just realized the underscore in my object path. Maybe that's illegal and gets removed internally or something. I will try and see if that may be the problem.

**Comment by cschramm** [comment]
Nope, that's not it...

**Comment by infirit** [comment]
Sorry, stupid question perhaps (I do not understand this very well), but are you sure you need to use the system bus? org.bluez.obex for me is on the session bus.

**Comment by cschramm** [comment]
Hrmm... Interesting. I think I just took the system bus because our BlueZ agent uses it as well. I'll try. :smiley:

**Comment by cschramm** [comment]
I just love you! :heart: :smile:
