### ISSUE TITLE
Unable to connect to a Bluetooth HC05 Serial Module

### ISSUE THREAD

**Issue by baldyman01** [blueman-project/blueman#1605]
blueman: 2.1.2
BlueZ: 5.53
Distribution: Ubuntu 20.04
Desktop environment: Cinammon

I have a number of Bluetooth devices working perfect on my Ubuntu machine. I am trying to connect to an HC05 Bluetooth Serial Adapter. The module works flawlessly from Android devices, it discovers immediately and connects immediately.

On my linux machine - 
It is paired with a pin
It is trusted
Info shows -
        Device 98:D3:31:F6:08:48 (public)
	Name: HC-05
	Alias: HC-05
	Class: 0x00001f00
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: no
	LegacyPairing: yes
	UUID: Serial Port               (00001101-0000-1000-8000-00805f9b34fb)

When I attempt to connect the UI sits and spins the status bar forever. It never seems to figure out there has been a problem.

From the command line I get -

[bluetooth]# connect 98:D3:31:F6:08:48
Attempting to connect to 98:D3:31:F6:08:48
[CHG] Device 98:D3:31:F6:08:48 Connected: yes
[CHG] Device 98:D3:31:F6:08:48 ServicesResolved: yes
Failed to connect: org.bluez.Error.NotAvailable
[CHG] Device 98:D3:31:F6:08:48 ServicesResolved: no
[CHG] Device 98:D3:31:F6:08:48 Connected: no
[bluetooth]#

The response is the same with bluetoothctl run from both user and sudo

Googling this issue produces a milliion and one people with the similar issues, a million and one suggestions and no solutions.

Blueman and Bluez debug info is attached

[Blueman_debug.txt](https://github.com/blueman-project/blueman/files/7227233/Blueman_debug.txt)
[Blue-Z_syslog.txt](https://github.com/blueman-project/blueman/files/7227234/Blue-Z_syslog.txt)

Thanks

Pete

**Comment by cschramm** [comment]
The data clearly indicates that the device did not respond to your adapter at some point. Might be an issue with Linux, firmware, the device itself (HC-05 stands for "counterfeit chip that can be absolutely everything"). Did you try a newer kernel?
