### ISSUE TITLE
2.2.3 release: configure: error: cannot find required auxiliary files: ltmain.sh compile missing

### ISSUE THREAD

**Issue by mgorny** [blueman-project/blueman#1624]
blueman: 2.2.3
BlueZ: 5.62
Distribution: Gentoo Linux
Desktop environment: XFCE

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

It seems that the .tar.xz for 2.2.3 release (i.e. https://github.com/blueman-project/blueman/releases/download/2.2.3/blueman-2.2.3.tar.xz) is incomplete. When trying to run `./configure`, I get:

```
$ ./configure -C
configure: loading site script /usr/local/share/config.site
configure: creating cache config.cache
configure: error: cannot find required auxiliary files: ltmain.sh compile missing
```

I see that there's `meson.build` there as well but FWICS autotools is listed in the docs and the `version` in meson.build isn't up-to-date, so I'm assuming autotools is the primary way of building blueman.

**Comment by infirit** [comment]
Blueman has an option to run uninstalled. I never got this to work with meson. Afaik this was the only thing holding it back being the default.

The main problem is that meson has a separate build dir. Blueman needs a couple of generated python files to work properly.

**Comment by mgorny** [comment]
Well, the lazy solution would be to have meson copy all Python files into the build dir.

**Comment by cschramm** [comment]
@infirit: In case you forgot, there's #1207 in the basement. 😉

As, I said: No strong opinion, so making meson the default ist perfectly fine for me.
