### ISSUE TITLE
Wrong message when not dhcp client is found?

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#1632]
Reviewing latest ~~master~~main I see a message of not getting an ip, which is technically true, but the exception in the log is

```
blueman-applet 18.06.14 WARNING  DhcpClient:54 err       : g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/blueman/plugins/mechanism/Network.py", line 44, in _run_dhcp_client
    dh.run()
  File "/usr/lib/python3.9/site-packages/blueman/main/DhcpClient.py", line 43, in run
    raise Exception("No DHCP client found, please install dhclient, dhcpcd, or udhcpc")
Exception: No DHCP client found, please install dhclient, dhcpcd, or udhcpc
```

I'd like to have the error actually show as a notification instead of no ip found. Am I missing something?

**Comment by cschramm** [comment]
@infirit! :scream: :smile: 

You're not missing something. That notification is always used by blueman-applet if the `DhcpClient` D-Bus call to blueman-mechanism fails, no matter why. It should actually forward the exception already but parsing it might get ugly.
