### ISSUE TITLE
Auto bluetooth pairing produces monaural audio

### ISSUE THREAD

**Issue by rkrisher** [blueman-project/blueman#1645]
blueman:2.0.8-1+deb10u1
BlueZ:
Distribution:Debian uname 4.19.0-16-amd64
Desktop environment:LXDE

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

When my headset MDR-XB950B1 turns on and connects to bluetooth, the sound is monaural and blares like thesound is from a tin can or distant room.  If I manually disconnect/reconnect, the audio is stereo and functions properly.  Pulseaudio for the OS.
->

**Comment by rkrisher** [comment]
When my headset MDR-XB950B1 turns on and connects to bluetooth, the sound is monaural and blares like the sound is from a tin can or distant room.  If I manually disconnect/reconnect, the audio is stereo and functions properly.  Pulseaudio for the OS.

**Comment by cschramm** [comment]
Could it be a different audio profile? Did you try switching the profile?
