### ISSUE TITLE
Notifications are crashing

### ISSUE THREAD

**Issue by dragonDScript** [blueman-project/blueman#1646]
blueman: 2.1.2
BlueZ: 5.52
Distribution: Ubuntu 20.04.3 LTS
Desktop environment: GNOME

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->
1. Start python console
2. Spawn a notification (see troubleshooting)
3. See crash.

**Comment by cschramm** [comment]
Please elaborate.

**Comment by dragonDScript** [comment]
OK, closing. From the program notifications are working. However I'm getting authorization cancelled.
