### ISSUE TITLE
Add option to disable popups

### ISSUE THREAD

**Issue by bitshiftnetau** [blueman-project/blueman#1650]
blueman: 2.2.3
BlueZ: n/a
Distribution: Arch Linux
Desktop environment: i3

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

This is a feature request for the GUI notifications. Sometimes my bluetooth device turns off after a period of non-use and that's fine, but then 3 or 4 popups will appear: battery notif, disconnected, another battery notif... it's just annoying. Then, because I'm using i3 I have to close those windows as proper windows. 

Are these being spawned as notifications? If so I can just use something like Dunst. If not, is there a way you can make them notifications?
<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
The Windows are just a fallback because you don't have a notification daemon running.

**Comment by bitshiftnetau** [comment]
Ah! Aha! Ok cool thanks 😅
