### ISSUE TITLE
reconnecting to a device that has been removed.

### ISSUE THREAD

**Issue by sharpiexx** [blueman-project/blueman#1651]
blueman: 2.0.8
BlueZ: 5.62
Distribution: PCLinuxOS
Desktop environment: Mate.

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow. Y

I accidentally deleted my cell phone from Bluetooth devices and cannot figure out how to get it back.  I have re scanned for devices.  Uninstalled all blueman and bluez packages and reinstalled all.  There seems to be a residual file that is not being deleted and/or re initialized on installation.  It also seems affect all users on this computer.  No other users can see this device.  There seems to be no way to recover this device.

**Comment by cschramm** [comment]
Removing a device from the list does not store any state on your system. It's the other way around: It *removes* state from your system. BlueZ state is at `/var/lib/bluetooth`. You could double-check for any left-overs there but as far as I know there's nothing that would block a device from showing up. If you fail to discover the device, I'd say it's just not pairable. Did you try to find it from another system?
