### ISSUE TITLE
blueman-sendto (send a note) fails and returns with "Unable to find service record"

### ISSUE THREAD

**Issue by gregg00** [blueman-project/blueman#1655]
Sending Device:
blueman: 2.1.4-1+b2
BlueZ: 5.5
Distribution: raspian os
Desktop environment: LXDE-pi

Receiving Device:
Pinetime watch

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I am able to connect and pair to the device, but when i try to send a note, i get the error "Unable to find service record".  I see the same "unable to find service record" message when i run `blueman-applet --loglevel debug` and `cat /var/log/syslog`

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Does blueman-manager offer the option to send a file in the device's right-click menu? Please provide the device info that you can find there.

**Comment by gregg00** [comment]
I can only "send a note" to my pinetime, with blueman-manager.
I'm traveling at the moment, but when I get home I plan to try to directly connect to the pinetime rather than trying to connect over bluetooth.  As far as I understand, obex is a necessary part of the bluetooth stack if you want to transfer data over bluetooth, and it looks like my pinetime is missing obex.

**Comment by cschramm** [comment]
The options to send a file should be disabled if the device does not advertise an OBEX Object Push service (ID 0x1105).
