### ISSUE TITLE
Use Exceptions instead of returning None

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#1657]
We now sprinkle `assert <something> is not None` but for most we almost always know that we get the results we need. For example, `adapter_path_to_name` may return `None` which makes it optional for typing. What if we instead throw an Exception, let's say `ValueError` if we get a invalid path or None?

**Comment by cschramm** [comment]
In case of `adapter_path_to_name` I think the callers are more or less happy if they get `None` and that definitely happens. If we change it to throwing an exception, the callers will have to catch and handle that exception or things will break. That's rather verbose as well, so just getting rid of the assertion does not seem like a good enough reason. :sweat_smile:
