### ISSUE TITLE
bluetooth mouse dont reconnects

### ISSUE THREAD

**Issue by simsonmeno** [blueman-project/blueman#166]
mouse is: Icon S450
I paired it and accepted it as trusted device, but to connect it i must push every time the pairing button on the muose and than select it as input device in the devices' right click menu.

**Comment by cschramm** [comment]
Sound's like the mouse does not remember the pairing. To avoid re-pairing both sides have to remember that they are paired with each other. On the BlueZ / blueman side this is simply indicated by the device being present even if it's switched off and not physically available.

To get some insight, please start blueman-applet within a terminal window (see the [FAQ](https://github.com/blueman-project/blueman/blob/master/FAQ) for help), then open the devices window and turn on the mouse. Please show us the terminal output starting at the point where you turned it on.
