### ISSUE TITLE
UI improvements suggestions v2

### ISSUE THREAD

**Issue by liar666** [blueman-project/blueman#1660]
blueman: 2.2.2
BlueZ:5.60-0ubuntu2.1
Distribution:Mint
Desktop environment:i3

* [X ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Hi, with the latest blueman-applet from the Ubuntu repos (2.2.2), now everytime I connect/disconnect from a device and everytime I send a file to a device, an information dialog window is created.
During a single session, where I send multiple files (+ I have to connect/disconnect several times because BT is so baaad...), I get myriads of useless windows that get created and pollute my desktop. Fortunately, I've configured my WM so that popup dialogs do not get the mouse focus, so I can continue to work even if such windows appear. However this still means there is a moment when I'll need to take/waste time to close all these popups.
These dialog windows come without any button. Indeed, their only purpose is to show an information to the user.
My request for improvement would be to use Desktop Notifications/OSD rather than dialog windows, because they are designed, thus better suited, for this exact purpose. And (if configured correctly) they will not require the user to do any action to disappear.
If you do not like my idea or have a good reason to keep opening dialog windows rather than simple notifications, at least, please provide a configuration option somewhere the user can disable all these popups.

**Comment by infirit** [comment]
The windows are only a fallback when a notification daemon is not available. Something like dunst should be sufficient.
