### ISSUE TITLE
jerky audio and poor quality on Asus Rog blueetooth chipset

### ISSUE THREAD

**Issue by christianpadovano** [blueman-project/blueman#1667]
blueman:
BlueZ: jerky audio and poor quality on Asus Rog blueetooth chipset
Distribution:  zorin 16 pro 
Desktop environment: gnome

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
There's hardly anything blueman can do for you there. It supports switching the pulseaudio profile, especially between HFP / HSP and A2DP but that's it. Anything else is happening in lower layers, especially pulseaudio, maybe firmware if it's actually a chipset topic.
