### ISSUE TITLE
Icon-name conflicts: settings versus panel applet

### ISSUE THREAD

**Issue by ochosi** [blueman-project/blueman#167]
Hey everyone,

I'm maintaining an icon-theme for Xfce/Xubuntu (amongst others) and noticed that with the transition to the new blueman, the icon names for the settings-app and the panel-applet are identical (blueman, as opposed to the previously in use blueman-tray, if I'm not mistaken).

It'd be great if there could be a separate icon-name for the panel applet in blueman, e.g. "blueman-applet". You could ofc just create a symlink from "blueman" to it in your upstream icons, but it would enable me/us to have a monochrome icon in the panel again like we used to.

Thanks for this really nice piece of software!

**Comment by cschramm** [comment]
Thanks for this really nice piece of feedback! :wink: 

@Teknocrat Do you want to take on this?

**Comment by cschramm** [comment]
No @Teknocrat far and wide. :cry: 

I've created a PR. Does it fit your requirements?

**Comment by ochosi** [comment]
Yup, looks good to me! Thanks a bunch!
