### ISSUE TITLE
Thank you note

### ISSUE THREAD

**Issue by Kaspazza** [blueman-project/blueman#1680]
Hi, I just wanted to say **thank you**! 
I couldn't connect AirPods to my ubuntu, I spent hours trying different solutions but nothing worked. 
With blueman it was just as simple as installing it, restarting my system, and airpods connected instantly.

So thank you very much for your amazing work!

**Comment by cschramm** [comment]
To be honest, I have no clue what blueman could have done for you in such a matter 😅, but a thank you is always appreciated. 👍

(It might have been the packaging system that actually solved your problem by installing recommended (or even required) packages together with blueman.)
