### ISSUE TITLE
Blueman indicator (tray) icon doesn't change colors to indicate connection

### ISSUE THREAD

**Issue by kendoori** [blueman-project/blueman#1683]
blueman: 2.1.2
BlueZ: 5.53
Distribution: Mint 20.3
Desktop environment: Cinnamon

Am running a combo Wifi Bluetooth card (AX210NGW). The indicator (tray) icon doesn't change colors to indicate connection. I have an external USB Bluetooth that I've tried on the same machine. Blueman properly changes the indicator when it's connected to my devices. It shows in the tray I don't have both BT adapters enabled at the same time.

![image](https://user-images.githubusercontent.com/2447420/155390710-34bc4504-49a7-4080-808e-b2e02c2a957d.png)

**Comment by cschramm** [comment]
Please provide the debugging output of blueman-applet of when you connect to the device but the icon does not change.
