### ISSUE TITLE
bluetouth doesnt see my keyboard but see everything else

### ISSUE THREAD

**Issue by damnikindadontcare** [blueman-project/blueman#1684]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by freakluis** [comment]
I'm right where you are. I've tried all of my bt keyboards: newer or older. Nothing seems to work. Could it be a matter of the kernel rather than a problem with this package?

**Comment by cschramm** [comment]
Check `bluetoothctl` to see if your system knows the device in general, e.g. `bluetoothctl devices` for already discovered devices or `bluetoothctl scan on` for discovery. If it does not, check with another system if the device is visible at all. `btmon` could also help to check the physical layer but might be overwhelming of course.

**Comment by kybernetik42** [comment]
This is at my Laptop Linuxmint:
[Linux:~$ sudo bluetoothctl
[sudo] Passwort für harald:             
Agent registered
[M720 Triathlon]# agent KeyboardOnly
Agent is already registered
[M720 Triathlon]# default-agent
Default agent request successful
[M720 Triathlon]# pairable on
Changing pairable on succeeded
[M720 Triathlon]# pair 34:88:5D:6F:D0:EE
Device 34:88:5D:6F:D0:EE not available
[NEW] Device 34:88:5D:6F:D0:EE Keyboard K380
[CHG] Device 34:88:5D:6F:D0:EE Connected: no
[DEL] Device 34:88:5D:6F:D0:EE Keyboard K380
[M720 Triathlon]# pair 34:88:5D:6F:D0:EE
Device 34:88:5D:6F:D0:EE not available
[M720 Triathlon]# agent KeyboardOnly
Agent is already registered
[M720 Triathlon]# agent KeyboardOnly
Agent is already registered
[M720 Triathlon]# pair 34:88:5D:6F:D0:EE
Device 34:88:5D:6F:D0:EE not available
[M720 Triathlon]# scan on
Discovery started
[CHG] Controller 9C:FC:E8:DC:BA:71 Discovering: yes
...
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
....
[M720 Triathlon]# pair 34:88:5D:6F:D0:EE
Attempting to pair with 34:88:5D:6F:D0:EE
[CHG] Device 34:88:5D:6F:D0:EE Connected: yes
[agent] Passkey: 465628
[agent] Passkey: 465628
[agent] Passkey: 465628
[agent] Passkey: 465628
[agent] Passkey: 465628
[agent] Passkey: 465628
[agent] Passkey: 465628
[CHG] Device 34:88:5D:6F:D0:EE Modalias: usb:v046DpB342d4201
[CHG] Device 34:88:5D:6F:D0:EE UUIDs: 00001000-0000-1000-8000-00805f9b34fb
[CHG] Device 34:88:5D:6F:D0:EE UUIDs: 00001124-0000-1000-8000-00805f9b34fb
[CHG] Device 34:88:5D:6F:D0:EE UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Device 34:88:5D:6F:D0:EE ServicesResolved: yes
[CHG] Device 34:88:5D:6F:D0:EE Paired: yes
Pairing successful
[CHG] Device 34:88:5D:6F:D0:EE ServicesResolved: no
[CHG] Device 34:88:5D:6F:D0:EE Connected: no
[CHG] Device 74:F0:7D:E3:55:20 RSSI: -79
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[NEW] Device 6B:41:45:81:34:50 6B-41-45-81-34-50
[CHG] Device 35:12:4A:87:3C:60 RSSI: -86
[CHG] Device 6A:A9:70:B0:32:BA ManufacturerData Key: 0x004c
[CHG] Device 6A:A9:70:B0:32:BA ManufacturerData Value:
  10 06 23 1a e4 50 c4 76                          ..#..P.v        
[NEW] Device 20:19:16:47:23:08 20-19-16-47-23-08
[NEW] Device 76:12:2D:33:C6:9E 76-12-2D-33-C6-9E
[NEW] Device 5F:A1:13:EB:1B:7E 5F-A1-13-EB-1B-7E
[NEW] Device 5E:38:A4:D3:E1:4F 5E-38-A4-D3-E1-4F
[NEW] Device 03:EA:60:46:C0:10 03-EA-60-46-C0-10
[NEW] Device 42:9B:23:27:5E:66 42-9B-23-27-5E-66
[CHG] Device 20:19:16:47:23:08 Name: FM 01 Slider
[CHG] Device 20:19:16:47:23:08 Alias: FM 01 Slider
[CHG] Device 6B:AE:77:15:44:21 RSSI: -103
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[NEW] Device 72:CB:47:F6:10:2B 72-CB-47-F6-10-2B
[NEW] Device 62:C2:70:C2:5D:1C 62-C2-70-C2-5D-1C
[CHG] Device 6B:41:45:81:34:50 RSSI: -89
[CHG] Device 03:EA:60:46:C0:10 RSSI: -100
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[CHG] Device 6B:A7:22:95:6B:90 RSSI: -97
[NEW] Device 65:BF:15:28:4A:7C 65-BF-15-28-4A-7C
[NEW] Device 73:B6:E5:AA:E7:34 73-B6-E5-AA-E7-34
[CHG] Device 62:C2:70:C2:5D:1C ManufacturerData Key: 0x004c
[CHG] Device 62:C2:70:C2:5D:1C ManufacturerData Value:
  10 05 18 18 d4 3d 08                             .....=.         
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[CHG] Device 03:EA:60:46:C0:10 RSSI: -88
[NEW] Device 7D:CC:73:E2:48:A1 7D-CC-73-E2-48-A1
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[NEW] Device 7C:91:4E:B7:F6:62 7C-91-4E-B7-F6-62
[CHG] Device 7C:91:4E:B7:F6:62 RSSI: -82
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[CHG] Device 6B:41:45:81:34:50 RSSI: -99
[CHG] Device 6B:AE:77:15:44:21 RSSI: -90
[NEW] Device 70:26:08:24:0C:80 70-26-08-24-0C-80
[NEW] Device 7C:D1:C3:2F:5B:38 7C-D1-C3-2F-5B-38
[NEW] Device 48:DA:E9:D7:41:DD 48-DA-E9-D7-41-DD
[CHG] Device 34:88:5D:6F:D0:EE Class: 0x00000540
[CHG] Device 34:88:5D:6F:D0:EE Icon: input-keyboard
[CHG] Device 34:88:5D:6F:D0:EE Connected: yes
Authorize service
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   75 c8 12                                         u..             
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 73:C0:29:45:CE:44 ManufacturerData Key: 0x004c
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 73:C0:29:45:CE:44 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   0c 0e 00 c4 fe 4c a3 55 9d 9f b9 08 84 54 14 cb  .....L.U.....T..
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 40:62:37:ED:2F:1C 40-62-37-ED-2F-1C
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 35:12:4A:87:3C:60 RSSI: -78
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 5D:60:0B:15:01:2F 5D-60-0B-15-01-2F
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 4D:A8:E8:75:81:E1 4D-A8-E8-75-81-E1
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device F6:86:01:CA:BB:E0 RSSI: -100
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 73:C0:29:45:CE:44 ManufacturerData Key: 0x004c
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 73:C0:29:45:CE:44 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   10 07 3a 1f 7a f9 2e 8f 08                       ..:.z....       
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 64:4E:16:32:BB:A5 64-4E-16-32-BB-A5
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 35:12:4A:87:3C:60 RSSI: -88
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device E4:D5:99:B0:8A:B6 RSSI: -98
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   75 c8 12                                         u..             
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 03:EA:60:46:C0:10 RSSI: -99
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 66:41:2A:6A:FA:98 66-41-2A-6A-FA-98
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 67:B1:3C:CA:BD:1A 67-B1-3C-CA-BD-1A
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 6B:AE:77:15:44:21 ManufacturerData Key: 0x004c
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 6B:AE:77:15:44:21 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   0c 0e 00 8d 54 1d 93 fb c8 07 32 1b d3 83 1f 23  ....T.....2....#
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   10 06 4c 1d 4e 2b ec 38                          ..L.N+.8        
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   75 c8 12                                         u..             
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 55:1C:D7:D4:57:D3 55-1C-D7-D4-57-D3
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device E4:D5:99:B0:8A:B6 RSSI: -85
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 35:12:4A:87:3C:60 RSSI: -79
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 7A:56:20:1C:FC:E3 ManufacturerData Key: 0x004c
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 7A:56:20:1C:FC:E3 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   10 06 6b 1d 11 71 30 68                          ..k..q0h        
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 34:88:5D:6F:D0:EE Connected: no
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 34:88:5D:6F:D0:EE Class: 0x00002540
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 34:88:5D:6F:D0:EE Icon: input-keyboard
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 51:BB:62:AF:D1:7A 51-BB-62-AF-D1-7A
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device E4:D5:99:B0:8A:B6 RSSI: -94
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   75 c8 12                                         u..             
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 6B:AE:77:15:44:21 ManufacturerData Key: 0x004c
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 6B:AE:77:15:44:21 ManufacturerData Value:
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   0c 0e 00 8e 54 cd ce 32 26 46 66 00 b9 cd 79 52  ....T..2&Ff...yR
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no):   10 06 4c 1d 4e 2b ec 38                          ..L.N+.8        
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [CHG] Device 35:12:4A:87:3C:60 RSSI: -88
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): [NEW] Device 56:30:01:B8:6A:34 56-30-01-B8-6A-34
[agent] Authorize service 00001124-0000-1000-8000-00805f9b34fb (yes/no): Request canceled
[CHG] Device 7A:56:20:1C:FC:E3 ManufacturerData Key: 0x004c
[CHG] Device 7A:56:20:1C:FC:E3 ManufacturerData Value:
  0c 0e 00 4f 00 95 a1 39 01 7a 52 1b fd 23 2f 1e  ...O...9.zR..#/.
  10 06 6b 1d 11 71 30 78                          ..k..q0x        
[CHG] Device E4:D5:99:B0:8A:B6 RSSI: -81
[NEW] Device 64:DF:50:14:B2:EC 64-DF-50-14-B2-EC
[CHG] Device 35:12:4A:87:3C:60 RSSI: -78
[NEW] Device F1:A9:37:70:72:58 ScanWatch 78
[CHG] Device 6B:AE:77:15:44:21 ManufacturerData Key: 0x004c
[CHG] Device 6B:AE:77:15:44:21 ManufacturerData Value:
  0c 0e 00 8f 54 72 99 36 53 ce 6e fa 2a b8 e7 2f  ....Tr.6S.n.*../
  10 06 4c 1d 4e 2b ec 38                          ..L.N+.8        
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[NEW] Device 4E:F3:4C:25:06:56 4E-F3-4C-25-06-56
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[CHG] Device 34:88:5D:6F:D0:EE RSSI: -54
[CHG] Device F6:86:01:CA:BB:E0 RSSI: -91
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[CHG] Device 03:EA:60:46:C0:10 RSSI: -91
[CHG] Device 64:4E:16:32:BB:A5 ManufacturerData Key: 0x004c
[CHG] Device 64:4E:16:32:BB:A5 ManufacturerData Value:
  01 00 00 00 00 00 00 00 00 00 00 08 00 00 00 00  ................
  00                                               .               
[CHG] Device 7A:56:20:1C:FC:E3 ManufacturerData Key: 0x004c
[CHG] Device 7A:56:20:1C:FC:E3 ManufacturerData Value:
  10 06 6b 1d 11 71 30 78                          ..k..q0x        
[CHG] Device 4E:F3:4C:25:06:56 RSSI: -94
[NEW] Device 72:82:F9:98:3C:A7 72-82-F9-98-3C-A7
[CHG] Device 35:12:4A:87:3C:60 RSSI: -88
[CHG] Device 34:88:5D:6F:D0:EE RSSI: -44
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[CHG] Device 6B:AE:77:15:44:21 RSSI: -99
[CHG] Device 64:4E:16:32:BB:A5 ManufacturerData Key: 0x004c
[CHG] Device 64:4E:16:32:BB:A5 ManufacturerData Value:
  10 07 00 1f c1 17 5d 86 48                       ......].H       
[CHG] Device E4:D5:99:B0:8A:B6 RSSI: -93
[NEW] Device 74:24:33:AE:35:CE 74-24-33-AE-35-CE
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[NEW] Device 61:88:6D:24:3D:8B 61-88-6D-24-3D-8B
[NEW] Device 70:8B:34:DF:EB:FF 70-8B-34-DF-EB-FF
[CHG] Device 64:4E:16:32:BB:A5 ManufacturerData Key: 0x004c
[CHG] Device 64:4E:16:32:BB:A5 ManufacturerData Value:
  01 00 00 00 00 00 00 00 00 00 00 08 00 00 00 00  ................
  00                                               .               
[NEW] Device F2:93:55:46:A2:19 F2-93-55-46-A2-19
[M720 Triathlon]# trust 34:88:5D:6F:D0:EE
[CHG] Device 34:88:5D:6F:D0:EE Trusted: yes
Changing 34:88:5D:6F:D0:EE trust succeeded
[CHG] Device 6B:AE:77:15:44:21 RSSI: -89
[CHG] Device 6B:41:45:81:34:50 ManufacturerData Key: 0x004c
[CHG] Device 6B:41:45:81:34:50 ManufacturerData Value:
  10 06 0d 1a 1a 05 83 f6                          ........        
[NEW] Device 5F:B4:3C:80:98:0E 5F-B4-3C-80-98-0E
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[CHG] Device 64:4E:16:32:BB:A5 ManufacturerData Key: 0x004c
[CHG] Device 64:4E:16:32:BB:A5 ManufacturerData Value:
  10 07 00 1f c1 17 5d 86 48                       ......].H       
[NEW] Device 53:8B:F0:B4:FF:1A 53-8B-F0-B4-FF-1A
[M720 Triathlon]# connect 34:88:5D:6F:D0:EE
**Attempting to connect to 34:88:5D:6F:D0:EE
Failed to connect: org.bluez.Error.Failed**
[CHG] Device E4:D5:99:B0:8A:B6 RSSI: -81
[CHG] Device F6:86:01:CA:BB:E0 RSSI: -100
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[CHG] Device 74:24:33:AE:35:CE RSSI: -90
[CHG] Device 74:24:33:AE:35:CE ManufacturerData Key: 0x004c
[CHG] Device 74:24:33:AE:35:CE ManufacturerData Value:
  10 07 5e 1f 5a 6c cd 43 c8                       ..^.Zl.C.       
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[CHG] Device 4E:F3:4C:25:06:56 RSSI: -102
[NEW] Device 6F:E2:E7:6E:0F:41 6F-E2-E7-6E-0F-41
[CHG] Device 74:24:33:AE:35:CE ManufacturerData Key: 0x004c
[CHG] Device 74:24:33:AE:35:CE ManufacturerData Value:
  10 07 5b 1f 5a 6c cd 43 c8                       ..[.Zl.C.       
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[CHG] Device 7A:56:20:1C:FC:E3 ManufacturerData Key: 0x004c
[CHG] Device 7A:56:20:1C:FC:E3 ManufacturerData Value:
  10 06 23 1d 11 71 30 38                          ..#..q08        
[NEW] Device 67:6B:0A:EC:C3:F2 67-6B-0A-EC-C3-F2
[NEW] Device 6A:28:96:92:0E:BF 6A-28-96-92-0E-BF
[CHG] Device 35:12:4A:87:3C:60 RSSI: -79
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[CHG] Device 6F:E2:E7:6E:0F:41 ManufacturerData Key: 0x004c
[CHG] Device 6F:E2:E7:6E:0F:41 ManufacturerData Value:
  01 00 00 00 00 00 00 00 00 00 00 08 00 00 00 00  ................
  00                                               .               
[CHG] Device 6B:41:45:81:34:50 RSSI: -87
[CHG] Device 03:EA:60:46:C0:10 RSSI: -99
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b 12           ..........MK.   
[CHG] Device 6F:E2:E7:6E:0F:41 ManufacturerData Key: 0x004c
[CHG] Device 6F:E2:E7:6E:0F:41 ManufacturerData Value:
  01 00 00 00 00 00 00 00 00 00 00 08 00 00 00 00  ................
  00                                               .               
[CHG] Device 4E:F3:4C:25:06:56 RSSI: -90
[CHG] Device 74:24:33:AE:35:CE ManufacturerData Key: 0x004c
[CHG] Device 74:24:33:AE:35:CE ManufacturerData Value:
  10 07 5b 1f 5a 6c cd 4b c8                       ..[.Zl.K.       
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Key: 0x0003
[CHG] Device C0:28:8D:4E:75:C8 ManufacturerData Value:
  00 8c 09 00 00 08 c4 98 80 c4 4d 4b c0 28 8d 4e  ..........MK.(.N
  75 c8 12                                         u..             
[M720 Triathlon]# scan off
Discovery stopped
....
[M720 Triathlon]# 





It is ending with this:
[M720 Triathlon]# connect 34:88:5D:6F:D0:EE
Attempting to connect to 34:88:5D:6F:D0:EE
Failed to connect: org.bluez.Error.Failed

**Comment by kybernetik42** [comment]
@cschramm: The point, why I posted it, that I was able to connect the keyboard, but after boot, it was not reconizable. I must delete the keyboard from the list, and the pair again. But pairing again was not easy, it takes several tries, before the keyboard was paired again. Indeed, it is not exactly a contribution to this topic, you are right.

**Comment by freakluis** [comment]
By the way, the problem I had had with my k380 keyboard was solved with this comment by @cschramm 

> Check `bluetoothctl` to see if your system knows the device in general, e.g. `bluetoothctl devices` for already discovered devices or `bluetoothctl scan on` for discovery. If it does not, check with another system if the device is visible at all. `btmon` could also help to check the physical layer but might be overwhelming of course.
