### ISSUE TITLE
How to connect Blueman automatically

### ISSUE THREAD

**Issue by TonSino** [blueman-project/blueman#1688]
I'm using Blueman with Manjaro xfce 22. I want to be able to connect automatically at startup, but it doesn't work very well for beginners.
I want you to teach me the method in detail and in an easy-to-understand manner.

**Comment by cschramm** [comment]
This is supported by blueman 2.2 and for supported (i.e. auto-connect (HID and audio), network, and serial) services only.

**Comment by TonSino** [comment]
> This is supported by blueman 2.2 and for supported (i.e. auto-connect (HID and audio), network, and serial) services only.

OK. Thank you.
