### ISSUE TITLE
[Feature Request]Add option to never show the tray icon / indicator

### ISSUE THREAD

**Issue by FreaxMATE** [blueman-project/blueman#1689]
If you are using the Ayatana bluetooth indicator you do not want the blueman app indicator to always appear when you turn on the bluetooth. So an option (gsettings key) to never show the tray/indicator icon would be helpful.

**Comment by cschramm** [comment]
This is duplicate of #1495. You're welcome to check #1496 that makes the StatusIcon plugin unloadable.
