### ISSUE TITLE
blueman-applet not starting after building latest version

### ISSUE THREAD

**Issue by avma** [blueman-project/blueman#1691]
blueman:2.2.4
BlueZ: 5.63
Distribution: Linux Mint 20.3
Desktop environment: Cinnamon

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->
[blueman-applet --loglevel debug.txt](https://github.com/blueman-project/blueman/files/8260694/blueman-applet.--loglevel.debug.txt)

**Comment by avma** [comment]
[blueman-applet --loglevel debug.txt](https://github.com/blueman-project/blueman/files/8260968/blueman-applet.--loglevel.debug.txt)

**Comment by avma** [comment]
The debug output for ver 2.2.4
[blueman-applet --loglevel debug_2.2.4.txt](https://github.com/blueman-project/blueman/files/8261759/blueman-applet.--loglevel.debug_2.2.4.txt)

**Comment by cschramm** [comment]
So did you try to unmask blueman-mechanism.service?

**Comment by avma** [comment]
No,  how do i do that?

**Comment by cschramm** [comment]
That should work, yes. According to the D-Bus error message you masked the service in systemd, i.e. in addition to disabling it (removing the symlink to the unit file) you symlinked it to `/dev/null`.

**Comment by infirit** [comment]
Where is `blueman-mechanism` installed? And if you run it as root what does it output?

**Comment by avma** [comment]
It is located in '/usr/local/libexec'

this is the output of the command `sudo blueman-mechanism`

`❯       sudo ./blueman-mechanism
Traceback (most recent call last):
  File "./blueman-mechanism", line 6, in <module>
    from blueman.main.MechanismApplication import MechanismApplication
ModuleNotFoundError: No module named 'blueman'`

**Comment by infirit** [comment]
Basically, don't install Blueman to your home dir. Blueman-mechanism runs as root and will not be able to find the python modules it needs. Everything to `/use/local` will be better.

**Comment by avma** [comment]
How do I do that? 
I was following the build instruction on the README:
`./autogen.sh` `./configure` `make` `sudo make install`

**Comment by cschramm** [comment]
To get a newer version you could try any of

- https://blueman.cschramm.eu/debian/ git snapshot packages
- building a proper .deb (check https://salsa.debian.org/cschramm/blueman/-/tree/main/debian)
- hacking the installation; something like `sudo mv /usr/local/lib/python3.8/site-packages/_blueman.so /usr/local/lib/python3.8/site-packages/blueman /usr/local/lib/python3.8/dist-packages/` could already do the trick

**Comment by avma** [comment]
Ok, I'll give it a try....

**Comment by avma** [comment]
yep, it worked, I now have  ver 2.2.1instaled. Thank you
