### ISSUE TITLE
I want to upgrade from 2.12 to 2.24

### ISSUE THREAD

**Issue by kendoori** [blueman-project/blueman#1698]
blueman: 2.12
BlueZ:  5.62
Distribution: Linux Mint
Desktop environment: Cinnamon

Since my distribution doesn't include a newer version, I downloaded source and tried to compile. When I try to run blueman-manager, it doesn't work.

https://pastebin.com/3kq2gci0

I went as far as removing 2.12. but that didn't work.

**Comment by cschramm** [comment]
`sudo ./configure && make && make install` unnecessarily runs `./configure` as root but does not run `make install` as root. The prefix is `/usr/local` (as you do not actually configure anything) and you do not have permission to write there, so `make install` fails to do its job.

However, you'll run into more problems, cp. #1691. For Debian based systems you'd typically want something like `CYTHONEXEC=cython3 PYTHON=python3 ./configure --prefix=/usr --with-dhcp-config=/etc/dhcp/dhcpd.conf --with-systemdsystemunitdir=/lib/systemd/system` and need to apply or emulate some `dh_python3 --shebang=/usr/bin/python3` magic (installing to dist-packages, rewriting shebang, ...).

**Comment by kendoori** [comment]
@cschramm I'm not so smart about these things, how do I fix this?

**Comment by cschramm** [comment]
The simple answer is, your system does not support blueman 2.2. You could go with third party packages, e.g. snapshots from https://blueman.cschramm.eu/debian/, or get a system that does. The closest match would be Ubuntu 21.10. It has blueman 2.2.2.

**Comment by infirit** [comment]
> Isn't this a bit of a bug in Linux, or is it just user error?

User error but it's not their fault. Building from source isn't something regular user should do.

**Comment by souravdas142** [comment]
@infirit  I have been continuously supporting Blueman newest package to all possible versions of ubuntu[derived] and debian. taking package information from @cschramm  @ https://pipewire-debian.github.io, If user want to download from there they can.
