### ISSUE TITLE
Repository has an empty about section

### ISSUE THREAD

**Issue by thedrow** [blueman-project/blueman#1706]
It's easier to search for these kind of projects if the repository's about section is filled and the repository has topics.

**Comment by cschramm** [comment]
Not sure what people would search for, but an about section would be nice in any way. Do you have a proposal?

**Comment by thedrow** [comment]
"Blueman is a GTK+ Bluetooth Manager" should be fine for the description

**Comment by thedrow** [comment]
As for topics, I think:

- linux
- bluetooth
- gtk
- python-library

should be a good start
