### ISSUE TITLE
Bluetooth-Manager device listing is not persistent - Devices spontaneously disappear from dialog after 15-60 seconds

### ISSUE THREAD

**Issue by nsleasy** [blueman-project/blueman#1713]
blueman:
  2.2.4-2.1

BlueZ:
  5.64-2.1

Linux Kernel:
5.17.x

Distribution:
  Fedora 25
  Fedora 26
  openSUSE Tumbleweed

Desktop environment:
  Cinnamon
  Xfce

Problem Description:
All devices disappear from the Blueman listing after keeping the dialog open 15-60 seconds and will not be re-detected on subsequent runs.

The lack of persistent device listing is independent of any other bluetooth front-end GUI being installed. The behavior is the same: The device listing is not persistent and items start disappearing from the Buetooth-Manager dialog after 15-60 seconds.

Test Results -

F36 Cinnamon Spin on Thinkpad T450:
  > Blueman fails to detect devices by itself
  > Blueberry install in Spin environment is okay

F36 Cinnamon Spin on Dell Latitude 7480:
  > Blueman fails to detect devices by itself
  > Blueberry install in Spin environment is okay

F36 Cinnamon Fresh install on Thinkpad T450:
  > Blueman fails to detect devices by itself
  > Blueberry install is okay

F35 Cinnamon working environment on Thinkpad T450
  > Blueman (installed) fails to detect devices by itself
  > Blueberry (default) install is okay

F36 Cinnamon upgrade from working F35 Cinnamon install on Thinkpad T450:
  > Blueman fails to detect devices by itself
  > Blueberry is okay

openSUSE Tumbleweed - Cinnamon & Xfce: Same results as above, although after initial testing, the Search function started working without Blueberry. The lack of persistent device listings remains the same.

# systemctl status bluetooth.service
● bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-05-07 16:31:34 EDT; 30min ago
       Docs: man:bluetoothd(8)
   Main PID: 815 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 9140)
     Memory: 2.0M
        CPU: 320ms
     CGroup: /system.slice/bluetooth.service
             └─815 /usr/libexec/bluetooth/bluetoothd

May 07 16:31:34 t450 bluetoothd[815]: Bluetooth management interface 1.21 initialized
May 07 16:31:43 t450 bluetoothd[815]: Player registered: sender=:1.60 path=/media_player0
May 07 16:31:43 t450 bluetoothd[815]: Endpoint registered: sender=:1.60 path=/MediaEndpoint/A2DPSource/ldac
May 07 16:31:43 t450 bluetoothd[815]: Endpoint registered: sender=:1.60 path=/MediaEndpoint/A2DPSource/aac
May 07 16:31:43 t450 bluetoothd[815]: Endpoint registered: sender=:1.60 path=/MediaEndpoint/A2DPSink/sbc
May 07 16:31:43 t450 bluetoothd[815]: Endpoint registered: sender=:1.60 path=/MediaEndpoint/A2DPSource/sbc
May 07 16:31:43 t450 bluetoothd[815]: Endpoint registered: sender=:1.60 path=/MediaEndpoint/A2DPSink/sbc_xq
May 07 16:31:43 t450 bluetoothd[815]: Endpoint registered: sender=:1.60 path=/MediaEndpoint/A2DPSource/sbc_xq
May 07 16:31:43 t450 bluetoothd[815]: Endpoint registered: sender=:1.60 path=/MediaEndpoint/A2DPSource/fastst>
May 07 16:31:43 t450 bluetoothd[815]: Endpoint registered: sender=:1.60 path=/MediaEndpoint/A2DPSource/fastst>
lines 1-22/22 (END)

**Comment by cschramm** [comment]
Please stop any running blueman-applet process and start `blueman-applet --loglevel debug` in a terminal, then continue as usual (search for devices?) to gather debugging output.

**Comment by nsleasy** [comment]
Hi Christopher,

The terminal output from blueman-applet is attached.

The problem occurs on multiple platforms, but this particular environment is Fedora Live with SE Linux enabled by default. Initially in that environment, SE Linux threw up an error on blueman start-up, but then did not recur. I've attached that output as well in just case it provides any useful information for you.

Let me know if there's anything else that I can do.

Thanks!
Nolan

________________________________

**Comment by infirit** [comment]
This looks pretty normal to me. The removal comes from the underlying linux bluetooth subsystem. Any unpaired devices will be removed after discovery has ended.

**Comment by cschramm** [comment]
Yes, I agree.

For Fedora you write that blueman fails to detect devices, so are you saying that the devices that are visible in the log do not appear in blueman-manager?

**Comment by nsleasy** [comment]
The initial testing on Fedora 36-Beta may have confused the issue, but in the many environments where I've tested it since, blueman DOES pick up detected devices but they are NOT persistent in the listing. After about 15-60 seconds, all of the discovered devices start disappearing from the blueman list until they are gone.

This is not normal. I just checked all of the following environments and the bluetooth device listing is persistent in all of them:

Cinnamon using the 'blueberry' client
GNOME using the 'gnome-bluetooth' client
KDE using the 'bluedevil5' client
Android
Windows

This is not the bluetooth stack removing unpaired devices after discovery has ended. This appears to be conflict between the blueman client and some process running in the underlying stack. All of the other bluetooth clients handle it somehow so that the listing is persistent. Something is not being handled by blueman.

________________________________

**Comment by infirit** [comment]
> The initial testing on Fedora 36-Beta may have confused the issue, but in the many environments where I've tested it since, blueman DOES pick up detected devices but they are NOT persistent in the listing. After about 15-60 seconds, all of the discovered devices start disappearing from the blueman list until they are gone.

Which is how it's intended and not a bug.

>This is not normal. 

According to you but this is how blueman-manager is intended to work.

>I just checked all of the following environments and the bluetooth device listing is persistent in all of them: Cinnamon using the 'blueberry' client GNOME using the 'gnome-bluetooth' client KDE using the 'bluedevil5' client Android Windows 

All those work differently. Each one of them keep discovering while adding devices. Blueman on the other hand stops discovery after 60 seconds (there is a little progress bar in bottom left in blueman-manager).

>This is not the bluetooth stack removing unpaired devices after discovery has ended. This appears to be conflict between the blueman client and some process running in the underlying stack. All of the other bluetooth clients handle it somehow so that the listing is persistent. Something is not being handled by blueman.

Yes it is how the bluetooth stack works. You can literally test this yourself by running the tools that comes with the bluetooth stack. `bluetootctl`. Let it scan for a bit, turn scan off and see how devices get removed.

**Comment by nsleasy** [comment]
Then I simply would never use blueman, since every other option in the Linux repositories is better. Much better.





________________________________

**Comment by cschramm** [comment]
So this is basically a feature request for not stopping the discovery in blueman-manager? I don't remember such a request up to now (what we had are discussions if it makes sense to start the discovery but nothing about the stop mechanism). Could you elaborate on the use case?

**Comment by nsleasy** [comment]
What you call a design feature, I consider a bug. Literally, every other bluetooth tool remains in discovery mode as long as the Discovery/Search/Available-Devices dialog is open. Blueman is the lone exception and, by definition, that means that its behavior is not normal.

What if I have a device which, for whatever reason, takes more time to be discovered? With Blueman, I might never be able to pair it because the Blueman Devices dialog leaves discovery mode almost immediately. I have seen older devices that take 1-3 minutes to become available, especially in crowded environments.

From my perspective, Blueman is unusable in its current state. Fedora has adopted it as the default for its Cinnamon environment. I will simply uninstall it and replace it with Blueberry, which is the default in the Linux Mint implementation of their flagship DE.

________________________________

**Comment by cschramm** [comment]
> Literally, every other bluetooth tool remains in discovery mode as long as the Discovery/Search/Available-Devices dialog is open. Blueman is the lone exception and, by definition, that means that its behavior is not normal.

I agree but have to add:
- There are basically only two tools valid for closer comparison: gnome-bluetooth and bluedevil.
- We do not aim at doing the exact same as those tools. What would be the point of blueman then (except partly avoiding vast dependencies)?

The design decision we talk about was taken by the original authors of blueman, so I do not have any personal stake in it, just nobody considered it a bug or problem up to now.

> I have seen older devices that take 1-3 minutes to become available, especially in crowded environments.

I'd appreciate some data on that, ideally a btmon / btsnoop trace. That sounds like an actual problem that have never been raised before.

> I will simply uninstall it and replace it with Blueberry, which is the default in the Linux Mint implementation of their flagship DE.

You're welcome but prepare that Linux Mint will probably have bad news for you. :wink:

**Comment by nsleasy** [comment]
"The design decision we talk about was taken by the original authors of blueman, so I do not have any personal stake in it, just nobody considered it a bug or problem up to now."

It's a poor design. Perhaps your current users have simply resigned themselves to put up with the anomaly or the vast majority never use bluetooth in the Linux environment in the first place. openSUSE doesn't even install a bluetooth manager as part of its Cinnamon desktop pattern, allowing its users to get whatever they chose elsewhere.

In any case, please understand that blueman is an outlier for its lack of a persistent available device listing. Frankly, it feels very amateurish in that regard. Otherwise, it has some nice features.

If the Cinnamon folks ever decide to eliminate Blueberry in favor of Bluetooth-Manager ('blueman'), then I would likely switch to any of the other desktop environments (GNOME or KDE), where things work normally. It would be unfortunate, however, because it would be the only flaw in an otherwise perfect Cinnamon desktop.


________________________________
