### ISSUE TITLE
Can't find mouse

### ISSUE THREAD

**Issue by NatGarrison** [blueman-project/blueman#1718]
blueman: 2.2.3
BlueZ:
Distribution: Fedora 36
Desktop environment: Cinnamon

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->
I just replaced Fedora 34 with a complete new install of Fedora 36.  I have a Logitech M557 Bluetooth mouse.  The mouse would connect and work with my Fedora 34.  Now with the new installation of Fedora 36 the Blueman program will not find my M557 when I click the "Search" item in the program after pushing the "connect" button on the bottom of my mouse.

**Comment by cschramm** [comment]
Did you check bluetoothctl or any other frontend? If it does not show up anywhere, I'd say it's just not visible.
