### ISSUE TITLE
Bluetooth mouse (vaio) cannot reconnect

### ISSUE THREAD

**Issue by sonic1776** [blueman-project/blueman#172]
I have installed blueman. Thereafter, I have connected and use my mouse. After the first reboot, I cannot reconnect. When I click on "setup new device" said "no adapters found"! I do not understand why this happend. I use a lenovo G510 laptop.

**Comment by cschramm** [comment]
See the [No adapter or not able to turn on bluetooth](https://github.com/blueman-project/blueman/wiki/Troubleshooting#no-adapter-or-not-able-to-turn-on-bluetooth) for debugging this.
