### ISSUE TITLE
Plugins: Selection fails

### ISSUE THREAD

**Issue by clefebvre** [blueman-project/blueman#1726]
blueman: main branch
BlueZ: N/A
Distribution: Linux Mint
Desktop environment: Cinnamon

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Steps to reproduce:

- Launch the applet
- Right-click the tray icon
- Choose "Plugins"
- Select any plugin in the list

No details are loaded in the right pane. The following exception is visible in the output:

```
clem@airtop ~/Sandbox/blueman $ blueman-applet 
blueman-applet 12.45.41 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 12.45.42 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority

(blueman-applet:380964): Gtk-CRITICAL **: 12:45:44.769: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/gui/applet/PluginDialog.py", line 196, in on_selection_changed
    name = self.list.get(tree_iter, "name")["name"]
  File "/usr/lib/python3/dist-packages/blueman/gui/GenericList.py", line 145, in get
    ret[items[i]] = self.liststore.get(tree_iter, self.ids[items[i]])[0]
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 934, in get
    values.append(self.get_value(treeiter, col))
TypeError: unknown type (null)
```

The issue happens at:

`name = self.list.get(tree_iter, "name")["name"]`

The generic nature of GenericList makes this a pain to debug. I didn't manage to find a solution, but the tree_iter in any case is correct since it can be used to get the value directly without any problems:

`name = model.get_value(tree_iter, 4)`

**Comment by clefebvre** [comment]
In case it's relevant. This is with python 3.10.4.

**Comment by cschramm** [comment]
I can confirm that. Caused by 4f2520b19fcfd0dbb02758126eedf6208ec2d5f3. @infirit

**Comment by infirit** [comment]
It's most likely that I forgot to convert from/to a child iter. I'll have a look.

**Comment by infirit** [comment]
Here is a quick fix. I want to dig a bit deeper before as I see some oddities I like to investigate.

```patch
diff --git a/blueman/gui/applet/PluginDialog.py b/blueman/gui/applet/PluginDialog.py
index 78c8e51f..168ee2bb 100644
--- a/blueman/gui/applet/PluginDialog.py
+++ b/blueman/gui/applet/PluginDialog.py
@@ -190,7 +190,7 @@ class PluginDialog(Gtk.Window):
         return False

     def on_selection_changed(self, selection: Gtk.TreeSelection) -> None:
-        model, tree_iter = selection.get_selected()
+        tree_iter = self.list.selected()
         assert tree_iter is not None

         name = self.list.get(tree_iter, "name")["name"]
```
