### ISSUE TITLE
2.2.5 release tarball broken: configure has literal `PKG_CHECK_MODULES`

### ISSUE THREAD

**Issue by mgorny** [blueman-project/blueman#1743]
blueman: 2.2.5
BlueZ: 5.64
Distribution: Gentoo Linux
Desktop environment: Xfce

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

It seems that the 2.2.5 release tarball was generated on a system without pkg-config installed. It has literal:

    PKG_CHECK_MODULES(PYTHON, python-${PYTHON_VERSION})

which makes the script fail with:

    ./configure: line 14427: syntax error near unexpected token `PYTHON,'
    ./configure: line 14427: `PKG_CHECK_MODULES(PYTHON, python-${PYTHON_VERSION})'

**Comment by infirit** [comment]
@mgorny I have updated the tarballs which should be ok as they pass distcheck.

**Comment by cschramm** [comment]
How did that break? 🙄

**Comment by mgorny** [comment]
Thanks, I can confirm that it works now. Also, seems to work nice with Python 3.11 :+1:.

**Comment by infirit** [comment]
Thanks for letting us know so quickly  @mgorny .
