### ISSUE TITLE
Can't find my OnePlus Bullet Wireless Z from my Linux Mint (on RedmiBook Pro 14)

### ISSUE THREAD

**Issue by ShaminAsfaq** [blueman-project/blueman#1744]
blueman:
BlueZ:
Distribution: Linux Mint 20.3 MATE 64-bit
Desktop environment: MATE

I can't see my bluetooth earphone and thus can't pair it.

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
Most devices don't show up unless you put it in a pairing state. If it still does not show follow the troubleshooting page https://github.com/blueman-project/blueman/wiki/Troubleshooting
