### ISSUE TITLE
blueman restarts bluetoothd wrongly

### ISSUE THREAD

**Issue by gentoo-root** [blueman-project/blueman#175]
https://github.com/blueman-project/blueman/blob/master/blueman/plugins/mechanism/Config.py#L35

Killing bluetoothd and restarting in manually is completely wrong, especially on systemd systems.

1. If you restart bluetoothd by hands, systemd will be unable to keep track of it. Also cgroups mechanism of systemd will be omitted.
2. bluetoothd may be out of $PATH (e.g. on my system it is at /usr/libexec/bluetooth/bluetoothd), so restarting it by calling "bluetoothd" will not work.
3. Capabilities and limits set by systemd will be gone after restarting bluetoothd by hands.
4. Any possible parameters that should be given to bluetoothd will be gone.
5. bluetoothd may not terminate in one second, in that case it will not be restarted.

So it is completely wrong to manually restart bluetoothd by killing it and running "bluetoothd" after a second (not only on systemd systems). In case of systemd, it could be restarted by using D-Bus interface of systemd. In case of other init systems, their methods of restarting should be used.

**Comment by cschramm** [comment]
I agree. Depending on #174, we hopefully don't even need the restart anymore with recent BlueZ versions.
