### ISSUE TITLE
Use gtkinfobar instead of MessageArea

### ISSUE THREAD

**Issue by ochosi** [blueman-project/blueman#178]
I know blueman has been around longer than Gtk3, but it'd be nice to use some of the new widgets (where they make sense), especially when the current widget seems to break with many themes.

For failed attempts at establishing a connection, a "blueman+gui+MessageArea+MessageArea" widget is used. It would be great to just use the appropriate infobar instead.

See the screenshots below (with the Numix gtk theme, same results with Ambiance or Greybird).

![irc0c9u](https://cloud.githubusercontent.com/assets/261436/6059365/f2a85ce4-ad30-11e4-8d87-36bee34494de.png)
![ereuhpr](https://cloud.githubusercontent.com/assets/261436/6059368/fb9d462a-ad30-11e4-94f5-6c9bb034b144.png)

**Comment by cschramm** [comment]
Definitely. PR? :grin:

**Comment by infirit** [comment]
Merged the code from @cschramm with some modification. There is one thing to still, see #747. Closing this one, further comments can be done in #747
