### ISSUE TITLE
Force automake 1.16.4 for python >=3.10 support

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#1781]
Bulseeye does not have a recent enough automake version but bookworm will.

Reminder to update the python docker images when they move to bookworm. Then we can force the minimum automake version in configure.ac.

**Comment by cschramm** [comment]
I think 1.16.3 is sufficient and it's in bullseye. Missing something? :thinking:

**Comment by infirit** [comment]
I am :disappointed:
