### ISSUE TITLE
Missing test directory in 2.3.1 tarball

### ISSUE THREAD

**Issue by knuxify** [blueman-project/blueman#1790]
blueman: 2.3.1

The latest tarballs (https://github.com/blueman-project/blueman/releases/download/2.3.1/blueman-2.3.1.tar.gz, https://github.com/blueman-project/blueman/releases/download/2.3.1/blueman-2.3.1.tar.xz) are missing the test directory.

**Comment by infirit** [comment]
I know why. I'll fix it for 2.3.2.

**Comment by infirit** [comment]
Should be fixed with #1794

**Comment by infirit** [comment]
Merged, closing.
