### ISSUE TITLE
Improve the notification error message for a failed connect

### ISSUE THREAD

**Issue by birdie-github** [blueman-project/blueman#1809]
blueman: blueman-2.2.5-1.fc36.x86_64
BlueZ: bluez-5.65-1.fc36.x86_64
Distribution: Fedora 36
Desktop environment: XFCE

When trying to manually connect to a known BT device this message is shown which is not human readable. Maybe you could show something more comprehensible.

Thanks!

![error](https://user-images.githubusercontent.com/4958603/182257323-df19831a-f6e1-4839-879d-caae6817a2c5.png)

**Comment by birdie-github** [comment]
@cschramm 

Error messages in `ManagerDeviceMenu.py` are not exactly human readable and kinda misleading as well. :(

E.g. `"Host is down", "br-connection-page-timeout"`? What's the "host"? Is it my laptop? Is it its Bluetooth adapter? Is it the device I'm trying to connect to?

Also, to me it makes sense to show a human readable code as well as a low level original code, so that it would be easier to track it down because it actually comes from https://github.com/bluez/bluez

So, it would be great if you showed something like:

Failed to connect
br-connection-page-timeout: Timeout initiating a connection with the remote device
br-connection-profile-unavailable: The remote device does not support the selected protocol

Maybe these messages should be reported to upstream instead considering your merge request, dunno.

**Comment by cschramm** [comment]
Not sure what you mean. Where do you get to see `Host is down`?

**Comment by birdie-github** [comment]
> Not sure what you mean. Where do you get to see `Host is down`?

https://github.com/cschramm/blueman/commit/f72c0cbbbdce1172fbf8b28df30ae677779b2d62

**Comment by cschramm** [comment]
That's the code where we catch the bluetoothd / libc error message. The message we show in the UI for it is `Device did not respond`.
