### ISSUE TITLE
NetworkManager PAN support doesn't work with new NetworkManager

### ISSUE THREAD

**Issue by gentoo-root** [blueman-project/blueman#181]
https://github.com/blueman-project/blueman/blob/master/blueman/plugins/applet/NMPANSupport.py#L201

/system/networking/connections key in gconf is deprecated and no longer supported. As for now, all connections reside in /etc/NetworkManager/system-connections directory. Connection files support ACLs to allow user-specific connections:

    [connection]
    permissions=user:max:;

But it is just details of NetworkManager implementation. Blueman should stop trying to write gconf keys to add new connections, but rather should add new connections via NetworkManager D-Bus interface (org.freedesktop.NetworkManager.Settings.AddConnection method at /org/freedesktop/NetworkManager/Settings).

**Comment by infirit** [comment]
This has become more urgent as set_list is missing in PyGI for me now. Found bug [6841433](https://bugzilla.gnome.org/show_bug.cgi?id=681433) which made me :cry:
