### ISSUE TITLE
Label Empty

### ISSUE THREAD

**Issue by mdhishamsayed** [blueman-project/blueman#1815]
blueman: 2.3.1-1
BlueZ: 5.64-2
Distribution: Arch Linux
Desktop environment: Cinnamon

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

When one left clicks it shows label empty after the latest update

![new](https://user-images.githubusercontent.com/95240865/183275609-5cec184d-974a-4fa9-b8fb-19450eaae8f8.png)

**Comment by cschramm** [comment]
#1791
