### ISSUE TITLE
Blueman wakes up xscreensaver

### ISSUE THREAD

**Issue by Carl393** [blueman-project/blueman#1816]
blueman: 2.3.1
Distribution: Debian 11 (bookworm)
Desktop environment: xfce 4.16

hello Folks

my bluetooth dongle for my mouse is waking up my xscreensaver randomly or asking me to logout randomly
when I unplug the bluetooth dongle it no longer happens

has anyone else had this issue before?

**Comment by cschramm** [comment]
I can find a lot references to xfce4-power-manager causing such things by simulating key presses. I would not expect the presence of a Bluetooth dongle to influence that, but who knows. :shrug:

I'd check if it happens without:
- the mouse
- xfce4-power-manager (`killall xfce4-power-manager`)
- blueman-applet (right-click, exit or `killall blueman-applet`)

Apart from any weird things going on, of course mouse input does wake the screensaver, so there might just be some events from the mouse even though you're sure it's not moving at all. Applications like `xev` or `xinput` make such events visible.
