### ISSUE TITLE
Bluetooth program not storing non-image files in selected directory

### ISSUE THREAD

**Issue by AnnePH** [blueman-project/blueman#1817]
blueman:
BlueZ:
Distribution:  Mint 21
Desktop environment: Cinnamon

Just  upgraded my Mint 20 to Mint 21 and found a problem with  non image files transferred  via bluetooth.

 1.  Image  files are stored in the selected directory
 2.  PDF, txt, mp4, xl files etc., never make it to the selected directory,
 3.  I found the missing files in this location...   /home/anne/.cache/obexd/"file name.ext"

**Comment by cschramm** [comment]
That is the temporary folder used during transfer, so it seems like the transfer does not complete successfully.

Please `killall blueman-applet`, then run `blueman-applet --loglevel debug` and provide the output of where you receive a file that does end up in the cache directory. Also provide `dconf read /org/blueman/transfer/shared-path`.
