### ISSUE TITLE
Unable to hear audio, music via web, native apps or other music apps even via music on harddrive keeps stuttering via bluetooth

### ISSUE THREAD

**Issue by jsarkari** [blueman-project/blueman#1820]
blueman: 
BlueZ: 
Distribution: Linux Mint 21
Desktop environment: Cinnamon 64-bit

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Using Sony WH-1000XM4 headphones connected via Bluetooth and playing voice audio, music via web apps or native apps etc there is constant stuttering or the music is playing faster than normal and dropping parts of the music so unable to listen. When plugged in via cable, then it isn't a problem. 
This only occurred since upgrading from 20.3 to 21.

**Comment by cschramm** [comment]
This is out of blueman's scope and sounds like an issue with pulseaudio. I personally cannot provide any help here, sorry.

**Comment by jsarkari01** [comment]
Please close as it was no longer an issue on the latest version.
