### ISSUE TITLE
When connecting bluetooth headphones the sound doesn't switch immediately to bluetooth headphones

### ISSUE THREAD

**Issue by jsarkari** [blueman-project/blueman#1821]
blueman:
BlueZ:
Distribution: Linux Mint 21
Desktop environment: Cinnamon

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

So when cpnnecting bluetooth headphones to LM 21 it doesn't then start playing the audio/music via headphones so you always have to open Sound settings and switch to the desired output. One would assume that if you are connecting headphones it would then switch to that automatically or at least have an option to do so if possible.

**Comment by infirit** [comment]
We have no control over which audio device is selected when a new device shows up. Blueman only takes care if the Bluetooth connection and then the pulseaudio or pipewire take over.

Both pulseaudio and pipewire have ways to control what device will get priority. Best is to ask on the mint forums how to configure this.

**Comment by birdie-github** [comment]
This how it works in recent versions of PipeWire. Not sure PulseAudio is capable of that.

**Comment by cschramm** [comment]
@birdie-github: Capable of what? Switching devices? It has `module-switch-on-connect` to switch the default device to a newly added one, yes.
