### ISSUE TITLE
optional feature: prevent downgrade of connections

### ISSUE THREAD

**Issue by fugbixer** [blueman-project/blueman#1822]
Block Bluetooth devices sending connection requests with a lower (potential vulnerable) 
Bluetooth version than the user has set as default (if feature is enabled).

Ensures upwards compatibility only, prevent downgrade of connections.

Please think about it, thank you very much!

**Comment by infirit** [comment]
This information isn't exposed by BlueZ over dbus to blueman. If the Folks at BlueZ think it's useful and expose this then we can think about this.

For now though it's best to raise this to the BlueZ folks http://www.bluez.org/.
