### ISSUE TITLE
keyboard logitech k380 - not pairing and not showing on search

### ISSUE THREAD

**Issue by hubrootgit** [blueman-project/blueman#1825]
blueman: 2.3.1
BlueZ: 5.64
Distribution: Linux Mint 21 Cinnamon
Desktop environment: Cinnamon 5.4.9

Kernel: 5.15.0-46-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
Desktop: Cinnamon 5.4.9 tk: GTK 3.24.33 wm: Mutter vt: 7 dm: LightDM 1.30.0
Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy

![Screenshot 2022-08-13 at 05-11-43 Captura de tela de 2022-08-13 05-07-33 png (PNG Image 2726 × 768 pixels)](https://user-images.githubusercontent.com/111175764/184477232-d6b77a4e-6b52-47a1-b178-e84c9c739995.png)

![Screenshot 2022-08-13 at 05-15-19 Captura de tela de 2022-08-13 05-14-44 png (PNG Image 2726 × 768 pixels)](https://user-images.githubusercontent.com/111175764/184477384-de10dd36-8b59-4e41-8d2c-7184d5c84fbe.png)

![Screenshot 2022-08-13 at 05-18-27 Captura de tela de 2022-08-13 05-17-51 png (PNG Image 2726 × 768 pixels)](https://user-images.githubusercontent.com/111175764/184477474-7374c3a6-7931-472c-b59b-7e69955ba447.png)

**Comment by infirit** [comment]
Most likely the bluetooth adapter is not working properly. This could be missing firmware, rfkill switch block or something in the linux kernel. Which bluetooth adapter is this (check `lsusb` or `lspci` )Do you see messages in `dmesg` that relate to missing firmware? Also check if the killswitch is blocking (check `rfkill`).

**Comment by hubrootgit** [comment]
![1](https://user-images.githubusercontent.com/111175764/184509238-72a5fed6-04b6-430f-ae5d-71cfdd2da04f.png)

![2](https://user-images.githubusercontent.com/111175764/184509306-c2d0fbc2-9c41-44d0-99ca-37db11232965.png)

![3](https://user-images.githubusercontent.com/111175764/184509391-af0a1ae4-6f48-43c0-902c-7741e08d2f3c.png)

https://user-images.githubusercontent.com/111175764/184509586-44c07d70-1d44-4d71-a23b-0617c8554bb9.mp4

**Comment by hubrootgit** [comment]
- I followed these steps and everything worked out:

![Bluetooth - ArchWiki](https://user-images.githubusercontent.com/111175764/184524259-2101bbb5-4fad-4115-b000-19c5a8856bea.png)

**Comment by bagusa4** [comment]
i have same issue on linux mint 21.3 "Virginia", not showing on search blueman. any suggestion ?

**Comment by cschramm** [comment]
> i have same issue on linux mint 21.3 "Virginia", not showing on search blueman

What are you referring to?

> any suggestion ?

You probably just need to unhide unnamed devices in blueman-manager's view menu.
