### ISSUE TITLE
Couldn't install blueman from source

### ISSUE THREAD

**Issue by erkin98** [blueman-project/blueman#1830]
blueman: 2.3.2
BlueZ: 5.64-0ubuntu1
Distribution: Ubuntu Wayland
Desktop environment: Gnome

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

```
checking for a Python interpreter with version >= 3.8... python
checking for python... /home/erkin/miniconda3/bin/python
checking for python version... 3.8
checking for python platform... linux
checking for GNU default python prefix... ${prefix}
checking for GNU default python exec_prefix... ${exec_prefix}
checking for python script directory (pythondir)... ${PYTHON_PREFIX}/lib/python3.8/site-packages
checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python3.8/site-packages
checking for python-3.8... no
configure: error: Package requirements (python-3.8) were not met:

No package 'python-3.8' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PYTHON_CFLAGS
and PYTHON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

```

**Comment by cschramm** [comment]
You do not seem to have a python package (in terms of pkg-config). Installing `python3-dev` gets the necessary metadata on the system (`libpython3-dev` should actually be sufficient).

You will not get a working installation with your system's Python distribution as it does not add the `site-packages` directory to its search paths. dh-python can handle paths for you if you build a proper deb package.
