### ISSUE TITLE
failed to apply network setting

### ISSUE THREAD

**Issue by Anas-jaf** [blueman-project/blueman#1831]
when i enable NAP i get this error on the startup 
![image](https://user-images.githubusercontent.com/63655663/185518590-d3980986-6b5b-413b-92ef-caa6377b1d32.png)

blueman: 2.3.1-1
BlueZ: 5.64-2+kali1
Distribution: kali linux raspberry pi 4
Desktop environment: xfce4

**Comment by cschramm** [comment]
Assuming 2.3.1-1 is the respective Debian package, it ships the following polkit rules: https://salsa.debian.org/debian/blueman/-/blob/debian/2.3.1-1/debian/blueman.rules

That means, you need to be in the `sudo` or `netdev` groups.

**Comment by Anas-jaf** [comment]
i added my user to `netdev` and `sudo` groups with `usermod -aG sudo kali`  and `usermod -aG netdev kali` and  `gpasswd -a kali netdev ` and still having the same issue 

I put my user in visudo 
![image](https://user-images.githubusercontent.com/63655663/185742233-09c9bcbc-519b-4d92-bdea-1bca46a9ecaf.png)

also I checked using id the groups 
![image](https://user-images.githubusercontent.com/63655663/185742246-a0dbb89a-e5b5-494e-a347-9ee42a7094e0.png)

thanks in advance

**Comment by cschramm** [comment]
Did you restart blueman-applet with the new groups? Maybe try if `pkcheck --action-id org.blueman.network.setup --process $(pgrep blueman-applet)` gives you anything useful.

**Comment by Anas-jaf** [comment]
i tried `pkcheck --action-id org.blueman.network.setup --process $(pgrep blueman-applet)` but it returnes with `not authorized`

**Comment by Anas-jaf** [comment]
i didn't find how to authorize blueman policy kit so I found this article that discript how to create pan with bluez-tools with the help of this article [article](https://thesmashy.medium.com/raspberry-pi-zero-w-wifi-hacking-gadget-63e3fa1c3c8d) until I find how to fix this issue I will use this method

**Comment by cschramm** [comment]
I would have expected a diagnostic message from `pkcheck`. Maybe try with `--allow-user-interaction`.

As I already mentioned if 2.3.1-1 is the respective Debian package, authorization rules are set up as https://salsa.debian.org/debian/blueman/-/blob/debian/2.3.1-1/debian/blueman.rules installed at `/usr/share/polkit-1/rules.d/blueman.rules`.

Just to make sure: This is not a long-running system and you did restart at some point?

**Comment by Anas-jaf** [comment]
i'm using raspberrypi kali linux which is based on debian
