### ISSUE TITLE
Blueman-applet menu gets corrupted

### ISSUE THREAD

**Issue by mfreeman72** [blueman-project/blueman#1834]
blueman: 2.3.1
BlueZ: 5.64-0ubuntu1
Distribution: Linux Mint 21
Desktop environment: Cinnamon 5.4.10

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I'm running Blueman 2.3.1, included with Linux Mint 21. When I select Turn Bluetooth Off and then later Turn Bluetooth On, or when I suspend my computer and then wake it up, the menu in the blueman panel changes the separator lines between menu sections into "Label Empty" text. I must kill and restart the applet to fix it.

Here is the log output: https://pastebin.com/giuEiWg3

Here's a screenshot of the problem:

![Screenshot from 2022-08-15 16-23-17](https://user-images.githubusercontent.com/7842664/185768986-0d53d088-6d20-4ed1-86bd-dce4aa3d1d9a.png)

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
#1815
