### ISSUE TITLE
Weird visual bug when connected to bluetooth audio device.

### ISSUE THREAD

**Issue by TomBayne** [blueman-project/blueman#1835]
blueman: blueman 2.3.1-1
BlueZ: bluez 5.65-2
Distribution: Arch Linux 
Desktop environment: XFCE

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

After connecting a device via blueman. The dropdown menu has a weird visual bug:
![image](https://user-images.githubusercontent.com/29130704/185789658-135a0368-5570-4d8c-85fb-6aec02964684.png)

**Comment by cschramm** [comment]
#1791
