### ISSUE TITLE
ELM 237 Serial Port

### ISSUE THREAD

**Issue by DIGIFAULT** [blueman-project/blueman#1839]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
We really don't need any info at all. At least do the minimal effort of providing what we ask in the template.

**Comment by DIGIFAULT** [comment]
DDT4ALL With python3 - Serial Port Error (unrecognized) on fake Chinese ELM 237 and Bluetooth USB ASUS BT500, not recognized. Toshiba, 64 bites, Linux Mint 20...
 ---------------------------------------------------------------
class SerialBase(io.RawIOBase):
    """\
    Serial port base class. Provides __init__ function and properties to
    get/set port settings.
---------------------------------------------------------------
