### ISSUE TITLE
icon help

### ISSUE THREAD

**Issue by PeterFHill** [blueman-project/blueman#1840]
![image](https://user-images.githubusercontent.com/112488110/187444767-910630f1-57fd-4dc5-b3a0-dc9fb4889573.png)
can someone tell me what the orange, green and blue symbol/icons are?
thanks

**Comment by cschramm** [comment]
They are called (in that order and as visible in the tooltip) _Received Signal Strength_, _Link Quality_ and _Transmit Power Level_ and often pointless standard values.

See #1620 regarding concepts to change the UI and e.g. #860 (and #1642) regarding issues with the values.
