### ISSUE TITLE
Gtk CRITICAL Error while trying to dockerise blueman

### ISSUE THREAD

**Issue by thesuhas** [blueman-project/blueman#1844]
blueman: 2.02
BlueZ: 5.53
Distribution: Ubuntu 20.04
Desktop environment: Ubuntu 20.04 in a Docker Container on Pop OS 22.04

Hi, 
I am trying to dockerise an older version of blueman for a personal project of mine.
I've installed all the required dependencies. When trying to run `blueman-manager` I am getting a Gtk-CRITICAL Error and I am unable to fix it.
Attaching a screenshot for your reference.

![Error](https://user-images.githubusercontent.com/54014218/188455980-2658f8bc-5ced-4954-bf8e-baa0851ed7ea.png)

**Comment by infirit** [comment]
Can you run it through gdb and get a backtrace. That should tell you where
it faults.

**Comment by cschramm** [comment]
GTK cannot connect to the display server. I guess the errors are more or less expected under some circumstances then.

With just `apt update; apt install blueman; /etc/init.d/dbus start; blueman-manager` I get

```
Traceback (most recent call last):
  File "/usr/bin/blueman-manager", line 44, in <module>
    manager = Blueman()
  File "/usr/lib/python3/dist-packages/blueman/main/Manager.py", line 29, in __init__
    super().__init__(title=_("Bluetooth Devices"))
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 515, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
```

Might be something else in older versions (I don't get what you mean with `2.02`).

**Comment by thesuhas** [comment]
@cschramm 
I meant the 2.02 release of blueman

**Comment by cschramm** [comment]
There is no such release. Possibly 2.0.2 or 2.2.

**Comment by thesuhas** [comment]
@cschramm 
My bad, I meant 2.0.2

**Comment by cschramm** [comment]
I can confirm that error in that ancient version. In 2.0 the first call to `Gtk.Builder.add_from_file` causes a crash when there's no connection to the display server.

Not sure about your expectations here. blueman-manager is not expected to work without a display server.
