### ISSUE TITLE
System tray menu looks wrong

### ISSUE THREAD

**Issue by resiehnnes** [blueman-project/blueman#1845]
blueman: 2.3.2
BlueZ: 5.65
Distribution: Fedora 36
Desktop environment: Gnome 42.4, X11

System tray menu looks kinda messy when I turn the bluetooth on. When it's off it looks alright.

Bluetooth OFF:

![Screenshot from 2022-09-06 13-53-14](https://user-images.githubusercontent.com/52158526/188630083-f4aa7625-c156-47e3-8295-a4774b0e7a0b.png)

Bluetooth ON:

![Screenshot from 2022-09-06 13-53-30](https://user-images.githubusercontent.com/52158526/188630078-71170850-085c-4b66-935d-097b635c0116.png)

**Comment by cschramm** [comment]
What's rendering those? To my knowledge Gnome itself does not have the concept of tray icons anymore. :raised_eyebrow:

**Comment by resiehnnes** [comment]
I am using [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel) + [KStatusNotifierItem](https://github.com/ubuntu/gnome-shell-extension-appindicator) First extension gives a 'Windows' like panel, where's the other one is for tray icons.

**Comment by cschramm** [comment]
Ok, sounds like we're having a compatibility issue with [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator)
Public then. I'll try to have a look. Can you confirm that blueman 2.2 works fine with it?

**Comment by resiehnnes** [comment]
Yep, looking good with 2.2.3

**Comment by infirit** [comment]
I can't reproduce this on my fedora 36 vm

**Comment by cschramm** [comment]
Weird, I can, without doing anything fancy. :confused:

Looks like that thing has a fundamental flaw at least when changing items between separators and standard ones. Providing it with unique identifiers solves the problem for me. -> #1847

**Comment by kuraga** [comment]
blueman 2.3.2, XFCE 4.16

![image](https://user-images.githubusercontent.com/1063219/189484742-12553e31-35cd-41e3-9be6-f219ad27d6d6.png)

(sometimes without `Label Empty`)
