### ISSUE TITLE
Cannot open preferences dialogue

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#185]
bluez-101, blueman git as of 2015/02/18

When I try to open the preferences dialogue blueman complains that bluetooth is not switched on and does not open a dialogue window - since blueman scans and finds devices, bluetooth is working.

get_interface_version (/usr/local/lib/python2.7/site-packages/blueman/bluez/BlueZInterface.py:8)
Detected BlueZ 4 
_________
SetAdapter (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:264)
None 
_________
on_adapter_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerToolbar.py:75)
toolbar adapter /org/bluez/7605/hci0 
blueman-adapters version 1.99.alpha1 starting
ERROR:dbus.proxies:Introspect error on org.blueman.Applet:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/local/bin/blueman-applet exited with status 1
Traceback (most recent call last):
  File "/usr/local/bin/blueman-adapters", line 232, in <module>
    BluemanAdapters(adapter_name)
  File "/usr/local/bin/blueman-adapters", line 44, in __init__
    check_bluetooth_status(_("Bluetooth needs to be turned on for the adapter manager to work"), lambda: exit())
  File "/usr/local/lib/python2.7/site-packages/blueman/Functions.py", line 81, in check_bluetooth_status
    if "PowerManager" in applet.QueryPlugins():
  File "/usr/local/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/local/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/local/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/local/bin/blueman-applet exited with status 1
_________
child_closed (/usr/local/lib/python2.7/site-packages/blueman/Functions.py:153)
['/usr/local/bin/blueman-adapters', 'hci0'] closed

**Comment by cschramm** [comment]
This is the result of blueman-applet crashing, sames as #184.
