### ISSUE TITLE
Missed file in 2.3.2 asset

### ISSUE THREAD

**Issue by kuraga** [blueman-project/blueman#1850]
[blueman-2.3.2.tar.xz](https://github.com/blueman-project/blueman/releases/download/2.3.2/blueman-2.3.2.tar.xz) asset (and, maybe, others) doesn't contain [`blueman/plugins/applet/PulseAudioProfile.py`](https://github.com/blueman-project/blueman/blob/2.3.2/blueman/plugins/applet/PulseAudioProfile.py) file (and, maybe, others).

**Comment by infirit** [comment]
Because it's in plugins/manager

**Comment by kuraga** [comment]
@infirit is it another?

**Comment by kuraga** [comment]
Ok but such plugin is missed in Gentoo package's UI.
And file is missed, too.
Coincidence?

**Comment by infirit** [comment]
You will need to enable the pulseaudio use flag for it to be installed https://packages.gentoo.org/packages/net-wireless/blueman

**Comment by infirit** [comment]
The applet plugin was removed in 62548f74262a9125afca75a88b579516190d8ceb but even that never used `plugins/applet/PulseAudioProfile.py` :thinking: . @cschramm do you have any idea why we have this file there ?

@kuraga we only have the manager plugin now. Enable the use flag and it will be in the device right click menu.

**Comment by cschramm** [comment]
Yeah, well, looks like that was missed in #1617. :grimacing:

**Comment by infirit** [comment]
I see the items being made but the submenu is empty. I'm really not familiar enough with the whole statusnotifier to comment on why. Below diff adds the relevant bits to automake and meson.

```diff
diff --git a/blueman/plugins/applet/Makefile.am b/blueman/plugins/applet/Makefile.am
index 6f174c85..833c4808 100644
--- a/blueman/plugins/applet/Makefile.am
+++ b/blueman/plugins/applet/Makefile.am
@@ -27,6 +27,9 @@ blueman_PYTHON = \
     StatusNotifierItem.py \
     TransferService.py
 
+if HAVE_PULSEAUDIO
+blueman_PYTHON += PulseAudioProfile.py
+endif
 
 CLEANFILES =           \
        $(BUILT_SOURCES)
diff --git a/meson.build b/meson.build
index a552180d..d7679a3d 100644
--- a/meson.build
+++ b/meson.build
@@ -332,6 +332,7 @@ blueman_exclude_files = ['Constants.py.in'] + blueman_makefiles
 pulseaudio = get_option('pulseaudio')
 if not pulseaudio
     blueman_exclude_files += 'plugins/manager/PulseAudioProfile.py'
+    blueman_exclude_files += 'plugins/applet/PulseAudioProfile.py'
 endif
 
 install_subdir(
```

```
_generate_profiles_menu: [{'text': 'Uit', 'markup': True, 'icon_name': 'bluetooth-symbolic', 'sensitive': True, 'callback': <function AudioProfiles.add_device_profile_menu.<locals>._activate_profile_wrapper.<locals>._wrapper at 0x7f744d35cca0>, 'tooltip': ''}, {'text': 'High Fidelity Playback (A2DP Sink)', 'markup': True, 'icon_name': 'bluetooth-symbolic', 'sensitive': True, 'callback': <function AudioProfiles.add_device_profile_menu.<locals>._activate_profile_wrapper.<locals>._wrapper at 0x7f744d35ce50>, 'tooltip': ''}, {'text': 'Headset Head Unit (HSP/HFP)', 'markup': True, 'icon_name': 'bluetooth-symbolic', 'sensitive': True, 'callback': <function AudioProfiles.add_device_profile_menu.<locals>._activate_profile_wrapper.<locals>._wrapper at 0x7f744d35cee0>, 'tooltip': ''}, {'text': 'High Fidelity Playback (A2DP Sink, codec SBC)', 'markup': True, 'icon_name': 'bluetooth-symbolic', 'sensitive': True, 'callback': <function AudioProfiles.add_device_profile_menu.<locals>._activate_profile_wrapper.<locals>._wrapper at 0x7f744d35cdc0>, 'tooltip': ''}, {'text': '<b>High Fidelity Playback (A2DP Sink, codec SBC-XQ)</b>', 'markup': True, 'icon_name': 'bluetooth-symbolic', 'sensitive': True, 'callback': <function AudioProfiles.add_device_profile_menu.<locals>._activate_profile_wrapper.<locals>._wrapper at 0x7f744d35d000>, 'tooltip': ''}, {'text': 'High Fidelity Playback (A2DP Sink, codec aptX)', 'markup': True, 'icon_name': 'bluetooth-symbolic', 'sensitive': True, 'callback': <function AudioProfiles.add_device_profile_menu.<locals>._activate_profile_wrapper.<locals>._wrapper at 0x7f744d35da20>, 'tooltip': ''}, {'text': 'Headset Head Unit (HSP/HFP, codec CVSD)', 'markup': True, 'icon_name': 'bluetooth-symbolic', 'sensitive': True, 'callback': <function AudioProfiles.add_device_profile_menu.<locals>._activate_profile_wrapper.<locals>._wrapper at 0x7f744d35dab0>, 'tooltip': ''}, {'text': 'Headset Head Unit (HSP/HFP, codec mSBC)', 'markup': True, 'icon_name': 'bluetooth-symbolic', 'sensitive': True, 'callback': <function AudioProfiles.add_device_profile_menu.<locals>._activate_profile_wrapper.<locals>._wrapper at 0x7f744d35db40>, 'tooltip': ''}]
```

**Comment by cschramm** [comment]
:thinking: They show up on my side and the items do not differ from the pre-#1799 recent connections submenu.

**Comment by infirit** [comment]
I'll check xfce as it's not looking good in plasma.

**Comment by infirit** [comment]
It's fine on XFCE but broken under plasma. I'll see if I can find a commit where it worked. 
![image](https://user-images.githubusercontent.com/3465730/190222155-7af50bb2-8b83-4a04-afbb-b19045c8e35e.png)

**Comment by infirit** [comment]
It's all submenu's that are broken, recentconns is also broken on plasma.

**Comment by infirit** [comment]
The moment `AppIndicator` 5ff2a8f2d38ed00aac37f354c5a7a6bcd705e77e is removed and `StatusNotifier` is now generating the menu it breaks.

I never noticed as I don't use RecentConns.

**Comment by cschramm** [comment]
They will be part of a 2.4 release and possibly 2.3.3.

**Comment by kuraga** [comment]
@cschramm , I asked exactly about GitHub assets (`.tar.gz`, `.tar.xz`). Because I don't know how are they constructed and don't see if files are added to them in #1855. Thanks.

**Comment by cschramm** [comment]
Not sure what you mean with GitHub assets (if not the release tarballs) and whether you're asking for additional information.

**Comment by kuraga** [comment]
I mean: [`blueman/plugins/applet/PulseAudioProfile.py`](https://github.com/blueman-project/blueman/blob/2.3.2/blueman/plugins/applet/PulseAudioProfile.py) has to exist not only after `make && make install` but also in [release tarrballs (`.tar.gz`, `.tar.xz`)](https://github.com/blueman-project/blueman/releases/tag/2.3.2).

For now, it doesn't exist in tarballs. And I don't know if #1855 fixes this.

**Comment by cschramm** [comment]
It will get added neither to the archives nor the build configurations of 2.3.2 retroactively.

**Comment by kuraga** [comment]
> It will get added neither to the archives nor the build configurations of 2.3.2 retroactively.

Talked about next release, of course.

Understand. Thanks.
