### ISSUE TITLE
Submenus do not work in KDE Plasma

### ISSUE THREAD

**Issue by cschramm** [blueman-project/blueman#1856]
It's all submenu's that are broken, recentconns is also broken on plasma.

_Originally posted by @infirit in https://github.com/blueman-project/blueman/issues/1850#issuecomment-1247088923_

**Comment by kuraga** [comment]
#1815, #1834, #1845, #1847, #1791, #1803 ?

**Comment by cschramm** [comment]
There's a fix in #1859.

@infirit: I'm surprised that you do not have any issues with KDE. While replicating and testing this, I've seen #1845 there (not #1791 as #1803 does not fix it). I've used a Manjaro 21.3.7 live system (Plasma 5.24.6).

**Comment by infirit** [comment]
I really don't. Maybe it is a problem but I just don't see it. 

```
Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.8-xanmod1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: AMD Radeon RX 590 Series
```

**Comment by cschramm** [comment]
Hrm. :thinking: I just run manjaro-kde-21.3.7-220816-linux515.iso in QEMU with a forwarded USB Bluetooth adapter, then `sudo pacman -Sy blueman && blueman-applet`, turn Bluetooth off (it's on by default) and end up with this:

![Bildschirmfoto zu 2022-09-20 08-46-09](https://user-images.githubusercontent.com/464848/191186922-32f2f1ef-5632-4dd1-a0d1-3e616e0349f3.png)

Plasma 5.24.6, Frameworks 5.96.0, Qt 5.15.5. A full system update (Plasma 5.25.5, Frameworks 5.97.0) changes the look a little bit but not the glitch.

Anyway, #1847 fixes it, so we're fine but that fix is of higher importance than expected. Might be worth a 2.3.3.
