### ISSUE TITLE
Cannot open setup dialogue

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#186]
bluez-101, blueman git as of 2015/02/18

After scanning and finding a bluetooth device, right-clicking on the device brings up a menu box. If I choose "setup..." from this menu box (or the title bar) nothing happens

on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:148)
adapter propery changed Discovering 1 
_________
on_device_found (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:128)
Device discovered 48:5A:B6:3F:CE:FE 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
add_device (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:310)
adding new device 
_________
do_cache (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:489)
Caching new device 48:5A:B6:3F:CE:FE 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Fake True 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Trusted 0 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Paired 0 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event RSSI -81 
('opacity', 147)
('RSSI:', dbus.Int16(-81, variant_level=1))
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:148)
adapter propery changed Discovering 0 
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:148)
adapter propery changed Discovering 1 
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:148)
adapter propery changed Discovering 0 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
ERROR:dbus.proxies:Introspect error on org.blueman.Applet:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/local/bin/blueman-applet exited with status 1
ERROR:dbus.proxies:Introspect error on org.blueman.Applet:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/local/bin/blueman-applet exited with status 1
Loading configuration plugins
_________
<module> (/usr/local/lib/python2.7/site-packages/blueman/main/Config.py:1)
Skipping plugin Gconf
cannot import name GConf 
Using file config backend
Traceback (most recent call last):
  File "/usr/local/bin/blueman-assistant", line 28, in <module>
    from blueman.main.applet.BluezAgent import TempAgent
  File "/usr/local/lib/python2.7/site-packages/blueman/main/applet/BluezAgent.py", line 13, in <module>
    from blueman.gui.Notification import Notification
  File "/usr/local/lib/python2.7/site-packages/blueman/gui/Notification.py", line 1, in <module>
    from gi.repository import Notify
ImportError: cannot import name Notify
_________
save (/usr/local/lib/python2.7/site-packages/blueman/plugins/config/File.py:105)
Saving config 
Exception TypeError: 'isinstance() arg 2 must be a class, type, or tuple of classes and types' in <bound method File.__del__ of <File object at 0xb5e17acc (blueman+plugins+config+File+File at 0x88b5d70)>> ignored
_________
child_closed (/usr/local/lib/python2.7/site-packages/blueman/Functions.py:153)
['/usr/local/bin/blueman-assistant', u'--device=48:5A:B6:3F:CE:FE'] closed

**Comment by cschramm** [comment]
This is the result of blueman-applet crashing, sames as #184.
