### ISSUE TITLE
Scripts contain hardcoded path to python

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#187]
The blueman python scripts installed to bin and libexec are hardcoded to /usr/bin/python.

Suggest that either /usr/bin/env python or the actual location of python is used - /usr/local/bin/python in my case

**Comment by cschramm** [comment]
I think changing to /usr/bin/env is reasonable, yes.

**Comment by rworkman** [comment]
As expected, this tests out fine locally. Perhaps make it use python2 so long as blueman is not fully python3 ready (or is it now?) though...

**Comment by juanitotc** [comment]
It'd be good to have the choice of using python2 or python3

**Comment by rworkman** [comment]
It looks pretty trivial to rename the relevant scripts to .in files and use autotools magic to sub in "python2" or "python3" -- but assuming the code does (or will before 2.0) work fine in either 2 or 3, then leaving it as is (/usr/bin/env python) would be my preference, as then the system default is what will be used.

**Comment by cschramm** [comment]
Python 3 is not ready yet, but close. We need to get rid of the unicode type and fix some str vs. bytes issues in the cython functions, see https://github.com/blueman-project/blueman/issues/19#issuecomment-73652652.
