### ISSUE TITLE
Blueman Manager 2.3.2

### ISSUE THREAD

**Issue by felixecited** [blueman-project/blueman#1873]
blueman: 2.3.2
BlueZ:
Distribution: Linux Mint 21
Desktop environment: Cinamon

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I have M720 triathlon 3 device mouse and K380 3 device keyboard. I use both to connect to linux mint 21 ct201 and samsung galaxy s10. i can switch between devices and back without issue except when returning to linux mint the keyboard has dropped every time, without exception. sometimes reconecting using bt manager search cannot find the keyboard. sometimes restarting the search finds it most times it does not. logging off does not help, only a reboot seems to allow it to be found. both other devices the tablet and phone have no issue moving back and forth between devices only returning to mint k380 has a problem.

->  https://pastebin.com/myCJj4n9

**Comment by infirit** [comment]
It looks like the kernel driver for the RTL8821CE bluetooth adapter is crashing. Which is likely the reason it doesn't want to reconnect.. Does it still happen if you use `bluetoothctl connect <bluetoothaddress>`?

**Comment by yuquanguo** [comment]
I have the same problem, I have K480 3 device keyboard. It outputs an error "Failed to connect: org.bluez.Error.Failed br-connection-create-socket" if i use "bluetoothctl connect <bluetoothaddress>"

**Comment by cschramm** [comment]
@yuquanguo: Are you saying that you're on rtl8821ce and see it crashing as well or that you see the same behavior without such a driver crash? You can check the bluetoothd logs, enabling debug logging, to get behind where the error is happening.

**Comment by felixecited** [comment]
I just received an Blueman update to 2.3.3 k380 still disconnects when switching to phone or tablet then back. M720 mouse has no problem its always connected across all devices

**Comment by felixecited** [comment]
what driver is crashing? i am not providing drivers. all drivers are included in linux mint. if some driver is crashing it needs updating and my system if fully updated

**Comment by infirit** [comment]
> what driver is crashing? i am not providing drivers. all drivers are included in linux mint. if some driver is crashing it needs updating and my system if fully updated

Never said you provided the driver, just that it was crashing. Bugs can be present even if you have a fully updated install.

Regardless, crashing drivers is not something we can fix. Blueman is just the frontend to the underlying Bluetooth stack. Perhaps posting the kernel log on the mint forums helps with solving the problem.
