### ISSUE TITLE
Feature request: Default profile on connection

### ISSUE THREAD

**Issue by Thalley** [blueman-project/blueman#1875]
blueman: 2.3.2
BlueZ: 5.6.5
Distribution: Arch
Desktop environment: XFCE

It would be a nice feature if it was possible to choose which profile a connected device (e.g. a headset) will default to. For now it seems that if a headset supports both A2DP and HFP, A2DP will always be the default profile, but for someone that uses the headset mostly for communication, it would be nice if it was possible to set the default profile to e.g. HFP.

**Comment by infirit** [comment]
This is outside of the scope of blueman and up to the underlying soundserver like pulseaudio. In pulse you can set a default profile in the pulseaudio user config with `set-card-profile <symbolic-name> <profilename>`. see https://wiki.archlinux.org/title/PulseAudio/Examples#Set_the_default_output_sink_profile

**Comment by Thalley** [comment]
That's not a bad point, and is a solution that works for me. 

However since this is a Bluetooth specific request, as well as Blueman serving as a GUI for many users, it still seems to me that this would be a nice feature to do via Blueman, instead of modifying the `pulse` config.

**Comment by infirit** [comment]
AFAIK there is no real solution other than (re)writing config files. Personally I am not in favour of doing that.

**Comment by Thalley** [comment]
> AFAIK there is no real solution other than (re)writing config files. Personally I am not in favour of doing that.

If it is possible to change the profile via the Blueman GUI, why wouldn't it be possible to store the available profiles for a device, and select one of them as the default?

**Comment by cschramm** [comment]
I second what @infirit said. We're supporting to switch profiles in pulseaudio via its API as well as in other sound servers that provide a compatible API (PipeWire). Setting a default profile is not possible via an API and we'd have to mess around with your default.pa configuration file. Beside it being not nice, ugly, and error-prone, that's also not compatible to other sound servers even if they do provide a compatible API for switching.

**Comment by Thalley** [comment]
Alright, point taken. I'll resort to the pulseaudio configuration then - Thanks

**Comment by Thalley** [comment]
> This is outside of the scope of blueman and up to the underlying soundserver like pulseaudio. In pulse you can set a default profile in the pulseaudio user config with `set-card-profile <symbolic-name> <profilename>`. see https://wiki.archlinux.org/title/PulseAudio/Examples#Set_the_default_output_sink_profile

This solution doesn't seem to work my my device for some reason. 

I've added
```
set-card-profile bluez_card.4C_87_5D_2A_59_EC handsfree_head_unit
```

to my `/etc/pulse/default.pa`, and I have verified that doing `pactl set-card-profile bluez_card.4C_87_5D_2A_59_EC handsfree_head_unit` correctly changes the profile. 

@infirit Do you by any chance know why this wouldn't work, or how to debug it?

**Comment by infirit** [comment]
Does `pactl set-card-profile bluez_card.4C_87_5D_2A_59_EC handsfree_head_unit` works?

**Comment by Thalley** [comment]
> Does `pactl set-card-profile bluez_card.4C_87_5D_2A_59_EC handsfree_head_unit` work?

It does yes, and also correctly works with switching to e.g. `a2dp_sink` and back again. It is simply that the profile is not set on connection by following the suggested solution. 

I have no tried using an index, rather than the name.

**Comment by cschramm** [comment]
I think that actually does not work as the `default.pa` is "run" once and can only affect devices that are already available at that point and a Bluetooth device most probably isn't connected just yet (or maybe it is if, but still, if you switch it on later, the configuration will not take effect for it). I found a current, lengthy blog post about this here: https://ansonvandoren.com/posts/pulseaudio-auto-bluetooth-hfp-profile/ It includes a solution but that's definitely much less user-friendly than editing the default.pa and puts this feature request into a whole new perspective.

**Comment by Thalley** [comment]
> I think that actually does not work as the `default.pa` is "run" once and can only affect devices that are already available at that point and a Bluetooth device most probably isn't connected just yet (or maybe it is if, but still, if you switch it on later, the configuration will not take effect for it). I found a current, lengthy blog post about this here: https://ansonvandoren.com/posts/pulseaudio-auto-bluetooth-hfp-profile/ It includes a solution but that's definitely much less user-friendly than editing the default.pa and puts this feature request into a whole new perspective.

Thanks, and I agree. 

The odd part is that it probably would be quite easy to solve in Bluez or PulseAudio, if we could control the priority:
```
	Profiles:
		a2dp_sink: High Fidelity Playback (A2DP Sink) (sinks: 1, sources: 0, priority: 40, available: yes)
		handsfree_head_unit: Handsfree Head Unit (HFP) (sinks: 1, sources: 1, priority: 30, available: yes)
```
Since `a2dp_sink` has priority 40, it will always be selected instead of `handsfree_head_unit` which has priority of 30.

**Comment by cschramm** [comment]
Those priorities are hard-coded in pulseaudio.

Digging deeper, it looks like pulseaudio does have non-default support for auto-switching, though, by setting `module-bluetooth-policy`'s `auto_switch` argument to `2`.

**Comment by Thalley** [comment]
> Those priorities are hard-coded in pulseaudio.
> 
> Digging deeper, it looks like pulseaudio does have non-default support for auto-switching, though, by setting `module-bluetooth-policy`'s `auto_switch` argument to `2`.

Yes, I've actually disable the auto switching (setting it to `0`), because the main use of my BT headset is for Teams ("native" client), and Teams does not support modifying audio sources/sinks, so if I switch from e.g. HFP to A2DP then I need to restart teams. Teams default behavior is to switch between A2DP and HFP whenever joining a call (which it oddly enough does not actually support doing...). 

Teams is actually the reason why I want to force my headset to always use the HFP when connected.

**Comment by cschramm** [comment]
I see. Tricky case. I'd be curious about some pulseaudio discussion on this. Did not find anything, surprisingly.

Obviously Teams' audio is broken (it does not seem like auto_switch causes it to lose audio in general, though, but see e.g. https://learn.microsoft.com/en-us/answers/questions/191013/is-there-a-fix-coming-for-how-teams-handles-audio.html for much more fun) but it seems to affect other applications like steam games as well. The immediate solution to disable auto-switching makes pulseaudio use A2DP.

Still not sure how general the issue is and I'd be interested in how PipeWire's `bluez-autoswitch` pendant plays with Teams.

**Comment by infirit** [comment]
>I see. Tricky case. I'd be curious about some pulseaudio discussion on this. Did not find anything, surprisingly.

The core of the issue afaics is the lack of hfp/hsp support in pulse. The only proper implementation right now is ofono. There is https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/693

**Comment by Thalley** [comment]
> Still not sure how general the issue is and I'd be interested in how PipeWire's bluez-autoswitch pendant plays with Teams.

I understand that. The issue I am having is probably not that that general, as it involves a BT headset that supports both HFP and A2DP, and the native Linux Teams client. 

However, being able to set a specific profile as default with Pulseaudio seems to be quite general (simply based on the significant amount of workarounds suggested), and is something that could be done in blueman. 

> > I see. Tricky case. I'd be curious about some pulseaudio discussion on this. Did not find anything, surprisingly.
> 
> The core of the issue afaics is the lack of hfp/hsp support in pulse. The only proper implementation right now is ofono. There is https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/693

Maybe they'll managed to get that merged just before the next generation Bluetooth Low Energy Audio is getting to the market with a plethora of new profiles to support :) 

HFP is working quite fine in terms of just supporting bidirectional audio data, but probably not all the other functional stuff that HFP can do. For my usecase, just supporting audio data is good enough. 

I've also raised an issue towards Teams on Linux a long time ago, but since they switched to Teams V2 now, I doubt that they will spend any time on it.

**Comment by cschramm** [comment]
> being able to set a specific profile as default with Pulseaudio seems to be quite general

I disagree. `module-bluetooth-policy` with `auto_switch` > 0 makes it unnecessary and is default configuration. I did not find a single discussion about setting a default profile in pulseaudio and that's probably due to that.

Obviously you do have a need again when you cannot use `auto_switch` as it breaks your applications but still I found no discussion about such a case.

In any case, the right place to handle this would be pulseaudio to me. I'm not against implementing a udev-rule-like auto-switching on connect in blueman, though.

We could also think about something more generic (less user friendly (1)) like the user scripts that our `SerialManager` plugin supports. Not sure if there might be other use cases matching "do something when an (audio) device connects".

(1) Well, the user managed to find his problem and edit his `default.pa` to disable auto-switching, so I'd expect him to be capable of setting a script path and writing a pactl command.

**Comment by Thalley** [comment]
> In any case, the right place to handle this would be pulseaudio to me. I'm not against implementing a udev-rule-like auto-switching on connect in blueman, though.

I agree, this should ideally be solved in pulseaudio. Perhaps I'll go and create a feature request there instead :) 

> (1) Well, the user managed to find his problem and edit his `default.pa` to disable auto-switching, so I'd expect him to be capable of setting a script path and writing a pactl command.

I haven't yet found a solution that works with setting the profile on connection, but presumably I can probably find a solution at some point. 

In any case, thanks for your time @cschramm and @infirit

**Comment by cschramm** [comment]
> I haven't yet found a solution that works with setting the profile on connection

Not sure if I'm missing something, but it should be pretty straightforward with udev, e.g. a PipeWire user presents his solution at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/640#note_986747. (This was before PipeWire got auto-switching as well, which probably solves his case out-of-the-box nowadays (unless he uses Teams and has the same issue with it and PipeWire's auto-switching as you do with pulseaudio's, so that he has to disable it :laughing:)).

> Perhaps I'll go and create a feature request there instead :)

I'd be super curious to follow that. Please link if you do.

**Comment by Thalley** [comment]
> > I haven't yet found a solution that works with setting the profile on connection
> 
> Not sure if I'm missing something, but it should be pretty straightforward with udev, e.g. a PipeWire user presents his solution at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/640#note_986747. (This was before PipeWire got auto-switching as well, which probably solves his case out-of-the-box nowadays (unless he uses Teams and has the same issue with it and PipeWire's auto-switching as you do with pulseaudio's, so that he has to disable it laughing)).
> 
> > Perhaps I'll go and create a feature request there instead :)
> 
> I'd be super curious to follow that. Please link if you do.

I haven't created an issue yet. While going through their open issues, I noticed https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/975 which I am currently trying out now. At least it seems to work when I connect/disconnect my headset right now, but will need to check tomorrow after a reboot. It isn't exactly what I wanted, but I think that, if it works, it will do the trick for me :)

**Comment by kuraga** [comment]
Stop! Are we talking about default Bluetooth profile or about default input/output device.

The latter is very wishful but it's out of scope.

But the first is, isn't it?

> A2DP will always be the default profile

It's false, at least with _Recent Connections_ plugin. The last profile will be "default".

**Comment by Thalley** [comment]
> Stop! Are we talking about default Bluetooth profile or about default input/output device?
> 
> The latter is very wishful but it's out of scope.
> 
> But the first is, isn't it?
> 
> > A2DP will always be the default profile
> 
> It's false, at least with _Recent Connections_ plugin. The last profile will be "default".

I am only talking about Bluetooth profiles :) 

I have no tried the `Recent Connections` plugin, but I assume it works the same as 
```
load-module module-card-restore restore_bluetooth_profile=true
``` 
does (which I am currently using)

**Comment by cschramm** [comment]
`Recent Connections` does not do anything special. It just lists the - well - recent connections. Using them is no difference to the respective entries in the device's menu. The active profile is completely up to the sound server that establishes the connection with the audio service.

**Comment by kuraga** [comment]
Hm. But (I see) it uses the most recent profile being used not "A2DP by default".

**Comment by cschramm** [comment]
Connecting in `blueman-manager` should do exactly the same then. pulseaudio persisted card profiles before 13.0 by default and `argument to module-card-restore` did get a non-default `restore_bluetooth_profile=true` option to re-enable it. See https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/13.0/. (You might be using a different sound server than pulseaudio, of course.)
