### ISSUE TITLE
My desktop icon is suddenly In Italian.  I don't even have an Italian keyboard.

### ISSUE THREAD

**Issue by ernie-cordell** [blueman-project/blueman#1879]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by ernie-cordell** [comment]
I don't understand this status: Is that like "Act of God?"

**Comment by cschramm** [comment]
Feel free to re-open with the basic information we ask for.
