### ISSUE TITLE
Messages Not Cleared

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#188]
I tried using bluez-5.24 instead of bluez-4.101 with blueman

As I had not realised that the bluetooth adapter has to be enabled in Adapter/Preferences/Enable with bluez-5.x, I tried to scan for devices and got the message "Resource Not Ready..." and the notification pop-up below.

Not a big deal, but the message "Resource Not Ready..." is not cleared from the notification area, even when the adapter is enabled and has scanned successfully.

----------

Resource Not Ready...
Traceback (most recent last call)
File "/usr/local/bin/blueman-manager" line 228 in inquiry
self.List.DiscoverDevices()
File "/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py", line 394, in DiscoverDevices
self.Adapter.start_discovery()
File "/usr/local/lib/python2.7/site-packages/blueman/bluez/errors.py", line 143, in warp
raise parse_dbus_error(exception)
DBusNotReadyError: Resource Not Ready

**Comment by cschramm** [comment]
The notification area can be cleared manually and will be overwritten by subsequent messages, but won't disappear by itself. We could add a timeout, but why hide messages the user may not have seen yet?
