### ISSUE TITLE
Unable to connect with paired devices

### ISSUE THREAD

**Issue by viveksreedharan88** [blueman-project/blueman#1886]
Hi, every time i attempt to connect with a paired device, i get an error stating "le-connection-abort by local". Everytime i have to remove it and pair it again. Please help!

blueman: 2.3.2
BlueZ:
Distribution: Linux Mint 21
Desktop environment: Cinnamon

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
In #1623 the conclusion was an issue with the controller.

You can find the hardware ID with `lsusb` (or `lspci`). Running bluetoothd with debug logging enabled could also give more insights, but probably checking the Internets (e.g. Arch wiki) for the controller will be the shortcut.
