### ISSUE TITLE
Unable to connect Audio devices

### ISSUE THREAD

**Issue by swapnilman** [blueman-project/blueman#1894]
blueman: 2.3.3+mint1+vanessa
BlueZ: 5.64-0ubuntu1
Distribution: Linux Mint 21 Cinnamon
Desktop environment: Cinnamon 5.4.12

* [✅] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

When I try to connect to a paired headset device the connection fails. My am able to connect my Bluetooth keyboard and mouse, but non of my headset devices (Galaxy Buds 2 and Bluedio Headphones) are able to connect anymore. The problem appeared after updating blueman to 2.3.3.
**Full error message:** https://pastebin.com/fK8BxEFu

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
#1887
