### ISSUE TITLE
Blueman is not listing my bluetooth keyboard

### ISSUE THREAD

**Issue by viveksreedharan88** [blueman-project/blueman#1898]
Blueman is unable to list my bluetooth keyboard. Device is not showing up in the list. Please advise. 

blueman:
BlueZ:
Distribution: Linux Mint
Desktop environment:Cinnamon

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.
![Screenshot from 2022-10-16 19-17-08](https://user-images.githubusercontent.com/76948666/196038952-a81cbd64-c53a-45da-a4bc-d1c83b2b3810.png)

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by viveksreedharan88** [comment]
May I know what info is needed?

**Comment by cschramm** [comment]
The blueman version would be a great start.

Do you see the device from another system?

Did you try disabling `Hide unnamed devices` in the `View` menu?

**Comment by viveksreedharan88** [comment]
Blueman 2.3.4.  have unchecked the Hide unchecked devices in view menu. Afer the recent update, the keyboard is connecting and is working.Apologies for the delay in updating this!

**Comment by infirit** [comment]
> Blueman 2.3.4. have unchecked the Hide unchecked devices in view menu. Afer the recent update, the keyboard is connecting and is working.Apologies for the delay in updating this!

@viveksreedharan88 Would you mind telling me which keyboard this was. It seems more people are having difficulty with hiding these by default.

**Comment by viveksreedharan88** [comment]
No problem. Its Logitech K480 Wireless Multi-Device Keyboard.
