### ISSUE TITLE
Unable to connect to bluetooth speaker, stack trace in UI

### ISSUE THREAD

**Issue by kvelakur** [blueman-project/blueman#1899]
blueman: 2.3.3+mint1+vanessa
BlueZ: 5.64-0ubuntu1
Distribution: Linux Mint 21
Desktop environment: Cinnamon 5.4.12

I am unable to connect to pair or connect to my bluetooth speaker. I see a stack trace in UI. 

![image](https://user-images.githubusercontent.com/1902234/196054223-95e6b968-e07a-4e9e-9c17-c1716ff5ed9a.png)

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
#1887
