### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by cschramm** [blueman-project/blueman#19]
Currently the code should be compatible with ~~2.6 and~~ 2.7.

Goal is to also make it compatible with ~~3.2+~~ 3.3+

**Comment by cschramm** [comment]
Fixed some easy issues. The most obvious items left are:

* module __builtin__
* module cPickle
* module StringIO
* method cmp
* method long
* method file
* method xrange
* type basestring
* U prefix (3.2 only?)

**Comment by cschramm** [comment]
Replaced xrange, file, long, and cPickle as well.

The iniparse library is a real pain including all StringIO, basestring, and the u prefix.

Concerning the blueman code, we only have some usages of cmp (which is easy to replace), `__builtin__`, and some u prefixes in blueman-sendto.

**Comment by infirit** [comment]
I have in my [python3](https://github.com/infirit/blueman/compare/python3?expand=1) branch fixes for ```__builtin__```, sorting (cmp) and StrinIO.

The ``u`` prefix was added in python 3.3 afaik but, I think we may want to import ```unicode_literals``` from the ```__future__``` module instead of adding the ``u`` prefix on every string. The import enables the unicode handling from python3 and will ignored completely in python3.

**Comment by cschramm** [comment]
Nice. :smiley: Shall we add this to master or do you expect any issues?

Concerning the u prefix, apart from the iniparse lib we only use it in apps/blueman-sendto. It's probably unnecessary as we don't use it anywhere else, but I'm not sure.

**Comment by cschramm** [comment]
Oh, I see, your branch is python 3 _only_, right? Since e.g. io.StringIO does not exist in python 2.7 I think.

**Comment by infirit** [comment]
It should be compatible with 2 and 3, [io module](https://docs.python.org/2.6/library/io.html) was added in 2.6.

I am using this branch right now. However I like to test it a bit more before I send it off to master.

Also Python3 does not allow ``relative`` imports any-more and we need to add a dots in front. I am looking into this atm but it should be in the list.

**Comment by cschramm** [comment]
You're right, io.StringIO works with 2.7 as well.

**Comment by infirit** [comment]
Send a pull request for testing as things ended up being a bit large.

**Comment by cschramm** [comment]
@infirit You [mentioned](https://github.com/blueman-project/blueman/pull/168#issuecomment-73080855) there is still work to do. Any concrete issues?

**Comment by infirit** [comment]
Not looked at this but I am seeing maximum recursion.. Below repeats indefinitely.
```python
_________
Destroy (/usr/lib64/python3.3/site-packages/blueman/main/Device.py:98)
invalidating device None 
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Device.__del__ of <Device object at 0x7fa5d7fe8d20 (blueman+main+Device+Device at 0x22e3ae0)>> ignored
_________
__del__ (/usr/lib64/python3.3/site-packages/blueman/main/Device.py:60)
deleting device None 
_________
Destroy (/usr/lib64/python3.3/site-packages/blueman/main/Device.py:98)
invalidating device None 
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Device.__del__ of <Device object at 0x7fa5d7fe8d20 (blueman+main+Device+Device at 0x22e3ae0)>> ignored
_________
__del__ (/usr/lib64/python3.3/site-packages/blueman/main/Device.py:60)
deleting device None 
_________
Destroy (/usr/lib64/python3.3/site-packages/blueman/main/Device.py:98)
invalidating device None 
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Device.__del__ of <Device object at 0x7fa5d7fe8d20 (blueman+main+Device+Device at 0x22e3ae0)>> ignored
_________
```

**Comment by cschramm** [comment]
Looks like the recusion actually happens on line 120 when `Destroy` tries to get the `Signals` property. The getter than tries to get the `Device` property and calls itself recursively, since it is not set. This is probably the result of an exception in the constructor, since the unicode type is not defined in Python 3. Here are all the appearances, not sure what to do about the type checks (ignore iniparse, dropped in #180):

````
blueman/plugins/applet/NMPANSupport.py
148:        if type(value) == str or type(value) == unicode:

blueman/iniparse/ini.py
542:            if linecount == 0 and isinstance(line, unicode):

blueman/main/Device.py
23:        if isinstance(instance, str) or isinstance(instance, unicode):

apps/blueman-browse
62:            d.props.secondary_text = "%s\n\n" % unicode(e.message, 'UTF-8') + \
````

Another exception I got looks like we potentially have a problem with any method call for the Cython module with char * arguments due to str vs. bytes.

````
Traceback (most recent call last):
  File "/home/cschramm/src/blueman/blueman/plugins/applet/StandardItems.py", line 110, in on_devices
    icon="blueman")
  File "/home/cschramm/src/blueman/blueman/Functions.py", line 128, in startup_notification
    sn.set_name(name)
  File "_blueman.pyx", line 448, in _blueman.sn_launcher.set_name (_blueman.c:4614)
TypeError: expected bytes, str found
````

We could either look at all usages or change the definitions in some way. The `_ustring` helper from http://docs.cython.org/src/tutorial/strings.html looks a little like what we would need.

**Comment by cschramm** [comment]
Any other known issues than the unicode type and cython str vs. bytes?

**Comment by infirit** [comment]
It is one of those things that when you fix one thing three others show up :angry:

I now added all the future imports in python2.7 and am working through all the problems now. I pushed these commits just now to my [futurize](https://github.com/blueman-project/blueman/compare/master...infirit:futurize?expand=1) if you are curious :grinning:

**Comment by infirit** [comment]
It is alive, https://github.com/blueman-project/blueman/pull/215

**Comment by Plaque-fcc** [comment]
Recursion?

I got these on nearby devices discovery:

Destroy
(/usr/local/lib/python2.7/dist-packages/blueman/main/Device.py:92)
invalidating device None Exception RuntimeError: 'maximum recursion
depth exceeded' in <bound method Device.__del__ of <Device object at
0xa6d8d2d4 (blueman+main+Device+Device at 0x9a50e20)>> ignored
_________ __del__
(/usr/local/lib/python2.7/dist-packages/blueman/main/Device.py:70)
deleting device None _________

They loop infinitely.

It's there for a while, I later could report where it comes from, but
I'm sure you can reproduce and squash the bug much faster than lame I
can.

And thanks in advance!

**Comment by cschramm** [comment]
@Plaque-fcc Probably the result of a previous error as in https://github.com/blueman-project/blueman/issues/19#issuecomment-73652652. Any exceptions in the output before that happens?

**Comment by infirit** [comment]
@Plaque-fcc, I can not reproduce this with python 2.7 here on Gentoo. So you'll need to be more descriptive on the steps to reproduce.

**Comment by infirit** [comment]
@Plaque-fcc, Do try https://github.com/infirit/blueman/tree/string_type (two commits)

@cschramm, the new function string_type is a bit hacky but instead of sprinkling ``hassattr`` all over the place I thought this may be a better solution. My naming skills are horrible so if you have a better name for it do let me know :smile:

**Comment by Plaque-fcc** [comment]
No, it feeds all the screen with this looping. ;D

  Actually, I'm back to git bisect on it. No steps to reproduce this,
simply because it's as simple as «Hit Search button and have a loop»
and probably is system/versions-depended.

**Comment by infirit** [comment]
@Plaque-fcc Don't run bisect as it is quite useless in this case. Plus I know which one you will end up with, it is 82b84eed05b455ddaf16f9c9873f6fa6e373ac9e.

Try my commits in the string_type branch in my fork and see if that sort the problem out.

**Comment by Plaque-fcc** [comment]
Hi!

  No, I found that on e486d77034d3e5a08fd9159b4185a3e62b11c0b0 it
starts to get reproduced and from there on.

  And no, building from your repo/string_type doesn't prevent it from
recursive looping on discovery in Device.py. Although, thank you for
your suggestion.

**Comment by cschramm** [comment]
> I found that on e486d77 it starts to get reproduced and from there on.

@infirit I guess that means `BluezDevice(instance)` fails due to the type of `instance`?

@Plaque-fcc You could redirect the output to less or a file or whatever to see what happens before the loop.

**Comment by infirit** [comment]
@Plaque-fcc please apply the below debug patch and paste(bin) the output.

@cschramm, yes which is weird because I only ever saw ```BluezDevice``` instances on my machine. I can undo the logic reverse and check for string by using ```hasattr``` but now I am curious :smile: 

```diff
diff --git a/blueman/main/Device.py b/blueman/main/Device.py
index dd45740..ad298ef 100644
--- a/blueman/main/Device.py
+++ b/blueman/main/Device.py
@@ -30,6 +30,10 @@ class Device(GObject.GObject):
         self.Fake = True
         self.Temp = False
 
+        dprint("***DEBUG***")
+        dprint(type(instance))
+        dprint(repr(instance))
+        dprint("***DEBUG END***")
         if isinstance(instance, BluezDevice):
             self.Device = instance
         else:
```

**Comment by Plaque-fcc** [comment]
Eh… http://paste.ubuntu.com/10816669/ — you won't like it.

On top of infirit's branch:

$ git diff
diff --git a/blueman/main/Device.py b/blueman/main/Device.py
index dd45740..ad298ef 100644
--- a/blueman/main/Device.py
+++ b/blueman/main/Device.py
@@ -30,6 +30,10 @@ class Device(GObject.GObject):
         self.Fake = True
         self.Temp = False
 
+        dprint("***DEBUG***")
+        dprint(type(instance))
+        dprint(repr(instance))
+        dprint("***DEBUG END***")
         if isinstance(instance, BluezDevice):
             self.Device = instance
         else:

**Comment by infirit** [comment]
>you won't like it

I do as it is enlightening :wink:.

It is weird that this is a problem for you but not for me. But it is clear things go wrong when we see a ```FakeDevice```. I'll poke at the instance object to see if this is an instance of string or unicode and come up with a fix.

**Comment by cschramm** [comment]
Then it's probably BlueZ 4 vs. BlueZ 5. There shouldn't be any FakeDevice instances around when you have BlueZ 5.

**Comment by Plaque-fcc** [comment]
Ubuntu 14.10 x86, latest packages.

$ dpkg-query --show --showformat='${package} ${version} ${status} \n' bluez
bluez 4.101-0ubuntu20 install ok installed

**Comment by infirit** [comment]
@Plaque-fcc, please test https://github.com/blueman-project/blueman/pull/253

**Comment by hobarrera** [comment]
> $ dpkg-query --show --showformat='${package} ${version} ${status} \n' bluez
bluez 4.101-0ubuntu20 install ok installed

Hasn't bluez 4 been deprecated for some time now? I recall the move to bluez5 being over half a year ago.

**Comment by infirit** [comment]
It is but BlueZ 5 breaks lots of things so they have been putting it off. AFAIK 15.04 will come with BlueZ 5.

**Comment by cschramm** [comment]
Yes, the Ubuntu guys are working on it, but honestly, it is 15.04 now. I have no idea how that shall make it into the release...

Anyway, blueman currently supports both major versions, so issues with BlueZ 4 have to be dealt with. We'll drop that for 2.1 once 2.0 is finished.

**Comment by Plaque-fcc** [comment]
Yaaayy! Works!! ^_^ Than you!

**Comment by infirit** [comment]
Perfect, pushed the fix to master. Thanks for the report @Plaque-fcc.

**Comment by Plaque-fcc** [comment]
Always ready! And thanks for your immediate fix!
