### ISSUE TITLE
Connection failed: Protocol not Available

### ISSUE THREAD

**Issue by bhusal-rj** [blueman-project/blueman#1902]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

When I try to connect my wireless Earbud it gets paired but can't connect to device as there is an error popping up saying Connection failed: Protocol not Available

**Comment by cschramm** [comment]
You do not have a proper audio server installed. Typically the pulseaudio Bluetooth module is missing.
