### ISSUE TITLE
Paired Bluetooth headsets won't connect

### ISSUE THREAD

**Issue by josh-bartz** [blueman-project/blueman#1907]
blueman: 2.3.3+mint1+vanessa
BlueZ: 5.6.4-0ubuntu1
Distribution: Linux Mint 21
Desktop environment: Cinnamon 5.4.12

* [X ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Within the last week, bluetooth headsets/speakers (3 different ones - one Jabra 750, Sony Headphones, and Sony earbuds) have stopped connecting despite being paired. Once in a while one will randomly connect 10 minutes after I get the failure message (same message for all 3). Here's my [syslog](https://gist.github.com/josh-bartz/f566f048d4e3fedb5e1c8f02a0ec31c2). Keyboard and mouse still work. pulseaudio-bluetooth-module is installed.
<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by kvelakur** [comment]
This is a [bug](https://github.com/blueman-project/blueman/issues/1887) on blueman 2.3.3 which is the version available on the Linux Mint 21 main repository. So all PCs running LM21 have broken a broken bluetooth manager at the moment. 

Do one of the maintainers know when this bugfix will be released, and when we can expect it to appear on the main repository?

**Comment by infirit** [comment]
2.3.4 was release specifically to address this. https://github.com/blueman-project/blueman/releases/tag/2.3.4
