### ISSUE TITLE
blueman times out before remote device responds

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#191]
Using bluez-5.24

When trying to pair with an iPhone, blueman times out (in a few seconds) before the random pin message appears on the iPhone.

blueman-applet and blueman-manager output below:

iphone

$ blueman-applet
Loading configuration plugins
_________
<module> (/usr/local/lib/python2.7/site-packages/blueman/main/Config.py:1)
Skipping plugin Gconf
cannot import name GConf 
blueman-applet version 1.99.alpha1 starting
Using file config backend
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:55)
['TransferService', 'StatusIcon', 'StandardItems', 'ShowConnected', 'SerialManager', 'RecentConns', 'PowerManager', 'PPPSupport', 'Networking', 'NetUsage', 'NMPANSupport', 'NMDUNSupport', 'Menu', 'KillSwitch', 'Headset', 'GameControllerWakelock', 'ExitItem', 'DiscvManager', 'DhcpClient', 'DBusService', 'AuthAgent', 'AppIndicator'] 
Using file config backend
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:55)
Unable to load plugin module NMPANSupport
cannot import name GConf 
_________
get_interface_version (/usr/local/lib/python2.7/site-packages/blueman/bluez/BlueZInterface.py:8)
Detected BlueZ 5 
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:55)
Unable to load plugin module AppIndicator
cannot import name AppIndicator3 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.DBusService.DBusService'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.Headset.Headset'> 
Using file config backend
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.Menu.Menu'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'> 
Using file config backend
_________
update_menuitems (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:114)
warning: Adapter is None 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.DhcpClient.DhcpClient'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.TransferService.TransferService'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'> 
Using file config backend
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.ExitItem.ExitItem'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
Using file config backend
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'> 
Using file config backend
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
Not loading PPPSupport because it's conflict has higher priority 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.Networking.Networking'> 
Using file config backend
_________
load_nap_settings (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/Networking.py:30)
Loading NAP settings 
_________
update_state (/usr/local/lib/python2.7/site-packages/blueman/main/KillSwitchNG.py:153)
State: True 
_________
on_switch_added (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:27)
killswitch registered 1 
_________
on_obex_owner_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/TransferService.py:50)
obex owner changed:  
_________
on_dbus_name_owner_change (/usr/local/bin/blueman-applet:89)
org.bluez owner changed to :1.0 
_________
set_nap (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/Networking.py:61)
set nap False 
_________
try_start_ods (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/TransferService.py:44)
Could not acquire obex-data-server org.freedesktop.DBus.Error.ServiceUnknown: The name org.openobex was not provided by any .service files 
_________
register_agent (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/AuthAgent.py:58)
Registering agent 
_________
initialize (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:139)
rebuilding menu 
_________
enumerate_connections (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/ShowConnected.py:45)
Found 0 existing connections 
_________
save (/usr/local/lib/python2.7/site-packages/blueman/plugins/config/File.py:105)
Saving config 
_________
RequestPowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:112)
Requesting False 
_________
on_power_state_change_requested (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:53)
False 
_________
SetGlobalState (/usr/local/lib/python2.7/site-packages/blueman/main/KillSwitchNG.py:143)
set False 
_________
on_power_state_query (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:43)
True 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:140)
off True 
foff False 
on True 
current state True 
new state False 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:140)
Signalling False 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py", line 59, in timeout
    self.RequestPowerState(self.adapter_state)
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py", line 122, in RequestPowerState
    self.UpdatePowerState()
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py", line 178, in UpdatePowerState
    self.BluetoothStatusChanged(new_state)
  File "/usr/local/lib/python2.7/site-packages/dbus/decorators.py", line 300, in emit_signal
    for location in self.locations:
AttributeError: 'PowerManager' object has no attribute 'locations'
_________
update_state (/usr/local/lib/python2.7/site-packages/blueman/main/KillSwitchNG.py:153)
State: False 
_________
on_switch_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:31)
Global state: False 
switch.soft: 1 
switch.hard: 0 
_________
on_power_state_query (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:43)
False 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:140)
off True 
foff False 
on False 
current state False 
new state False 
_________
check (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:100)
callbacks done 
_________
set_adapter_state (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:71)
False 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001200-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001800-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001801-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110a-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110b-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1) 
_________
RequestPowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:112)
Requesting 1 
_________
on_power_state_change_requested (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:53)
1 
_________
SetGlobalState (/usr/local/lib/python2.7/site-packages/blueman/main/KillSwitchNG.py:143)
set 1 
_________
on_power_state_query (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:43)
False 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:140)
off True 
foff False 
on False 
current state False 
new state False 
_________
update_state (/usr/local/lib/python2.7/site-packages/blueman/main/KillSwitchNG.py:153)
State: True 
_________
on_switch_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:31)
Global state: True 
switch.soft: 0 
switch.hard: 0 
_________
on_power_state_query (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:43)
True 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:140)
off True 
foff False 
on True 
current state False 
new state False 
_________
check (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:100)
callbacks done 
_________
set_adapter_state (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:71)
1 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop Class 786700 
_________
adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:194)
adapter powered on while in off state, turning bluetooth on 
_________
RequestPowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:112)
Requesting True 
_________
on_power_state_change_requested (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:53)
True 
_________
SetGlobalState (/usr/local/lib/python2.7/site-packages/blueman/main/KillSwitchNG.py:143)
set True 
_________
on_power_state_query (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:43)
True 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:140)
off False 
foff False 
on True 
current state False 
new state True 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:140)
Signalling True 
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blueman/bluez/PropertiesBlueZInterface.py", line 51, in wrapper
    handler(name, value, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py", line 198, in adapter_property_changed
    self.RequestPowerState(True)
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py", line 122, in RequestPowerState
    self.UpdatePowerState()
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py", line 178, in UpdatePowerState
    self.BluetoothStatusChanged(new_state)
  File "/usr/local/lib/python2.7/site-packages/dbus/decorators.py", line 300, in emit_signal
    for location in self.locations:
AttributeError: 'PowerManager' object has no attribute 'locations'
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop Powered 1 
_________
check (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:100)
callbacks done 
_________
set_adapter_state (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:71)
True 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop Discovering 1 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop Discovering 0 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:60)
deleting device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:98)
invalidating device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
RequestConfirmation (/usr/local/lib/python2.7/site-packages/blueman/main/applet/BluezAgent.py:196)
Agent.RequestConfirmation 

(blueman-applet:9423): libnotify-WARNING **: Failed to connect to proxy
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:60)
deleting device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:98)
invalidating device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:60)
deleting device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:98)
invalidating device /org/bluez/hci0/dev_54_E4_3A_22_48_E9 

**********

$ blueman-manager
Loading configuration plugins
_________
<module> (/usr/local/lib/python2.7/site-packages/blueman/main/Config.py:1)
Skipping plugin Gconf
cannot import name GConf 
Using file config backend
/usr/local/bin/blueman-manager:49: Warning: The property GtkAlignment:left-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.Builder.add_from_file(UI_PATH + "/manager-main.ui")
/usr/local/bin/blueman-manager:49: Warning: The property GtkAlignment:right-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.Builder.add_from_file(UI_PATH + "/manager-main.ui")
/usr/local/bin/blueman-manager:49: Warning: The property GtkAlignment:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.Builder.add_from_file(UI_PATH + "/manager-main.ui")
/usr/local/bin/blueman-manager:49: Warning: The property GtkAlignment:xscale is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.Builder.add_from_file(UI_PATH + "/manager-main.ui")
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:55)
['Services', 'PulseAudioProfile'] 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.manager.Services.Services'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.manager.PulseAudioProfile.PulseAudioProfile'> 
_________
pa_context_event (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:333)
1 
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:38: Warning: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.icon.props.xpad = 4
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:49: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.b_more.set_image(im)
blueman-manager version 1.99.alpha1 starting
_________
pa_context_event (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:333)
2 
_________
on_bluez_name_owner_changed (/usr/local/bin/blueman-manager:108)
org.bluez owner changed to  :1.0 
Using file config backend
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
_________
pa_context_event (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:333)
3 
_________
pa_context_event (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:333)
4 
_________
on_pa_ready (/usr/local/lib/python2.7/site-packages/blueman/plugins/manager/PulseAudioProfile.py:24)
connected 
_________
<lambda> (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:345)
1 
_________
get_interface_version (/usr/local/lib/python2.7/site-packages/blueman/bluez/BlueZInterface.py:8)
Detected BlueZ 5 
_________
SetAdapter (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:264)
None 
_________
on_adapter_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerToolbar.py:75)
toolbar adapter /org/bluez/hci0 
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:148)
adapter propery changed Class 786700 
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:148)
adapter propery changed Powered 1 
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:148)
adapter propery changed Discovering 1 
_________
on_device_created (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:246)
created /org/bluez/hci0/dev_48_5A_B6_3F_CE_FE 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
add_device (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:310)
adding new device 
_________
do_cache (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:489)
Caching new device 48:5A:B6:3F:CE:FE 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Fake False 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Trusted 0 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Paired 0 
_________
on_device_created (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:246)
created /org/bluez/hci0/dev_E4_E0_C5_C3_A5_24 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
add_device (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:310)
adding new device 
_________
do_cache (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:489)
Caching new device E4:E0:C5:C3:A5:24 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Fake False 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Trusted 0 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Paired 0 
_________
on_device_created (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:246)
created /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
add_device (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:310)
adding new device 
_________
do_cache (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:489)
Caching new device 54:E4:3A:22:48:E9 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Fake False 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Trusted 0 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Paired 0 
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:148)
adapter propery changed Discovering 0 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
on_device_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:156)
list: device_prop_ch Connected 1 /org/bluez/hci0/dev_54_E4_3A_22_48_E9 () {} 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Connected 1 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
monitor_power_levels (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:178)
starting monitor 
_________
level_setup_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:322)
animating up 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
BRAVIA 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
BRAVIA 
/usr/local/lib/python2.7/site-packages/blueman/gui/GtkAnimation.py:263: Warning: The property GtkTreeView:rules-hint is deprecated and shouldn't be used anymore. It will be removed in a future version.
  if self.tw.props.rules_hint:
_________
on_device_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:156)
list: device_prop_ch Connected 0 /org/bluez/hci0/dev_54_E4_3A_22_48_E9 () {} 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Connected 0 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
level_setup_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:322)
animating down 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
BRAVIA 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
BRAVIA 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone 
_________
update (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:179)
stopping monitor (not connected) 
_________
RemoveDevice (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:420)
<Device object at 0x7f89ff095190 (blueman+main+Device+Device at 0x10c8da0)> 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:98)
invalidating device /org/bluez/hci0/dev_48_5A_B6_3F_CE_FE 
_________
RemoveDevice (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:420)
<Device object at 0x7f89ff0953c0 (blueman+main+Device+Device at 0x10ea7a0)> 
_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:60)
deleting device /org/bluez/hci0/dev_E4_E0_C5_C3_A5_24 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:98)
invalidating device /org/bluez/hci0/dev_E4_E0_C5_C3_A5_24 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
juanito_tc iPhone

**Comment by cschramm** [comment]
That's #189 again, isn't it?

**Comment by juanitotc** [comment]
Sorry - I hadn't realised the subject had been changed and forgot I posted it.

Please delete.
