### ISSUE TITLE
feat: Close adapters window with Esc

### ISSUE THREAD

**Issue by WhyNotHugo** [blueman-project/blueman#1946]
The adapters window is very nice and handy:

![image](https://user-images.githubusercontent.com/730811/203633154-71977f37-9e58-4318-8933-af053fc232d9.png)

But it's mildly annoying that pressing <kbd>Esc</kbd> doesn't close it; most pop-ups are dismissed with <kbd>Esc</kbd>, so I intuitively try the same here but it doesn't work.

**Comment by WhyNotHugo** [comment]
Wow, that screenshot size o.O

**Comment by infirit** [comment]
Let's include this in the other feature request for keyboard shortcuts  #1523
