### ISSUE TITLE
Blueman gives the vague error "Connection Failed: Unable to get a session"

### ISSUE THREAD

**Issue by robbie0630** [blueman-project/blueman#195]
I have been trying to connect my bluetooth speaker to my computer for at least a couple days. I finally decided to just ask for help on the project itself. I really want to set this up with my computer. Help would be appreciated.

**Comment by cschramm** [comment]
Looks like an error from BlueZ 4. Is the device paired?

Please give more information on what you're using: https://github.com/blueman-project/blueman/wiki/Troubleshooting

**Comment by robbie0630** [comment]
@cschramm This is the error I get when I tried to pair the device.

**Comment by cschramm** [comment]
?

**Comment by robbie0630** [comment]
@cschramm "Connection Failed: Unable to get a session" is the error I get when I tried to pair the device.

**Comment by cschramm** [comment]
Sorry, we cannot help if you do not follow simple requests and answer simple questions.
