### ISSUE TITLE
No able to find any device in blueman

### ISSUE THREAD

**Issue by amitpranav** [blueman-project/blueman#1952]
blueman:2.3.4
BlueZ:5.64-0ubuntu1
Distribution:Linux Mint 21Cinnamon -64 bit
Desktop environment: Cinnamon

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Did you try unchecking `Hide unnamed devices` in the `View` menu?
