### ISSUE TITLE
There is a transparent gap on the left from menu items

### ISSUE THREAD

**Issue by kuraga** [blueman-project/blueman#1957]
blueman: 2.3.5
BlueZ: 5.6.5
Distribution: Calculate Linux (Gentoo)
Desktop environment: XFCE

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

There is a transparent gap on the left from menu items:

![image](https://user-images.githubusercontent.com/1063219/205080131-f06b0069-7465-4123-bcbf-91974545027b.png)

I'm talking not about beauty now, but could it be a symptom to some UI issues?

**Comment by cschramm** [comment]
That's most probably not rendered by blueman but xfce4-panel, using blueman-applet's StatusNotifierItem plugin. If you disable that plugin, `blueman-tray` will render it.

**Comment by kuraga** [comment]
> If you disable that plugin

Yes, behavior changes. There is no a gap.

Feel free to close.
