### ISSUE TITLE
Connection Failed: Protocol not available

### ISSUE THREAD

**Issue by skeeperloyaltie** [blueman-project/blueman#1958]
Cannot conenct even after purging blueman bluez pulseaudio

![Screenshot at 2022-12-01 20-24-52](https://user-images.githubusercontent.com/54027203/205119650-cdee8e07-0be8-4124-a235-1afef838b928.png)

**Comment by cschramm** [comment]
https://github.com/blueman-project/blueman/wiki/Troubleshooting

**Comment by skeeperloyaltie** [comment]
Still doesnt solve the problem. Am still getting the problem
