### ISSUE TITLE
Blutooth is always getting enabled after opening lid even though it was deactivated and Autoenable is set to false

### ISSUE THREAD

**Issue by JulezJay** [blueman-project/blueman#1967]
blueman: 2.3.4+mint1+vanessa
BlueZ: 5.64-Oubunto1
Distribution: Mint21
Desktop environment: Cinamon

* As the title says my Bluetoothadapter on my HP-Envy x360 13-bd0350ng is activated always when I open the lid. It was deactivated before closing the lid (I very seldom use Bluetooth). I have turned off Autoenable in the Manager of Blueman as well as in the config file under /etc/bluetooth/main.conf as well as with this command in the terminal: "gsettings set org.blueman.plugins.powermanager auto-power-on false". The adapter stays off during reboot but is getting enabled always after opening the lid.

**Comment by infirit** [comment]
Start it in the terminal, make sure bluetooth is disabled, close the lid. Then when you resume post the whole blueman-applet log here. See the following on how to provide the log https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging-blueman.

**Comment by cschramm** [comment]
You can also just terminate blueman (e.g. right-click => Exit on the tray icon) before closing the lid to check if it is even involved.

**Comment by JulezJay** [comment]
I just checked that if I quit the Bluetooth-Manager and come back from suspend (open the lid or wake up from sleepmode) Bluetooth is deactivated. So it should be caused by the Manager.  I did as @infirit said and activated the debugging, suspended and woke up. This is the terminal output I got:

blueman-applet --loglevel debug
blueman-applet 15.24.08 INFO     PluginManager:87 load_plugin: ['TransferService', 'DisconnectItems', 'DBusService', 'StatusNotifierItem', 'DhcpClient', 'RecentConns', 'NMDUNSupport', 'ShowConnected', 'Menu', 'AutoConnect', 'NetUsage', 'AuthAgent', 'SerialManager', 'KillSwitch', 'StandardItems', 'GameControllerWakelock', 'DiscvManager', 'StatusIcon', 'NMPANSupport', 'PPPSupport', 'Networking', 'ExitItem', 'PowerManager', 'ConnectionNotifier']
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.TransferService.TransferService'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.Menu.Menu'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.DisconnectItems.DisconnectItems'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'>
blueman-applet 15.24.08 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0 {'Address': 'CC:15:31:3B:3B:A1', 'AddressType': 'public', 'Name': 'julez-ENVY', 'Alias': 'julez-ENVY', 'Class': 0, 'Powered': False, 'Discoverable': False, 'DiscoverableTimeout': 180, 'Pairable': False, 'PairableTimeout': 0, 'Discovering': False, 'UUIDs': ['00001133-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '00001105-0000-1000-8000-00805f9b34fb', '00001132-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '00001104-0000-1000-8000-00805f9b34fb', '00005005-0000-1000-8000-0002ee000001', '00001108-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000112f-0000-1000-8000-00805f9b34fb', '0000110b-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb', '00001800-0000-1000-8000-00805f9b34fb', '0000111f-0000-1000-8000-00805f9b34fb', '0000110a-0000-1000-8000-00805f9b34fb', '00001106-0000-1000-8000-00805f9b34fb'], 'Modalias': 'usb:v1D6Bp0246d0540', 'Roles': ['central', 'peripheral']}
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.DBusService.DBusService'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.StatusNotifierItem.StatusNotifierItem'>
blueman-applet 15.24.08 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.PowerManager.PowerManager'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.RecentConns.RecentConns'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.AutoConnect.AutoConnect'>
blueman-applet 15.24.08 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.SerialManager.SerialManager'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.StandardItems.StandardItems'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.NMPANSupport.NMPANSupport'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.Networking.Networking'>
blueman-applet 15.24.08 INFO     Networking:35 load_nap_settings: Loading NAP settings
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.ExitItem.ExitItem'>
blueman-applet 15.24.08 INFO     PluginManager:160 __load_plugin: loading <class 'blueman.plugins.applet.ConnectionNotifier.ConnectionNotifier'>
blueman-applet 15.24.08 INFO     KillSwitch:106 io_event  : killswitch registered 0
blueman-applet 15.24.08 INFO     KillSwitch:122 io_event  : State: False
blueman-applet 15.24.08 INFO     PowerManager:179 update_power_state: off True | foff False | on True | current state True | new state False
blueman-applet 15.24.08 INFO     PowerManager:182 update_power_state: Signalling False
blueman-applet 15.24.08 INFO     KillSwitch:85 _on_connman_vanished: net.connman vanished
blueman-applet 15.24.08 INFO     TransferService:234 _on_dbus_name_appeared: org.bluez.obex :1.61
blueman-applet 15.24.08 INFO     Applet:63 _on_dbus_name_appeared: org.bluez :1.4
blueman-applet 15.24.08 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0/dev_E8_07_BF_FE_45_39 {'Address': 'E8:07:BF:FE:45:39', 'AddressType': 'public', 'Name': 'DOCKIN D Fine', 'Alias': 'DOCKIN D Fine', 'Class': 2360324, 'Icon': 'audio-headset', 'Paired': True, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000110b-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}
blueman-applet 15.24.08 INFO     Functions:114 launch    : Gtk eventtime is 0, not using LaunchContext
blueman-applet 15.24.08 INFO     BluezAgent:56 register_agent: Register Agent
blueman-applet 15.24.08 INFO     Networking:71 set_nap   : set nap False
blueman-applet 15.24.08 INFO     AgentManager:17 on_registered: /org/bluez/obex/agent/blueman
blueman-applet 15.24.08 INFO     ShowConnected:50 enumerate_connections: Found 0 existing connections
blueman-applet 15.24.08 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0 {'Pairable': True}
blueman-applet 15.24.08 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Pairable True
blueman-applet 15.24.24 INFO     KillSwitch:112 io_event  : killswitch changed 0
blueman-applet 15.24.24 INFO     KillSwitch:122 io_event  : State: True
blueman-applet 15.24.24 INFO     PowerManager:179 update_power_state: off True | foff False | on True | current state False | new state False
blueman-applet 15.24.24 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0 {'Class': 8126464}
blueman-applet 15.24.24 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Class 8126464
blueman-applet 15.24.24 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0 {'Powered': True}
blueman-applet 15.24.24 WARNING  PowerManager:203 on_adapter_property_changed: adapter powered on while in off state, turning bluetooth on
blueman-applet 15.24.24 INFO     PowerManager:140 request_power_state: Requesting True
blueman-applet 15.24.24 INFO     KillSwitch:138 on_power_state_change_requested: True
blueman-applet 15.24.24 DEBUG    KillSwitch:151 on_power_state_change_requested: Using mechanism to set state: True
blueman-applet 15.24.24 INFO     PowerManager:179 update_power_state: off False | foff False | on True | current state False | new state True
blueman-applet 15.24.24 INFO     PowerManager:182 update_power_state: Signalling True
blueman-applet 15.24.24 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Powered True
blueman-applet 15.24.24 INFO     PowerManager:125 check     : callbacks done
blueman-applet 15.24.24 INFO     PowerManager:96 set_adapter_state: True
blueman-applet 15.24.24 INFO     PowerManager:179 update_power_state: off False | foff False | on True | current state True | new state True
blueman-applet 15.24.30 INFO     KillSwitch:112 io_event  : killswitch changed 0
blueman-applet 15.24.30 INFO     KillSwitch:122 io_event  : State: False
blueman-applet 15.24.30 INFO     PowerManager:179 update_power_state: off True | foff False | on True | current state True | new state False
blueman-applet 15.24.30 INFO     PowerManager:182 update_power_state: Signalling False
blueman-applet 15.24.30 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0 {'Class': 0, 'Powered': False, 'Discovering': False}
blueman-applet 15.24.30 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Class 0
blueman-applet 15.24.30 INFO     PowerManager:179 update_power_state: off True | foff False | on False | current state False | new state False
blueman-applet 15.24.30 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Powered False
blueman-applet 15.24.30 INFO     DiscvManager:109 on_adapter_property_changed: Stop
blueman-applet 15.24.30 DEBUG    DiscvManager:92 on_adapter_property_changed: prop Discovering False
^Cblueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.ConnectionNotifier.ConnectionNotifier object at 0x7ff9361a9e10>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.ExitItem.ExitItem object at 0x7ff9361a9ba0>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.Networking.Networking object at 0x7ff9361a98a0>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.NMPANSupport.NMPANSupport object at 0x7ff9361a96f0>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.DiscvManager.DiscvManager object at 0x7ff9361a9b40>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock object at 0x7ff9361a9750>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.StandardItems.StandardItems object at 0x7ff9361a9540>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.KillSwitch.KillSwitch object at 0x7ff9361a91b0>
blueman-applet 15.24.45 DEBUG    SerialManager:50 on_delete : Terminating any running scripts
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.SerialManager.SerialManager object at 0x7ff9361a9480>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.AuthAgent.AuthAgent object at 0x7ff9361a8f70>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.AutoConnect.AutoConnect object at 0x7ff9361a9420>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.ShowConnected.ShowConnected object at 0x7ff9361a93f0>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.NMDUNSupport.NMDUNSupport object at 0x7ff9361a9390>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.RecentConns.RecentConns object at 0x7ff9361a8f10>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.PowerManager.PowerManager object at 0x7ff9361a8eb0>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.StatusNotifierItem.StatusNotifierItem object at 0x7ff9361a8e50>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.DBusService.DBusService object at 0x7ff9361a88e0>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <StatusIcon.StatusIcon object at 0x7ff93a8c0a80 (blueman+plugins+applet+StatusIcon+StatusIcon at 0x55e4c51f5b00)>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.DisconnectItems.DisconnectItems object at 0x7ff93a8b8f10>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.Menu.Menu object at 0x7ff93a8b8ee0>
blueman-applet 15.24.45 DEBUG    BasePlugin:63 _on_plugin_delete: Deleting plugin instance <blueman.plugins.applet.TransferService.TransferService object at 0x7ff93a8b8a30>

**Comment by infirit** [comment]
I see we get the Powered property set True on resume but the Killswitch is still on. We then proceed to put the adapter in a good state and turn off the Killswitch. If blueman-applet is not running the last step doesn't happen.

Not sure if we are doing the right thing here, maybe we should follow the Killswitch state and power down the adapter...?

**Comment by JulezJay** [comment]
@infirit: Thanks for your efforts to help me! 
As I am new to Linux I am not shure if I understood everything. Somehow the powered property is set to TRUE after I wake up from suspend but the KillSwitch is still on and then turned off by Blueman to match the new powered property. Is the problem on "my" side so something that is caused by my Linux system or the settings in powermanager (PowerManager:203 on_adapter_property_changed: adapter powered on while in off state, turning bluetooth on)?

**Comment by cschramm** [comment]
It looks like the killswitch gets unblocked on resume. I don't get why it would behave like that. :thinking:

**Comment by JulezJay** [comment]
I updated to Mint 21.1 and after some days it seems like the issue is gone. Now I have another minor bug I can live with. After some hours of use and several hibernates the blueman symbol is gone from the taskbar and blueman is shut down.

**Comment by cschramm** [comment]
No blueman-applet process? You can run it from the terminal (with `--loglevel debug`) to see the termination. Otherwise there could be something e.g. in .xsession-errors.
