### ISSUE TITLE
My bluetooth headphones keep disconnecting after 20 minutes and then reconnecting automatically

### ISSUE THREAD

**Issue by imashishnegi** [blueman-project/blueman#1971]
blueman: 2.3.4
BlueZ: 5.64-0ubuntu1
Distribution: Linux Mint 21
Desktop environment: Cinnamon

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I am using Realme buds Air 2 bluetooth headphone. Previously in Linux Mint 20 they worked fine. In mint 21, headphones are disconnecting after every 20 min. This is really annoying.

![Screenshot from 2022-12-18 23-57-44](https://user-images.githubusercontent.com/20860151/208314108-a1e207cf-3503-4dd2-a8a9-c43e1930dd5e.png)

**Address**: 18:95:52:6E:A9:BE
**AddressType**: public
**Name**: realme Buds Air 2
**Alias**: realme Buds Air 2
**Class**: 0x240404
**Appearance**: 0x0000
**Icon**: audio-headset
**Paired**: yes
**Trusted**: yes
**Blocked**: no
**LegasyPairing**: no
**Connected**: yes
**UUIDS**: 00000000-0000-0000-0099-aabbccddeeff Proprietary
00001101-0000-1000-8000-00805f9b34fb Serial Port
0000110b-0000-1000-8000-00805f9b34fb Audio Sink
0000110c-0000-1000-8000-00805f9b34fb Remote Control Target
0000110d-0000-1000-8000-00805f9b34fb Advanced Audio
0000110e-0000-1000-8000-00805f9b34fb Remote Control
0000111e-0000-1000-8000-00805f9b34fb Handsfree
00001200-0000-1000-8000-00805f9b34fb PnP Information
00001801-0000-1000-8000-00805f9b34fb Generic Attribute
df21fe2c-2515-4fdb-8886-f12c4d67927c Proprietary
**Modalias**: bluetooth:v0094p0123d1000
**Adapter**: /org/bluez/hci0

**Comment by cschramm** [comment]
I found a couple of hits on the Internets that are somewhat similar. realme even has a support article about (random) disconnects.

I would check the kernel and BlueZ logs at disconnect, maybe enable BlueZ debugging, but I guess all you'll find is that the remote device disconnects.
