### ISSUE TITLE
Cant connect bluetooth headset anymore (br-connection unknown)

### ISSUE THREAD

**Issue by andreo141** [blueman-project/blueman#1976]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by ThigSchuch** [comment]
I'm having a similar problem.

My headset have the MAC 7C:96:D2...
I try to connect to it, but instead, the manager tries to connect on the neighbor's TV, yes, try to connect on a random device.
If this not occur, some other device shows up with different MAC from my headset and I get this "br-connection unknown"

I'm using a recent installation of Mint 21.1 and blueman v2.3.4.

**Comment by cschramm** [comment]
@ThigSchuch: Broken right-click targets have been fixed in 2.3.5. Workarounds include showing unnamed devices via the "View" menu.
