### ISSUE TITLE
Connection Failed:  Protocol not available

### ISSUE THREAD

**Issue by abhijithm2001** [blueman-project/blueman#1981]
blueman:
Connection failed while connecting bluetooth headset.
showing error: " **Protocol not available**"
![image](https://user-images.githubusercontent.com/57061768/209616996-79fb3612-ac4b-4b54-8302-2e98921eacac.png)

**Comment by cschramm** [comment]
Your unspecified system lacks an audio server with Bluetooth support.

**Comment by pakair** [comment]
`sudo apt install pulseaudio-module-bluetooth`, reboot, and try again.

**Comment by diveloper53** [comment]
> Your unspecified system lacks an audio server with Bluetooth support.

It's Parrot OS, I have it too

> `sudo apt install pulseaudio-module-bluetooth`, reboot, and try again.

Doesn't help :(

**Comment by cschramm** [comment]
Obviously, if e.g. your audio server happens to be PipeWire (I don't know what's default in Parrot), a pulseaudio plugin is of no help. `libspa-0.2-bluetooth` would be the package for the PW module.
