### ISSUE TITLE
blueman segfaults on setting iPhone as network connection

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#199]
Using bluez-4.101

After pairing an iPhone with "personal hotspot" enabled and clicking on "set as network connection" (I don't remember the exact phrase), blueman segfaults.

$ blueman-applet
Loading configuration plugins
_________
<module> (/usr/local/lib/python2.7/site-packages/blueman/main/Config.py:1)
Skipping plugin Gconf
cannot import name GConf 
blueman-applet version 1.99.alpha1 starting
Stale PID, overwriting
Using file config backend
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:55)
['TransferService', 'StatusIcon', 'StandardItems', 'ShowConnected', 'SerialManager', 'RecentConns', 'PowerManager', 'PPPSupport', 'Networking', 'NetUsage', 'NMPANSupport', 'NMDUNSupport', 'Menu', 'KillSwitch', 'Headset', 'GameControllerWakelock', 'ExitItem', 'DiscvManager', 'DhcpClient', 'DBusService', 'AuthAgent', 'AppIndicator'] 
Using file config backend
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:55)
Unable to load plugin module NMPANSupport
cannot import name GConf 
_________
get_interface_version (/usr/local/lib/python2.7/site-packages/blueman/bluez/BlueZInterface.py:8)
Detected BlueZ 4 
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:55)
Unable to load plugin module AppIndicator
cannot import name AppIndicator3 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.DBusService.DBusService'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.Headset.Headset'> 
Using file config backend
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.Menu.Menu'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'> 
Using file config backend
_________
update_menuitems (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:114)
warning: Adapter is None 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.DhcpClient.DhcpClient'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.TransferService.TransferService'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'> 
Using file config backend
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.ExitItem.ExitItem'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
Using file config backend
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'> 
Using file config backend
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
Not loading PPPSupport because it's conflict has higher priority 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.applet.Networking.Networking'> 
Using file config backend
_________
load_nap_settings (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/Networking.py:30)
Loading NAP settings 
_________
update_state (/usr/local/lib/python2.7/site-packages/blueman/main/KillSwitchNG.py:153)
State: True 
_________
on_switch_added (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:27)
killswitch registered 0 
_________
on_obex_owner_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/TransferService.py:50)
obex owner changed:  
_________
on_dbus_name_owner_change (/usr/local/bin/blueman-applet:89)
org.bluez owner changed to :1.0 
_________
set_nap (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/Networking.py:61)
set nap False 
_________
try_start_ods (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/TransferService.py:44)
Could not acquire obex-data-server org.freedesktop.DBus.Error.ServiceUnknown: The name org.openobex was not provided by any .service files 
_________
register_agent (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/AuthAgent.py:58)
Registering agent 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
initialize (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:139)
rebuilding menu 
_________
enumerate_connections (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/ShowConnected.py:45)
Found 0 existing connections 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110a-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1) 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110a-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110b-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1) 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
notify (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:234)
<Device object at 0xb5fc97ac (blueman+main+Device+Device at 0x90af060)> org.bluez.Network dbus.Array([dbus.String(u'00001116-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s')) 
_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:60)
deleting device /org/bluez/7344/hci0/dev_54_E4_3A_22_48_E9 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:98)
invalidating device /org/bluez/7344/hci0/dev_54_E4_3A_22_48_E9 
_________
initialize (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:139)
rebuilding menu 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110b-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1) 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1) 

**********

$ blueman-manager
Loading configuration plugins
_________
<module> (/usr/local/lib/python2.7/site-packages/blueman/main/Config.py:1)
Skipping plugin Gconf
cannot import name GConf 
Using file config backend
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:55)
['Services', 'PulseAudioProfile'] 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.manager.Services.Services'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:128)
loading <class 'blueman.plugins.manager.PulseAudioProfile.PulseAudioProfile'> 
_________
pa_context_event (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:333)
1 
W: [pulseaudio] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because this Pulseaudio was built without libcap support.
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:49: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.b_more.set_image(im)
blueman-manager version 1.99.alpha1 starting
Stale PID, overwriting
_________
pa_context_event (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:333)
2 
_________
on_bluez_name_owner_changed (/usr/local/bin/blueman-manager:108)
org.bluez owner changed to  :1.0 
Using file config backend
_________
get_interface_version (/usr/local/lib/python2.7/site-packages/blueman/bluez/BlueZInterface.py:8)
Detected BlueZ 4 
_________
SetAdapter (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:264)
None 
_________
on_adapter_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerToolbar.py:75)
toolbar adapter /org/bluez/7344/hci0 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
_________
add_device (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:310)
adding new device 
_________
do_cache (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:489)
Caching new device 54:E4:3A:22:48:E9 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Fake False 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Trusted 0 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Paired 1 
_________
init_services (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:73)
Loading services 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
j-frankish iPhone 
_________
pa_context_event (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:333)
3 
_________
pa_context_event (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:333)
4 
_________
on_pa_ready (/usr/local/lib/python2.7/site-packages/blueman/plugins/manager/PulseAudioProfile.py:24)
connected 
_________
<lambda> (/usr/local/lib/python2.7/site-packages/blueman/main/PulseAudioUtils.py:345)
1 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
j-frankish iPhone 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
j-frankish iPhone 
_________
set_op (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:77)
op: regenerating instance <ManagerDeviceMenu object at 0xb5ff7144 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x8c55620)> 
_________
set_op (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:77)
op: regenerating instance <ManagerDeviceMenu object at 0xb5d0448c (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x8c557a0)> 
_________
unset_op (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:91)
op: regenerating instance <ManagerDeviceMenu object at 0xb5ff7144 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x8c55620)> 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:215)
j-frankish iPhone 
_________
unset_op (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:91)
op: regenerating instance <ManagerDeviceMenu object at 0xb5d0448c (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x8c557a0)> 
_________
fail (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:121)
fail (DBusException(dbus.String(u'Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.'),),) 

(blueman-manager:8044): Gtk-CRITICAL **: gtk_style_context_get_property: assertion 'priv->widget != NULL || priv->widget_path != NULL' failed
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:153: Warning: gtype.c:4221: type id '0' is invalid
  self.show()
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:153: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  self.show()
Segmentation fault

**Comment by cschramm** [comment]
This is #42, some GTK+ theme issue. Please add the name of your theme to that ticket. I'll have a look if I find a way to fix or avoid that in our MessageArea.
