### ISSUE TITLE
Magic Keyboard iMac 2009 cannot connect on startup and disconnects for periods between 30 sec and 2 min

### ISSUE THREAD

**Issue by etzvetanov** [blueman-project/blueman#2001]
blueman: 2.3.5
BlueZ: 
Distribution: Fedora 36
Desktop environment: iMac 10.1 (2009)

* [ v] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

There are no logs. Upon restarting my iMac, regardless if it is cold or warm reboot, my Magic Keyboard has issues connecting.
During regular work with the computer I get disconnects, which last between 30 seconds and 2 minutes.  The batteries in the keyboard are new. I used to run Linux Mint, but there is some issue with support of some video drivers, so I switched to Fedora and have been working with it for a while. But this issue has never been addressed. I tried filing it in the Fedora (RedHat) Bugzilla, no attention whatsoever. Maybe because us old timers with old equipment do not deserve to have attention from anyone? :-)
<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Did you see the very same issue in Linux Mint?

I assume "no logs" specifically includes `bluetooth.service` and kernel messages.

Two things you can try to look into this: Enable debug logging for `bluetoothd` and / or run `btmon` and check what you see there when the disconnect takes place.
