### ISSUE TITLE
Can not discover iclever keyboard bk10

### ISSUE THREAD

**Issue by DrStrom66** [blueman-project/blueman#2003]
blueman: 2.3.4
BlueZ: 5,64
Distribution: Linux Mint 21.1 Cinnamon
Desktop environment: Cinnamon

I can't discover an Iclever keyboard BK10.
but ii is discover-able by two Windows laptops

**Comment by cschramm** [comment]
What name does Windows show when it discovers the device? Did you try disabling "Hide unnamed devices" in the "View" menu?

**Comment by DrStrom66** [comment]
Hi Christopher,

Thanks for the tip with disabling unnamed devices, that made the
keyboard detectable. I have it now in the list.
But still I can't use it. It is marked as trusted and when I click on
connect I get following error : Connection Failed: br-connection-
create-socket

**Comment by cschramm** [comment]
I would not expect the connection to succeed for an unpaired keyboard, but wouldn't expect the socket error either. You can check if `dmesg` or `journalctl -u bluetooth.service` have some info on it.

First thing you need to do is pairing. Typically when devices are pairable, they provide a name, but it might fall into #1954.
