### ISSUE TITLE
blueman-applet error on startup

### ISSUE THREAD

**Issue by vinjana** [blueman-project/blueman#2005]
blueman: blueman/jammy,now 2.2.4-1
BlueZ: bluez/jammy,now 5.64-0ubuntu1
Distribution: Ubuntu 22.04.1 LTS
Desktop environment: LXQT (lxqt/jammy 30ubuntu1)

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Start `blueman-applet` or log in to LXQT session.

A window opens with the following text:
```
Failed to apply network settings
You might not be able to connect to the Bluetooth network via this machine

Exception
g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/DbusService.py", line 126, in _handle_method_call
    ok(method(*args))
  File "/usr/lib/python3/dist-packages/blueman/plugins/mechanism/Network.py", line 56, in _reload_network
    nc = NetConf.get_default()
  File "/usr/lib/python3/dist-packages/blueman/main/NetConf.py", line 313, in get_default
    obj: "NetConf" = pickle.load(f)
EOFError: Ran out of input
 (0)
```

The same window opens if I go to "extensions" and activate the "Networking" extension (after having deactivated it).

Note that I did not observe any restrictions in the functionality of bluetooth itself, just the somewhat annoying error window every startup. But I also did not do any extensive tests with different bluetooth devices.

A full log of ` blueman-applet --loglevel debug` is available [here](https://gist.github.com/vinjana/8ca2e5f9ef0a337656c0a1e18ca4a559) (MACs and device names are obfuscated).

**Comment by infirit** [comment]
Try removing `/var/lib/blueman/network.state` and try again.

**Comment by cschramm** [comment]
If possible, please provide the `/var/lib/blueman/network.state` before removal. :smile: 

Did you update from an earlier Ubuntu release?

**Comment by vinjana** [comment]
O.k., the file is empty. I anyway renamed it and restarted `blueman-applet`, and :tada: -- no error message anymore. Perfect! That was easy. Thanks!

Indeed, the system was updated from Ubuntu 20.04 to Ubuntu 22.04.

**Comment by cschramm** [comment]
🤔 Surprising.

**Comment by cschramm** [comment]
After a quick look at the code, I don't see many chances for something like this. The best explanation is probably that the `pickle.dump` call failed. If you still have the modification time of the file, you could check at least .xsession-errors for something related at that time.

In any case, that file is not used in the current code (upcoming 2.4) anymore. 🙂

**Comment by vinjana** [comment]
Unfortunately, the error bugged me already some weeks and the `.xsession-errors` file for that time is lost.

**Comment by cschramm** [comment]
I think we cannot find any traces then. Anyway, we dump the file in 2.4, so the issue is most probably not relevant anymore.

**Comment by vinjana** [comment]
Thanks for you really swift support! Sorry that I couldn't provide you with more debugging information. At least from my side the issue could be closed.

**Comment by cschramm** [comment]
> we dump the file

No pun intended. :laughing:
