### ISSUE TITLE
MX Anywhere 2 mouse keeps disconnecting after 10 secs

### ISSUE THREAD

**Issue by ferthelet** [blueman-project/blueman#2006]
blueman: blueman-manager 2.3.5
BlueZ: version:        2.22
vermagic:       6.1.4-arch1-1 SMP preempt mod_unload 
Distribution: arch (archcraft)
Desktop environment: openbox

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I have followed the usual steps to search, pair and connect the mouse, the connected pop up shows up as well as the colored green, amber icons at the bottom right corner of the BT window manager; mouse shows it's connected by the steady white light at the bottom but wont move the pointer or do anything; after 10 sec or so, it disconnects completely

Note, mouse has been successfully connected to my Win 11 machine and works with no issues

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
> BlueZ: version: 2.22

That's obviously something else, but doesn't really matter here. :smile: 

Did you check kernel and bluetoothd logs? In successful cases I'd expect at least a kernel message from `input` and in this case probably something from `logitech-hidpp-device`.

**Comment by ferthelet** [comment]
Sorry, I was thinking I had provided a link to the config and logs... same behavior trying to pair an ms mouse which works  perfectly on another computer

extra/bluez 5.66-1 [installed]
extra/bluez-libs 5.66-1 [installed]
extra/bluez-utils 5.66-1 [installed]
extra/libldac 2.0.2.3-1 [installed]
extra/pulseaudio-bluetooth 16.1-3 [installed]
extra/sbc 2.0-1 [installed]
community/blueman 2.3.5-1 [installed]
community/hidapi 0.13.1-1 [installed]


[arch-openbox-buetooth-logs.txt](https://github.com/blueman-project/blueman/files/10426402/arch-openbox-buetooth-logs.txt)

**Comment by ferthelet** [comment]
I've noticed a couple of error just before it disconnects after 10 secs or so

1) 
Jan 16 06:55:21 fer-20u9005mus pulseaudio[967]: Could not find org.bluez.BatteryProviderManager1.RegisterBatteryProvid>

2) [    7.416062] Bluetooth: hci0: Malformed MSFT vendor event: 0x02

3)
= bluetoothd: profiles/deviceinfo/deviceinfo.c:read_pnpid_cb() Error reading PNP_ID value: Request attri..   68.529374
= bluetoothd: profiles/deviceinfo/dis.c:read_pnpid_cb() Error reading PNP_ID value: Request attribute ha..   68.529390
= bluetoothd: profiles/input/hog-lib.c:proto_mode_read_cb() Protocol Mode characteristic read failed: Re..   68.529419
= bluetoothd: profiles/input/hog-lib.c:report_read_cb() Error reading Report value: Request attribute ha..   68.529430
= bluetoothd: profiles/input/hog-lib.c:report_reference_cb() Read Report Reference descriptor failed: Re..   68.529442



[arch-openbox-btmon-log.txt](https://github.com/blueman-project/blueman/files/10426473/arch-openbox-btmon-log.txt)

**Comment by cschramm** [comment]
>     1. at boot it seems :: "solved" using experimental config
>        Jan 16 06:55:21 fer-20u9005mus pulseaudio[967]: Could not find org.bluez.BatteryProviderManager1.RegisterBatteryProvid>

Not a problem. pulseaudio is trying to use experimental BlueZ API there, which is disabled by default.

>     2. at boot it seems
>        [    7.416062] Bluetooth: hci0: Malformed MSFT vendor event: 0x02

From what I find on the Internets that's not a problem either as all reports mention that it does not affect Bluetooth functionality.

>     3. just when the connections drops...
> 
> 
> = bluetoothd: profiles/deviceinfo/deviceinfo.c:read_pnpid_cb() Error reading PNP_ID value: Request attri.. 68.529374 = bluetoothd: profiles/deviceinfo/dis.c:read_pnpid_cb() Error reading PNP_ID value: Request attribute ha.. 68.529390 = bluetoothd: profiles/input/hog-lib.c:proto_mode_read_cb() Protocol Mode characteristic read failed: Re.. 68.529419 = bluetoothd: profiles/input/hog-lib.c:report_read_cb() Error reading Report value: Request attribute ha.. 68.529430 = bluetoothd: profiles/input/hog-lib.c:report_reference_cb() Read Report Reference descriptor failed: Re.. 68.529442

A little concerning, especially as I find references on the Internets that report problems with Logitech mice with such error messages, but they all refer to BlueZ 5.55 (up to 5.58), nothing recent like your 5.66, and from the btmon log it clearly looks like they appear *after* the unexpected disconnect.

From the btmon log the disconnect seems to be trigger from your system at 68.169276.

Run `sudo dbus-monitor --system destination=org.bluez,interface=org.bluez.Device1` to monitor if any and which client requests the disconnect from bluetoothd.

**Comment by ferthelet** [comment]
Hi thanks for your comments, I did get rid of that battery msg but as you mentioned  no relation to this issue

Attaching logs from the bluetootctl and from dbus system as a whole, still reading through it since it's kin of long; I did it this way since adding dest and interface only output I was getting was like 4 lines (?)

Thank you again 

[bluetootctl-log.txt](https://github.com/blueman-project/blueman/files/10458509/bluetootctl-log.txt)
[dbus-monitor-system.txt](https://github.com/blueman-project/blueman/files/10458510/dbus-monitor-system.txt)

**Comment by cschramm** [comment]
Does not contain a disconnect call. There are not many other ways how the `< HCI Command: Disconnect` in btmon could get triggered by bluetoothd. It might get triggered by the kernel as well, though.

Enabling bluetoothd debug logging and checking it around the time of the disconnect could give some hints.
