### ISSUE TITLE
problem for connecting JBL Charge 4 to Linux

### ISSUE THREAD

**Issue by beaud37210** [blueman-project/blueman#2008]
blueman:2.3.4
BlueZ:5.64
Distribution:Linux Mint
Desktop environment:Cinnamon
Hello, I have a JBL Charge 4 which works fine, but since the Linux update replacing gnome bluetooth, I can't connect it anymore. It worked great before and it still works great on other devices. I have a Dell Latitude 5480.
Thanks very much!
* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->
Hello, I have a JBL Charge 4 which works fine, but since the Linux update replacing gnome bluetooth, I can't connect it anymore. It worked great before and it still works great on other devices. I have a Dell Latitude 5480.
Thanks very much!

**Comment by cschramm** [comment]
It's really hard to support without any problem statement.

**Comment by beaud37210** [comment]
the problem is that i can't connect my speaker

**Comment by cschramm** [comment]
The generic solution is to start blueman-manager, right-click on the desired device, and click the connect entry.

Note that 2.3.5 contains important UI fixes.
