### ISSUE TITLE
Acer Aspire E1-572G Bluetooth not working

### ISSUE THREAD

**Issue by JDogX** [blueman-project/blueman#201]
Running Linux Mint
Acer Aspire E1-572G Bluetooth not picking up devices nor is it dicoverable.
What should i do?

**Comment by rworkman** [comment]
https://github.com/blueman-project/blueman/blob/master/FAQ

**Comment by jeremyb31** [comment]
JDogX, can you start a topic at forums.linuxmint.com and I will help you there as this is not really a blueman problem
