### ISSUE TITLE
JBL Tune 760NC problem wit connecting (1. no detect device, 2. not show in audio output with first connecting)

### ISSUE THREAD

**Issue by AndreyUfa** [blueman-project/blueman#2011]
linux MInt 21.1
1. The headphones was not found during the search. After installing additional software (`blueberry` and `bluez-tools`) and executing commands, a search in `bluetoothctl` began to appear. I don't know exactly what helped.
2. When turn on the headset, it automatically connects, but there is no audio profile and it is not displayed in the list of output devices. After that, I disconnect it in the program and connect it, and then set audio profile and the device is visible in the output devices.

**Comment by cschramm** [comment]
Regarding the first point, well, it's hard to look into past issues without any traces.

Regarding the second, I recommend checking `journalctl --unit bluetooth.service` and `journalctl --user --unit pulseaudio.service` after the "incomplete" connection got established. Most probably something goes wrong there. I'm not sure if it's theoretically possible that the device establishes a connection without BlueZ trying to connect to its audio profiles.
