### ISSUE TITLE
Cannot mute/unmute Sandberg Bluetooth Office Headset Pro+

### ISSUE THREAD

**Issue by janstanka** [blueman-project/blueman#2014]
blueman: 2.3.4
BlueZ: 5.64-0ubuntu1
Distribution: Mint 21.1
Desktop environment: Cinnamon 5.6.7

In Linux Mint 21 Blueman replaces Blueberry. 
In my case I noticed malfunctional mic mute button on my Sandberg Bluetooth Office Headset Pro+ after upgrade to Mint 21. Mute button doesn't mute/unmute microphone anymore. With Blueberry in Mint 20 is OK.

**Comment by infirit** [comment]
Blueman doesn't provide a mute button so I'm assuming you are referring to your desktop audio mixer. This isn't handled by blueman but by the audio server (usually pulseaudio) and mixer so my suggestion is to report this on the mint forums.

**Comment by janstanka** [comment]
I mean mute button on headset - firstly it must be recognized by bluetooth manager (...I hope).
