### ISSUE TITLE
cant cant to any device through bluetooth,bluetooth not working

### ISSUE THREAD

**Issue by badalraj09** [blueman-project/blueman#2015]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by wlarch** [comment]
I am experiencing the same issue since the last update. 
I cannot find any devices nor connect to previously paired devices.

blueman : 2.3.5

Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

Desktop env. : cinnamon 5.6.7

**Comment by cschramm** [comment]
@wlarch: What exactly do you mean with "last update"? Are you reporting a regression in blueman 2.3.5 (vs. 2.3.4)? So your system did not change otherwise and does find devices, showing e.g. in bluetoothctl but not in blueman?

**Comment by wlarch** [comment]
@cschramm Thanks for the follow-up. It seems the problem has been resolved after a system reboot. I will get back here with more details if the problem repeats.
