### ISSUE TITLE
B450-XT II v1.05 headset not recognized as input device

### ISSUE THREAD

**Issue by jarrod843** [blueman-project/blueman#2019]
blueman: 2.3.2
BlueZ: 5.5.3
Distribution: Ubuntu 22.10
Desktop environment: Ubuntu Desktop

Blueman recognizes my headset , displays the correct model, and works for output, but does not seem to allow the system to select it as an input device. 

![image](https://user-images.githubusercontent.com/48655149/214898958-3cb0c900-9b67-45f3-b6fd-0fe31dd65112.png)

![image](https://user-images.githubusercontent.com/48655149/214899014-5c3f8060-a1d3-4b7b-9280-8ee293f2d0a2.png)

* [X ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
Unfortunately pulseaudio doesn't support bluetooth HSP/HFP which makes the microphone work. If you want to use the microphone the only option at the moment is to use HSP/HFP through ofono. If you need help with that the ubuntu forums is probably the best place to ask.

**Comment by cschramm** [comment]
To my understanding, ofono is not strictly required since pulseaudio 15 and Ubuntu 22.04 has something 16-ish, but in any case you have to switch the profile. Your sound settings how that it's set to A2DP which is just playback.

**Comment by infirit** [comment]
didn't know. Good. Hopefully changing profile in pavucontrol works for you @jarrod843
