### ISSUE TITLE
bluetooth keyboard cannot pair

### ISSUE THREAD

**Issue by Zorglub44** [blueman-project/blueman#2020]
blueman:2.3.5
BlueZ:
Distribution:Linux mint 21.1
Desktop environment: cinnamon

Hello everyone,

I can't connect a bluetooth keyboard to my linux PC, everything went well to connect a mouse but for the keyboard it asks me for a code which is not displayed to pair it.

https://i.postimg.cc/Y0m6WvQ3/ecran.jpg

I tried the keyboard under windows 10 and everything works well and the code (variable) to pair it is displayed well.
Thank you in advance for the feedback

**Comment by cschramm** [comment]
Totally unexpected, yes. This is clearly the dialog that is expected in case of legacy pairing for a device that has a display capacity. The device might be that old but it obviously does not have a display capacity.

You could capture the process up to that point with btmon and I'll have a look. Also check if `sudo journalctl -u bluetooth.service` shows anything related.
