### ISSUE TITLE
Support Snap.

### ISSUE THREAD

**Issue by rokejulianlockhart** [blueman-project/blueman#2025]
My rationale is available at https://github.com/safing/portmaster-packaging/issues/45#issue-961633238:~:text=packages%20for%20snap%20are%20able%20to%20be%20distributed%20without%20necessitating%20containerization.

In case this has already been completed, please know that https://snapcraft.io/search?q=blueman provides no relevant results.

I am thankful for any assistance.

**Comment by rokejulianlockhart** [comment]
Please reopen.

**Comment by cschramm** [comment]
See https://github.com/blueman-project/blueman/issues/2024#issuecomment-1512928662. I don't get the point of keeping this issue open.
