### ISSUE TITLE
my earbuds is not connecting to the laptop 

### ISSUE THREAD

**Issue by Payal8chauhan** [blueman-project/blueman#2028]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
Try again and provide the info in the issue template and read https://github.com/blueman-project/blueman/wiki/Troubleshooting

**Comment by Payal8chauhan** [comment]
i am  trying but it is not working

**Comment by Akashlatya** [comment]
i am  also trying but it is not working
