### ISSUE TITLE
What network packages will blueman work with?

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#203]
What networking packages will blueman work with in order to use a mobile phone as a network connection via bluetooth?

It looks like dhcp (only dhcp-3.x?) and networkmanager (is network-manager-applet required?), but are there others?

**Comment by cschramm** [comment]
blueman ships the NMPANSupport plugin which makes use of network-manager and the DhcpClient plugin which can use dhclient or dhcpd.

nm-applet is not required as we only use the dbus API of network-manager.
