### ISSUE TITLE
Sound peats bluetooth headset connected. no sound on headset but has sound on laptop

### ISSUE THREAD

**Issue by jefrey-creator** [blueman-project/blueman#2037]
E8:AB:FA:54:E0:41
public
SOUNDPEATS A6
SOUNDPEATS A6
0x240404
0x0000
audio-headset
yes
no
no
no
yes
0000110b-0000-1000-8000-00805f9b34fb Audio Sink
0000110c-0000-1000-8000-00805f9b34fb Remote Control Target
0000110e-0000-1000-8000-00805f9b34fb Remote Control
0000111e-0000-1000-8000-00805f9b34fb Handsfree
/org/bluez/hci0

**Comment by infirit** [comment]
The issue template isn't there to be ignored. 

blueman:
BlueZ:
Distribution:
Desktop environment:

Also https://github.com/blueman-project/blueman/wiki/Troubleshooting
