### ISSUE TITLE
 Bug in blueman-manager v2.3.5 

### ISSUE THREAD

**Issue by Sim4n6** [blueman-project/blueman#2042]
Hi,
I would like to report a little annoying bug in blueman-manager v2.3.5.
When I power on my Bluetooth audio headset, it's automatically recognized by blueman-manager and connects automatically while the sound remains being outputted from my laptop. But if I click on disconnect and then connect again from within blueman-manager, it works like a charm!

Some technical information was extracted from blueman-manager v2.3.5.

```
B3:59:7A:E7:32:B0
public
E45BT
E45BT
0x240404
0x0000
audio-headset
yes
yes
no
no
yes
0000110b-0000-1000-8000-00805f9b34fb Audio Sink
0000110c-0000-1000-8000-00805f9b34fb Remote Control Target
0000110e-0000-1000-8000-00805f9b34fb Remote Control
0000111e-0000-1000-8000-00805f9b34fb Handsfree
/org/bluez/hci0
```

I remain available for further details.

**Comment by cschramm** [comment]
Probably not related to blueman at all. Check bluetoothd and audio server logs for errors or warnings.

I remember similar issues where a reconnect was necessary to get audio working being discussed here recently, but I only found #2011 where the (counterfeit) device itself seems to have caused the issue.
