### ISSUE TITLE
Huawei freebuds 4, connecting problem

### ISSUE THREAD

**Issue by domis3000** [blueman-project/blueman#2046]
blueman:
BlueZ:5.64
Distribution: ubuntu 22.04.2 LTS
Desktop environment: Mate
I am unable to connect to Huawei freebuds 4.
Nothing works, reinstalling, restarting, i get a spinner for couple seconds then connection is canceled.
All other headphones are working, apple airpods, huawei am64, only freebuds 4 are having problems.

Please help

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Please provide a debug log of the connection (actually pairing?) attempt as described on the troubleshooting page.
