### ISSUE TITLE
Fix all error either audio or connection of Bluetooth in parrot os  or kali  

### ISSUE THREAD

**Issue by uic17bsc1008** [blueman-project/blueman#2051]
`sudo apt-get install pulseaudio`

create a blue.sh file add command give bellow to blue.sh file.
step - 1
`vi blue.sh`

step - 2
```
systemctl --user start pulseaudio.service
pulseaudio --start
```
run blue.sh file
`sh blue.sh`

It will fix all issue regarding audio issue or protocol issue or host issue.

**Comment by infirit** [comment]
Looks to me you need to talk to your distribution as this has nothing to do with blueman itself.
