### ISSUE TITLE
Bluetooth Sony WH-1000XM4 Headphones do not auto-connect consistently

### ISSUE THREAD

**Issue by adrummer354** [blueman-project/blueman#2054]
blueman: 2.3.5 
BlueZ: 5.64-0ubuntu1
Distribution: Linux Mint 21.1 
Desktop environment: Cinnamon 

Sony headphones will connect manually usually without issue. Headphones sometimes autoconnect but other times it will fail. Usually consistently connects after a system reboot. 

System Info: https://termbin.com/age3

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
Are you using blueman's autoconnect plugin or relying on BlueZ?
