### ISSUE TITLE
Missing Option To Turn Off Bluetooth Automatically

### ISSUE THREAD

**Issue by napperley** [blueman-project/blueman#2059]
blueman: 2.3.4
BlueZ: 5.64
Distribution: Linux Mint 21.1
Desktop environment: Cinnamon

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

No option is available in Blueman to automatically turn off Bluetooth at startup.

**Comment by infirit** [comment]
You can update `/etc/bluetooth/main.conf` and set `AutoEnable=false` under `[Policy]`

**Comment by napperley** [comment]
Updating a configuration file to disable Bluetooth isn't user friendly, and defeats the purpose of using Blueman in the first place.

**Comment by cschramm** [comment]
I'd argue that a frontend to  `/etc/bluetooth/main.conf` is out of blueman 's scope. It is rather something for a system settings UI. I agree that it would be a cool feature but honestly... it means managing a text-based configuration file with a vast amount of really complex options, some of them hardly ever used and compatibility mess. I absolutely do not see us building anything like that with the resources we have.
