### ISSUE TITLE
No way for HFP when JBL T510BT reconnects, but Ok with manual connect.

### ISSUE THREAD

**Issue by Maksons** [blueman-project/blueman#2060]
blueman: 2.3.5
BlueZ: 5.64
Distribution: Linux Mint 21.1
Desktop environment: Cinnamon 5.6.8

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

When first time connect to headphones or connect manualy HFP and A2DP profiles work good and could switch between profiles from Blueman-manager or in Sound settings.
Debug console output of manual connect:
```
blueman-applet 14.08.15 INFO     RecentConns:112 notify    : <Device.Device object at 0x7fabc83951c0 (blueman+bluez+Device+Device at 0x55cc5f0482f0)> 00000000-0000-0000-0000-000000000000
blueman-applet 14.08.17 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0/dev_74_2A_8A_66_82_B9 {'Connected': True}
blueman-applet 14.08.18 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0/dev_74_2A_8A_66_82_B9 {'ServicesResolved': True}
blueman-applet 14.08.19 DEBUG    Manager:86 _on_interface_added: Battery1 added to /org/bluez/hci0/dev_74_2A_8A_66_82_B9
```

When headphones reconnect (turned off and on) and Device Trusted/connection Accepted/Always Accept :
- no "BlueTooth input" in Sound settings
- volume control work incorrectly (like software volume limitation not real full range of headphones)
- switching to HPF do not work in Sound setting (both profiles shown, but always A2DP)
- switching to HFP from Blueman-manager report: "Failed to change profile to handsfree_head_unit" botomn red.
Debug console output:
```
blueman-applet 14.15.37 DEBUG    Base:60 do_g_properties_changed: /org/bluez/hci0/dev_74_2A_8A_66_82_B9 {'Connected': True}
```
It's look lie `ServicesResolved` do not happen this time. 
In syslog is extra line :
```
Apr  6 14:36:26 .... pulseaudio[5038]: org.freedesktop.DBus.Properties.Get /org/bluez/hci0/dev_74_2A_8A_66_82_B9/sep1/fd11 Volume failed: org.freedesktop.DBus.Error.InvalidArgs: No such property 'Volume'
```

Is it Blueman related or shoud I dig deeper to BlueZ ?

**Comment by cschramm** [comment]
Definitely not blueman, but I'd rather blame the audio server. pulseaudio is Linux Mint's default. You should check its logs and could possibly try PipeWire to see if results differ.
