### ISSUE TITLE
Connection Failed:  Protocol not available [bluetooth error in Linux (Parrot OS)]

### ISSUE THREAD

**Issue by darshakkanani** [blueman-project/blueman#2063]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by rafa7404** [comment]
he hecho de todo debe ser problema de hardware es una laptop hp envy 360

**Comment by cschramm** [comment]
"Protocol not available" is definitely not a hardware issue. Most probably you're just trying to connect an audio device without an appropriate sound server in place. Installing package `pulseaudio-module-bluetooth` could do the trick.

**Comment by linux-noob1** [comment]
> "Protocol not available" is definitely not a hardware issue. Most probably you're just trying to connect an audio device without an appropriate sound server in place. Installing package `pulseaudio-module-bluetooth` could do the trick.

I have installed package  "pulseaudio-module-bluetooth" haven't fixed the issue, any other suggestions been trying for over than 2 days now

**Comment by cschramm** [comment]
@linux-noob1: The designated way for Bluetooth audio support (if any) is distribution specific. Your distribution might use e.g. use a different audio server than pulseaudio, require extra steps to effectively enable the module (or a pulseaudio service in general), or just not include Bluetooth audio support at all.

**Comment by linux-noob1** [comment]
@cschramm Thanks for the reply i appreciate it, am running "Parrot OS 5.2 (Electro Ara)" i triple checked the hardware am using it's working perfectly so it's something to do with software but still cannot determine which is it

**Comment by cschramm** [comment]
Bluetooth audio is obviously out of scope for a penetration testing system. I actually fail to find which default audio server it's using, but the release notes of 5.2 lead me to suspect PipeWire. See e.g. https://wiki.debian.org/BluetoothUser/a2dp#PipeWire then if Parrot does not have any own resources.

**Comment by linux-noob1** [comment]
@cschramm Somehow it magically did work i been reinstalling all the services tried to upgrade my parrot os and i got it to connect perfectly now, to be honest with the amount of things i tried am not 100% sure what have got it fixed but last thing i have tried is your advice : 

i did run this : sudo apt install libspa-0.2-bluetooth=0.3.65-2~bpo11+1

and then did reboot the machine, tried to pair and connect my headset in cli with "bleutoothctl" and it worked like magic.

hope this help other people out there, and thanks for the advice you had me searching on the pipewire and ended up trying that and it worked.

**Comment by Thenathayalan** [comment]
For me I have installed the package " pulseaudio-module-bluetooth " and we need to start pulse audio manually by running the command " pulseaudio --start " and now try to connect your Bluetooth device I hope this works 🙂

**Comment by diveloper53** [comment]
> For me I have installed the package " pulseaudio-module-bluetooth " and we need to start pulse audio manually by running the command " pulseaudio --start " and now try to connect your Bluetooth device I hope this works 🙂

Thank you! I have the same issue, and it helped me!
