### ISSUE TITLE
Dynaudio Xeo2 bluetooth speakers incorrectly displayed with audio-headphones icon

### ISSUE THREAD

**Issue by AJPoulter** [blueman-project/blueman#2065]
blueman: 2.3.5-1
BlueZ: 5.66-1
Distribution:archlinux
Desktop environment: endeavouros

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

The blueman bluetooth manager incorrectly displays my [Dynaudio Xeo2 | Red active desktop speakers (discontinued model)](https://dynaudio.com/discontinued-models/xeo/xeo-2) as _audio-headphones_. The icon should be amended appropriately.

The device information (Icon) is incorrect.

> sudo bluetoothctl info CC:90:93:0A:CD:5F  
Device CC:90:93:0A:CD:5F (public)
	Name: Dynaudio Xeo 2 | Red  
	Alias: Dynaudio Xeo 2 | Red  
	Class: 0x00240418
	Icon: audio-headphones
	Paired: yes
	Bonded: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Audio Source              (0000110a-0000-1000-8000-00805f9b34fb)
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: Advanced Audio Distribu.. (0000110d-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	Modalias: bluetooth:v000ApFFFFdFFFF

**Comment by infirit** [comment]
> Icon: audio-headphones

This is what BlueZ (linux bluetooth subsystem) gives us so that what we use. We are not BlueZ, just a frontend using it.

**Comment by cschramm** [comment]
>  Class: 0x00240418

And this is what the device itself reports.

Audio, Rendering, Audio/Video, Headphones

https://btprodspecificationrefs.blob.core.windows.net/assigned-numbers/Assigned%20Number%20Types/Assigned_Numbers.pdf#10
