### ISSUE TITLE
Bluetooth is not searching/connecting devices

### ISSUE THREAD

**Issue by kha1mamatov** [blueman-project/blueman#2066]
blueman:2.3.5-2+b1
BlueZ:5.66
Distribution: Kali GNU/Linux Rolling 2023.1
Desktop environment: Gnome 44

I have a problem with bluetooth. I cannot open devices tab to search it opening adapters everytime. here is some logs...

bluetooth status:
`● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; preset: disabled)
     Active: active (running) since Sun 2023-04-16 16:11:02 +05; 10s ago
       Docs: man:bluetoothd(8)
   Main PID: 16056 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 8999)
     Memory: 980.0K
        CPU: 54ms
     CGroup: /system.slice/bluetooth.service
             └─16056 /usr/libexec/bluetooth/bluetoothd`

bluetooth adapter(RTL8821CE
![Screenshot from 2023-04-16 16-24-22](https://user-images.githubusercontent.com/108548358/232306597-32ceba5e-15c6-49cb-907c-83b9400386e2.png)
):
Bus 001 Device 004: ID 0bda:b00e Realtek Semiconductor Corp. Bluetooth Radio

**Comment by cschramm** [comment]
Do you mean the "Device" menu? It's for the currently selected device. As the list is empty, there can't be one. That's not where you start searching. Try the big search button instead.

In case you can't do anything useful, you might just not have a working adapter. As long as e.g. `bluetoothctl` doesn't show one, blueman can't do anything for you.

**Comment by Norparn** [comment]
I have the exact same problem, after install i found an adaptor! But I didn't marked it before the system was rebooted. 
How remove and reactivate the bluetoth adapter?
The system says I do not need any new drivers!
/Nor

**Comment by cschramm** [comment]
@Norparn: You do not have an adapter e.g. in `blueman` or `bluetoothctl` but you do see one e.g. with `lsusb`  or `lspci`? No driver picked it up properly then.

**Comment by Norparn** [comment]
Tnx for answer, to day when I started my laptop I tried to connect to my
Bluetooth with my mouse. Behold they made contact and I make it permanent.
Reboot seems to solved the problem.
/ Nor

Den mån 24 apr. 2023 08:38Christopher Schramm ***@***.***>
skrev:

**Comment by Shyamvalliattu** [comment]
I have the exact same problem in my laptop. Do anyone have a permanent solution to it ?

**Comment by donottellmetonottellyou** [comment]
I am having this problem, using Linux Mint 21.1. Device is greyed out.

**Comment by Manukula** [comment]
so how do u fix the bluetooth not connecting problem, should it be something you must download in linix mintor what
