### ISSUE TITLE
Can't conect to smartphone for audio profile

### ISSUE THREAD

**Issue by blackshark1213** [blueman-project/blueman#2068]
blueman: install 
BlueZ: install 
Distribution: Kali GNU/Linux Rolling x86_64
Desktop environment: xfce 4.18

Connection Failed: br-connection-profile-unavailable 

while connecting to smartphone 
plz help  me to resolve this problem

**Comment by cschramm** [comment]
Most probably you're trying to connect an audio device without an appropriate sound server in place. If you're using pulseaudio, installing package `pulseaudio-module-bluetooth` could do the trick.

**Comment by marwank270** [comment]
Hi, I have the same problem since a month, same configuration but with a headseat and everything I tried didn't changed anything, tried to install `pulseaudio-module-bluetooth` and it's already in place

**Comment by blackshark1213** [comment]
>

**Comment by blackshark1213** [comment]
> Most probably you're trying to connect an audio device without an appropriate sound server in place. If you're using pulseaudio, installing package `pulseaudio-module-bluetooth` could do the trick.

pulseaudio-module-bluetooth 
Already it install in my system , but can't fix problem

**Comment by cschramm** [comment]
You might be using a different sound server like PipeWire, your pulseaudio installation might have some issue and not work properly, etc. ...

Things to try include checking `systemctl status --user pulseaudio.service` and looking for media endpoint registrations (from the user's pulseaudio daemon) in `sudo journalctl -u bluetooth.service`.
