### ISSUE TITLE
blueman.rules are not installed when meson is used

### ISSUE THREAD

**Issue by tpgxyz** [blueman-project/blueman#2073]
blueman: 2.3.5
BlueZ:
Distribution: OpenMandriva cooker
Desktop environment:

* [x ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Hi, looks like [blueman.rules](https://github.com/blueman-project/blueman/blob/main/data/configs/blueman.rules) file is not installed when using meson as a build system.

**Comment by infirit** [comment]
Good catch, should be fixed with #2074
