### ISSUE TITLE
Request to be a Traditional Chinese reviewr on Weblate

### ISSUE THREAD

**Issue by brianhsu** [blueman-project/blueman#2076]
blueman: 2.3.5
BlueZ:
Distribution:
Desktop environment:

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Hi, I'm a long time blueman user. The Traditional Chinese translation hasn't been maintained for a long time. I've update it on Weblate and almost done, but I would also like to request to be a Traditional Chinese reviewer on Weblate if that's possible. 

It will make proof reading much easier on Weblate, as I could mark a translation as approved and track if any new translations in Traditional Chinese need proof reading.

Thanks.

**Comment by cschramm** [comment]
Sure. I already took a quick look at it on Weblate but got lost. :see_no_evil:

**Comment by infirit** [comment]
Create a reviewers team for traditional Chinese and made you member @brianhsu . Also enabled reviews globally. 

@brianhsu can you check you are able to review and approve strings?

**Comment by brianhsu** [comment]
Hi, @infirit @cschramm Thanks for your help, confirmed that I could approve Traditional Chinese translations now. Will close this ticket, thanks.
