### ISSUE TITLE
blueman completely non functional

### ISSUE THREAD

**Issue by russ-burkert** [blueman-project/blueman#2079]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

New install of Linux Mint 21.1 desktop.  All patches have been applied.  Blueman does nothing.  It finds zero bluetooth devices using Adapter|search.  After a few seconds the message bar says "Resource not ready..."
bluetoothctl says this:
bluetooth]# list
Controller 7C:5C:F8:76:14:1F russ-550-227c [default]
[bluetooth]# show 7C:5C:F8:76:14:1F
Controller 7C:5C:F8:76:14:1F (public)
	Name: russ-550-227c
	Alias: russ-550-227c
	Class: 0x00000000
	Powered: no
	Discoverable: yes
	DiscoverableTimeout: 0x00000000
	Pairable: yes
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: Message Access Server     (00001132-0000-1000-8000-00805f9b34fb)
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: Message Notification Se.. (00001133-0000-1000-8000-00805f9b34fb)
	UUID: Phonebook Access Server   (0000112f-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: OBEX Object Push          (00001105-0000-1000-8000-00805f9b34fb)
	UUID: IrMC Sync                 (00001104-0000-1000-8000-00805f9b34fb)
	UUID: OBEX File Transfer        (00001106-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (00005005-0000-1000-8000-0002ee000001)
	UUID: Handsfree Audio Gateway   (0000111f-0000-1000-8000-00805f9b34fb)
	UUID: Audio Source              (0000110a-0000-1000-8000-00805f9b34fb)
	UUID: Headset                   (00001108-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d0540
	Discovering: no
	Roles: central
	Roles: peripheral
[bluetooth]# devices
Device 4C:AB:4F:90:E8:30 4C-AB-4F-90-E8-30
[bluetooth]# info 4C:AB:4F:90:E8:30
Device 4C:AB:4F:90:E8:30 (public)
	Alias: 4C-AB-4F-90-E8-30
	Paired: no
	Trusted: yes
	Blocked: no
	Connected: no
	LegacyPairing: no
[bluetooth]# pair 4C:AB:4F:90:E8:30
Attempting to pair with 4C:AB:4F:90:E8:30
Failed to pair: org.bluez.Error.AuthenticationFailed
[bluetooth]# connect 4C:AB:4F:90:E8:30
Attempting to connect to 4C:AB:4F:90:E8:30
Failed to connect: org.bluez.Error.Failed Input/output error

**Comment by russ-burkert** [comment]
what does 'not planned' mean?

**Comment by cschramm** [comment]
You're welcome to provide at least a problem statement. There's nothing that we could help you with otherwise.

**Comment by russ-burkert** [comment]
Hmmm...the title of this ticket seems like a clearly worded problem to me..."[blueman completely non functional].  When I run the Bluetooth Manager app, I should be able to search for visible bluetooth devices and pair with those devices.  The Search button on the Bluetooth Devices dialog finds no BT devices, even when I have bluetooth headphones inches away in pairing mode.  My original post shows the output from running the bluetoothctl app at the command line

**Comment by cschramm** [comment]
Ha, it looks like you hid most of your original post in comment tags. I edited it to make it visible.

As you showed by unsuccessfully trying with `bluetoothctl`, your problem does not actually seem to have something to do with blueman.

You're clearly having a severe problem with your controller. I'd check `bluetooth.service` logs and `dmesg` for traces.

**Comment by russ-burkert** [comment]
I looked at syslog and journalctl results and all I can tell is 'there is  problem'.  So, I'm going to suspend further attempts and go with an external USB dongle and see what happens.  I suspect my HP PC is just to old for these modern OSs

**Comment by EspressoMan** [comment]
I'm also running Linux mint 21 on my 4 year old Lenovo Thinkpad. I have my late model pixel phone sitting beside my notebook. Bluetooth is enabled on both. Yet the laptop cannot discover the phone and the phone cannot see the laptop. This isn't necessarily a blueman issue but I don't recall experiencing this issue with previous versions of Linux Mint. @russ-burket isn't the only one experiencing this issue...
