### ISSUE TITLE
Bluetooh Connection Failed: No audio endpoints registered

### ISSUE THREAD

**Issue by shaswata-26** [blueman-project/blueman#2082]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by shaswata-26** [comment]
when i start bluetooth service then found Connection Failed: No audio endpoints registered error .can any one tell me about this

**Comment by cschramm** [comment]
Your audio server does not handle Bluetooth devices. You're typically just lacking some package.
