### ISSUE TITLE
Alexa echo is not visible in the searched devices. Unabe to connect

### ISSUE THREAD

**Issue by yashk0311** [blueman-project/blueman#2085]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by yashk0311** [comment]
Please fix this bug asap. It used to work 2 days back, but now it is not connecting to the echo (i clicked on remove device, when it was paired) but now it is not visible only.

**Comment by cschramm** [comment]
See https://github.com/blueman-project/blueman/issues/817#issuecomment-1145683735
