### ISSUE TITLE
cannot open blueman-manager through the applet right-click menu

### ISSUE THREAD

**Issue by playriven** [blueman-project/blueman#2090]
blueman:2.3.5
BlueZ:5.66 
Distribution:archlinux
Desktop environment:wayfire

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/blueman/main/DBusProxies.py", line 52, in call_finish
    proxy.call_finish(resp)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)

**Comment by infirit** [comment]
You probably are missing the DISPLAY variable when blueman manger starts from the tray. See https://github.com/blueman-project/blueman/issues/1598#issuecomment-922962739
