### ISSUE TITLE
Blueman spams the application toobar spam

### ISSUE THREAD

**Issue by stevef9432203** [blueman-project/blueman#2096]
blueman: 2.3.5
BlueZ:
Distribution: fedora 38
Desktop environment: mate

Using A bluetooth mouse the application bar gets  filled with mx mouse  application popups.  We need a way to autoclose  the notice window

**Comment by cschramm** [comment]
What are "mx mouse application popups"?

Regarding desktop notifications, blueman expects timeouts to be supported and mate-notification-daemon does have support.

**Comment by stevef9432203** [comment]
Like  Thus
![MxSpaming](https://github.com/blueman-project/blueman/assets/2072446/2d86cc05-959d-4716-b55c-64acbb9755ca)

**Comment by cschramm** [comment]
That looks like our fallback. Is your notification daemon fine?

`dbus-send --session --print-reply --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.GetServerInformation`
