### ISSUE TITLE
unable to connect paired bluetooth devices in xubuntu 23.01

### ISSUE THREAD

**Issue by dualboot91** [blueman-project/blueman#2098]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

when i attempt to pair via console i get the following dialogue:

[bluetooth]# pair 20:74:CF:48:78:D9
Attempting to pair with 20:74:CF:48:78:D9
[CHG] Device 20:74:CF:48:78:D9 Connected: yes
[CHG] Device 20:74:CF:48:78:D9 Bonded: yes
[CHG] Device 20:74:CF:48:78:D9 UUIDs: 00001108-0000-1000-8000-00805f9b34fb
[CHG] Device 20:74:CF:48:78:D9 UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device 20:74:CF:48:78:D9 UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device 20:74:CF:48:78:D9 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device 20:74:CF:48:78:D9 UUIDs: 0000111e-0000-1000-8000-00805f9b34fb
[CHG] Device 20:74:CF:48:78:D9 ServicesResolved: yes
[CHG] Device 20:74:CF:48:78:D9 Paired: yes
Pairing successful
[CHG] Device 20:74:CF:48:78:D9 ServicesResolved: no
[CHG] Device 20:74:CF:48:78:D9 Connected: no
--------------------------------------------------------------------------------

the gui says the connection profile is not available.  the problem occurs with every bluetooth device and with both onboard and external adapters.

**Comment by infirit** [comment]
You are probably missing a soundserver like PulseAudio.
