### ISSUE TITLE
Bluetooth device will not show up in Linux mint 21.2 cinnamon

### ISSUE THREAD

**Issue by jouletrix** [blueman-project/blueman#2107]
blueman:
BlueZ:
Distribution:
Desktop environment:
I was able to Connect my Device before but later i was not able to so i reinstalled the bluetooth now the device will not show
* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by jouletrix** [comment]
I was able to Connect my Device before but later i was not able to so i reinstalled the bluetooth now the device will not show

**Comment by cschramm** [comment]
You are searching for devices and not discovering the one you are looking for although it is pairable and you are able to discover it from other systems and you are able to discover other devices from the same system at the same time? What kind of device is it? Did you try bluetoothctl?
