### ISSUE TITLE
Why? Why is there no connection, yet there is clearly a connection? Please.

### ISSUE THREAD

**Issue by lordofthecringe** [blueman-project/blueman#2108]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Sorry if I'm not going about this exactly the right way but it's my first time here and I'm no expert... trying to connect bluetooth headset and it is being detected and pairing/connecting fine, but for some reason just doesn't work. The sound continues playing through the speakers. What am I missing, besides a more sound knowledge of these tools? Please request any details I've left out here if you're responding, thanks.

**Comment by cschramm** [comment]
The connection is handled by your audio server. Something's really broken there if it does connect the device but not provide it as an audio device. If it does provide it, but just not switch over to it as the default sink, that might be expected behavior.
