### ISSUE TITLE
Wireless keyboard can't be detected. Using opensuse with i3wm

### ISSUE THREAD

**Issue by mapi100** [blueman-project/blueman#2109]
blueman: blueman-adapters
BlueZ:
Distribution: opensuse tumbleweed
Desktop environment: i3wm

When searching for a new adapter in blueman-adapters, the searching bar keeps searching forever. I'm sure that my Bluetooth wireless keyboard works, since I can connect it to other devices that support Bluetooth as well.

Thank you for your time.

**Comment by cschramm** [comment]
Can you see it when showing unnamed devices from the "View" menu or e.g. in bluetoothctl. Could be #1954.
