### ISSUE TITLE
GSettings related improvements

### ISSUE THREAD

**Issue by cschramm** [blueman-project/blueman#211]
Follow up to #204 (also https://github.com/blueman-project/blueman/pull/204#issuecomment-77294035)

- [ ] Bind more widgets to keys with the bind_to_widget function.
- [ ] Look at the apply code in the services plugins. For example most of the Transfer ui options are already instant apply but still make the button active. Use use instant apply/checks plus move some code to the close button to remove the apply button?
- [ ] Move NetConf to config instead of using /var/lib/blueman/network.state

**Comment by infirit** [comment]
I looked at the apply code and there is not much we can do here. Also we can not move NetConf to gsettings as mechanism runs as root not the user that runs the gui. Binding more widgets is nice but not something really important.

My suggestion then is to close this as two out of the three are solved/not possible.
