### ISSUE TITLE
bluethoo automatic connection bug

### ISSUE THREAD

**Issue by AlexAR93** [blueman-project/blueman#2112]
Hello, I currently use linux mint cinnamon, but I have the problem that when I connect a headset automatically, it connects but does not detect it as an audio output until I manually disconnect and connect it. The truth is that it is quite annoying to have to wait for it to connect, then disconnect it and connect it manually so that it detects it as an audio output. From already thank you very much.

**Comment by cschramm** [comment]
Your audio server handles the connection. Should be pulseaudio in your case.
