### ISSUE TITLE
cannot established BT connection over GUI

### ISSUE THREAD

**Issue by antondrroid** [blueman-project/blueman#2118]
blueman:yes
BlueZ:
Distribution:debian 12
Desktop environment:xfce

1.I had tried to connect my devices over BTmanager, it has device connected, then (after 2-5 seconds) disconnected, and after few attempts it  refused even to pair and to trust, (all 3 devices - keyboard, mouse and headphones) I tried about 30 min and make about 30 attempts.

while by CLI over blutothctl cmd it has all 3 paired, trusted & connected, sometimes from the first attempt, sometimes 2nd or 3rd.

2.i had wrote the data of all the connected devices into file /etc/bluetooth/hcid.conf, (4 items -2 mouses, 1 kbrd, 1 HdPhones), then i commented 2 of them (1 headphones and 1 mouse) and rebooted.
I had expected, that after boot will be work 1 KBrd + 1 mouse, but work KB only, while mouse doesn't, i had wait 5 min,  then i had used other wireless mouse to reconnect this mouse.
Of coarse, i had tried over GUI at first, but mouse didn't connected, while the signs of paired and trusted was in it's icon.

then i had used the CLI, and mouse was connected from the 1st attempt, i even not used pair and trust this time.

3. in spite of  at config file it was commented 2 devices, on the BTmanager panel there was all 4 devices icon, (and only one of them had green, red, and blue stripes, showing connection quality.) So may be have one more place where data keep, but this is not documented in installation manual on   github.com/blueman-project

5. if need some logs, i can to add, just suggest me, please, where they are placed on.

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
`hcid.conf` is a thing of a long forgotten past.

If you encounter reproducible situations where you can pair or connect a device with `bluetoothctl` but the same step fails in blueman, please provide the blueman debug output of that attempt.

**Comment by antondrroid** [comment]
if you can advice, where is output of blueman has stored in system, i can send it.  i had send dmesg already.

and if hcid.conf is absoleted, may be can you advice, which config file i need to use now?

**Comment by antondrroid** [comment]
if you can advice, where is output of blueman has stored in system, i can send it.  i had send dmesg already.

and if hcid.conf is absoleted, may be can you advice, which config file i need to use now?

**Comment by cschramm** [comment]
See "Debugging blueman" on the troubleshooting page that you consulted earlier.

> and if hcid.conf is absoleted, may be can you advice, which config file i need to use now?

To do what?

**Comment by antondrroid** [comment]
to comment items, which i want temporarily to disable
