### ISSUE TITLE
New version?🤔 

### ISSUE THREAD

**Issue by wuch-g2v** [blueman-project/blueman#2120]
https://github.com/blueman-project/blueman/compare/2.3.5...main shows +150 commits since last release which was more than year ago.
Do  you have any plans to release new version soon? 🤔

**Comment by cschramm** [comment]
Absolutely, yes. See milestone 2.4. I personally just do not find much time for the project at the moment.

**Comment by kloczek** [comment]
gentle ping .. 🤔

**Comment by kloczek** [comment]
This ticker is not completed.

**Comment by infirit** [comment]
While I appreciate the interest in the project it doesn't make sense to have this open. When the 2.4 milestone is complete a new release is likely.
