### ISSUE TITLE
Adapter Preferences popup window not closing

### ISSUE THREAD

**Issue by icedwater** [blueman-project/blueman#2126]
blueman: 2.1.2-1ubuntu0.3
BlueZ: 5.53-0ubuntu3.6
Distribution: Ubuntu 20.04.6 LTS
Desktop environment: i3

I had a similar issue to #2125 with the Adapters popup window not closing, though it might have a different cause.

Logs are readable at http://ix.io/4EhD.

Clicking Adapter -> Preferences spawns a popup window as a separate process (`/usr/bin/python3 /usr/bin/blueman-adapters`) and I can kill that without affecting the applet itself, but there is no way from within the dialog to close it, whether Ctrl-C, Ctrl-Q, Ctrl-W, or Esc.

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by cschramm** [comment]
Accelerators got added in #1982.

**Comment by icedwater** [comment]
Thanks! I guess I just need to build a more recent version then.
