### ISSUE TITLE
Keyboard effect of a hanging key

### ISSUE THREAD

**Issue by DrStrom66** [blueman-project/blueman#2130]
blueman: 2.3.5
BlueZ:5,64-0ubuntu1
Distribution: Mint 21.2
Desktop environment: cinnamon

 I have a iClever IC-BK10 Keyboard. Sometimes it is like a key is hanging or bouncing , that letter is typed many times. Since I use that keyboard also for two windows laptops , I know that nothing like this is happen there. What could be the solution?

**Comment by cschramm** [comment]
You could check input events with something like `xev` and the Bluetooth stream with something like `btmon` to see if the glitch is visible in the Bluetooth data and in the input system. The bluetoothd logs could also provide some information on the matter.
