### ISSUE TITLE
Bluetooth Problem (Cannnot connect)

### ISSUE THREAD

**Issue by SmartEasyTechChannel** [blueman-project/blueman#2131]
There is problem with Bluetooth connection after resting many time not happened any thing.
*) Cannot find Device
*) After finding Device can not connect with 
*) By luck connected with device but then cant change device profile

**Comment by Danideoliveiras2** [comment]
After finding device, can't connect with!

**Comment by houseinbox** [comment]
Linux Mint Cinnamon
Bluetooth não deteta dispositivos e quando deteta não comunica. Algum problema com blueman noutros utilizadores?
