### ISSUE TITLE
how can i show the battery of my bluetooth device

### ISSUE THREAD

**Issue by zeyadelkholyttt** [blueman-project/blueman#2133]
blueman: latest
BlueZ: latest
Distribution: void
Desktop environment: kde

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--
i just asking how can i check the battery of my bluetooth device

->

**Comment by infirit** [comment]
Latest isn't very helpful. Regardless the latest stable release will show battery percentage in blueman-manager and in the connection notification. This however depends wether it's exposed over the BlueZ dbus api.

**Comment by zeyadelkholyttt** [comment]
> Latest isn't very helpful. Regardless the latest stable release will show battery percentage in blueman-manager and in the connection notification. This however depends wether it's exposed over the BlueZ dbus api.

i found where i can get it in the panel but i will be very thx if i can get it in the kde bar

**Comment by cschramm** [comment]
If upower picks up the device (check e.g. `upower -e`), desktops typically provide some kind of battery applet for it.
