### ISSUE TITLE
Fedora 38 - Blueman fills log with messages 

### ISSUE THREAD

**Issue by didierga** [blueman-project/blueman#2134]
blueman: blueman-2.3.5-3.fc38.x86_64 blueman-nautilus-2.3.5-3.fc38.noarch
BlueZ: bluez-5.69-1.fc38.x86_64
Distribution: Fedora 38 Workstation
Desktop environment: gnome-shell-44.4-1.fc38.x86_64

blueman fills syslog with these two messages:
`sept. 08 02:07:12 desktop nautilus[28067]: TypeError: BluemanSendtoExtension.get_background_items() missing 1 required positional argument: 'file'`
`sept. 08 02:07:12 desktop nautilus[28067]: TypeError: BluemanSendtoExtension.get_file_items() missing 1 required positional argument: 'files'`

**Comment by cschramm** [comment]
nautilus 0.43 changes the extension interface. Can you test #2135? You could just apply the changes to your `/usr/share/nautilus-python/extensions/nautilus_blueman_sendto.py`.

**Comment by didierga** [comment]
Fix in https://github.com/blueman-project/blueman/pull/2135 works fine.
Many thanks for tour prompt answer.
