### ISSUE TITLE
problem with playing headphones redme bugs 3 pro

### ISSUE THREAD

**Issue by saber716rus** [blueman-project/blueman#2170]
blueman:2.3.5+mint1+faye
BlueZ: 5.66-1
Distribution: lmde6
Desktop environment:cinnamon

the problem is manifested by the loss of sound in one of the headphones, by long switching or restarting the PC. The sound is restored.
url hw-probe https://linux-hardware.org/?probe=ea047f0b15

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by serainox420** [comment]
Do you use pulseaudio and blueman?
If so, make sure pulseaudio-module-bluetooth is installed.

**Comment by cschramm** [comment]
Never heard of such an issue. Did you try restarting your sound server or re-connecting the device?

**Comment by saber716rus** [comment]
> Never heard of such an issue. Did you try restarting your sound server or re-connecting the device?

if I reboot, the problem disappears for a while, but then it reappears.

**Comment by saber716rus** [comment]
> Do you use pulseaudio and blueman? If so, make sure pulseaudio-module-bluetooth is installed.

just installed it, I will monitor the problem.

**Comment by cschramm** [comment]
Not sure, but I think LMDE6 uses PipeWire, not pulseaudio, so the package is pointless (also, if it was not installed and pulseaudio would be your sound server, connecting the device as an audio sink would not have worked anyway).

Restarting your sound server should probably be something along `systemctl --user restart wireplumber pipewire pipewire-pulse`, re-connecting the device would be disconnect and connect e.g. in blueman.
