### ISSUE TITLE
Cannot transfer a file to a blueman laptop

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#219]
Using bluez-5.25 and obex-data-server-0.4.6

When iniating the transfer on the remote laptop, I get the message "unable to discover services on blueman laptop" and the transfer does not initiate.

It sort of looks as though the laptop is not paired, but blueman shows it as paired.

From bluetoothd:

bluetoothd[10108]: src/adapter.c:connected_callback() hci0 device C4:46:19:E9:C1:EC connected eir_len 5
bluetoothd[10108]: src/adapter.c:dev_disconnected() Device C4:46:19:E9:C1:EC disconnected, reason 3
bluetoothd[10108]: src/adapter.c:adapter_remove_connection() 
bluetoothd[10108]: plugins/policy.c:disconnect_cb() reason 3
bluetoothd[10108]: src/adapter.c:bonding_attempt_complete() hci0 bdaddr C4:46:19:E9:C1:EC type 0 status 0xe
bluetoothd[10108]: src/device.c:device_bonding_complete() bonding (nil) status 0x0e
bluetoothd[10108]: src/device.c:device_bonding_failed() status 14
bluetoothd[10108]: src/adapter.c:resume_discovery() 

from blueman-manager:

row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:261)
row update event Connected 0 
_________
Generate (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:165)
laptop 
_________
level_setup_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:322)
animating down

**Comment by cschramm** [comment]
#84
