### ISSUE TITLE
BM30X Bluetooth Mouse reconnection issues

### ISSUE THREAD

**Issue by Syewm** [blueman-project/blueman#2190]
blueman:2.3.5
BlueZ:5.64
Distribution: Linux Mint 21.2
Desktop environment:Xfce

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

When trying to trust and connect my BM30X bluetooth mouse device through Blueman it looses connection after some time and then fails to reconnect. It says "device disconnected", then "device connected" then "device disconnected" again.
Changing blueman config or bluetooth config files never fixed anything for me, i've been searching for solution for months and the only fix i have found for now is connecting through blueoothctl manually in terminal:

"bluetoothctl
scan on
pair DC:2C:26:D3:14:18
trust DC:2C:26:D3:14:18"

now when my bluetooth mouse looses connection it simply reconnects again without disconnecting after connection.

Please find solution so i don't have to use terminal every time i want to connect my mouse. Thank you for your work

**Comment by cschramm** [comment]
You're saying when you pair via bluetoothctl the device stays connected but when you pair via blueman it does not? That's very surprising.

Does bluetoothd give you any logs on the disconnects?

**Comment by Syewm** [comment]
When i pair through the Blueman it fails to reconnect when the device goes to sleep. If i do the same thing through terminal using bluetoothctl it always reconnects when the device comes back from sleep.

When i type bluetoothd in terminal it gives me:

"D-Bus setup failed: Connection ":1.134" is not allowed to own the service "org.bluez" due to security policies in the configuration file"

**Comment by cschramm** [comment]
bluetoothd logs should be browsable with `sudo journalctl -u bluetooth.service`.
