### ISSUE TITLE
Shokz OpenRun Pro show as "miscellaneous" rather than "headphones"

### ISSUE THREAD

**Issue by AdamBullen** [blueman-project/blueman#2203]
blueman: 2.3.5
BlueZ: 5.64
Distribution: Linux Mint 21.2
Desktop environment: Cinnamon

I connect my new Shokz OpenRun Pro headset which works well, pair / trust / auto reconnect all work. But the new headset shows as "miscellaneous" rather than "headphones". I have other headphones (Microsoft Modern Wireless Headset) that are connected and show as "headphones".

UUID's from blueman of the Shokz
> 00001100-d102-11e1-9b23-00025b00a5a5 Proprietary
00001800-0000-1000-8000-00805f9b34fb Generic Access
00001801-0000-1000-8000-00805f9b34fb Generic Attribute
0000180f-0000-1000-8000-00805f9b34fb Battery Service
0000fe2c-0000-1000-8000-00805f9b34fb Unknown

vs from the microsoft headset
>00001101-0000-1000-8000-00805f9b34fb Serial Port
00001108-0000-1000-8000-00805f9b34fb Headset
0000110b-0000-1000-8000-00805f9b34fb Audio Sink
0000110c-0000-1000-8000-00805f9b34fb Remote Control Target
0000110d-0000-1000-8000-00805f9b34fb Advanced Audio
0000110e-0000-1000-8000-00805f9b34fb Remote Control
0000111e-0000-1000-8000-00805f9b34fb Handsfree
00001124-0000-1000-8000-00805f9b34fb Human Interface Device Service (HID)
00001200-0000-1000-8000-00805f9b34fb PnP Information
12a24d2e-fe14-488e-93d2-173c63010000 Proprietary
543cea22-ad9c-4254-a47e-5e1ae25a40bd Proprietary

**Comment by cschramm** [comment]
Most probably that's just what the device indicates by its device class. Check "Info" from the device's right-click menu.

**Comment by AdamBullen** [comment]
> Most probably that's just what the device indicates by its device class. Check "Info" from the device's right-click menu.

Added to the original post

**Comment by cschramm** [comment]
The class property is relevant, not the UUIDs.

**Comment by AdamBullen** [comment]
> The class property is relevant, not the UUIDs.

Shokz class: 0x000000
Microsoft headset class: 0x240418

So the Shokz don't report their class I guess.

**Comment by cschramm** [comment]
Ah, sorry, it's an LE device, so the Appearance property is used instead.

It looks like https://github.com/blueman-project/blueman/blob/8f641749f0c6fc0bd0e97a5929b773c32a47a5a6/blueman/DeviceClass.py#L167-L228 needs a heavy update. Compared to the current Assigned Numbers document it completely lacks categories 19 - 43 and 55. I guess the value is 0x0942.

**Comment by infirit** [comment]
Looks like they provide a yaml file for them, https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/core/appearance_values.yaml
