### ISSUE TITLE
Add gnome-bluetooth support

### ISSUE THREAD

**Issue by kacperpaczos** [blueman-project/blueman#2212]
blueman: 2.3.5
BlueZ:
Distribution: Linux Mint 
Desktop environment: Cinnamon

AirPods on Gnome Bluettoth which use: https://gitlab.gnome.org/GNOME/gnome-bluetooth work better than blueman.

Consider add alternative backend.

**Comment by cschramm** [comment]
Not an option, but please elaborate on "work better".

**Comment by labbatt50** [comment]
When I Open it ***everything*** is greyed out.
Restart to conect, same issue.
Only option is Help and Quit.

![Screenshot_Bluetooth](https://github.com/blueman-project/blueman/assets/37849078/715b3bbb-67df-4ad5-acfc-081d0b572b91)

**Comment by SzymonPaczos** [comment]
Hello everyone

Kacper Paczos has observed an issue with pairing a laptop running Linux Mint Cinnamon with Apple Air Pods Pro 2. 
While both devices can be successfully paired, they automatically disconnect shortly afterward. Despite the pairing, establishing a connection is not possible. 

Please suggest troubleshooting steps to help identify the root cause of the issue.

**Comment by cschramm** [comment]
Audio connections are handled by the system's audio server, usually pulseaudio or PipeWire. Its logs (and maybe bluetoothd's) might already give a hint.

**Comment by cschramm** [comment]
pulseaudio logs should be `journalctl --user -u pulseaudio.service` and BlueZ' `sudo journalctl -u bluetooth.service` on your system.

**Comment by cschramm** [comment]
I did not get that you're the off-topic one, probably not on Linux Mint then...

I'm not really sure what's going in this issue thread, but it seems like @SzymonPaczos reported an issue with audio connections on behalf of @kacperpaczos who opened the issue with no information on the actual problem and @labbatt50 jumped in with a completely different issue and now tries to follow my hints for @SzymonPaczos / @kacperpaczos.

@labbatt50, please open a new issue if you want us to look into that. I don't understand why you ended up in this thread.

**Comment by labbatt50** [comment]
Christopher,

No, Mint was ages ago. PCLinuxOS Xfce now.
I will login later and try to find the correct thread.

Cheers and Happy New Year
L

Get Outlook<https://aka.ms/o0ukef>
________________________________
