### ISSUE TITLE
bluetooth keyboard and bluetooth mouse drop connection Ubuntu 23.04

### ISSUE THREAD

**Issue by hubbertsmith** [blueman-project/blueman#2213]
blueman: 2.3.5
BlueZ:
Distribution: ubuntu 23.04
Desktop environment: Mate

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by cschramm** [comment]
I'd first check `journalctl -u bluetooth.service` for hints on the connection drop.

**Comment by hubbertsmith** [comment]
still drops, about once per day
