### ISSUE TITLE
Controller problem

### ISSUE THREAD

**Issue by aelindos** [blueman-project/blueman#2225]
hello
im new in linux mint and tried to play with my xbox wireless controller but its disconnecting the whole time and i dont know why.
like i said im new and i saw a lot of reviews how to fix such problem but none helped. so i thought it was the bluetooth app cuz my controller works on other devices.

please help
aelindos

**Comment by aelindos** [comment]
where is the issue template you are asking for ?

**Comment by aelindos** [comment]
where is the issue template you are asking for?

**Comment by cschramm** [comment]
The form gets initialized with it when you create a new issue: https://github.com/blueman-project/blueman/issues/new
