### ISSUE TITLE
Bluetooth connection with Brydge 10.5 keyboard

### ISSUE THREAD

**Issue by baqlias** [blueman-project/blueman#2227]
blueman: 2.3.5
BlueZ:
Distribution: Linux Mint 21.2
Desktop environment: Microsoft Surface Go 2, M3 CPU

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I recently installed Mint on my Surface Go 2. I'm fairly new to Linux, so please let me know what logs I may need to upload. I tried to pair my Brydge Bluetooth keyboard (the one designed for the Go) with my Mint Go.  Blueman identifies the keyboard correctly. I try to link.  I'm given a code to enter on my keyboard. I do so, but I'm not sure that this happened. The next message tells me I'm connected. But the connection drops a few seconds later. At no time does any key on the keyboard do anything on my Go.  

Some say that Brydge keyboards are not compatible with Linux.  Is this the case, or can we look into a possible fix?  Thanks!

**Comment by baqlias** [comment]
For some reason, my comment didn't posy above, so I'll add it here.  I have been trying to link a Bridge 10.5 Bluetooth keyboard to my Surface Go 2 which now runs Linux Mint 21.2.  Blueman correctly identifies the keyboard. When I try to connect, I get a message asking me to enter a 6-digit code. I do so, but there's no indication that my keyboard's strokes are registering at all. I get a message that I am connected, but the connection then drops in a few seconds.  

Some say that Brydge keyboards aren't compatible with Linux. If you know that this is the case, that answers my question. If not, let me know what logs I can post.  Thanks!

**Comment by infirit** [comment]
> For some reason, my comment didn't posy above

You posted between `<!--` and `-->`, I fixed it for you. Can you post a blueman-applet log as described here https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging-blueman.

You may need to press enter to complete the pin.

**Comment by baqlias** [comment]
[bluemanlog.odt](https://github.com/blueman-project/blueman/files/13732103/bluemanlog.odt)
The keyboard works now, but the touchpad doesn't work at all.

**Comment by baqlias** [comment]
[xinput.odt](https://github.com/blueman-project/blueman/files/13732156/xinput.odt)
The touchpad is recognized as a mouse, apparently!

**Comment by cschramm** [comment]
Initial problem gone. Broken touchpad could be an issue in BlueZ 5.64 (https://github.com/bluez/bluez/issues/298). I guess you're stuck with that version on Linux Mint 21. You could try https://packages.ubuntu.com/lunar/bluez.
