### ISSUE TITLE
PS3 controller requires authorization

### ISSUE THREAD

**Issue by NXX99** [blueman-project/blueman#2228]
I'm not using a terminal, but it's asking be to authenticate the controller itself, but it has no screen, or anything to fetch a PIN from It works fine whenever I hook it up to my Dell Latitude D530 with a Mini USB cable, and the D530 is the laptop I have this issue on.

blueman: 2.3.5
BlueZ: 5.66
Distribution: Debian 12 (Bookworm,  stable)
Desktop environment: Cinnamon

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by infirit** [comment]
See https://github.com/bluez/bluez/issues/673

**Comment by gangadharSO** [comment]
I NEED AUTHORIZATION CODE
