### ISSUE TITLE
bluetooth keyboard disconnects after sometime even while working

### ISSUE THREAD

**Issue by h3th-IV** [blueman-project/blueman#2232]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by infirit** [comment]
You didn't provide any of the requested info so bit much we can do to help. Generally speaking if you can pair/connect blueman as a frontend to BlueZ did it's job. You might be able to get a hint from Bluetooth daemon logs. Ask in your distribution's support channels how to do this.
