### ISSUE TITLE
Bluetooth Devices Linux Mint

### ISSUE THREAD

**Issue by Axellarator** [blueman-project/blueman#2250]
blueman:
BlueZ:
Distribution: Linux Mint k1-lm-mate 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Desktop environment: Mate

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Trying to connect Bluetooth mice from Corsair and Logitech. Not visible. Tested several USB adapter from old stuff to new BT 5.3 versions. Also my phones are not visible.

**Comment by cschramm** [comment]
Did you try other frontends like `bluetoothctl`?
