### ISSUE TITLE
game pad

### ISSUE THREAD

**Issue by Hosein716** [blueman-project/blueman#2253]
hi there . i have problem with my wireless bluetooth gamepad . It's connect well but the buttons doesn't working . I don't have any reaction to my gamepad . I install the driver but I steal have problem .

I have wireless gamepad x3 . 

sorry about my text . my enghlish not good.

**Comment by alexrowlingofc** [comment]
i got this same problem with my ps4-controll , linux mint.

**Comment by cschramm** [comment]
See [the BlueZ issues](https://github.com/bluez/bluez/issues).
