### ISSUE TITLE
Before new version my PS4 controller dont work

### ISSUE THREAD

**Issue by alexrowlingofc** [blueman-project/blueman#2256]
blueman: last version
BlueZ:
Distribution:
Desktop environment: dell optlex linux mint 21.3

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by alexrowlingofc** [comment]
Before updating the Bluetooth manager, I used my PS4 controller on my notebook normally but after updating the controller connects but no buttons work

**Comment by cschramm** [comment]
As far as I'm aware, there exist no updates for blueman in Linux Mint. You probably updated the bluez package instead.

**Comment by infirit** [comment]
This happens to me when the kernel got updated and I haven't rebooted yet.

**Comment by emonteirotcc** [comment]
The same here, my PS4 Controller (generic) is connected with the bluetooth, but not working, none joystick manager are recognizing. But the joystick is working normally connected by cable usb.

**Comment by gustavolinux** [comment]
> The same here, my PS4 Controller (generic) is connected with the bluetooth, but not working, none joystick manager are recognizing. But the joystick is working normally connected by cable usb.

I'm also having the same problem here on archlinux(my system is all updated). I'm not able to use any of my bluetooth gamepads and I've tested a bunch of them(all used to work fine weeks ago)
