### ISSUE TITLE
issues on nixos

### ISSUE THREAD

**Issue by sachinchaudhary1808** [blueman-project/blueman#2262]
blueman: idk using nixos stable 
BlueZ: idk this thing 
Distribution: nixos  23.11 (stable channel)
Desktop environment: hyprland

so i'm having issues only with blueman but no with other things like blueberry

like it shows my device but when i try to connect it gives me a notification for pairing request and i click on that i accept the request on my phone,  it takes some time then say's disconnected on notification 

like i'm new to linux so guide me through this i have enabled this thing in my nixos configs 

services.blueman.enable = true;
hardware = {
                bluetooth.enable = true;
                bluetooth.powerOnBoot = true;
        };
        
      also some times it doesn't show any device  
        
        
        this are some logs:
        
        [coco@nixos:~]$ blueman-applet
blueman-applet 16.07.28 WARNING  PluginManager:94 load_plugin: Failed to start plugin GameControllerWakelock: Only X11 platform is supported
blueman-applet 16.07.29 WARNING  TransferService:213 _make_share_path: Failed to get Download dir from XDG
Traceback (most recent call last):
  File "/nix/store/qq0jvxn5hxxzrmdl36gi7m552vdxjd0i-blueman-2.3.5/lib/python3.11/site-packages/blueman/main/DBusProxies.py", line 52, in call_finish
    proxy.call_finish(resp)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Unknown action ‘Activate’ (16)
        
        
   also got some error in blueberry which is alternative of blueman it's like gnome one

   (blueberry.py:5646): Bluetooth-WARNING **: 16:26:12.261: Setting up /org/bluez/hci0/dev_18_AB_1D_46_49_14 failed: GDBus.Error:org.bluez.Error.InProgress: In Progress
[coco@nixos:~]$

like in this app i can connect using via sending request with my phone and then can pair it like i can't pair using laptop     
        
        

![image](https://github.com/blueman-project/blueman/assets/138745629/3057a5f1-b009-4eef-b190-eb832e57fe13)

**Comment by ghaif** [comment]
did you find a solution , going through the same situation as you right now
