### ISSUE TITLE
Mobile power draw

### ISSUE THREAD

**Issue by ChiefBigFeather** [blueman-project/blueman#2278]
blueman: 2.3.5-2+b1
BlueZ: 5.66-1+deb12u1
Distribution: debain 12
Kernel: 6.5
Desktop environment: xfce

I've noticed a relatively high idle power draw caused by blueman on my xps13. I installed the pipewire drop in plugin, but blueman seems to wake a pulse audio component creating interrupts and noticeably increasing idle power draw.

If idling my machine draws ~1W, blueman often wakes it to ~3W. The issue is easily fixed by removing blueman from autostart.

**Comment by cschramm** [comment]
Does it help to disable the `AudioProfiles` plugin?
