### ISSUE TITLE
blueman applet doesn't show anything in context menu

### ISSUE THREAD

**Issue by alejomka** [blueman-project/blueman#2289]
blueman: 2.3.5+mint1+vera
BlueZ: 5.64-0ubuntu1.1
Distribution: Mint 21.3
Desktop environment: Cinnamon 6.0.4

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

When I right click on the applet icon it doesn't show anything. Just a small empty box. The problem appeared suddenly because it was working perfectly before.
![Sin título](https://github.com/blueman-project/blueman/assets/162226318/39a6d36c-9942-495c-a263-ac94c17e69a8)

**Comment by cschramm** [comment]
Did you find the cause?

**Comment by alejomka** [comment]
> Did you find the cause?

Hello. I forgot to post my solution. My bad.
I didn't find a solution to that bug, but I think I found a way to prevent it.
This bug seems to manifest itself when I turn off the system with Bluetooth on.
My half-solution was to change the AutoEnable parameter to false in the main.conf file located in etc/bluetooth.
If the problem occurs, restarting the system will solve it.

**Comment by cschramm** [comment]
Weird. I wonder if it could be a more generic issue with Cinnamon 6, but I'd have expected dozens of users drop here already then. :thinking:
