### ISSUE TITLE
How to pair bluetooth and devuan?

### ISSUE THREAD

**Issue by rmd1433** [blueman-project/blueman#2290]
blueman: 2.3.5
BlueZ Version: 5.66-1+deb12u1
Distribution: Devuan 5 sysvinit
Desktop environment: xfce

Problem with connecting wireless headphones, writes that the resource is not ready. But the smartphone is detected as BlueZ 5.66

I added my device here  sudo nano  ~/.asoundrc

pcm.!default headphones

pcm.headphones {
    type bluealsa
    device 41:42:EA:F9:CF:3
    profile a2dp
}

the bug was published on privatbin.net.

but for some reason the link leads to github!

**Comment by infirit** [comment]
We don't support bluealsa in blueman, only pulseaudio. If you need help with bluealsa see https://github.com/arkq/bluez-alsa
