### ISSUE TITLE
Rapid dis- and reappearing of the blueman applet icon

### ISSUE THREAD

**Issue by franzmondlichtmann** [blueman-project/blueman#2311]
blueman: 2.3.5
BlueZ: 5.71
Distribution: OpenSuse Tumbleweed (Rolling Release)
Desktop environment: i3

Blueman is running, but the bluetooth-applet-icon is "appearing" and disappearing (in very short spans of time ca. every ~30 milliseconds) in the right part of the bar. The Icon itself is not visible but a black or transparent square where the icon should be.
I tried it out with blueman running and with other programs closed.
The bug seems to appear when I start the dolphin file manager.
This right part of the bar is part of the desktop environment i3 (if I understood correctly).
I already filed a bug in the bumblebee-status bar github page, but they say it's very probably not their bug.
I tried it with  bumblebee-status and i3 default status bar, but the bug happens with both statusbars, and seems independent of the set status bar. I don't think its a graphical glitch in the sense, that it has anything to do with the gpu.
Maybe it's the way the icon gets drawn or updated?

State 1:
![image](https://github.com/blueman-project/blueman/assets/105480088/2ca40f1e-9229-4d4a-b4bd-6cb64b2509df)
State 2:
![image](https://github.com/blueman-project/blueman/assets/105480088/f1c2e8eb-8322-4316-b6cb-678d18369c27)
Imagine rapid switching between the two states.

In the next test, I closed the other applet icons, so that only blueman is open. Same problem.

**Comment by franzmondlichtmann** [comment]
If I disable the status-notifier-item plugin in blueman the blueman icon reappears and no more rapid dis- and reappearing.

**Comment by franzmondlichtmann** [comment]
It happens on my pc with a 100% probability when I get this message box from dolphin.
"What do you wish to do with this file? Execute. Cancel."
![image](https://github.com/blueman-project/blueman/assets/105480088/5fb7573e-c1f9-46f1-9c12-72d509ca6db9)

**Comment by cschramm** [comment]
Pardon my ignorance, but how can I trigger that?

**Comment by franzmondlichtmann** [comment]
You need some executable program (for example anki). But a executable script should also do it. Right click on the script -> properties -> make executable -> execute with double click in dolphin

**Comment by cschramm** [comment]
Ok, I managed to get that dialog, using an executable shell script (i.e. a text file with a shebang). It looks completely different though, regarding both styling and content (I get an additional "Open" button). Does not cause any problem with the tray icon. Dolphin 23.08.5.

**Comment by franzmondlichtmann** [comment]
I uninstalled many  packages, including plasma 6 desktop environment and many other KDE 6 packages, therefore the issue does not happen anymore. This is kind of a shame, because I would have liked to know how this issue happens.
Now I'm torn apart, if I should install plasma again or not.

**Comment by franzmondlichtmann** [comment]
The styling is coming from qt6ct, a app which lets you change look and feel.

**Comment by franzmondlichtmann** [comment]
Ok I reinstalled Plasma 6 Desktop Environment along with it's dependencies. And Dolphin as a "standalone" application does not trigger the bug, but with Plasma 6 and it's dependencies installed the bug happens!

**Comment by infirit** [comment]
Make sure bluedevil is not installed by using `--assume-installed=bluedevil` when installing plasma.

**Comment by franzmondlichtmann** [comment]
I won't install any KDE applications anymore, because uninstalling and installing KDE Plasma again, broke my system. So I might make a test in a VM, but later.

**Comment by cschramm** [comment]
Shot in the dark: Do you happen to have audio profiles or recent connection items with `&` in their name? #2327 could be a fix then. While working on it I found that it's not only causing warnings as in #2326, but it can e.g. cause #2289 in Cinnamon. One obvious way the KDE packages could trigger it could be that they connect an audio device which leads to the profiles getting added to the menu.

**Comment by cyberpunkrocker-zero** [comment]
That on-off flashing started on Arch Linux after the update to Plasma6, with both 2.3.5 and 2.4 versions of blueman. When starting blueman-applet from terminal, I get the following messages:
```blueman-applet 20.33.34 WARNING  PluginManager:150 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 20.33.34 WARNING  PluginManager:150 __load_plugin: Not loading DhcpClient because its conflict has higher priority
```

**Comment by cyberpunkrocker-zero** [comment]
As noted above, either disabling the `status-notifier-item` plugin on blueman, or removing KDE6's Bluedevil  helps.

**Comment by cschramm** [comment]
I was able to reproduce it now, simply by running `kded6` on i3, but cannot confirm that removing bluedevil helps. #2334 should fix it.
