### ISSUE TITLE
 bluetooth icon in system tray shows as connected when discconnected

### ISSUE THREAD

**Issue by mrsteve0924** [blueman-project/blueman#2321]
blueman: 2.4-1
BlueZ: 5.73-4
Distribution: archlinux
Desktop environment: wayfire

after disconnecting bluetooth device from computer, the tray icon is still showing the blueman-active image.
![blueman-active](https://github.com/blueman-project/blueman/assets/37476191/f78950a2-f28e-4663-b6d0-431c77d61d4a)

**Comment by dmillfree868** [comment]
#2323 I can confirm that this fixes the icon issue
