### ISSUE TITLE
V2.4 GTK-Warning

### ISSUE THREAD

**Issue by dmillfree868** [blueman-project/blueman#2326]
blueman: 2.4
BlueZ: 5.73
Distribution: Slackware 64 current
Desktop environment: xfce4 4.18

GTK has a warning about markup failing

(blueman-tray:1745): Gtk-WARNING **: 17:17:11.376: Failed to set text 'Audio Gateway (A2DP Source & HSP/HFP AG)' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;

(blueman-tray:1745): Gtk-WARNING **: 17:17:11.382: Failed to set text '<b>Audio Gateway (A2DP Source & HSP/HFP AG)</b>' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;

![GTK-Warning](https://github.com/blueman-project/blueman/assets/95503349/ea516225-044e-44ce-8354-94dfadc15720)

**Comment by cschramm** [comment]
Could you try #2327?

**Comment by dmillfree868** [comment]
OK I made the changes to the file PulseAudioProfile.py as suggested logged out and then logged back in, connected the phone and that fixed the issue. Thank You!
