### ISSUE TITLE
Tray icon does not update when a bluetooth device was disconnected

### ISSUE THREAD

**Issue by rizalmart** [blueman-project/blueman#2336]
blueman: 2.4
BlueZ: 5.73
Distribution: Slackware Current
Desktop environment: XFCE 4.18

When a bluetooth  device was connected, a green bluetooth icon shown. However when the bluetooth device was disconnected, the blueman applet tray icon does not update. It's still in green indicator on the system tray. The blueman icon will update if the bluetooth device was turn-off then turn-on

**Comment by infirit** [comment]
This bug was fixed and will be in 2.4.1 which should be out soonish.

**Comment by infirit** [comment]
2.4.1 is out
