### ISSUE TITLE
JBL Clip Bluetooth Connection

### ISSUE THREAD

**Issue by JR51** [blueman-project/blueman#234]
I am unable to connect my speaker using Linux Mint 17.1.  When requesting A2DP Sink I always get "Device Added but Failed to Connect"   Help!

**Comment by cschramm** [comment]
I think you're experiencing a known issue in blueman 1.23-git201403102151 which is fixed in 1.23-git201406261335-deb. You can [get the later version from utopic](http://packages.ubuntu.com/utopic/blueman). Make sure to restart your system to see the effect.

**Comment by JR51** [comment]
I followed the instructions in cschramm's link to install the 20140626 version, but no joy.
Software manager shows this as the installed version.  Version: 1.23-git201406261335-deb-1ubuntu1

**Comment by JR51** [comment]
Here's the troubleshooting data - hope I got it right.
/John
pineywoods@pineywoods ~ $ killall blueman-applet
blueman-applet: no process found
pineywoods@pineywoods ~ $ blueman-applet
Loading configuration plugins
blueman-applet version 1.23 starting
Using gconf config backend
_________
Load (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:54)
['AuthAgent', 'KillSwitch', 'SerialManager', 'ShowConnected', 'NetUsage',
'PulseAudio', 'DiscvManager', 'StatusIcon', 'NMPANSupport',
'TransferService', 'Menu', 'PowerManager', 'DhcpClient', 'PPPSupport',
'ExitItem', 'DBusService', 'StandardItems', 'Headset', 'AppIndicator',
'RecentConns', 'NMDUNSupport', 'Networking']
Using gconf config backend
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.Headset.Headset'>
Using gconf config backend
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.Networking.Networking'>
Using gconf config backend
_________
load_nap_settings
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/Networking.py:30)
Loading NAP settings
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'>
Using gconf config backend
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.DBusService.DBusService'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.Menu.Menu'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
Not loading PPPSupport because it's conflict has higher priority
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.PulseAudio.PulseAudio'>
Using gconf config backend
_________
pa_context_event
(/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
1
_________
on_load
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/PulseAudio.py:160)
PulseAudio version: [4, 0, 0]
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'>
Using gconf config backend
_________
on_load
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/KillSwitch.py:25)
Using the new killswitch system
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.DhcpClient.DhcpClient'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'>
Using gconf config backend
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.AppIndicator.AppIndicator'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
Not loading NMPANSupport because it's conflict has higher priority
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.TransferService.TransferService'>
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'>
Using gconf config backend
_________
update_menuitems
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/DiscvManager.py:114)
warning: Adapter is None
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'>
Using gconf config backend
_________
__load_plugin
(/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'>
_________
pa_context_event
(/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
2
_________
update_state
(/usr/lib/python2.7/dist-packages/blueman/main/KillSwitchNG.py:162)
State: True
_________
on_switch_added
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/KillSwitch.py:45)
killswitch registered 3
_________
on_obex_owner_changed
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/TransferService.py:70)
obex owner changed: :1.86
Using gconf config backend
_________
on_dbus_name_owner_change (/usr/bin/blueman-applet:81)
org.bluez owner changed to :1.1
_________
set_nap
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/Networking.py:63)
set nap False
_________
register_agent
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/AuthAgent.py:51)
Registering agent
_________
__init__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:16)
caching initial properties
_________
initialize
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/RecentConns.py:136)
rebuilding menu
_________
enumerate_connections
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/ShowConnected.py:48)
Found 0 existing connections
_________
pa_context_event
(/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
3
_________
on_started
(/usr/lib/python2.7/dist-packages/blueman/main/applet/Transfer.py:72)
opp Started
_________
on_started
(/usr/lib/python2.7/dist-packages/blueman/main/applet/Transfer.py:72)
ftp Started
_________
pa_context_event
(/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
4
_________
on_adapter_property_changed
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs
dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000112d-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001105-0000-1000-8000-00805f9b34fb')],
signature=dbus.Signature('s'), variant_level=1)
_________
<lambda>
(/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:318)
1
_________
on_adapter_property_changed
(/usr/lib/python2.7/dist-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs
dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000112d-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001105-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001106-0000-1000-8000-00805f9b34fb')],
signature=dbus.Signature('s'), variant_level=1)
^CTraceback (most recent call last):
  File "/usr/bin/blueman-applet", line 106, in <module>
    BluemanApplet()
  File "/usr/bin/blueman-applet", line 58, in __init__
    gtk.main()
KeyboardInterrupt
pineywoods@pineywoods ~ $
<http://mirrors.kernel.org/ubuntu/pool/universe/b/blueman/blueman_1.23-git201406261335-deb-1ubuntu1_i386.deb>

**Comment by cschramm** [comment]
This looks like the startup only. Did you actually open manager and try to connect the audio service?

**Comment by JR51** [comment]
So I started blueman, then tried to connect to A2DP, got the failed to
connect message, then ran blueman-applet and as expected got
pineywoods@pineywoods ~ $ blueman-applet
Loading configuration plugins
blueman-applet version 1.23 starting
There is an instance already running
So I probably didn't understand your last message.
/John

**Comment by cschramm** [comment]
You need to kill the running applet and start it again in a terminal. When it's running, use it to open the device manager and try to connect to the audio service. This will produce more output and that is portion that's important to see what's happening.

**Comment by JR51** [comment]
Maybe this has it.... I ran the applet from the terminal, then opened
Blueman from the settings menu and tried to connect to A2DP

pineywoods@pineywoods ~ $ killall blueman-applet
pineywoods@pineywoods ~ $ blueman-applet
Loading configuration plugins
blueman-applet version 1.23 starting
Using gconf config backend
_________
Load (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:54)
['AuthAgent', 'KillSwitch', 'SerialManager', 'ShowConnected', 'NetUsage',
'PulseAudio', 'DiscvManager', 'StatusIcon', 'NMPANSupport',
'TransferService', 'Menu', 'PowerManager', 'DhcpClient', 'PPPSupport',
'ExitItem', 'DBusService', 'StandardItems', 'Headset', 'AppIndicator',
'RecentConns', 'NMDUNSupport', 'Networking']
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.Headset.Headset'>
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.Networking.Networking'>
Using gconf config backend
_________
load_nap_settings (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/Networking.py:30)
Loading NAP settings
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'>
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.DBusService.DBusService'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.Menu.Menu'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
Not loading PPPSupport because it's conflict has higher priority
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.PulseAudio.PulseAudio'>
Using gconf config backend
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/
PulseAudioUtils.py:306)
1
_________
on_load (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/PulseAudio.py:160)
PulseAudio version: [4, 0, 0]
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'>
Using gconf config backend
_________
on_load (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/KillSwitch.py:25)
Using the new killswitch system
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.DhcpClient.DhcpClient'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'>
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.AppIndicator.AppIndicator'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
Not loading NMPANSupport because it's conflict has higher priority
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.TransferService.TransferService'>
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'>
Using gconf config backend
_________
update_menuitems (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/DiscvManager.py:114)
warning: Adapter is None
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'>
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/
PluginManager.py:127)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'>
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/
PulseAudioUtils.py:306)
2
_________
update_state (/usr/lib/python2.7/dist-packages/blueman/main/
KillSwitchNG.py:162)
State: True
_________
on_switch_added (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/KillSwitch.py:45)
killswitch registered 3
_________
on_obex_owner_changed (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/TransferService.py:70)
obex owner changed: :1.86
Using gconf config backend
_________
on_dbus_name_owner_change (/usr/bin/blueman-applet:81)
org.bluez owner changed to :1.1
_________
set_nap (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/Networking.py:63)
set nap False
_________
register_agent (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/AuthAgent.py:51)
Registering agent
_________
__init__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:16)
caching initial properties
_________
initialize (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/RecentConns.py:136)
rebuilding menu
_________
enumerate_connections (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/ShowConnected.py:48)
Found 0 existing connections
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/
PulseAudioUtils.py:306)
3
_________
on_started (/usr/lib/python2.7/dist-packages/blueman/main/applet/
Transfer.py:72)
opp Started
_________
on_started (/usr/lib/python2.7/dist-packages/blueman/main/applet/
Transfer.py:72)
ftp Started
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/
PulseAudioUtils.py:306)
4
_________
on_adapter_property_changed (/usr/lib/python2.7/dist-
packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000112d-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001105-0000-1000-8000-00805f9b34fb')],
signature=dbus.Signature('s'), variant_level=1)
_________
<lambda> (/usr/lib/python2.7/dist-packages/blueman/main/
PulseAudioUtils.py:318)
1
_________
on_adapter_property_changed (/usr/lib/python2.7/dist-
packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000112d-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'),
dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001105-0000-1000-8000-00805f9b34fb'),
dbus.String(u'00001106-0000-1000-8000-00805f9b34fb')],
signature=dbus.Signature('s'), variant_level=1)
_________
__init__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:16)
caching initial properties
_________
__del__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:60)
deleting device /org/bluez/756/hci0/dev_00_12_6F_62_9A_6F
_________
Destroy (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:95)
invalidating device /org/bluez/756/hci0/dev_00_12_6F_62_9A_6F
_________
__init__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:16)
caching initial properties
_________
notify (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/RecentConns.py:237)
<Device object at 0xa8d220cc (blueman+main+Device+Device at 0x9f8ac00)>
org.bluez.AudioSink dbus.Array([], signature=dbus.Signature('s'))
_________
__del__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:60)
deleting device /org/bluez/756/hci0/dev_00_12_6F_62_9A_6F
_________
Destroy (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:95)
invalidating device /org/bluez/756/hci0/dev_00_12_6F_62_9A_6F
_________
initialize (/usr/lib/python2.7/dist-packages/blueman/plugins/
applet/RecentConns.py:136)
rebuilding menu
_________
__init__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:16)
caching initial properties
_________
__del__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:60)
deleting device /org/bluez/756/hci0/dev_00_12_6F_62_9A_6F
_________
Destroy (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:95)
invalidating device /org/bluez/756/hci0/dev_00_12_6F_62_9A_6F

**Comment by cschramm** [comment]
The device just disconnects when you try to use the service. Please start blueman-manager from a terminal to see if it gives any more information when trying to disconnect.

You could also try 1.99.alpha1 to see if it works in a more recent version: http://packages.ubuntu.com/vivid/blueman

**Comment by JR51** [comment]
Christopher,
Good news is my JBL Click is now working.   Blueman Manager still gives me
the fail to connect message when I select A2DP. (In windows the JBL didn't
work when I selected the headphone option.)  I don't have an explanation
for the change but I was poking around in the pulse-audio menus and may
have turned something on that had been off previously.   Also, I'd never
started blueman-manager from the terminal before, don't know why that would
have made a difference.   Anyway it now connects automatically when I turn
it on, so all is good.  Thanks /John

**Comment by cschramm** [comment]
:smiley: 

> I'd never started blueman-manager from the terminal before, don't know why that would have made a difference.

Shouldn't. That's just for getting its output.
