### ISSUE TITLE
Error: Failed to start plugin GameControllerWakelock: Only X11 platform is supported

### ISSUE THREAD

**Issue by J053Fabi0** [blueman-project/blueman#2352]
blueman: 2.4.1-1
BlueZ: 5.75-1
Distribution: EndeavourOS Linux x86_64, 6.8.7-arch1-1
Desktop environment: sway

* [x] I have consulted the [Troubleshooting page](`https://github.com/blueman-project/blueman/wiki/Troubleshooting`) and done my best effort to follow.

## Logs
https://gist.github.com/J053Fabi0/6c154bf753c8e5352031d3cbec2fc4fb

## Description
I recently updated my system and when I restarted it, `blueman-applet` was not working.

**Comment by infirit** [comment]
The error in the subject is non fatal and is expected on wayland compositors. The log is also not helpful as you forgot the important step to `killall blueman-applet` https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging-blueman
