### ISSUE TITLE
Asset tarballs missing `meson_options.txt`

### ISSUE THREAD

**Issue by triallax** [blueman-project/blueman#2369]
As the title states, both https://github.com/blueman-project/blueman/releases/download/2.4.1/blueman-2.4.1.tar.gz and https://github.com/blueman-project/blueman/releases/download/2.4.1/blueman-2.4.1.tar.xz seem to be missing `meson_options.txt` for some reason. The GitHub-generated tarballs for the same release (e.g. https://github.com/blueman-project/blueman/archive/refs/tags/2.4.1.tar.gz) do have `meson_options.txt` though.

**Comment by infirit** [comment]
Should be fixed with #2370

**Comment by infirit** [comment]
Should be in 2.4.2. Thanks for the report.

**Comment by triallax** [comment]
thanks!
