### ISSUE TITLE
Could blueman be made to work with udhcpc

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#237]
Just a suggestion, but could blueman be made to work with udhcpc (busybox) for network connections?

**Comment by juanitotc** [comment]
I just noticed that there had been some updates to the udhcpc branch so I tried again.

When attempting to set an iPhone as a network access point, I get the error "Connection Failed: The name org.freedesktop.NetworkManager was not provided by any .service files:

..but if I'm trying to use udhcpc, I shouldn't need networkmanager?

**Comment by cschramm** [comment]
I just rebased the branch on master. Still have to test an iPhone myself.

Are you sure you have enabled the DhcpClient plugin (and thus disabled the NM integration)?

**Comment by juanitotc** [comment]
Ah, forgot that.

So, cutting and pasting the following with dconf-editor into org.blueman.general plugin-list:

`['TransferService', 'StatusIcon', 'StandardItems', 'ShowConnected', 'SerialManager', 'RecentConns', 'PowerManager', 'PPPSupport', 'Networking', 'NetUsage', '!NMPANSupport', '!NMDUNSupport', 'Menu', 'KillSwitch', 'Headset', 'GameControllerWakelock', 'ExitItem', 'DiscvManager', 'DhcpClient', 'DBusService', 'AuthAgent', 'AppIndicator']`

it works :)

Not to appear ungrateful, but ref:

`$ ps aux | grep udhcpc
 3163 root     /sbin/udhcpc -b -i eth0 -x hostname boxdell -p /var/run/udhcpc.eth0.pid
 7737 root     /sbin/udhcpc -t 20 -n -i bnep0`

..would it be possible to pick up the hostname and create a pid file?

BTW, where is the blueman "plugin manager" meant to appear in the gnome desktop environment (I don't see it anywhere)?

**Comment by juanitotc** [comment]
http://forum.tinycorelinux.net/index.php/topic,18121.msg111250.html#msg111250

**Comment by cschramm** [comment]
Great. No idea why the connection works for you now (and I hope it will last...), but we can definitely merge udhcpc then.

> would it be possible to pick up the hostname and create a pid file?

Hostname seems to make sense. I'll add that to dhclient and dnsmasq as well if possible.

I don't think a pid file makes sense as blueman manages the process (if it does not terminate itself it should be killed after a timeout).

> where is the blueman "plugin manager" meant to appear in the gnome desktop environment (I don't see it anywhere)?

It's in the menu of our applet. I guess it's "Extensions" in English.

> http://forum.tinycorelinux.net/index.php/topic,18121.msg111250.html#msg111250

Thanks for the "nice man" title. Now I finally know what strange system you are working with there. :wink:

**Comment by cschramm** [comment]
#258 implements the hostname argument
