### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by ryuukk** [blueman-project/blueman#2387]
blueman: 2.4.1
BlueZ: 5.76
Distribution: Arch Linux
Desktop environment: xfce

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Hello,

I get a spam of notifcations related to my bluetooth headset that i can't seem to be able to disable

Mostly related to battery status, every 10% i get a notification, wich is annoying

# Workaround

As a workaround i put blueman in the mute list, but this is not long term viable..

# Suggestion

Please make it possible to disable notifications

Best would be to select what kind of notification to allow/disallow
 

Thanks

**Comment by cschramm** [comment]
#2317
