### ISSUE TITLE
Jun 01 19:35:10 kali bluetoothd[62166]: src/adv_monitor.c:btd_adv_monitor_power_down() Unexpected NULL btd_adv_monitor_manager object upon power down

### ISSUE THREAD

**Issue by krstark** [blueman-project/blueman#2401]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by infirit** [comment]
You'll want to report that to BlueZ project here https://github.com/bluez/bluez
