### ISSUE TITLE
Unable to Connect Stadia Controller via Bluetooth on Lubuntu

### ISSUE THREAD

**Issue by Dany78p** [blueman-project/blueman#2406]
Stadia Controller Bluetooth Connection Issue on Lubuntu

Distribution: Lubuntu 20.04
Desktop Environment: LXQt
Blueman Version: 2.1.4
BlueZ Version: 5.53
Problem Description:

I am trying to connect my Stadia controller to my Lubuntu system via Bluetooth, but each time I use Blueman to search for devices, the controller does not appear in the list of available devices. I have followed the steps recommended on the [Blueman troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) to the best of my ability, but I have not been successful.
Steps Taken:

    Ensured that Bluetooth is enabled on both my system and the Stadia controller.
    Put the Stadia controller into pairing mode.
    Opened Blueman and selected the option to search for new devices.
    Waited for the device to appear in the list, but nothing was found.

Logs and Command Output:

To provide more details about the issue, here are the logs and outputs of some commands I have run:

    Output from the bluetoothctl command:

    ruby

[bluetooth]# scan on
Discovery started
[CHG] Device XX:XX:XX:XX:XX:XX RSSI: -XX
[CHG] Device XX:XX:XX:XX:XX:XX Name: Stadia Controller
[bluetooth]# devices
Device XX:XX:XX:XX:XX:XX Stadia Controller

Syslog during the search:

less

    Jun 15 12:34:56 lubuntu bluetoothd[1234]: Bluetooth daemon 5.53
    Jun 15 12:34:58 lubuntu bluetoothd[1234]: Starting SDP server
    Jun 15 12:35:00 lubuntu bluetoothd[1234]: Bluetooth management interface 1.14 initialized

Additional Actions Taken:

    Verified that the Stadia controller works with other Bluetooth devices (such as my phone) without issues.
    Restarted the Bluetooth service and repeated the steps above without success.
    Consulted various forums and the documentation for Blueman and BlueZ, but found no specific solution for this issue.

I would appreciate any help or suggestions to resolve this issue and successfully connect my Stadia controller via Bluetooth on my Lubuntu system.

**Comment by cschramm** [comment]
Your system is very old and I'm surprised by the blueman version as it should even have 2.1.2.

You're seeing the controller in `bluetoothctl` but not in blueman. Is that correct?
