### ISSUE TITLE
Feature/improvement: taskbar icon when using dark theme

### ISSUE THREAD

**Issue by jayjayseal** [blueman-project/blueman#2411]
blueman-(manager):2.3.5
BlueZ:
Distribution: Linux Mint Cinnamon
Desktop environment: 

Feature/improvement

Hi,

I'm using the blueman-(manager) and i noticed that when you are using the dark theme the icon in the taskbar becomes almost invisible when there are no devices connected. Is it possible to change the icon to something else? In the past this was a nice B/W icon with a white dot to show if a device was connected.

![blueman-manager-icon](https://github.com/blueman-project/blueman/assets/19550114/ce2a7d7b-454e-4d5c-9eb5-785d4a1546e6)

admittedly this would also be nicer against my own current icons

**Comment by cschramm** [comment]
That does not look like any of our icons.

**Comment by infirit** [comment]
Does `gsettings set org.blueman.general symbolic-status-icons true` work for you?

**Comment by jayjayseal** [comment]
> Does `gsettings set org.blueman.general symbolic-status-icons true` work for you?

Yes, this worked :-) Thank you! :)
