### ISSUE TITLE
Rii i4 Dual Mode Multimedia Keyboard Touchpad Combo Blutooth and 2.4G Mini Keyboard US Layout

### ISSUE THREAD

**Issue by LAP47** [blueman-project/blueman#2436]
blueman:
BlueZ:
Distribution: Linux Mint 22 Beta
Desktop environment: Mate'

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Blueman doesn't find the keyboard when searching for it so the keyboard only works when using the included 2.4G USB Adapter which I'm using right now.

**Comment by cschramm** [comment]
Did you try `bluetoothctl`? Is it discoverable from another device at the same time?

**Comment by LAP47** [comment]
> Did you try `bluetoothctl`? Is it discoverable from another device at the same time?

No. I haven't. I just went right to using the 2.4GHz once I decided that I wasn't able to figure it out.
