### ISSUE TITLE
Unable to Connect to USB Devices on Kali Linux

### ISSUE THREAD

**Issue by Bridges22** [blueman-project/blueman#2443]
Unable to Connect to USB Devices on Kali Linux

Description:
Hello,

I am experiencing a significant issue on my Kali Linux system where I am unable to connect to any USB devices. Despite multiple troubleshooting attempts, including reinstalling relevant packages and ensuring services are running correctly, the issue persists. I am seeking assistance to resolve this problem.

System Information:

    OS: Kali Linux
    Kernel Version: (Provide your kernel version, e.g., 5.10.0-kali7-amd64)

Steps Taken:

    Verified USB ports with different devices (e.g., USB flash drive, external HDD).
    Reinstalled Bluetooth packages (which might relate to the issue):

    sh

sudo apt-get remove --purge bluez bluetooth
sudo apt-get install bluez bluetooth
sudo apt-get install blueman

Ensured USB-related services are running:

sh

    sudo systemctl restart bluetooth
    sudo systemctl restart udev

Current Status:

    USB devices are not being recognized or mounted.
    lsusb command does not list connected USB devices.

Commands and Outputs:

Output of lsusb:

plaintext

Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Output of dmesg | grep usb:

plaintext

(Include relevant log entries here)

Output of sudo systemctl status udev:

plaintext

● systemd-udevd.service - Rule-based Manager for Device Events and Files
     Loaded: loaded (/lib/systemd/system/systemd-udevd.service; static)
     Active: active (running) since [Timestamp]; [Duration]
       Docs: man:systemd-udevd.service(8)
             man:udev(7)
   Main PID: [PID] (systemd-udevd)
     Status: "Processing with 0 children at max, 0 running"

Additional Information:

    I have tried different USB ports with no success.
    The issue persists across reboots.
    There are no apparent hardware issues with the USB devices as they work on other machines.

Request for Assistance:
Could you please provide guidance on how to diagnose and resolve this issue? Any insights into potential misconfigurations or additional steps to troubleshoot this problem would be greatly appreciated.

Thank you for your support.

**Comment by infirit** [comment]
We can't help with general system issues. Perhaps you should ask in the Kali linux support options here https://www.kali.org/community/
