### ISSUE TITLE
Sort Recent Connections with most recent at the top

### ISSUE THREAD

**Issue by PanderMusubi** [blueman-project/blueman#2445]
blueman: 2.2.4-1
BlueZ:
Distribution: Pop!_OS 22.04 LTS
Desktop environment: GNOME

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Sort the devices in Recent Connections... with the most recent at the top.

See `gnome-control-center bluetooth` where the sort order is like this.

**Comment by cschramm** [comment]
You need to elaborate a little as that's already the case. You are using a rather old version. From looking at the code it might actually present the most recent entry at the bottom.

**Comment by PanderMusubi** [comment]
I will have a look again when Pop!_OS has released their new version.
