### ISSUE TITLE
Pair Toolbar option not accessible with keyboard

### ISSUE THREAD

**Issue by nickspiker** [blueman-project/blueman#2448]
You can turn on/off and scan for bluetooth devices, you can even select the mouse that shows up in the list but enter and specebar do nothing.

**Comment by infirit** [comment]
You can pair/connect from the device menu. Is that menu not available for you?

**Comment by nickspiker** [comment]
Nope.  I can see the menu but tab only goes back and fourth between the top buttons and the devices so I can't actually do anything with the menus.  When you right click the menu comes up (I had to pair thru bash as I didn't have a mouse to right click of course)

**Comment by infirit** [comment]
Ah, I see you haven't been introduced to accelerators on menus. Hold `Alt` and one of the letters in the menu will be underlined.  Then while holding alt press the underlined key (d in my example) on your keyboard. Like this.
![image](https://github.com/user-attachments/assets/0fcb1bda-d15a-46ea-93cb-b4ef4ad10063)

**Comment by infirit** [comment]
Ooh, but I see the bug now. Let me check that out. In the mean time use the menu with the accelerator.

**Comment by infirit** [comment]
Not having a great day. Here is how it should work.

* Tab moves between sections
* When in the toolbar use the left and right arrow keys to switch between the buttons.
* Buttons that are not sensitive (for example the device is already paired) are not accessible.

The issue I think there is no visible indication that the button is not sensitive as the icon doesn't change.

**Comment by infirit** [comment]
@nickspiker Would the top screenshot in #2449 help you better identifying when a button can't be pressed?

**Comment by nickspiker** [comment]
Ah, you have to hold alt, yes.  I tried that but I didn't 'Hold' it.  Typically alt brings you to the menus so you can arrow thru them but I think the biggest thing is that enter and space should bring up the menu.  That way you can choose what to do with the device if you don't have a mouse and I intuitively didn't even think to hold alt so...

**Comment by nickspiker** [comment]
Checking other apps and yes, holding alt seems to be the default so I think just the menu when selected is the one that should be added.
