### ISSUE TITLE
Blueman suddently stopeed detecting my devices.

### ISSUE THREAD

**Issue by Scottie5000** [blueman-project/blueman#2458]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

 Suddenly Blueman cannot detect ANY of my bluetooth devices. Did so just fine with 21.3 and prior versions. Worked initially on 22, and did some updates today 08.12.2024 and it still worked, rebooted my pc and it no longer detects anything. Help

Apple mouse, apple keyboard, sonos move

**Comment by infirit** [comment]
Probably better to ask on the Mint forums as it happened after updating something.

There may be some hints in the blueman-applet debug log. See https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging-blueman

**Comment by Scottie5000** [comment]
NM upon reboot it's working just fine. Just a glitch in the Matrix.
