### ISSUE TITLE
blueman manager pair

### ISSUE THREAD

**Issue by antonvdh** [blueman-project/blueman#2465]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by antonvdh** [comment]
I wanted to pair my bluetooth keyboard but I did not manage because the pincode will only  be visible for 3 seconds

**Comment by PapaJS** [comment]
Connects with my bluetooth keyboard but will disconnect after about 8 sec. Won't stay connected.

**Comment by infirit** [comment]
> I wanted to pair my bluetooth keyboard but I did not manage because the pincode will only be visible for 3 seconds

Fill in the issue template and post a blueman-applet debug log of you trying to pair. See how to do the debug log here: https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging-blueman
