### ISSUE TITLE
stutering blue tooth on bluetooth speaker not evident when in a windows 10 platform on device.

### ISSUE THREAD

**Issue by Momdad14** [blueman-project/blueman#2466]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by infirit** [comment]
Blueman doesn't handle the lower level connection. If the connection is made blueman's job is done.

Maybe you can post to your distribution's support channels for help.
