### ISSUE TITLE
No UI is presented for requests for confirmation

### ISSUE THREAD

**Issue by pvonmoradi** [blueman-project/blueman#2477]
blueman: 2.3.5-2
BlueZ: 5.66-1
Distribution: Debian 12
Desktop environment: i3wm (no DE), dunst notification daemon

According to [Wiki](https://github.com/blueman-project/blueman/wiki/Integrations#desktop-notifications), blueman defers the yes/no confirmation for various bluetooth services to the notification daemon. But what happens when the daemon doesn't support "buttons"? Since blueman already uses gtk, shouldn't it present the yes/no confirmation UI with a normal gtk dialog too (why it defers this task to third-party notification daemons)?

For example I had trouble pairing with an Android device since I couldn't confirm the code on desktop side. I had to resort to `bluetoothctl` then run `scan on` and `pair MAC_ADDRESS`. 

Same issue when receiving a file from the paired device (I have to `trust` the device and enable `Accept files from trusted devices` option to be able to receive anything at all)

**Comment by infirit** [comment]
> blueman: 2.3.5-2 BlueZ: 5.66-1 Distribution: Debian 12 Desktop environment: i3wm (no DE), dunst notification daemon
> 
> According to [Wiki](https://github.com/blueman-project/blueman/wiki/Integrations#desktop-notifications), blueman defers the yes/no confirmation for various bluetooth services to the notification daemon. But what happens when the daemon doesn't support "buttons"?

Dunst should support [actions](https://dunst-project.org/documentation/#ACTIONS).

> Since blueman already uses gtk, shouldn't it present the yes/no confirmation UI with a normal gtk dialog too (why it defers this task to third-party notification daemons)?

Blueman has a Gtk Dialog fallback if there is no notification daemon available.

> For example I had trouble pairing with an Android device since I couldn't confirm the code on desktop side. I had to resort to `bluetoothctl` then run `scan on` and `pair MAC_ADDRESS`.

Post the blueman-applet log when you attempt to pair (some some other action that requires a notification). See https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging-blueman how to.

Most of the issues with dunst have been due some misconfigured/broken system. When we see the blueman-applet log we can see what happened.

**Comment by hrideshmg** [comment]
If you, like me, find dunst actions to be quite clunky for this purpose (why should i have to dedicate a keybind to access a dialog box) then it is possible to tell blueman to avoid using the notification daemon, use the following dconf configuration:

`gsettings set org.blueman.general notification-daemon false`
