### ISSUE TITLE
blueman-applet does not exit automatically when blueman-manager is closed

### ISSUE THREAD

**Issue by mesaprotector** [blueman-project/blueman#2482]
blueman: 2.4.3-1
BlueZ: 5.77-1
Distribution: Arch Linux
Desktop environment: Openbox (X11)

[ ✓] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

[Full debug log](https://gist.github.com/mesaprotector/5f37ad7fd631325c334aaeb890d31e25)

Normally when I have used blueman it is not enough to close the blueman-manager window - I have to right-click on the tray icon to exit. However, I found out (#1495 ) that the tray icon can be turned off. I tried this (via the option in the Plugins menu) - and found that blueman-applet still will continue running after blueman-manager has closed, with the only difference being that now I have to look up the PID to turn it off :) Supposedly since 4bd96fc (reference: #949 ) blueman-applet should exit automatically if opened by blueman-manager, but this is not happening. 

I don't actually mind the tray icon existing but it should also exit automatically if blueman-manager exits.

**Comment by cschramm** [comment]
That commit is not part of this repository. It only exists in my fork. I can give it a shot.
