### ISSUE TITLE
Bluetooth visibility

### ISSUE THREAD

**Issue by StevenGamer2006** [blueman-project/blueman#2496]
My Bluetooth headphones isn't showing up for parable devices can someone give me some guidance.

**Comment by thiagomandrik** [comment]
same here since yesterday

**Comment by Prapul1614** [comment]
Me too

**Comment by thiagomandrik** [comment]
I found this partial solution:

    sudo apt purge bluez
    sudo apt install bluez
    sudo apt install blueman
    Reboot

It works, but the bug reappears after the next boot.

Source:
https://forums.linuxmint.com/viewtopic.php?t=425923

**Comment by infirit** [comment]
Looks like this was something in mint so closing.

**Comment by ewinITservices** [comment]
I am currently using Linux Mint Cinnamon 22 and have been facing difficulties since yesterday. I tried connecting my Bluetooth speaker to both my Android phone and Windows 10, and it worked well on both devices. However, it does not seem to connect on Mint 22.
