### ISSUE TITLE
Missing strings in translation files due to incorrect inclusion in POTFILES.in

### ISSUE THREAD

**Issue by lepata** [blueman-project/blueman#2532]
blueman: 2.4.3
BlueZ:
Distribution: ALT 
Desktop environment: xfce

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

The _po/POTFILES.in_ file does not include the _data/ui/services-window.ui_ file. As a result, the strings "Apply" and "Local Services" are missing from the translation files (po).

Similarly, the file _blueman/plugins/applet/PulseAudioProfile.py_ is also not included in po/POTFILES.in, causing the string "Adds audio profile selector to the status icon menu" to be absent from the translation files.

**Comment by infirit** [comment]
Good catch. Unless someone beats me to it I'll open a PR soon.
