### ISSUE TITLE
Logitech Keyboard Not Presenting Pairing Code

### ISSUE THREAD

**Issue by thinkgrowbe** [blueman-project/blueman#2544]
I have a logitech bluetooth keyboard MX keys. The computer has had no problem previously connecting to my computer for 1.5 years. One day it disconnects and won't reconnect. The computer can see the keyboard, can connect to it, but then it will not display the pairing code needed to actually connect the keyboard. Tested the keyboard on my phone and another computer and it had no problem connecting. I tested another keyboard on this computer and it would not display the pairing code. Please help, thanks!

blueman: 2.3.5
BlueZ: Unsure, where can I find this?
Distribution: cinnamon 6.0.4
Desktop environment: Linux Mint 21.3 Cinnamon

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

 https://gist.github.com/thinkgrowbe/008c5788ea7db6a4c4d60e3a0eb4c48a

**Comment by infirit** [comment]
You need to close (killall blueman-applet) blueman-applet and then run it in a terminal. Then attempt to connect the keyboard and post the output from the terminal.

**Comment by thinkgrowbe** [comment]
Got it. I'm sorry to say I'm a bit of a linux noob. I copy pasted and posted "killall blueman-applet" in the terminal and hit enter and it did not do anything. Could you tell me the commands I need to enter to kill it and then attempt to pair my keyboard?

**Comment by infirit** [comment]
The killall command will produce no output if it's successful. After that just run `blueman-applet` in that same terminal and attempt to pair the keyboard.

**Comment by thinkgrowbe** [comment]
Perfect, I ran that and I was able to see the passkey I needed to link my keyboard in the terminal. Thanks! It still didn't pop up the passkey in the app, but I can use this for the time being. Thank you very much for the help.

**Comment by infirit** [comment]
That suggests whatever desktopbor window manager is not displaying notifications. You should probably fix that as blueman relies on that.
