### ISSUE TITLE
i cant connect my bloetooth speaker.it just keeps connecting and disconnecting.

### ISSUE THREAD

**Issue by yathuxxx** [blueman-project/blueman#2548]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by mohmmedrehan** [comment]
i connect but with in a seconds it disconnected why it doing like this

**Comment by bayatalireza** [comment]
I connect to the headset via Bluetooth, but the sound actually comes out of the laptop.
