### ISSUE TITLE
File transfer: existing files are silently overwritten, file renaming failure

### ISSUE THREAD

**Issue by Vrihub** [blueman-project/blueman#2574]
blueman: 2.3.5
BlueZ: 5.66
Distribution: Debian 12.8
Desktop environment: none

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Steps to reproduce:
- Transfer a file from an external device
- Repeat the previous step with the same file (or with another file having the same file name)
- In the first notification popup message (`"Incoming file over Bluetooth"`) the original file name is displayed, e.g. `bluetooth_content_share.html`
- In the final popup message (`"File Received"`) the file name has a timestamp string prepended, e.g. `20241220140923_bluetooth_content_share.html`
- The blueman log says: `TransferService:294 _on_transfer_completed: Destination file exists, renaming to: 20241220140923_bluetooth_content_share.html`

Expected result: the existing file should be left alone and the new copy should be saved under the modified file name (timestamp prepended)

Actual result: the existing file is silently overwritten.
It looks like the safety renaming mentioned in the log doesn't take place actually

**Comment by Vrihub** [comment]
Thanks, I applied the patch in #2575 to my blueman installation and I can confirm that the bug is fixed: the old file is preserved and the new file is written using the correct filename.

I also get a couple of small side effects, though:
- I get a new popup notification message: `"Files received: Received -1 files in the background"`. I've never seen this message before
- The final popup notification message says `"Transfer failed: Transfer of file 20241220202409_bluetooth_content_share.html failed"`, even if the transfer was actually successful (see above)
- (I also get a FileNotFoundError exception and other related errors in blueman's log)

I presume this is because I'm applying the patch to an old 2.3.5 installed release? Or is it because more work is needed instead? Let me know if I can help you (though I can't install-test the current HEAD on my system, sorry)

**Comment by infirit** [comment]
Can you upload the log here? So we can have a closer look at these errors. This bit of the code hasn't really been touched for a while so the patch should be ok on 2.3 as well.

**Comment by Vrihub** [comment]
> Can you upload the log here? So we can have a closer look at these errors. This bit of the code hasn't really been touched for a while so the patch should be ok on 2.3 as well.

Here you are.

[blueman.log](https://github.com/user-attachments/files/18214780/blueman.log)

**Comment by Vrihub** [comment]
Maybe this is useful too, for historical reference:
https://github.com/blueman-project/blueman/pull/263

**Comment by infirit** [comment]
I suck. I'll update the PR in the next 10 minutes. I added an extra `shutil.move(src, dest)` by accident. Obvious the second time we run this the original file is gone.

**Comment by Vrihub** [comment]
> edit: PRs have been updated

Thanks! Just tested the new version. Now everything works as expected, no side effects.
