### ISSUE TITLE
blueman applet not starting.

### ISSUE THREAD

**Issue by joelmathewthomas** [blueman-project/blueman#2577]
blueman: 15.43.05
BlueZ: 5.79
Distribution: Arch Linux
Desktop environment: Hyprland

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I cant start blueman-applet. 
[Here](https://pastebin.com/KK78Q6xY) are the logs

**Comment by infirit** [comment]
Duplicate of #2551. This is fixed in a newer GLib version so update.
