### ISSUE TITLE
Add ability to start plugins configuration from blueman-manager

### ISSUE THREAD

**Issue by juanitotc** [blueman-project/blueman#264]
For window managers that do not have a panel, would it be possible to add a menu item to blueman-manager to be able to run blueman-services?

The main reason being to swap between networkmanager and udhcpc functionality to set a network access point without having to paste a long string into dconf-editor or similar.

**Comment by cschramm** [comment]
blueman-services is a separate app. I guess you mean the plugins configuration of the applet?

**Comment by juanitotc** [comment]
affirmative :)

**Comment by cschramm** [comment]
Shouldn't be a problem. I'll look into it.

**Comment by juanitotc** [comment]
The plugins branch works fine - thanks.

On a separate, but related, point - is it possible to start blueman-services from blueman-manager?

**Comment by cschramm** [comment]
Added.

**Comment by juanitotc** [comment]
thanks - that works too.

Only PAN with bluez-4 and udhcpc to go now :)
