### ISSUE TITLE
blueman doesn t switch to hci1 if hci0 is present

### ISSUE THREAD

**Issue by geoubuntu** [blueman-project/blueman#297]
hi. ubuntu gnome 15.04 blueman doesn't allw t chose the second bt adapter but it sticks to the first one. not even powering off the hci0 i am able to switch to hci1.
can you help me cause hci0 is a bt realtek 8723be that doesnt work.

**Comment by cschramm** [comment]
https://github.com/blueman-project/blueman/wiki/Troubleshooting

**Comment by cschramm** [comment]
Closing as no info was provided.
