### ISSUE TITLE
Can't receive files with bluez 5.30

### ISSUE THREAD

**Issue by lilydjwg** [blueman-project/blueman#299]
I'm sorry if this is duplicate, but I don't think my issue is exactly the same with those other issues I can find.

Arch Linux, bluez 5.30, obexd is within the bluez package, blueman 1.99.alpha2 from AUR. (And blueman-report doesn't work because bluetoothd isn't at /usr/sbin/bluetoothd.)

Pair ok, sending files ok, but receiving fails. Here's obexd log:

```
6月 06 20:04:27 lilyforest obexd[29718]: CONNECT(0x0), (null)(0xffffffff)
6月 06 20:04:27 lilyforest obexd[29718]: CONNECT(0x0), (null)(0x0)
6月 06 20:04:27 lilyforest obexd[29718]: PUT(0x2), (null)(0xffffffff)
6月 06 20:04:27 lilyforest obexd[29718]: PUT(0x2), FORBIDDEN(0x43)
6月 06 20:04:27 lilyforest obexd[29718]: DISCONNECT(0x1), (null)(0xffffffff)
6月 06 20:04:27 lilyforest obexd[29718]: DISCONNECT(0x1), SUCCESS(0x20)
```

But running ` /usr/lib/bluetooth/obexd -n -a` works. So I think the problem is that blueman somehow fails to decide to receive the files. Share folder is set and available; Object push is enabled and I've tried with the checkbox below (receive files from trusted devices) on and off, I've given my phone the star icon marking that it's trusted.

**Comment by cschramm** [comment]
1.99 was not able to receive files via obexd. You need 2.0 for that.
