### ISSUE TITLE
Can't accept file transfer initiated from device

### ISSUE THREAD

**Issue by DavidGriffith** [blueman-project/blueman#312]
I managed to get a phone paired with my Debian 8 box using bluetoothctl.  Now, I want to select several files on the phone and upload them to the Debian box through bluetooth.  If my box was running Debian 7, a little dialog would pop up from the bluetooth icon asking me if it's okay to accept the transfer.  Now in Debian 8, I instead see the rune in the icon turn green for a few seconds.  Then the phone reports that the transfer failed.  It's not clear what I'm supposed to do when the rune turns green.

Checking with version 2.0 in the git repo, I see now there's an option in Local Services to automatically accept transfers coming from trusted devices.  If turning the rune green is supposed to indicate that a transfer is occurring, it's not terribly obvious.  I think that there should be an option to ask the user if the transfer should be accepted.

**Comment by cschramm** [comment]
What notification daemon do you use?

Please provide the output of blueman-applet (see https://github.com/blueman-project/blueman/wiki/Troubleshooting) when trying to send a file.

**Comment by plaes** [comment]
I'm running into similar issue when trying to receive the file. The remote device is also shown for 1-2 seconds in the devices dialog. And following traceback appears in the console from blueman-applet:
```
__init__ (/usr/lib64/python2.7/site-packages/blueman/main/Device.py:16)
caching initial properties 
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBlueZInterface.py", line 51, in wrapper
    handler(name, value, **kwargs)
  File "/usr/lib64/python2.7/site-packages/blueman/plugins/applet/SerialManager.py", line 48, in on_device_property_changed
    d = Device(path)
  File "/usr/lib64/python2.7/site-packages/blueman/main/Device.py", line 39, in __init__
    self.Properties = self.Device.get_properties()
  File "/usr/lib64/python2.7/site-packages/blueman/bluez/errors.py", line 143, in warp
    raise parse_dbus_error(exception)
DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist
```

**Comment by DavidGriffith** [comment]
Using Bluez 5.23 in Debian Jessie.  I believe the notification daemon I'm using is from MATE.

**Comment by cschramm** [comment]
Do the current fixes (see https://github.com/blueman-project/blueman/issues/311#issuecomment-113864730) help?

**Comment by DavidGriffith** [comment]
The rune no longer turns green.  If the device is trusted, Blueman will silently accept the incoming file.  With the version of Blueman in Debian 7 (1.23), a balloon would pop up asking if it's okay to accept the file transfer.  From here it looks like someone decided to replace this behavior with the idea of "if this device is trusted, silently accept the transfer".  The thought is good, but it you really need to retain the option to have Blueman ask permission every time.  Furthermore, consider whether or not to say anything if something UNtrusted tries to send a file.  Maybe something like this: "An untrusted device, $name, is trying to send a file.  Do you want to accept it?  Ignore further attempts from $name?".

**Comment by cschramm** [comment]
You should of course alway get notifications no matter if the device is trusted or not. This only determines the text and if there are buttons or not. I'll look into why that happens. We refactored a lot signals stuff in the current master version, so there's probably something broken.

**Comment by cschramm** [comment]
Unfortunately I currently don't have the time to take a closer look at this. Could you please test if you have the same issue with release 2.0?

**Comment by DavidGriffith** [comment]
With the 2.0-tagged release, things will work as expected (balloons, green runes, etc) except that no permission is asked if the device is "trusted".  IMHO, there should be an option to ask permission even if the device is "trusted".  Or an I misunderstanding the meaning of "trust" as it applies to Blueman?

**Comment by cschramm** [comment]
Trusted means that the device does not need permission to connect services or send files.

**Comment by cschramm** [comment]
Works for me with current master.

**Comment by yars068** [comment]
On my system, that works, but when I started a transfer, I see dialog about it's state, the progress graph is always empty, nothing reported and dialog does not disappeared at end of transfer. The phone reports succesfully upload. I will attach a log in short time.

**Comment by cschramm** [comment]
Not sure what progress graph you're meaning. The dialog is expected not to disappear as it informs you about the received file and provides a button to open it.

**Comment by timothybarus77** [comment]
hello my name is timo, I have a problem with Blueman and I want to ask, is the "Accept file from trusted device" feature (on local setting -> transfer tab) having problems? I want to use this feature in my project, but when I try to send a file from my cellphone (Android), i got notification fails to send the file on my phone. can you help me? @cschramm 

My device already set in trusted device but didn't work

**Comment by cschramm** [comment]
@timothybarus77: Please open a new issue filling in the base information in the issue template and providing a log from blueman-applet as described in the troubleshooting information it provides.
