### ISSUE TITLE
Unable to scan for devices

### ISSUE THREAD

**Issue by DavidGriffith** [blueman-project/blueman#313]
Attempting to scan for devices fails.  Error log at http://pastebin.com/ACMzWkVq.  Open a Devices dialog and try to scan for devices.  The progress bar appears at the bottom, but nothing will actually happen.  No devices show up.

Using the latest from the repo (741463dac268e25c13379d75234e1470c1e2c076).  Debian Jessie, MATE, Bluez 5,

**Comment by cschramm** [comment]
Do the current fixes (see https://github.com/blueman-project/blueman/issues/311#issuecomment-113864730) help?

**Comment by DavidGriffith** [comment]
The progress bar moves and finishes, but nothing is displayed.

**Comment by cschramm** [comment]
Unfortunately I currently don't have the time to take a closer look at this. Could you please test if you have the same issue with release 2.0?

**Comment by DavidGriffith** [comment]
The 2.0 tag works.  The latest revision that will detect and display devices is c57bd1ecf6f340698066e40ced5894910c6d469e.

**Comment by cschramm** [comment]
OK, thanks for the info. https://github.com/blueman-project/blueman/commit/4d12346508adf224ad25a484ee0ae9623c4410ad is bad. ;) But you say https://github.com/blueman-project/blueman/commit/488b2038c80a3e3a16f37496d005e86ac8f89116 does not work as well? Hm. I'll have a look as soon as I have some time for it.

**Comment by DavidGriffith** [comment]
Correct.

**Comment by DavidGriffith** [comment]
Incidentally, if I pair up with my device using bluetoothctl while blueman-manager is running, the latter will notice this and update itself as expected.
