### ISSUE TITLE
Blueman icon briefly vanishes when turning bluetooth on

### ISSUE THREAD

**Issue by DavidGriffith** [blueman-project/blueman#314]
If Bluetooth is off and you turn it on using a right-click on the icon and selecting "Turn Bluetooth On", the icon will vanish for a quarter of a second and then reappear.  The icon should change from the off type to the on type without doing this vanishing act.

**Comment by cschramm** [comment]
I just had a look at this.

The icon is basically visible whenever bluetooth is soft-locked or adapters are available.

Before taking the action, bluetooth is soft-locked, so the icon is visible.

When enabling it and thus removing the soft lock no adapters are available when querying, so the icon is removed.

As soon as adapters become available, it will be visible again.

**Comment by yars068** [comment]
I think removal of icon is bad idea, IMO we need to change its color, for example, when bluetooth is hard-locked or no adapters available, the icon is gray, with red "x" at bottom-rigt corner, when adapters availabe, but soft-locked, the icon is gray, and so on...

**Comment by cschramm** [comment]
The x icon would be of no use. You cannot do anything with blueman if there's a hard lock or no adapters. And in a desktop environment with blueman pre-installed I would not want to have a Bluetooth widget if I either do not have our disabled Bluetooth.
