### ISSUE TITLE
Clicking the icon when blueman-manager is running should close blueman-manager

### ISSUE THREAD

**Issue by DavidGriffith** [blueman-project/blueman#315]
Many applications that put an icon in the notification area will behave as toggles.  That is, click it once and a window of some sort pops up.  Click it again and the window vanishes.  This doesn't happen with Blueman.  I cloned the repo to see if I could add it myself, but I got lost with the problem of how to properly determine if blueman-manager is already running or not and then how to terminate it.

**Comment by cschramm** [comment]
You can check it like

````python
lockfile = blueman.Functions.get_lockfile('blueman-manager')
if os.path.exists(lockfile):
    pid = blueman.Functions.get_pid(lockfile)
    if pid:
        if blueman.Functions.is_running('blueman-manager', pid):
````

Everything else means it's not running. See `blueman.Functions.check_single_instance`
