### ISSUE TITLE
SerialManager: AttributeError: 'Device' has no attribute 'Address'

### ISSUE THREAD

**Issue by yars068** [blueman-project/blueman#341]
Hi now,
As you noticed, at end of [these log](http://pastebin.com/1Se9GJk7), seen 
```
_________
_on_property_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBase.py:28)
None Connected 0
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/plugins/applet/SerialManager.py", line 59, in _on_device_property_changed
    self.terminate_all_scripts(device.Address)
AttributeError: 'Device' object has no attribute 'Address'
```
That is unrelated to #340, and for that reason, is another issue. Currently, I have no idea on how to fix it :(

**Comment by cschramm** [comment]
We possibly have issues wherever https://github.com/blueman-project/blueman/commit/4d12346508adf224ad25a484ee0ae9623c4410ad drops `path_keyword` and starts relying on the object provided by the glib signal. If this is used on some "Any" object which does not have a path, it also does not have a path and in consequence no properties when the handler is called.

I identified issues at the following places:

BluemanApplet._on_adapter_property_changed
GameControllerWakelock._on_device_property_changed
NetUsage._on_network_property_changed
SerialManager._on_device_property_changed

So it looks like DiscvManager, GameControllerWakelock, NetUsage, and SerialManager are actually broken in master.

**Comment by cschramm** [comment]
I hacked a patch. Completely untested yet. https://github.com/blueman-project/blueman/commit/98abc016842ad0e537ba40059ee84bb9f532cdd2

**Comment by yars068** [comment]
Please see the [log](http://pastebin.com/SMiu04qh) with having this patch. Sending and receiving still works, but we have some tracebacks.

**Comment by cschramm** [comment]
OK, I just checked the patch. It makes those handlers work correctly and fixes the `Address` property issue. I could not replicate your new traceback (I think the second one is just the consequence of the first one). How did you create it? Just by discovering a new device? Also, are you sure that it does not exit without my patch?

**Comment by yars068** [comment]
It appeared whien I tried send/receive file. That's works but only one time, then I get `AttributeError: 'NoneType' object has no attribute 'get_path'`. With my patch this is not appeared, because I  tried sending and receiving many times. With my patch, I have only UnicodeErrors when I tried with a file that have non-ASCII name (characters is out of range(128)).

**Comment by cschramm** [comment]
So that exception also occurs in current master?

> With my patch this is not appeared

Your code breaks and as a consequence disables the SerialManager plugin, so just disabling it should have the same effect then. Unfortunately I cannot spot any connection between the traceback and the SerialManager plugin... :confused:

**Comment by yars068** [comment]
With current master SerialManager works, but I have
```
Destination file exists, renaming to: 20150818130152_05 - A Place for my Head.mp3 
adding action
_________
_on_properties_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/obex/Transfer.py:26)
/org/bluez/obex/server/session3/transfer2 Transferred 0 
_________
_on_properties_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/obex/Transfer.py:26)
/org/bluez/obex/server/session3/transfer2 Status complete 
_________
_on_properties_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/obex/Transfer.py:26)
/org/bluez/obex/server/session3/transfer2 Transferred 0 
_________
_on_session_removed (/usr/lib64/python2.7/site-packages/blueman/bluez/obex/Manager.py:45)
/org/bluez/obex/server/session3 
_________
_on_property_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBase.py:28)
None Connected 0 
_________
_on_property_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBase.py:28)
None Connected 0 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/plugins/applet/SerialManager.py", line 59, in _on_device_property_changed
    self.terminate_all_scripts(device.Address)
AttributeError: 'Device' object has no attribute 'Address'
_________
_on_property_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBase.py:28)
/org/bluez/hci0/dev_C4_43_8F_28_B2_98 Connected 0 
_________
_on_property_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBase.py:28)
/org/bluez/hci0/dev_C4_43_8F_28_B2_98 Connected 0 
```
when tried to receive file.

**Comment by cschramm** [comment]
Sounds like there's a bug in my patch then... Strange that I cannot replicate this...

Maybe the issue was even covered by the Address property issue.

Can you try replacing the `.Address` call in master's `SerialManager.py` with `.get_properties()['Address']`. I think this should also fix the issue. Let's see if you get the `get_path` error then.

**Comment by yars068** [comment]
Yes, that solves the issue, when I receive a file from phone, but when I send file to phone, I get [this](http://pastebin.com/QiSDFc1X).

**Comment by cschramm** [comment]
So it's not related to my patch. I'll add it to master then and look into your issue.
