### ISSUE TITLE
Missing manual PIN entry when pairing

### ISSUE THREAD

**Issue by mr700** [blueman-project/blueman#345]
I have a bluetooth printer and it has predefined fixed key. I can only "Use Random Key" or "Proceed Without Pairing". Blueman used to have manual PIN input, that's how I used my GPS receiver. Please add this option again.

**Comment by cschramm** [comment]
This slipped through, but it should work although it's irritating. If you choose the random passkey option or just pair in the manager window without using the setup dialog you should get a request for the PIN code (the AuthAgent plugin needs to be enabled).

I'll rework the scheme in the setup dialog to improve this.

**Comment by Alecs69** [comment]
Same problem. On the headset fixed PIN and does not provide manual input. AutnAgent included. When connecting the keyboard is also a problem, since it is necessary to dial PIN on the keyboard. But what key was sent is not known.

**Comment by zarkone** [comment]
`bluetoothctl` shows this number -- so in my case, I used both tools because I couldn't enter commands in bluetoothctl without keyboard: 

![1623576820-13-06-21_11:33:40](https://user-images.githubusercontent.com/1899654/121802135-6126c680-cc3b-11eb-9386-6f938719940e.png)
