### ISSUE TITLE
Bluetooth Problems

### ISSUE THREAD

**Issue by gmseed** [blueman-project/blueman#356]
I'm new to the RaspberryPI unit and followed the instructions at:

http://thepihut.com/blogs/raspberry-pi-tutorials/17841464-bluetooth-installing-and-using-bluetooth-on-the-raspberry-pi

and with the bluetooth dongle plugged in to a usb port and calling "lsusb" I get:

...
Bus 001 Device 008: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)

Next, I did:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install bluetooth bluez-utils blueman bluez python-gobject python-gobject-2

All went fine.

Hears were the weird stuff starts! If I select Menu|Preferences|Bluetooth Manager I see the waiting cursor for several seconds and then it goes away without the application being displayed.

However, if I type the following in a terminal window:

sudo blueman-manager

then the "Bluetooth Devices" window is displayed. This seems strange and inconsistent.

Rebooting the RPi I notice at the top right of the GUI desktop window the blue Bluetooth icon. Hovering over the icon it states that bluetooth is enabled but if I select the "Adaptors..." menu item it brings up a daft window that just says "Close", which is pretty is not much use. If I then select Menu|Preferences|Bluetooth Manager I again get the wait cursor for a few seconds and then it goes away, and there still remains just 1 bluetooth icon on the main desktop bar. Selecting "Adaptors..." again gives the useless Close window. If I then type "sudo blueman-manager" in a terminal window the app gui pops up and I get a 2nd bluetooth icon on the desktop toolbar. Right-clicking the 1st bluetooth icon still gives Close when selecting Adaptors... whereas the 2nd icon brings up the expected "Bluetooth Adaptors" dialog. I do find this multiple instances thing a bit weird.

Next, I follow the above url article and select "Adapter|Preferences" and make the RPi bluetooth dongle always visible.

I then ensure that my Android tablet and watch are in range (ie; right next to the RPi!) and guess what ... they don't appear in the devices list in Bluetooth Devices. Even doing a search doesn't make them popup. All of the devices in the list have "Unknown" under them and a key next to the blue icon.

I also found this article:

http://www.modmypi.com/blog/installing-the-raspberry-pi-nano-bluetooth-dongle

and typed:

/etc/init.d/bluetooth status

and get:

[ ok ] bluetooth is running.

However, the command:

hcitool scan

just gives me:

Scanning ...

with no results of nearby devices.

Baffling! Has anyone else seen this and know a solution?

By the way, I also have a wifi dongle (used for Internet connection) plugged into one of the 4 usb ports. I assume that it can handle both wifi and bluetooth dongles at the same time.

My RPi unit is just a couple of weeks old and the Model 2 B type and running Raspian OS.

Thanks.
Graham

**Comment by yars068** [comment]
> sudo blueman-manager

That should be used under the regular user account, so no need to use sudo. This command is launches the "Bluetooth Devices" window, and I'm not sure that behavior are wrong. But, invoking this command as root should be produce a "unknown display" error and then exited with non-zero exit status.
What `hcitool dev` said about your bluetooth  dongle?
About managing Wi-Fi: that is not a blueman goal, to use Wi-Fi, you need another program, such as NetworkManager.
I am not a developer and all that I'd said is just my opinion.

Are you sure that your BT dongle is works fine? Please provide the output to the console from blueman-applet.
