### ISSUE TITLE
Icon label

### ISSUE THREAD

**Issue by cschramm** [blueman-project/blueman#372]
Unfortunately our mailing list archive is somehow inaccessible (@stefano-k: ?) , so I cannot link to it, but Raphaël POITEVIN reported the following there:

> When I want to
> access to the bluetooth icon, I get the applet by pressing ctrl alt tab
> to move on it and I press tab till the focus reach on the icon
> bluetooth. I notice this icon has no label because Orca says "icon".

**Comment by infirit** [comment]
One reason could be that Atk is not properly initialized when we only call GObjects ``__init__`` function. If so then [this](https://github.com/blueman-project/blueman/commit/07afca4cc142217c27b7e4ee2d5a830bebdbf06f#diff-dc542289623a34161b680b82e42e275e) hopefully will fix that.
