### ISSUE TITLE
bluetooth not detected i have samsung series 5 model NP530U. thanx

### ISSUE THREAD

**Issue by jaqol** [blueman-project/blueman#394]
![bluetooth](https://cloud.githubusercontent.com/assets/16015034/11394827/72421104-93a2-11e5-9a2c-72f5193b66a1.png)

**Comment by cschramm** [comment]
You do not have a (supported) adapter. Please check https://github.com/blueman-project/blueman/wiki/Troubleshooting#no-adapter-or-not-able-to-turn-on-bluetooth.
