### ISSUE TITLE
Pairing, cannot insert the key

### ISSUE THREAD

**Issue by MS893** [blueman-project/blueman#395]
When I search for a new device (using add new device in the menu), I can see my device, then I jsut can select random key or no association, but my device request a generic key (0000) that I have no possibility to insert the key...
Can you modify the pairing assistant or explain in the operation how to do it ?
THANKS !

**Comment by MS893** [comment]
Sorry, I just see that this was already reported as a bug.... MEA CULPA !

**Comment by cschramm** [comment]
#345 I'm hoping to get to it soon.
