### ISSUE TITLE
Two icons in the dash board

### ISSUE THREAD

**Issue by MS893** [blueman-project/blueman#396]
In the dash board, when adding the greffon (indicator), I have two icons for bluetooth, 1 for switching ON or OFF the bluetooth and the devices, 1 for general menu managing bluetooth.

Is it possible to group these two icons in only one ?

Thanks.

**Comment by cschramm** [comment]
What dashboard? Are you talking about tray icons? I doubt that they are both blueman's.

**Comment by MS893** [comment]
Yes tray icons... (in the bar on top screen or bottom)

I will sens a screen capture when back home (sunday).

One icon with BT configuration menu (with enable/disable option) and one with switches to change between ON and OFF and list of paires devices in which you have also switches to connecter device.

**Comment by yars068** [comment]
Which distribution you are running on?

**Comment by MS893** [comment]
I tell you when back home.

This problem is for long time and several xubuntu updates.

**Comment by MS893** [comment]
xubuntu...

**Comment by yars068** [comment]
Possible it is, because blueman uses libappindicator3, which is part of ubuntu-based distributions. Xfce have a system tray, which have a similar functionality as libappindicator. I use Slackware with Xfce and that does *not* use libappindicator anymore, so I have no problem with that.

**Comment by MS893** [comment]
Here are the screen captures...

![capture d ecran_2015-11-29_14-04-15](https://cloud.githubusercontent.com/assets/12143016/11457233/6c290972-96a3-11e5-80db-759596e73ee2.png)
![capture d ecran_2015-11-29_14-06-03](https://cloud.githubusercontent.com/assets/12143016/11457234/6c29fb84-96a3-11e5-9909-2bc1dc69194b.png)
![img_20151129_140135](https://cloud.githubusercontent.com/assets/12143016/11457235/6c2bbfbe-96a3-11e5-805a-102d0b528f11.jpg)
![img_20151129_140238](https://cloud.githubusercontent.com/assets/12143016/11457236/6c2dacc0-96a3-11e5-82b0-cc628c90e4bc.jpg)

**Comment by infirit** [comment]
The first one is __not__ blueman and from the looks of it it most likely is gnome-bluetooth. Do you have gnome-bluetooth installed and is it running?

**Comment by MS893** [comment]
I don't know.
Here is the blueman-applet informations :
![capture d ecran_2015-11-29_14-49-35](https://cloud.githubusercontent.com/assets/12143016/11457584/0d7bce00-96ad-11e5-9d31-39ac3b5f6881.png)
![capture d ecran_2015-11-29_14-50-16](https://cloud.githubusercontent.com/assets/12143016/11457585/0d7da7a2-96ad-11e5-88de-4eaa633093e3.png)

**Comment by infirit** [comment]
I just checked my vm and the first one is definitely gnome-bluetooth. You will need to prevent gnome-bluetooth from loading or remove gnome-bluetooth with the ubuntu package manager of choice.

**Comment by MS893** [comment]
I've removed gnome-bluetooth (gnome-bluetooth 3.16.1-1ubuntu2), but I still have 2 icons in the top bar.

Anyway, if I cannot remove one (or in fact merge the 2 icons), I give up I have this for a long time, and I'm not dead :-)

Thanks for trying to help

**Comment by infirit** [comment]
>but I still have 2 icons in the top bar

Just removing will not stop the still running process. Run the following command to kill it.
``
kill `pgrep gnome-bluetooth`
``

**Comment by MS893** [comment]
Yes I know, I have rebooted my computer after uninstalling gnome-bluetooth and there is no more process.

The 2 icons are not due to gnome_bluetooth, but the xfce4-indicator-plugin which display 2 icons. The problem is not from Blueman...

I don't know which alternative I have for the greffon (indicator plugin)...

Anyway, it's not a big problem, just not logical to have 2 icons for the same function. Thanks

**Comment by cschramm** [comment]
The gnome-bluetooth version shipped with wily should not have bluetooth-applet anymore, so basically it makes sense that removing that package does not have the expected effect. The applet is now provided by gnome-shell. I guess it uses the package libgnome-bluetooth13 so you can you check if it's installed and if removing it (is possible) and removes the other icon?

**Comment by MS893** [comment]
Yes libgnome-bluetooth13 is installed, but how can I uninstall it ?

**Comment by MS893** [comment]
I have done this : sudo apt-get remove libgnome-bluetooth13 to remove it, and now I have 1 icon, but "no indicator" displayed also !!!
![capture d ecran_2015-11-29_20-10-39](https://cloud.githubusercontent.com/assets/12143016/11459360/4965ba20-96d5-11e5-88aa-51393c49f05d.png)

**Comment by cschramm** [comment]
I guess that removed the only libindicator icon from xfce4-indicator-plugin so that it now displays a placeholder. You can get rid of it by removing it from the panel or uninstalling it completely.

**Comment by MS893** [comment]
Thanks, that's all good now !

I have reinstall the libgnome-bluetooth13, than I removed the indicator greffon from the tab, and I added other elements and now I have only one bluetooth icon in the notification element.

So my problem is solved, thank you very much for your patience !

![capture d ecran_2015-11-29_20-43-25](https://cloud.githubusercontent.com/assets/12143016/11459573/e49977c6-96d9-11e5-897a-c8bcfa71c58e.png)
