### ISSUE TITLE
Fedora 23: I cannot send files thru bluetooth to Windows 8.1

### ISSUE THREAD

**Issue by TJProgrammer** [blueman-project/blueman#404]
I open the blueman manager and the other PC with windows 8.1 are paired but the send files button is disable.
I'm using a Logilink usb bluetooth v4.0 dongle.
I've my PC upddated:
Linux 4.2.6-301.fc23.i686+PAE #1 SMP Fri Nov 20 22:42:36 UTC 2015 i686 i686 i386 GNU/Linux

**Comment by cschramm** [comment]
That means the device does not offer an OBEX Push service.
