### ISSUE TITLE
Cannot add keyboard or mouse through graphical interface

### ISSUE THREAD

**Issue by Carl393** [blueman-project/blueman#407]
I cannot pair a device using blueman applet...because it asks for a pin, and I am unable to enter it anywhere..

The only way I could pair both my keyboard and mouse was to refer to the website below.... and do it manually through the shell entering all of these commands
https://wiki.archlinux.org/index.php/Bluetooth_keyboard
this process should be easier..

**Comment by Carl393** [comment]
https://wiki.archlinux.org/index.php/Bluetooth_keyboard

**Comment by cschramm** [comment]
I did not get your issue, sorry.

**Comment by Carl393** [comment]
hello, i'm on debian jessie 8.2, you don't have the menu on "setup new bluetooth device" after pairing, you can input a number like 0000 ? but then you cannot type this in on the device (such as a mouse) so it does not pair.

**Comment by cschramm** [comment]
If you're asked for a PIN the device asks for it. It's usually preset. Read the device's documentation to find out how the process is supposed to work.

**Comment by cschramm** [comment]
0000 and 1234 are always good guesses in that situation. ;)

**Comment by cschramm** [comment]
So you set a `KeyboardOnly` agent in `bluetoothctl`, initiate pairing, are shown a PIN in the terminal and enter it on the new keyboard?

In blueman you initiate the pairing and are asked for a PIN? Did you try entering something (with a connected keyboard) and the repeating that sequence on the new keyboard?

**Comment by Carl393** [comment]
Yes sir! KeyboardOnly command in bluetoothctl like the archlinux website says! it then assigns me a random PIN when I type pair A1:0E (etc...) when I type connect A1:0E (Etc) afterwards it requests the PIN and I can type this PIN in from my bluetooth keyboard... however I cannot do this from the graphical interface (applet)

**Comment by cschramm** [comment]
I guess the only difference is that bluetoothctl chooses a random key while blueman asks you to set one. Did you try that?

**Comment by Carl393** [comment]
I believe the issue is... the PIN is randomly generated you are correct! however the blueman asks you to set one.. I tried both 0000 and 1234 and neither worked...

Why is it that the bluetoothctl works when it is randomly generated? and on the applet there is nowhere to input this information?

**Comment by Carl393** [comment]
in fact you can ask blueman to generate a PIN and it does but afterwards you cannot input it anyhere (there is no input box)

Many other people on forums are running into this problem. Either that or I simply am not doing something right..

**Comment by cschramm** [comment]
I think you have to e.g. enter something with a connected keyboard when blueman asks you for a PIN. After submitting, type the same sequence with the new keyboard. I'll check the bluetoothctl code to see in what cases it chooses a random key.

**Comment by cschramm** [comment]
Cannot see any such random choosing in the code.

A quick test you can do: Use a KeyboardDisplay agent in bluetoothctl and see how that changes the process. It's the same capability the blueman agent uses.

The more involving way to get behind it: Stop the bluetooth service (make sure blueman, bluetoothctl and similar are not running; they would restart it automatically) and start bluetoothd manually adding the -d option. You will get debugging messages in the syslog (daemon.log) then and we can compare the events when using blueman and when using bluetoothctl.

**Comment by Carl393** [comment]
you are correct I enter with a connected keyboard.. 0000.... then it says "please enter the PIN on your device" but there is no input window anywhere to input 0000.... so I find this confusing....

**Comment by Carl393** [comment]
I tried just not typing bluetoothctl on my already connected bluetooth keyboard.... and then the connection failed suddenly even though blueman applet says it is connected

this is very disappointing.

**Comment by cschramm** [comment]
> then it says "please enter the PIN on your device" but there is no input window anywhere to input 0000.... so I find this confusing....

Aha! Yes, blueman does not (yet) indicate the progress of your typing. But does it work or not?

**Comment by Carl393** [comment]
no it does not.. it automatically says FAILED...

Can you see how this is confusing for people who want to use graphical interface? how is the user even supposed to know if the applet is accepting the 0000 or other PIN that is being typed

In the Shell when i type pair A0:23 etc....the agent gives me the PIN code...then I type 'trust' A0:23 
which works... then i type 'connect A0:23 etc' but it never asks for the PIN code why is that?

**Comment by Carl393** [comment]
I find this confusing as well... am I doing something wrong?
![screenshot - 091215 - 09 54 46 pm](https://cloud.githubusercontent.com/assets/14049856/11709921/78f97f26-9ee9-11e5-8ed4-0358d891233c.png)

**Comment by Carl393** [comment]
I have tried the instructions here
https://wiki.archlinux.org/index.php/Bluetooth_keyboard

exactly and the device does not register... it works.. then I either get authentication error... or when I type quit... the Agent does not register.

**Comment by Carl393** [comment]
I can get the keyboard to work but no matter what I do... I can not get the device to pair...
as you can see I can get the keyboard to be trusted but I cannot pair.. so I have to keep adding the keyboard again every time I boot up. is this a bug
![screenshot - 101215 - 12 11 58 am](https://cloud.githubusercontent.com/assets/14049856/11712693/b347c814-9efc-11e5-8593-a7d7e4086f47.png)

**Comment by infirit** [comment]
Are you using separate bluetooth dongle or the one that came with the keyboard and mouse? If so and when following the wiki instructions for bluetoothctl, it looks like you skipped the step that sets the dongle pairable, ``[bluetooth]# pairable on``.

When I un-break my machine I'll have a look how blueman behaves.

**Comment by Carl393** [comment]
The dongle is already paired to my bluetooth mouse is this the problem ? (cannot be paired to two devices at the same time) my dongle did not come with either device it is one I purchased ages ago for use with my hp printer. I tried what you suggested pairable: on and doesn't work.

**Comment by Carl393** [comment]
Hello Please advise, I have set up my bluetooth keyboard after typing connect there is no prompt that asks you to enter the PIN and then hit enter... Can you fix this for the command line view?
I just tried typing in the PIN assigned without me asking for it... when I hit enter it worked!

It would be much easier if the terminal requests that the PIN be entered after typing "Connect 20:15:09:29:01:1F' and that you hit enter... as this isn't obvious.

On a further note. When I type the PIN in blueman applet.. and hit enter.. it does not work at all..
Could you duplicate the same prompts for the graphical interface? as the pairing process only works from the terminal.

Thank you for your help!

Whoever is in charge of the programing of blueman can you introduce these

**Comment by jamesjohn911** [comment]
when you try to pair and it gives you the pin you have to type the pin into your bluetooth keyboard your trying to pair then hit enter on same keyboard then it should work... im having similar problem with raspi3 bluetooth same issue wont pair my bluetooth keyboard or my bluetooth headset but will pair my galaxy s5 mobile (and use it for networking) and hp pavilion dv7 laptop. i also tryed to pair bt keyboard with terminal commands but still comes up not paired in the end sooo frustrating Aaargh!!!

**Comment by Carl393** [comment]
Hi JamesWould you like to correspond about raspi3 I just bought one!                                                                                                                                                                                                                                                                                                                                        Carl                                                                                                                                                                                                                From: James MoretonSent: Thursday, March 31, 2016 1:23 PMTo: blueman-project/bluemanReply To: blueman-project/bluemanCc: Carl393Subject: Re: [blueman-project/blueman] Cannot add keyboard or mouse through graphical interface (#407)when you try to pair and it gives you the pin you have to type the pin into your bluetooth keyboard your trying to pair then hit enter on same keyboard then it should work... im having similar problem with raspi3 bluetooth same issue wont pair my bluetooth keyboard or my bluetooth headset but will pair my galaxy s5 mobile (and use it for networking) and hp pavilion dv7 laptop. i also tryed to pair bt keyboard with terminal commands but still comes up not paired in the end sooo frustrating Aaargh!!! 

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by jamesjohn911** [comment]
Hi Carl mate yeah sure i'll correspond with you on RasPi3 its way better
than raspi2 bit of a pain to set up the bluetooth drivers and pair certain
devices that dont wanna pair for some stupid reason ...

do you own a cirrus audio card for your raspberry pi..??

regards
James Moreton

On Thu, Apr 21, 2016 at 10:29 AM, Carl393 <notifications@github.com> wrote:

> Hi JamesWould you like to correspond about raspi3 I just bought one! Carl
> From: James MoretonSent: Thursday, March 31, 2016 1:23 PMTo:
> blueman-project/bluemanReply To: blueman-project/bluemanCc: Carl393Subject:
> Re: [blueman-project/blueman] Cannot add keyboard or mouse through
> graphical interface (#407)when you try to pair and it gives you the pin you
> have to type the pin into your bluetooth keyboard your trying to pair then
> hit enter on same keyboard then it should work... im having similar problem
> with raspi3 bluetooth same issue wont pair my bluetooth keyboard or my
> bluetooth headset but will pair my galaxy s5 mobile (and use it for
> networking) and hp pavilion dv7 laptop. i also tryed to pair bt keyboard
> with terminal commands but still comes up not paired in the end sooo
> frustrating Aaargh!!!
>
> —You are receiving this because you authored the thread.Reply to this
> email directly or view it on GitHub
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/blueman-project/blueman/issues/407#issuecomment-212699357>
>



-- 
renegade_911

**Comment by Carl393** [comment]
Don't really want to bump a dead thread
Maybe just send me your email./

Carl

**Comment by infirit** [comment]
Old one, but I read that some keyboards just can not pair and we should instead mark them as trusted. Does marking the device as trusted make it keep it's connection?

**Comment by Carl393** [comment]
Yes                                                                                                                                                                                                                From: Sander SweersSent: Sunday, August 21, 2016 10:55 AMTo: blueman-project/bluemanReply To: blueman-project/bluemanCc: Carl393; AuthorSubject: Re: [blueman-project/blueman] Cannot add keyboard or mouse through graphical interface (#407)Old one, but I read that some keyboards just can not pair and we should instead mark them as trusted. Does marking the device as trusted make it keep it's connection?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/blueman-project/blueman","title":"blueman-project/blueman","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/blueman-project/blueman"}},"updates":{"snippets":[{"icon":"PERSON","message":"@infirit in #407: Old one, but I read that some keyboards just can not pair and we should instead mark them as trusted. Does marking the device as trusted make it keep it's connection?"}],"action":{"name":"View Issue","url":"https://github.com/blueman-project/blueman/issues/407#issuecomment-241262266"}}}

**Comment by dyyzhmm** [comment]
So, what's the situation now? I has been working on this bug for a week.
