### ISSUE TITLE
Privilege escalation in blueman dbus API

### ISSUE THREAD

**Issue by anisse** [blueman-project/blueman#416]
Just saw this online:
https://twitter.com/thegrugq/status/677809527882813440

Seems related to this:
https://github.com/blueman-project/blueman/blob/5b6308507e51699c9b5d3d6f4774f28cf6d94bd8/blueman/plugins/mechanism/Network.py#L56

**Comment by cschramm** [comment]
On it. Thanks for reporting!

**Comment by cschramm** [comment]
Could somebody (@infirit?) please review https://github.com/blueman-project/blueman/commit/0e9b15da86d941a1a20025503248a0fa0ed1b757? I'll put it into master and 2-0-stable and do a 2.0.3 security release then.

**Comment by infirit** [comment]
Works for me and gets rid of eval. I did make another suggestion on the commit, either one is fine by me.
