### ISSUE TITLE
Samsung Wireless Audio - Connection Failed

### ISSUE THREAD

**Issue by sgaucoin** [blueman-project/blueman#421]
Device is found. Can pair and trust but audio sink connects and disconnects immediately.

Linux Mint 17.3
Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)

**Comment by infirit** [comment]
Outside of the profile switching blueman does not do anything special and should be similar to using ``bluetoothctl``. Can you follow the steps described in __debugging__ section on the following page, https://github.com/blueman-project/blueman/wiki/Troubleshooting and paste them to paste site or a github gist?

**Comment by sgaucoin** [comment]
thanks for looking into this...here the gist link

https://gist.github.com/sgaucoin/4d03e865c3c4d421a255

**Comment by cschramm** [comment]
Can't see anything wrong except you're using a very old version of blueman. I'd suggest to try a newer one and / or bluetoothctl.

**Comment by sgaucoin** [comment]
Thanks. The bluez' version is the package that comes with the recent stable
version of Linux Mint. Ubuntu (Mint's base) has been extremely slow on
upgrading (i.e. I think over 4 years) to the newer version. Will attempt to
compile/install bluez 5.37.

**Comment by infirit** [comment]
Upgrading BlueZ is a PITA as you will likely also need a newer version of pulseaudio. Better is to just try blueman 2.0.X from a more recent ubuntu release and see how it goes. I think wily should do but as a gentoo guy I am not too familiar with binary distro's.

**Comment by sgaucoin** [comment]
PITA is an understatement....spent most of the morning
compiling/making/breaking to no avail. Since this is a relatively new ditro
installation, I may just nuke and pave and install something more bluez 5
friendly. I'm thinking Ubuntu Wily but any suggestions are welcome. I'm not
too familiar with linux distros.

**Comment by cschramm** [comment]
You can just download a recent package e.g. [here](http://packages.ubuntu.com/xenial/blueman#pdownload) and install it with e.g. `dpkg`. The dependencies should work in Linux Mint 17.3 (you may need to run `aptitude safe-upgrade` after `dpkg` to install them).

You can also try to connect with `hcitool` and see what the result is there.

**Comment by sgaucoin** [comment]
Thanks for the reply. Tried multiple times installing more recent bluetooth
packages but nothing worked with Mint 17.3. Since it was a clean install, I
just decided to try other packages. I've installed Ubuntu Wily 15.10 which
has the latest bluez package and everything works fine.

Thanks again.

Stephane

**Comment by infirit** [comment]
Ok, thanks, I'll close it then.
