### ISSUE TITLE
RFC: Drop Python2

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#425]
This allows us to remove some ugly code like below to check for strings.
```python
if hasattr(instance, "format") and hasattr(instance, "upper"):
```

AFAIK all ditro's now have a recent enough python 3 version.

**Comment by yars068** [comment]
Please no! :) Slackware currently will keep python2.

**Comment by infirit** [comment]
:sob:, also not in the next release @yars068 ?

**Comment by yars068** [comment]
The next release still not ready, currently it is a 14.2 beta. But, maybe Patrick will migrate to Python3, or do Python2/Python3 mix, I don't know. This time, we still have Python2... :-(

**Comment by cschramm** [comment]
I think specific handlings for python 2 (__builtins__ and hasattr) account for less than 10 lines of code. Not a big thing.

**Comment by infirit** [comment]
It is not just the code. It is the maintenance of keeping things working in both versions. For example I saw you GVariant map in the gdbus branch that maps the python types to variant signatutres which  was missing the ``unicode`` type so it would have failed running on python2.

But it is not a big problem for now but I will pester ppl again after blueman 2.1 :smiling_imp:
