### ISSUE TITLE
TransferService, standalone obexd and Bluez5

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#426]
In the TransferService applet plugin we have the below fixme. Is this still relevant now that bluez4 is no more supported? If not I'll remove it :smile:.

```
# stand-alone obexd
            # FIXME: /tmp is only the default. Can we get the actual root
            # directory from stand-alone obexd?
            root = '/tmp'
```

**Comment by cschramm** [comment]
No, stand-alone obexd was BlueZ 4, so this is obsolete.
