### ISSUE TITLE
Failed to apply network settings Exception: dnsmasq failed to start. Check the system log for errors

### ISSUE THREAD

**Issue by vinnitu** [blueman-project/blueman#438]
How to debug?

I have Ubuntu 14.04.3 LTS 64bit

**Comment by infirit** [comment]
The error should be in your system log, /var/log/message I guess for 14.04.

**Comment by vinnitu** [comment]
hm, I haven't /var/log/mes* files at all, what elese?

**Comment by vinnitu** [comment]
it was present wrong /etc/dnsmasq.conf
