### ISSUE TITLE
Blueman Assistant: no adapter found

### ISSUE THREAD

**Issue by francesco1119** [blueman-project/blueman#451]
On Debian Jessie the Bluetooth Manager seems installed correctly.
However if I press on setup new device it says: `Blueman Assistant: no adapter found`.
My bluetooth is an Atheros AR9485 and the [driver](https://packages.debian.org/jessie/kernel/firmware-atheros) is correctly installed.

What to do?

**Comment by yars068** [comment]
First, please read [Troubleshooting article](https://github.com/blueman-project/blueman/wiki/Troubleshooting).

**Comment by francesco1119** [comment]
blueman: 1.99.alpha1
BlueZ: Version: 5.23-2+b1
Distribution: Debian Jessie
Desktop environment: Cinnamon

I have no idea how to test my bluetooth with "bluez-test-adapater list" (BlueZ 4) or "bluetoothctl list" (BlueZ 5) as **there is no documentation out there!**

...and I'm not the only one who find it hard to debug:

http://danielhnyk.cz/bluetooth-linux-indecipherable-mystery/

**Comment by infirit** [comment]
>I have no idea how to test my bluetooth with

You have to run them from a terminal emulator window, in your case it will be ``bluetoothctl list``. I updated the wiki so it hopefully is more clear now.

**Comment by 1nf1del** [comment]
bluetoothctl list shows Nothing

**Comment by don-dev** [comment]
Seems old, but for context,... came here from System76\pop_OS upgrade where they suggest installing blueman to diagnose. Bluetooth Manager shows no adapters and list command returns 0 out
