### ISSUE TITLE
DeviceMenu: Services not available until paired but still available to connect to

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#454]
For example, the audio and network interfaces for a mobile phone are not exposed until we paired. We should probably raise some sort of exception or return something for the modules in `blueman/services` so the DeviceMenu can handle it. My suggestion would be to still show them but the user can not select them, the device exposes them in the uuids.

**Comment by cschramm** [comment]
Is this about the dbus interfaces? So it's probably BlueZ 4 related and those obsolete, right?

**Comment by infirit** [comment]
It is about services like pan which i can try to enable but unless the device is paired they will fail. Either we should inutiate a pair before connecting the service or grey the menu item so they can't be enabled (perhaps with tooltip to pair first).

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cschramm** [comment]
Ah, right, `Network1` is still there...

**Comment by cschramm** [comment]
Ref #208

**Comment by cschramm** [comment]
Still relevant?

**Comment by infirit** [comment]
Don't think so, I'll add the to my poke list for this weekend :-)

**Comment by infirit** [comment]
This is handled now, closing.
