### ISSUE TITLE
SDP needs an update

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#469]
I think SDP.py has not seen an update in quite a while. I can do this but I am having trouble finding these magic numbers so it would be nice if someone can walk me through how to do this with UUID ``00001132-0000-1000-8000-00805f9b34fb`` and I'll take care of the rest.

edit: the values I am missing for my phone are: 0x1132, 0x1800 and 0x1801
```python
for uuid in phone['UUIDs']:
	print(uuid)
	uuid16 = uuid128_to_uuid16(uuid)
	print(uuid16)
	print(uuid16_to_name(uuid16))

	
00001105-0000-1000-8000-00805f9b34fb
4357
OBEX Object Push
0000110a-0000-1000-8000-00805f9b34fb
4362
Audio Source
0000110c-0000-1000-8000-00805f9b34fb
4364
Remote Control Target
0000110d-0000-1000-8000-00805f9b34fb
4365
Advanced Audio
0000110e-0000-1000-8000-00805f9b34fb
4366
Remote Control
00001112-0000-1000-8000-00805f9b34fb
4370
Headset Audio Gateway
00001116-0000-1000-8000-00805f9b34fb
4374
Network Access Point
0000111f-0000-1000-8000-00805f9b34fb
4383
Handsfree Audio Gateway
0000112f-0000-1000-8000-00805f9b34fb
4399
Phonebook Access (PBAP) - PSE
00001132-0000-1000-8000-00805f9b34fb
4402
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/blueman/Sdp.py", line 217, in uuid16_to_name
    return uuid_names[uuid16]
KeyError: 4402
```

**Comment by cschramm** [comment]
Updated it in #470. Bluetooth SIG publishes short UUIDs under Assigned Names -> [Service Discovery](https://www.bluetooth.com/specifications/assigned-numbers/service-discovery).

Note that our AppleAgent service is not a standard service. Looks like it comes from BlueZ: http://git.kernel.org/cgit/bluetooth/bluez.git/tree/lib/sdp.h#n157
