### ISSUE TITLE
bluetooth automatically turn on 

### ISSUE THREAD

**Issue by rrishichauhan** [blueman-project/blueman#475]
i am using dell vostro 3000 series whenever i closed my lid and again open it. bluetooth automatically turn on .. why please tell me

**Comment by infirit** [comment]
In recent versions (2.0) of blueman the powermanager plugin will turn it on. You can check with ``gsettings get org.blueman.plugins.powermanager auto-power-on`` and if true change it with ``gsettings set org.blueman.plugins.powermanager auto-power-on false`` (or use dconf-editor).

**Comment by cschramm** [comment]
No need to use gsettings. It's also available through the UI in the plugin settings.

**Comment by infirit** [comment]
>UI in the plugin settings

:+1:, how can I forget something like that :confused:

**Comment by infirit** [comment]
Closing, if there still is an issue feel free to reply and we can re-open.
