### ISSUE TITLE
blue tooth bose linux mint

### ISSUE THREAD

**Issue by lavardin13** [blueman-project/blueman#485]
i cannot connect with linuxmint rosa trhu bluetooth my sound link?
?

how to do it?
it work easily with  windows-so why is it so difficult with linux?

it seems that there is an error with the bluetooth program in linux
I tried many times and it never work-why? also it works easily in 3sec with windows7
thanks for your help

**Comment by infirit** [comment]
Have a look at the troubleshooting page https://github.com/blueman-project/blueman/wiki/Troubleshooting. There is a new entry about A2DP which I hope will solve the problem for you.

**Comment by cschramm** [comment]
Possibly #492?
