### ISSUE TITLE
No bluetooth devce found (ever)

### ISSUE THREAD

**Issue by educobian** [blueman-project/blueman#490]
Since installing Linux Mint 17.3 bluetooth has never worked.
I have installed latest bios (lenovo b50-10. bios v: 2.05) and latest linux kernel (4.5. At least now shutdown works).

```
$ rfkill list
0: ideapad_wlan: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: ideapad_bluetooth: Bluetooth
	Soft blocked: no
	Hard blocked: no
2: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
3: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
```

**Comment by infirit** [comment]
Please look at [this](https://github.com/blueman-project/blueman/wiki/Troubleshooting#reporting-a-bug--asking-for-support) and provide the output of both the applet and manager. Make sure to paste them to a pastebin or a [gist](https://gist.github.com/).

Also please confirm the version of BlueZ and blueman.

**Comment by educobian** [comment]
Hi. Thanks.
Not sure to be able to do as you ask.
blueman version: 1.23.
BlueZ version: I don't know how to look at it but I re-installed it yesterday.
blueman-applet:
    `$ blueman-applet 
Loading configuration plugins
blueman-applet version 1.23 starting
Using gconf config backend
_________
Load (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:54)
['StatusIcon', 'DBusService', 'AuthAgent', 'PulseAudio', 'Headset', 'SerialManager', 'Networking', 'ShowConnected', 'StandardItems', 'DhcpClient', 'NMDUNSupport', 'KillSwitch', 'NMPANSupport', 'RecentConns', 'TransferService', 'PowerManager', 'Menu', 'NetUsage', 'ExitItem', 'PPPSupport', 'AppIndicator', 'DiscvManager'] 
Using gconf config backend
_________
Load (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:54)
Unable to load plugin module AppIndicator
No module named appindicator 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'> 
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.DBusService.DBusService'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.Headset.Headset'> 
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.Networking.Networking'> 
Using gconf config backend
_________
load_nap_settings (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/Networking.py:30)
Loading NAP settings 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.Menu.Menu'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'> 
Using gconf config backend
_________
update_menuitems (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/DiscvManager.py:114)
warning: Adapter is None 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.PulseAudio.PulseAudio'> 
Using gconf config backend
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
1 
_________
on_load (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/PulseAudio.py:160)
PulseAudio version: [4, 0, 0] 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'> 
Using gconf config backend
_________
on_load (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/KillSwitch.py:25)
Using the new killswitch system 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.DhcpClient.DhcpClient'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.TransferService.TransferService'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'> 
Using gconf config backend
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
Not loading PPPSupport because it's conflict has higher priority 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
Not loading NMPANSupport because it's conflict has higher priority 
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
2 
_________
update_state (/usr/lib/python2.7/dist-packages/blueman/main/KillSwitchNG.py:162)
State: True 
_________
on_switch_added (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/KillSwitch.py:45)
killswitch registered 1 
_________
on_obex_owner_changed (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/TransferService.py:70)
obex owner changed: :1.43 
Using gconf config backend
_________
on_dbus_name_owner_change (/usr/bin/blueman-applet:81)
org.bluez owner changed to :1.3 
_________
set_nap (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/Networking.py:63)
set nap False 
_________
register_agent (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/AuthAgent.py:51)
Registering agent 
_________
initialize (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/RecentConns.py:136)
rebuilding menu 
_________
update_state (/usr/lib/python2.7/dist-packages/blueman/main/KillSwitchNG.py:162)
State: True 
_________
on_switch_added (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/KillSwitch.py:45)
killswitch registered 4 
_________
enumerate_connections (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/ShowConnected.py:48)
Found 0 existing connections 
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
3 
_________
on_started (/usr/lib/python2.7/dist-packages/blueman/main/applet/Transfer.py:72)
opp Started 
_________
on_started (/usr/lib/python2.7/dist-packages/blueman/main/applet/Transfer.py:72)
ftp Started 
_________
on_adapter_property_changed (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000112d-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001105-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1) 
_________
on_adapter_property_changed (/usr/lib/python2.7/dist-packages/blueman/plugins/applet/DiscvManager.py:87)
prop UUIDs dbus.Array([dbus.String(u'00001000-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001001-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000112d-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001112-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111f-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000111e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001105-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001106-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1) 
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
4 
_________
<lambda> (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:318)
1 
`

bueman-manger:
`$ blueman-manager
Loading configuration plugins
Using gconf config backend
_________
Load (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:54)
['PulseAudioProfile', 'Services'] 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.manager.Services.Services'> 
_________
__load_plugin (/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.manager.PulseAudioProfile.PulseAudioProfile'> 
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
1 
blueman-manager version 1.23 starting
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
2 
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
3 
_________
pa_context_event (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:306)
4 
_________
on_pa_ready (/usr/lib/python2.7/dist-packages/blueman/plugins/manager/PulseAudioProfile.py:27)
connected 
_________
<lambda> (/usr/lib/python2.7/dist-packages/blueman/main/PulseAudioUtils.py:318)
1 
_________
on_bluez_name_owner_changed (/usr/bin/blueman-manager:112)
org.bluez owner changed to  :1.3 
Using gconf config backend
_________
SetAdapter (/usr/lib/python2.7/dist-packages/blueman/gui/DeviceList.py:276)
None 
_________
on_adapter_changed (/usr/lib/python2.7/dist-packages/blueman/gui/manager/ManagerToolbar.py:70)
toolbar adapter /org/bluez/646/hci0`

Hardware:
`$ sudo lshw
[sudo] password for yoda: 
yoda-lenovo-b50-10        
    description: Notebook
    product: 80QR (LENOVO_MT_80QR_BU_idea_FM_Lenovo B50-10)
    vendor: LENOVO
    version: Lenovo B50-10
    serial: MP08K1Z5
    width: 64 bits
    capabilities: smbios-2.7 dmi-2.7 vsyscall32
    configuration: administrator_password=disabled boot=normal chassis=notebook family=IDEAPAD frontpanel_password=disabled keyboard_password=disabled power-on_password=disabled sku=LENOVO_MT_80QR_BU_idea_FM_Lenovo B50-10 uuid=CB79194E-0F1B-E511-A26A-F0761CDF31B0
  *-core
       description: Motherboard
       product: Lenovo B50-10
       vendor: LENOVO
       physical id: 0
       version: No DPK
       serial: MP08K1Z5
       slot: Type2 - Board Chassis Location
     *-firmware
          description: BIOS
          vendor: LENOVO
          physical id: 0
          version: CCCN19WW(V2.05)
          date: 01/12/2016
          size: 64KiB
          capacity: 4032KiB
          capabilities: pci upgrade shadowing cdboot bootselect edd int9keyboard int14serial int17printer int10video acpi usb zipboot biosbootspecification netboot
     *-cpu
          description: CPU
          product: Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
          vendor: Intel Corp.
          physical id: 4
          bus info: cpu@0
          version: Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
          slot: CPU 1
          size: 2583MHz
          capacity: 2583MHz
          width: 64 bits
          clock: 83MHz
          capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat cpufreq
          configuration: cores=2 enabledcores=2 threads=1
        *-cache:0
             description: L1 cache
             physical id: 8
             slot: L1 Cache
             size: 32KiB
             capacity: 32KiB
             capabilities: synchronous internal write-back instruction
        *-cache:1
             description: L2 cache
             physical id: 9
             slot: L2 Cache
             size: 1MiB
             capacity: 1MiB
             capabilities: synchronous internal write-back unified
     *-cache
          description: L1 cache
          physical id: 7
          slot: L1 Cache
          size: 24KiB
          capacity: 24KiB
          capabilities: synchronous internal write-back data
     *-memory
          description: System Memory
          physical id: 25
          slot: System board or motherboard
          size: 4GiB
        *-bank:0
             description: SODIMM DDR3 Synchronous 1333 MHz (0,8 ns)
             product: RMT3170MN68F9F1600
             vendor: 67
             physical id: 0
             serial: 64358814
             slot: DIMM0
             size: 4GiB
             width: 64 bits
             clock: 1333MHz (0.8ns)
        *-bank:1
             description: SODIMM [empty]
             physical id: 1
             slot: DIMM1
     *-pci
          description: Host bridge
          product: ValleyView SSA-CUnit
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 0e
          width: 32 bits
          clock: 33MHz
          configuration: driver=iosf_mbi_pci
          resources: irq:0
        *-display
             description: VGA compatible controller
             product: ValleyView Gen7
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: pm msi vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: irq:93 memory:90000000-903fffff memory:80000000-8fffffff ioport:3050(size=8) memory:c0000-dffff
        *-storage
             description: SATA controller
             product: ValleyView 6-Port SATA AHCI Controller
             vendor: Intel Corporation
             physical id: 13
             bus info: pci@0000:00:13.0
             version: 0e
             width: 32 bits
             clock: 66MHz
             capabilities: storage msi pm ahci_1.0 bus_master cap_list
             configuration: driver=ahci latency=0
             resources: irq:90 ioport:3048(size=8) ioport:305c(size=4) ioport:3040(size=8) ioport:3058(size=4) ioport:3020(size=32) memory:90914000-909147ff
        *-usb:0
             description: USB controller
             product: ValleyView USB xHCI Host Controller
             vendor: Intel Corporation
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 0e
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:89 memory:90900000-9090ffff
        *-generic
             description: Encryption controller
             product: ValleyView SEC
             vendor: Intel Corporation
             physical id: 1a
             bus info: pci@0000:00:1a.0
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=mei_txe latency=0
             resources: irq:94 memory:90800000-908fffff memory:90700000-907fffff
        *-multimedia
             description: Audio device
             product: ValleyView High Definition Audio Controller
             vendor: Intel Corporation
             physical id: 1b
             bus info: pci@0000:00:1b.0
             version: 0e
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=snd_hda_intel latency=0
             resources: irq:95 memory:90910000-90913fff
        *-pci:0
             description: PCI bridge
             product: ValleyView PCI Express Root Port
             vendor: Intel Corporation
             physical id: 1c
             bus info: pci@0000:00:1c.0
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:87 ioport:4000(size=4096)
        *-pci:1
             description: PCI bridge
             product: ValleyView PCI Express Root Port
             vendor: Intel Corporation
             physical id: 1c.1
             bus info: pci@0000:00:1c.1
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:88 ioport:5000(size=4096) memory:90600000-906fffff
           *-generic
                description: Unassigned class
                product: RTS5229 PCI Express Card Reader
                vendor: Realtek Semiconductor Co., Ltd.
                physical id: 0
                bus info: pci@0000:02:00.0
                version: 01
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=rtsx_pci latency=0
                resources: irq:91 memory:90600000-90600fff
        *-pci:2
             description: PCI bridge
             product: ValleyView PCI Express Root Port
             vendor: Intel Corporation
             physical id: 1c.2
             bus info: pci@0000:00:1c.2
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:18 ioport:2000(size=4096) memory:90500000-905fffff
           *-network
                description: Ethernet interface
                product: RTL8101E/RTL8102E PCI Express Fast Ethernet controller
                vendor: Realtek Semiconductor Co., Ltd.
                physical id: 0
                bus info: pci@0000:03:00.0
                logical name: eth0
                version: 0a
                serial: f0:76:1c:df:31:b0
                size: 100Mbit/s
                capacity: 100Mbit/s
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd autonegotiation
                configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=2.3LK-NAPI duplex=full firmware=rtl8107e-2_0.0.2 02/26/15 ip=192.168.1.113 latency=0 link=yes multicast=yes port=MII speed=100Mbit/s
                resources: irq:92 ioport:2000(size=256) memory:90504000-90504fff memory:90500000-90503fff
        *-pci:3
             description: PCI bridge
             product: ValleyView PCI Express Root Port
             vendor: Intel Corporation
             physical id: 1c.3
             bus info: pci@0000:00:1c.3
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:19 ioport:1000(size=4096) memory:90400000-904fffff
           *-network
                description: Wireless interface
                product: RTL8723BE PCIe Wireless Network Adapter
                vendor: Realtek Semiconductor Co., Ltd.
                physical id: 0
                bus info: pci@0000:04:00.0
                logical name: wlan0
                version: 00
                serial: 4c:bb:58:c0:5b:89
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
                configuration: broadcast=yes driver=rtl8723be driverversion=4.6.0-040600rc1-lowlatency firmware=N/A ip=192.168.1.107 latency=0 link=yes multicast=yes wireless=IEEE 802.11bgn
                resources: irq:19 ioport:1000(size=256) memory:90400000-90403fff
        *-usb:1
             description: USB controller
             product: ValleyView USB Enhanced Host Controller
             vendor: Intel Corporation
             physical id: 1d
             bus info: pci@0000:00:1d.0
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: pm debug ehci bus_master cap_list
             configuration: driver=ehci-pci latency=0
             resources: irq:23 memory:90915000-909153ff
        *-isa
             description: ISA bridge
             product: ValleyView Power Control Unit
             vendor: Intel Corporation
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: isa bus_master cap_list
             configuration: driver=lpc_ich latency=0
             resources: irq:0
        *-serial UNCLAIMED
             description: SMBus
             product: ValleyView SMBus Controller
             vendor: Intel Corporation
             physical id: 1f.3
             bus info: pci@0000:00:1f.3
             version: 0e
             width: 32 bits
             clock: 33MHz
             capabilities: pm cap_list
             configuration: latency=0
             resources: memory:90916000-9091601f ioport:3000(size=32)
     *-scsi:0
          physical id: 1
          logical name: scsi0
          capabilities: emulated
        *-disk
             description: ATA Disk
             product: ST500LT012-1DG14
             vendor: Seagate
             physical id: 0.0.0
             bus info: scsi@0:0.0.0
             logical name: /dev/sda
             version: LVM1
             serial: W3PHTG55
             size: 465GiB (500GB)
             capabilities: partitioned partitioned:dos
             configuration: ansiversion=5 sectorsize=4096 signature=d9fa2484
           *-volume:0
                description: EXT4 volume
                vendor: Linux
                physical id: 1
                bus info: scsi@0:0.0.0,1
                logical name: /dev/sda1
                logical name: /
                version: 1.0
                serial: 3953528b-b7c5-4e1a-a0b5-d8132a7cb022
                size: 461GiB
                capacity: 461GiB
                capabilities: primary bootable journaled extended_attributes large_files huge_files dir_nlink recover extents ext4 ext2 initialized
                configuration: created=2016-03-27 10:03:21 filesystem=ext4 lastmountpoint=/ modified=2016-03-28 08:16:13 mount.fstype=ext4 mount.options=rw,relatime,errors=remount-ro,data=ordered mounted=2016-03-28 08:16:13 state=mounted
           *-volume:1
                description: Linux swap volume
                physical id: 2
                bus info: scsi@0:0.0.0,2
                logical name: /dev/sda2
                version: 1
                serial: c4b82e3b-922a-477e-a7c1-2735fd67d4c8
                size: 3905MiB
                capacity: 3905MiB
                capabilities: primary nofs swap initialized
                configuration: filesystem=swap pagesize=4096
     *-scsi:1
          physical id: 2
          logical name: scsi1
          capabilities: emulated
        *-cdrom
             description: DVD-RAM writer
             product: DVD-RAM UJ8HC
             vendor: MATSHITA
             physical id: 0.0.0
             bus info: scsi@1:0.0.0
             logical name: /dev/cdrom
             logical name: /dev/sr0
             version: GY01
             capabilities: removable audio cd-r cd-rw dvd dvd-r dvd-ram
             configuration: ansiversion=5 status=nodisc
  *-battery
       description: Lithium Ion Battery
       product: SR Real Battery
       vendor: Intel SR 1
       physical id: 1
       version: Date
       serial: 123456789
       slot: I2C2
       configuration: voltage=3,8V
  *-power UNCLAIMED
       description: OEM_Define1
       product: OEM_Define5
       vendor: OEM_Define2
       physical id: 2
       version: OEM_Define6
       serial: OEM_Define3
       capacity: 75mWh
`

**Comment by cschramm** [comment]
So... what's the problem?

**Comment by educobian** [comment]
The problem is that no bluetooth device is detected so I cannot use my bluetooth speaker.

Two hardware devices are UNCLAIMED: Smbus and power.

I have tried everything I've seen on internet and nothing works.

Thanks.

**Comment by infirit** [comment]
There is nothing out of the ordinary in the output. Please check and post the output after you tried to search for devices.

>Since installing Linux Mint 17.3 bluetooth

What did you use before, also Mint or another distribution?

**Comment by educobian** [comment]
Not working but closed anyway.

**Comment by cschramm** [comment]
No response from the reporter for four weeks...

**Comment by infirit** [comment]
>Not working but closed anyway.

Not working but still waiting for [info](https://github.com/blueman-project/blueman/issues/490#issuecomment-212497712) :wink:

**Comment by cschramm** [comment]
I know what follows, but again no response for nearly two months now...
