### ISSUE TITLE
Unknown method: connect_service is not a valid method of interface org.blueman.Applet

### ISSUE THREAD

**Issue by 411x** [blueman-project/blueman#491]
Since the last update (can't tell which).  
  
I can't connect to my bluetooth speaker. I got this message   
  
> Connection Failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: connect_service is not a valid method of interface org.blueman.Applet

**Comment by YitzhakStone** [comment]
I got the same problem!
