### ISSUE TITLE
Cannot pair to Logitech E-820 keyboard

### ISSUE THREAD

**Issue by Sawadee2u** [blueman-project/blueman#505]
Logitech Keyboard 820-000954
Process starts correctly and generates 4 digit code. 4 digit code entered using Logitech keyboard and hear beep when pressing Enter.  Get failure message shortly after.
Using Raspberry-Pi 3 B with latest Blueman build

**Comment by infirit** [comment]
Can you post the output from blueman applet as described in https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging
