### ISSUE TITLE
mailing list archives are forbidden

### ISSUE THREAD

**Issue by dlech** [blueman-project/blueman#511]
I can't view the mailing list archives, even after I subscribed to the mailing list and logged in.

http://ml.mate-desktop.org/pipermail/blueman/

**Comment by cschramm** [comment]
@stefano-k ?

**Comment by rworkman** [comment]
Mailing list appears to be dead anyway (i.e. the server hosting it died/went away and the mail lists were never restored).

**Comment by cschramm** [comment]
Thanks. I didn't even notice it's gone. 😉 Removed it from README.md. Guess we can live without it.
