### ISSUE TITLE
Autoconnect A2DP

### ISSUE THREAD

**Issue by maikcrew** [blueman-project/blueman#512]
Hello, I have Bluedio I4 in Linux Mint 17.2 working excellent, but new distros have blueman where is horror connect this device. 

I must:
1. turn on device
2. After connecting device. Disconnect device throught blueaman.
3. Connect like sound device.
4. And choose A2DP profile. (Sometimes show me that do not choose this profile and must try connect and disconnect again.)

This solving must make again and again :-( It is absolutely boring. Important that work.

**Comment by infirit** [comment]
Hi, have a look at [this](https://github.com/blueman-project/blueman/wiki/Troubleshooting#a2dp-audio-device-paired-but-fails-to-connect). I think the troubleshooting section on the debian page will solve your problem.

**Comment by maikcrew** [comment]
I tried set up, but hard for me set up normal connect audio headset adapter. I will try set up later. Arch forum I used before in Antergos, Fedora, Ubuntu 16.04 but still same problem.

**Comment by infirit** [comment]
Feel free to comment if you need further info or assistance, closing for now.
