### ISSUE TITLE
Error on RF-SPX15 "Connection Failed - No Such File or Directory"

### ISSUE THREAD

**Issue by Beaker319** [blueman-project/blueman#523]
This is a bluetooth Rockit Fish speaker.  The Raspberry PI3 finds the device fine but I keep getting this error and i get no audio from the speaker.  Any suggestions?

**Comment by cschramm** [comment]
It probably means the device does not offer any (connectable) services. What are the service UUIDs? You may just need to pair before connecting. However, if it does not provide (specific) services, blueman should not offer you the option to connect. BlueZ output may have more information in the syslog.
