### ISSUE TITLE
Applet asks for authentication

### ISSUE THREAD

**Issue by haarp** [blueman-project/blueman#527]
I've been using git blueman for a while now. After a recent update however, blueman-applet keeps asking for the root password twice on every start for networking and rfkill privileges.

I'm having a hard time pinpointing a commit that triggered this. Any ideas?

blueman: git master as of 2016-05-27
bluez: 5.39
Gentoo Linux, Xfce4

**Comment by cschramm** [comment]
https://github.com/blueman-project/blueman/wiki/PolicyKit

You can also `./configure --disable-polkit`.

**Comment by haarp** [comment]
Thank you, this works. Filed a bug downstream: https://bugs.gentoo.org/show_bug.cgi?id=584300
