### ISSUE TITLE
Cannot pair to bluetooth Headphones 

### ISSUE THREAD

**Issue by gameslayer** [blueman-project/blueman#530]
Can't use A2DP Sink or headset service to to my headphones (headphone not appearing in my pulse audio)

**Comment by infirit** [comment]
Have a look at our wiki entry for a2dp https://github.com/blueman-project/blueman/wiki/Troubleshooting#a2dp-audio-device-paired-but-fails-to-connect.

If you still have problems report back with the required in per https://github.com/blueman-project/blueman/wiki/Troubleshooting#reporting-a-bug--asking-for-support

**Comment by gameslayer** [comment]
@infirit I am using Xubuntu 14.04 shouldn't this already be built in and working with blueman?

**Comment by cschramm** [comment]
I don't think Xubuntu (14.04) ships pulseaudio-module-bluetooth.

**Comment by gameslayer** [comment]
Well why woulnd't it and how can I tell, I am now using Xubuntu 16.04

**Comment by cschramm** [comment]
> why woulnd't it

Because somebody decided against it? I don't know, but at least the xubuntu-desktop package does not suggest it, so I guess it's not getting installed in the first place.

> how can I tell

As usual, e.g. `dpkg -l pulseaudio-module-bluetooth`.

**Comment by infirit** [comment]
Closing this one as I see nothing left to discuss. Feel free to comment and we can always re-open.
