### ISSUE TITLE
can't connect memteq mouse

### ISSUE THREAD

**Issue by Openpony** [blueman-project/blueman#533]
Debian 9 user, I can't connect memteq mouse since few days (new update ?).
First it was impossible to pair the mouse with the computer.
Even impossible to detect it for pairing today.
I've tried another one (same model). Same issue.

**Comment by cschramm** [comment]
So what updates did you apply? Check your `/var/log/aptitude` or the log for the tool you used.

Did you check if you're able to discover the device with some other system?
