### ISSUE TITLE
Applet DBus service and methods, why do we have them?

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#540]
We literally do not use any of them inside blueman. Instead we call them directly through the applet object.

**Comment by cschramm** [comment]
What's the applet object you're talking about? If it's a `BluemanApplet` you're right, but we usually have an `AppletService` object which is the proxy object for the the service.

**Comment by infirit** [comment]
Ah, naming confusion on my part. When I see ``blueman.Applet`` I thought is was the actual applet, but this is the AppletService proxy. Thanks :smile:
