### ISSUE TITLE
Unclosed bold tags on Gnome applet

### ISSUE THREAD

**Issue by andreyluiz** [blueman-project/blueman#541]
Hello.

I see an unclosed bold tag in the gnome applet.

![blueman-applet](https://cloud.githubusercontent.com/assets/1965897/16545910/f7b4d942-410e-11e6-9756-0898c97eb894.png)

My blueman version follows.

![blueman-version](https://cloud.githubusercontent.com/assets/1965897/16545912/0c1497ce-410f-11e6-86b5-da14f3632a5e.png)

The version seems to be the latest. My Ubuntu is pt_BR. So I checked the translations for blueman but I had no success finding such a clue.

Thank you.

**Comment by andreyluiz** [comment]
Found it. It is in pt.po. Not pt_BR.po. I'll submit a Pull request.

**Comment by infirit** [comment]
Thanks, PR is welcome but it also needs to be updated at Transifex otherwise it will be overwritten next time we update the translations for 2.1.

Please do the PR for the 2-0-stable branch :smile:
