### ISSUE TITLE
asus x200ca bluetooth adapter not responding

### ISSUE THREAD

**Issue by vitimilocity** [blueman-project/blueman#545]
when i would use windows 10 the bluetooth adapter would work but i uninstalled it and use linux mint now and my bluetooth adapter doesnt turn on

**Comment by cschramm** [comment]
https://github.com/blueman-project/blueman/wiki/Troubleshooting

**Comment by infirit** [comment]
No reply for a month, closing. Feel free to comment with the required info and we will re-open.
