### ISSUE TITLE
Tecknet bluetooth mouse

### ISSUE THREAD

**Issue by rick212** [blueman-project/blueman#566]
chronically disconnects under Manjaro   blueman.bluez.errors.DbusFailedError

**Comment by infirit** [comment]
Blueman only manages the connection but is itself not responsible for the connection itself. Most likely you are running into communication problems between bluez and the device.

You probably missed the note at the top when creating this issue and forgot to add any relevant information. See https://github.com/blueman-project/blueman/wiki/Troubleshooting and provide at least the log from blueman-applet.
