### ISSUE TITLE
no me deja conectarme por bluetooth

### ISSUE THREAD

**Issue by GuillermoAlvez** [blueman-project/blueman#573]
Al ingresar a dispositivos bluetooth me dice "resource not ready" adjunto traceback

![image](https://cloud.githubusercontent.com/assets/13757334/17645390/383c3276-617b-11e6-9f8f-533f9548502c.png)

**Comment by cschramm** [comment]
Current release versions have a bug where blueman starts even if powering on the adapter failed. That's expected if you have a hardware switch enabled. It's fixed in the master branch.
