### ISSUE TITLE
Connection Failed: blueman.bluez.errors.DBusFailedError: Protocol not available

### ISSUE THREAD

**Issue by romulogcerqueira** [blueman-project/blueman#581]
I can't connect my bluetooth headphone in Xubuntu 16.04.

**Comment by infirit** [comment]
That means the pulseaudio bluetooth module is not available. For debian and derivatives see https://wiki.debian.org/BluetoothUser/a2dp

**Comment by romulogcerqueira** [comment]
Worked! Thanks!

**Comment by puma827** [comment]
i'm linux fan and half-expert from many years ago but it makes me shamed for example i set the bluetooth audio after many hours trying but tomorrow when i poweron system it doesn"t work i"m realy tired of wasting time

**Comment by filipuic** [comment]
`service bluetooth restart` worked for me.
