### ISSUE TITLE
Blueman installed for audio 

### ISSUE THREAD

**Issue by DrumNman** [blueman-project/blueman#582]
Hi,
I have linux 17.1 rebecca installed and installed Blue man for bluetooth. I have a Bose Sound Color
Bluetooth Speaker. When I installed Blue Man and setup a connection to pair with my Bose, I get an
error  message stating..Audio cannot pair. Maybe incorrect driver  ?

**Comment by infirit** [comment]
First go through https://wiki.debian.org/BluetoothUser/a2dp as it solves the majority of all the issues raised regarding audio and bluetooth under debian and derivatives.

**Comment by DrumNman** [comment]
Thanks a million for the help...Awesome :)


Sent via the Samsung Galaxy Note® 3, an AT&T 4G LTE smartphone

-------- Original message --------
