### ISSUE TITLE
SerialManager doesn't disconnect blueman-rfcomm-watcher for rfcomm0

### ISSUE THREAD

**Issue by tmojo** [blueman-project/blueman#583]
Although SerialManager disconnects /dev/rfcomm* and blueman-rfcomm-watcher for ports > 0
It doesn't for /dev/rfcomm0 because of the `continue` when the port is 0 in `active_ports`.

Attached patch.
[SerialManager.py.diff.txt](https://github.com/blueman-project/blueman/files/453926/SerialManager.py.diff.txt)

**Comment by infirit** [comment]
Thanks, fixed with https://github.com/blueman-project/blueman/commit/8a7142ce28ee65d3ae5dd238d5c6d896cd20f8d1 and https://github.com/blueman-project/blueman/commit/a0c5d173c293fa530cc8d4337de9ddd274d236f6
