### ISSUE TITLE
Reset RecentConns

### ISSUE THREAD

**Issue by cschramm** [blueman-project/blueman#607]
In [Debian #841869](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841869) Jelmer Vernooĳ reports a broken headset entry in the recent connections menu. This is due to the removal of `blueman/services/Headset.py` in #442.

To avoid such issues /org/blueman/plugins/recentconns/recent-connections should probably be reset on every `make install`.

**Comment by infirit** [comment]
Yes, ran into this as well in #575. I think we should retrieve the data directly from the device instead of relying on the service files. Have not gotten around to working on that :smile:
