### ISSUE TITLE
Appindicator get_geometry off

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#609]
When we enable the AppIndicator plugin we run into the below error and show the notification outside the screen. Without the status icon returns proper geometry, see the second block. Not sure what is going on but we need to fix this before final release.

```
(blueman-applet:25655): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
_________
geometry (/usr/lib64/python2.7/site-packages/blueman/plugins/applet/StatusIcon.py:45)
1274976 32542 1 1 
```

```
geometry (/usr/lib64/python2.7/site-packages/blueman/plugins/applet/StatusIcon.py:45)
1565 3 22 22 
```

**Comment by cschramm** [comment]
How do you get that error? Cannot reproduce (in Xfce panel).

**Comment by infirit** [comment]
I get it the moment we request the geometry under xfce panel.

btw, [API: Remove GtkStatusIcon](https://github.com/GNOME/gtk/commit/d2a8667f835ddce4ac88b9bee143556f9efa93c4)

**Comment by infirit** [comment]
#637 drops this so we can close it when it lands in master
