### ISSUE TITLE
cant send file and receive 

### ISSUE THREAD

**Issue by DarknessHunter** [blueman-project/blueman#612]
when i updated my OS (parrot security OS debian based) i cant receive or send files, before i update i was able to send and receive please any solve for my problem 
![screenshot at 2016-11-04 20-38-15](https://cloud.githubusercontent.com/assets/20493967/20017966/95e71d8e-a2ce-11e6-8695-e7f57f281902.png)
when i enable this plugin (transfer service) i get this error

**Comment by infirit** [comment]
It means you do not have a proper obex server installed and running. Most common in recent distrobutions is ``obexd`` provided by bluez. Install one and it should work again.

See https://github.com/blueman-project/blueman/blob/master/CONTRIBUTING.md for the minimum required info needed to start helping people :wink:

**Comment by DarknessHunter** [comment]
Thanks a lot!!
