### ISSUE TITLE
Prevent the applet from starting at boot

### ISSUE THREAD

**Issue by andoruB** [blueman-project/blueman#63]
First of all I wanted to say thanks for the lovely software to all contributors :)

Now, as the title says, I would like to know how to prevent the blueman-applet from starting a boot, as I rarely make use of the bluetooth dongle. I'm using Crunchbang Linux (based off Debian, with OpenBox DE), and so far I've only found a method to disable the autostart under GNOME.

**Comment by RadicalProton** [comment]
After disabling blueman.service with systemctl as above

The /usr/bin/blueman-applet still breaks horribly with a giant python exception stack and spams up /var/log/messages on bootstrap and who knows when else it may run.

Is it really that hard to see if bluetooth is disabled or otherwise unavailable before just assuming it is up and ready to go? 

As a general guideline, should one not check that the things you are dealing with are even wanted or needed before one just blindly starts going and doing things with them?

I just put an exit(0) in it after the imports for now, just to get it to shut up. It's absurd there are these turds all over the place that get into the releases.  This is about the 50th stupid and unnecessary error in syslog that shows up on boot on a Debian 9 stretch latest up to date install. It's revolting.

**Comment by cschramm** [comment]
blueman does not ship a `blueman.service` file, neither in general, nor in Debian stretch specifically.

**Comment by infirit** [comment]
Open a new issue and provide the required info (version numbers, logs etc). Complaining like this will not solve the error.

**Comment by cschramm** [comment]
@sixtyfive: My guess is that you have a `~/.config/autostart/blueman.desktop` or something similar used by your DE to manage its autostart configuration.

**Comment by sixtyfive** [comment]
@cschramm: Whoops, misunderstanding! I know how to get the applet to _not load_ when the DE is started. What I want is for the applet to _load_, but _not enable BT_ when it does. I.e. I want to see the BT symbol in the tray to be able to enable BT from there should I need it.

**Comment by cschramm** [comment]
@sixtyfive: Are you sure you're starting just `blueman-applet`, not e.g. `bluman-manager`? Which version?

**Comment by sixtyfive** [comment]
Yup, and I can also sort-of proof in a screenshot that it's the starting of `blueman-applet` which enables BT:

![image](https://user-images.githubusercontent.com/192860/40055485-6234a520-5848-11e8-905c-587c7a500835.png)

**Comment by cschramm** [comment]
Ah, another misunderstanding. :wink: 

You wrote "the applet refuses to launch without demanding that BT be enabled" but did not actually mean the dialog that comes up e.g. when you start `blueman-manager`, right? The auto-power is a feature of the PowerManager plugin. You can find its settings in the plugins dialog from the applet's right-click menu and disable that there.

**Comment by sixtyfive** [comment]
Aha! I think that might have been a misunderstanding I had with myself. Indeed it's `bluetooth-manager` which brings up that dialog. Found the PowerManager setting. Wow, that one was well-hidden. Thank you very much! :smile:

**Comment by cschramm** [comment]
I created #877 to improve that. Ideas are very welcome.

**Comment by qoheniac** [comment]
> You should have `/etc/xdg/autostart/blueman.desktop` which is a cross-desktop autostart entry. The start of the application can be prevented for any desktop by simply deleting it.
> 
> Gnome probably has a tool to selectively suppress the execution of such entries.

User-specific autostart entries override system-wide ones (as described [here](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html#idm46103232598304)). So an easy way to disable autostarting is writing a `~/.config/autostart/blueman.desktop` file that doesn't execute anything. A possible content could look like this:

```
[Desktop Entry]
Name=Blueman Applet
Type=Application
```

**Comment by HubKing** [comment]
Deleting `/etc/xdg/autostart/blueman.desktop` prevented autostart. But neither Gnome 46 nor KDE 6.0 had shown in in their autostart entries in their GUI settings.
