### ISSUE TITLE
Multiple file send from phone only receives one file

### ISSUE THREAD

**Issue by Rudd-O** [blueman-project/blueman#634]
Master branch when I send to my computer multiple files, only the first is received and notified for.

The version available on Fedora does not have that problem.  This is a new bug.

**Comment by infirit** [comment]
We dropped bluez 4 support in master which may have caused this. I am not at my machine for the next several days but if you are interested the code for this lives in TransferService if I am not mistaken.

Rudd-O <notifications@github.com> schreef op 25 december 2016 02:54:22 CET:
>Master branch when I send to my computer multiple files, only the first
>is received and notified for.
>
>The version available on Fedora does not have that problem.  This is a
>new bug.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blueman-project/blueman/issues/634

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Rudd-O** [comment]
I am famliar with the code but after toying with it, I couldn't get it
to work.  Sorry, but the code is broken, and whether it was caused or
not by Bluez4 being dropped, it needs to be fixed.

**Comment by infirit** [comment]
No worries, I may have found the problem. I'll confirm tomorrow and if correct I'll push a fix.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by infirit** [comment]
Silly bug introduced recently, https://github.com/infirit/blueman/commit/8c013b35401f28868cdfd78d8854ab0c844f60c8 should fix but not properly tested yet. Will do and push tomorrow.

**Comment by infirit** [comment]
Transferred 38 files with no problems, pushed as 8c013b35401f28868cdfd78d8854ab0c844f60c8.
