### ISSUE TITLE
Issues with Blueman 1.23 an A2DP

### ISSUE THREAD

**Issue by sebastian-de** [blueman-project/blueman#64]
Citing David Henningsson from https://bugs.launchpad.net/ubuntu/+source/gnome-bluetooth/+bug/1283003/comments/72

"Hi Blueman developers,

This is an outreach for help - let me know if this is the right channel
or not. We seem to have a lot of people claiming that pulseaudio's
module-bluetooth-discover is not loaded on startup on 14.04. This causes
problems with bluetooth headsets.

Reading the code I can see that blueman deliberately unloads
module-bluetooth-discover. Do you have a better idea than just removing
those lines of code, which probably are there for a reason?

Here are some related bugs:

https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1274613
https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1283003
## 

David Henningsson, Canonical Ltd.
https://launchpad.net/~diwic"

Another bug i found: https://bugs.launchpad.net/ubuntu/+source/blueman/+bug/1199059 (blueman and pulse's module-bluetooth-discover)

I already reassigned the Launchpad bug to blueman project, but I don't know if the Launchpad or GitHub Bugtracker is the official one.

**Comment by lispeaking** [comment]
Similar problem here (Xubuntu 15.04/14.10/14.04). 
When I try to connect to the audio sink of a Belkin Songstream BT it says 
"Connection Failed: Stream setup failed"

same error with lubuntu.
BT sound works fine with Ubuntu GNOME, Kubuntu, an Ubuntu

**Comment by Yanpas** [comment]
+1

**Comment by divneet** [comment]
the package has been removed and i'm still unable to connect to my speakers !
