### ISSUE TITLE
TransferService is not loadable (gives huge error message)

### ISSUE THREAD

**Issue by Vednier** [blueman-project/blueman#640]
Hello, just today i encountered exceptionally weird bug - i noticed that Blueman cannot receive files sent from mobile device, checked if something missing and found that TransferService is not enabled, i tried to enable it and...got this. I'm sorry it in image file but i dont see any way to copy-paste this.
![screenshot](https://cloud.githubusercontent.com/assets/15080370/21756046/1b632246-d62d-11e6-9207-be75a2f7b071.png)
Gettin this error windows every time i trying to enable TransferService.
Using Xubuntu 16.10 64 bit(XFCE), Blueman 2.0.4, Bluez 5.41, Bluez-obexd 5.41 is also present.
So far i really dont know that to add.

**Comment by infirit** [comment]
This means that the obex daemon is not enabled.

As a user do ``systemctl --user start obex`` and see if the error goes away. If it does you can enable it globally with ``sudo systemctl --global enable obex``.

**Comment by Vednier** [comment]
Yes, thats worked. I had no such issue previously, on 16.04 so didnt expected that. thanks.

**Comment by infirit** [comment]
Its the introduction of systemd you are suffering from. The same is seen on all systemd distros including Fedora and Arch.
