### ISSUE TITLE
Ability to boot in 'Turn Bluetooth off' mode

### ISSUE THREAD

**Issue by luzpaz** [blueman-project/blueman#641]
I can't figure out how to set the setting that stops blueman from booting as 'Turn Bluetooth on' and simultaneously keeps it in the taskbar. Is this feature available?

**Comment by infirit** [comment]
Open the plugin dialoque and find the "auto power on" plugin, it has an option to disable this.

**Comment by luzpaz** [comment]
Thanks @infirit  
That worked.

**Comment by lee-tts** [comment]
For posterity: This plugin may be called PowerManager, not auto power on. Open blueman-manager > View > Plugins > PowerManager > Configuration > Auto power on (uncheck this)
