### ISSUE TITLE
Allow adwaita-icon-theme usage

### ISSUE THREAD

**Issue by pacho2** [blueman-project/blueman#642]
Looking to configure.ac, this needs either the old and deprecated gnome-icon-theme, or faenza or mate-icon-theme. 

It would be nice to allow the usage of the successor of gnome-icon-theme: adwaita-icon-theme

Thanks a lot

**Comment by infirit** [comment]
Yes this is ok, all icons present we need. See pull request #643 which I'll merge in a week or so unless there are objections 😄
