### ISSUE TITLE
Select default location when receiving files

### ISSUE THREAD

**Issue by rsm-gh** [blueman-project/blueman#651]
As far as I know there is no option to set a default location when receiving files. It would be a nice option since the  `~/` dir is not always comfortable.

By the way, great work guys, the GUI is really good and it has a good quality :+1:

**Comment by infirit** [comment]
Yes you can, open the applet menu and locate the "Local services" entry. in the new window make sure to have "Transfer" selected on the left.

**Comment by rsm-gh** [comment]
Thanks for the response! That was exactly what I was looking for ! Plus the option "Accept files from trusted devices" is also something that I wanted :)
