### ISSUE TITLE
vkk-1bt speaker failed to Sink

### ISSUE THREAD

**Issue by musaranio** [blueman-project/blueman#660]
vkk-1bt speaker failed to Pair
Protocol Not aviable
Do notworks audio does not sound

**Comment by infirit** [comment]
Have a look at the links [here](https://github.com/blueman-project/blueman/wiki/Troubleshooting#a2dp-audio-device-paired-but-fails-to-connect) as most problems are discussed and solved with them. If you have further problems please see https://github.com/blueman-project/blueman/wiki/Troubleshooting#reporting-a-bug--asking-for-support
