### ISSUE TITLE
Microsoft bluetooth mouse gets disconnected continuously

### ISSUE THREAD

**Issue by novinsh** [blueman-project/blueman#664]
After pairing is done with Microsoft Bluetooth mouse 3600 it gets disconnected continuously. Sometimes it is fixed by turning the Blueman off and on. Sometimes with turning the mouse off and on. And sometimes nothing can be done about it.

I wonder what can fix the issue and what is actually originates from?
I also followed instruction from [this post](http://unix.stackexchange.com/questions/177998/bluetooth-mouse-disconnects).

**Comment by cschramm** [comment]
That's not really a topic for blueman. The StackExchange thread has much more and better advice that what we could give you.
