### ISSUE TITLE
No time to Pair a found-device - appears in device-list for < 0.5sec, before vanishing.

### ISSUE THREAD

**Issue by omeletteo** [blueman-project/blueman#665]
On a fresh-install (new OS installation for instance) Blueman will Search & find my Mpow headset, listing it in the Device-list and allow the user ample time to Pair it.  If I now Remove this paired device, it is deleted from the Device-list.  If I now run another Search, the Mpow headset, on pushing its Headset button, will again be found - BUT it is only displayed on the device-list for a fraction of a second, before being removed, giving me no time to pair it.  Restarting the computer has no effect, nor does removing/reinstalling Blueman - its devices-list contains whatever devices had been found & paired prior to removal, so this at least is not being deleted when Blueman is uninstalled.

I have found that by removing Blueman, searching at the root level for "blueman" and deleting everything that is found, then reinstalling Blueman, it will (once!) again pair with the device without problems.  A bit excessive a solution though!

It appears to me that the removed device is not being removed from all of the configuration files that Blueman deals with, which just confuses Blueman on subsequent Searches.  Needless to say, this is incredibly annoying as well.  Incidentally, my frequent need to remove devices from the device-list is that for whatever reason, Blueman often fails to determine a devices 'Services available' properly.

Edit:  A realisation, rather than delete everything 'Blueman' as described above  in order to restore normal operation, I have just discovered that by removing the most current PPA Blueman (1.99_alpha in my case) and installing Blueman 1.23 (version in repository), I can again successfully search/pair my BT headset.  I then need to upgrade 1.23 to 1.99 as 1.23 suffers from a known-about audio-sink bug.  Still quite a hassle though.

**Comment by infirit** [comment]
The hint is in the version number, it the first alpha release and had many issues. If you are on debian the latest stable 2.0.4 is in backports and should work well. If not on debian (or derivative) please let us know which distro and version.
