### ISSUE TITLE
Can not get online via blueman (blueman paired but not connected)

### ISSUE THREAD

**Issue by d1m92** [blueman-project/blueman#666]
_logs_

**When WIFI enabled**

> _________
> __init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
> caching initial properties 
> _________
> notify (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:239)
> <Device.Device object at 0x7fc2785b45a0 (blueman+main+Device+Device at 0x55cd72d56080)> <blueman.services.NetworkAccessPoint.NetworkAccessPoint object at 0x7fc2785b75f8> 00001116-0000-1000-8000-00805f9b34fb 
> _________
> __del__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:72)
> deleting device /org/bluez/hci0/dev_00_00_46_65_80_01 
> _________
> Destroy (/usr/lib/python3/dist-packages/blueman/main/Device.py:94)
> invalidating device /org/bluez/hci0/dev_00_00_46_65_80_01 
> _________
> initialize (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:144)
> rebuilding menu 
> /usr/lib/python3/dist-packages/blueman/gui/manager/ManagerProgressbar.py:165: Warning: Source ID 2444 was not found when attempting to remove it
>   GObject.source_remove(self.gsource)

**When WIFI not working**

> _________
> __init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
> caching initial properties 
> _________
> notify (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:239)
> <Device.Device object at 0x7f5148e5fc60 (blueman+main+Device+Device at 0x5586a1bde5a0)> <blueman.services.NetworkAccessPoint.NetworkAccessPoint object at 0x7f5148e64470> 00001116-0000-1000-8000-00805f9b34fb 
> _________
> __del__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:72)
> deleting device /org/bluez/hci0/dev_00_00_46_65_80_01 
> _________
> Destroy (/usr/lib/python3/dist-packages/blueman/main/Device.py:94)
> invalidating device /org/bluez/hci0/dev_00_00_46_65_80_01 
> _________
> initialize (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:144)
> rebuilding menu 
> /usr/lib/python3/dist-packages/blueman/gui/manager/ManagerProgressbar.py:165: Warning: Source ID 2437 was not found when attempting to remove it
>   GObject.source_remove(self.gsource)
> 

**When an attempt to transfer a file to the device:**

> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
> _________
> on_adapter_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:96)
> prop Discovering 1 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
>     return self.get_name_owner(bus_name)
>   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
>     's', (bus_name,), **keywords)
>   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez.obex': no such name
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/blueman-sendto", line 403, in <module>
>     SendTo()
>   File "/usr/bin/blueman-sendto", line 328, in __init__
>     self.do_send()
>   File "/usr/bin/blueman-sendto", line 365, in do_send
>     sender = Sender(self.device, self.adapter, self.files)
>   File "/usr/bin/blueman-sendto", line 107, in __init__
>     self.client = obex.Client()
>   File "/usr/lib/python3/dist-packages/blueman/bluez/obex/Client.py", line 19, in __init__
>     if self.__class__.get_interface_version()[0] < 5:
>   File "/usr/lib/python3/dist-packages/blueman/bluez/obex/Base.py", line 23, in get_interface_version
>     obj = dbus.SessionBus().get_object('org.bluez.obex', '/')
>   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
>     follow_name_owner_changes=follow_name_owner_changes)
>   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
>     self._named_service = conn.activate_name_owner(bus_name)
>   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
>     self.start_service_by_name(bus_name)
>   File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
>     'su', (bus_name, flags)))
>   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.bluez.obex.service not found.
> Exception ignored in: <bound method Base.__del__ of <Client.Client object at 0x7fccb3529fc0 (uninitialized at 0x(nil))>>
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/blueman/bluez/obex/Base.py", line 47, in __del__
>     self.__signals.DisconnectAll()
> AttributeError: 'Client' object has no attribute '_Base__signals'
> _________
> on_adapter_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:96)
> prop Discovering 0 

**So as soon as it came error:
Is attached as a screenshots.**

https://itmages.ru/image/view/5493705/1c0ef94a
https://itmages.ru/image/view/5493704/4a2e5c56

**When attempt to view the contents of the device:**

> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
> _________
> on_adapter_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:96)
> prop Discovering 1 
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
> _________
> on_adapter_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:96)
> prop Discovering 0 

Ubuntu 16.10
Blueman 2.0.4

Thanks)

**Comment by infirit** [comment]
The error is because of a missing dbus service namely the obex daemon. It is either disabled in systemd (most likely) or it is not installed at all. Try to start it as a user with ```systemctl --user start obex``` and see if that makes the errors go away.

However, the errors relate to file transfer not to networking. If you still have problems with bluemans networking after the errors are gone please post the __full__ output of blueman-applet and put it in a pastebin or gist.
