### ISSUE TITLE
M535 won't stay connected

### ISSUE THREAD

**Issue by j0nny55555** [blueman-project/blueman#668]
IBM X220
Manjaro 16.10.3
4.4.48-1-MANJARO

When I attempt to connect my Logitech m535 it connects and fails, then it appears like a part of the bluetooth system fails.

I am not sure what logs to send here, please let me know what more to find out. This has happened multiple times.

**Comment by cschramm** [comment]
See https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging on how to get output from blueman.
