### ISSUE TITLE
Bluetooth Headphones Paired but not receiving sound

### ISSUE THREAD

**Issue by mikemihai89** [blueman-project/blueman#672]
Able to find device and pair it okay (LG HBS-750 headphones)
Ran setup assistant 
Option 1 - connect to headset system (marked by default) (no sound over bluetooth with this option)
Option 2 - A2DP sink (Send Audio) results in message "Device added successfully but failed to connect"

Unpaired and tried again
This time by doing it from the main window, device tab.

Headset service would connect and speakers will say (connected) yet no other sounds coming out of them.
Switching to audio sink from the device tab shows message "Connection Failed. Stream setup failed"

I don't know much about using Linux except to follow tutorials. So far the bluetooth incompatibility is not a big deal. The rest of the OS is easy to use and beautiful! Thank you for the hard work. I will probably end up using this on my non bluetooth PC :)

**Comment by infirit** [comment]
This sound like you are missing the pulseaudio bluetooh module, see https://github.com/blueman-project/blueman/wiki/Troubleshooting#a2dp-audio-device-paired-but-fails-to-connect containing links to two wikis that solve most audio problems on linux.
