### ISSUE TITLE
Help with a review

### ISSUE THREAD

**Issue by Rudd-O** [blueman-project/blueman#673]
Hello!  Can someone review https://github.com/blueman-project/blueman/pull/632 ?  infirit was assigned as a reviewer, and I've performed all the changes infirit requested, but now I am getting radio silence from the reviewer.

Thank you in advance!  :-)

**Comment by cschramm** [comment]
It's on my radar. I'm sure @infirit will take another look at the current implementation. No hurry. We're moving slow. 😉

**Comment by Rudd-O** [comment]
Thank you :-)

On March 28, 2017 11:29:10 AM GMT+02:00, Christopher Schramm <notifications@github.com> wrote:
>It's on my radar. I'm sure @infirit will take another look at the
>current implementation. No hurry. We're moving slow. 😉 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blueman-project/blueman/issues/673#issuecomment-289714788

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by infirit** [comment]
I thought [this comment](https://github.com/blueman-project/blueman/pull/632#issuecomment-277024214) was clear how much more time I was going to invest in it (hint, this comment is already more than I wanted).

**Comment by Rudd-O** [comment]
That's okay, someone else is taking a look at it, and as usual I will make the changes that are requested, like I did last time, even though you were gratuitously rude to me.

On March 28, 2017 6:49:34 PM GMT+02:00, Sander Sweers <notifications@github.com> wrote:
>I thought [this
>comment](https://github.com/blueman-project/blueman/pull/632#issuecomment-277024214)
>was clear how much more time I was going to invest in it (hint, this
>comment is already more than I wanted).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blueman-project/blueman/issues/673#issuecomment-289832879

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
