### ISSUE TITLE
TransferService fails to start

### ISSUE THREAD

**Issue by vranki** [blueman-project/blueman#676]
TransferService plugin is not started by default. Checking it in the Plugins dialog results to non-copyable error message dialog in the attached image. 

![screenshot from 2017-04-06 15-07-32](https://cloud.githubusercontent.com/assets/81116/24753485/faf62b32-1ada-11e7-8011-80f4281d77fc.png)

Tested on Ubuntu 17.04 beta, Cinnamon desktop. Blueman version 2.0.4-1ubuntu2, Bluez version 5.43-0ubuntu1.

**Comment by infirit** [comment]
Hi, see https://github.com/blueman-project/blueman/issues/675#issuecomment-291486223

Same problem and same solution 😄
