### ISSUE TITLE
Problem receiving files with lxde/dunst

### ISSUE THREAD

**Issue by treaki** [blueman-project/blueman#68]
Hi,

i am using bluman 1.23 on my laptop running debian unstable with lxde desktop (which uses openbox wm) and the lightweight notification-daemon Dunst. Unfortunately i am not able to receive files with this setting. Ive get notified about the incoming file transfer but i am not able to accept it. Please ad a possibility to accept incoming files (obex push) without the need of an high-end notification daemon.

**Comment by treaki** [comment]
dose the desctop notification interface specification implies the ability for actions or is this optimal? can you suggest me another notification system that works grate and with low footage on my lxde system?

**Comment by cschramm** [comment]
Support for actions is optional, but blueman checks the daemon's capabilities and uses a fallback if it does not support actions. We now also have an option you can change with dconf-Editor to force the use of the fallback instead of the notification server in case your server has a malfunction.

**Comment by infirit** [comment]
If you want to force this by default when deploying systems make sure to create a gsettings override file ```/usr/share/glib-2.0/schemas/99-my-tweaks.gschema.override``` and add the following.

```
[org.blueman.general]
notification-daemon=False
```

Make sure that glib-compile-schemas is run after placing the file in the same directory.

**Comment by drzraf** [comment]
I can confirm the issue: dunst does not support action (at least not in a way compatible with blueman use, as of 1.1.0-1 (the Debian's version).
I can confirm @infirit workaround works
Long story short: dunst is a notification-daemon incompatible with blueman, and this makes things fail (device association/file transfers) in strange ways (pressing the dunst window is like pressing "Cancel" inside a correct notification daemon).
This makes this issue hard to diagnose.

**Comment by infirit** [comment]
>I can confirm the issue: dunst does not support action

It does through the context menu as of version 1.0.0

>dunst is a notification-daemon incompatible with blueman

Sure it is, just many people do not understand that one has to open the context menu.

>pressing the dunst window is like pressing "Cancel" inside a correct notification daemon

Which is the correct behaviour and should be the same for any daemon. One has to invoke the action and clicking anywhere else is interpreted as notification dismissed, iow cancelled.

**Comment by drzraf** [comment]
Allright but could please tell me (in https://github.com/knopwob/dunst/issues/220?) how actions are expected to work, given that the dunst manpage does not mention the words _action_, _press_,  or _key_?

**Comment by infirit** [comment]
>how actions are expected to work

I already told you, you open the ``context menu`` and then select action. IN the default config file the keyboard shortcut is ``ctrl+shift+period``. But what it is in yours I do not know. 

It relies on dmenu so make sure it is installed.

**Comment by treaki** [comment]
@infirit thanks for that hint, i wasnt aware of my dunst having a context menu, maybe someone could fill a bug report there about adding some howto on the first run/update that tells users that it exists but now i try to keep that in mind if i next try to use bluetooth with my tp.

thanks a lot for the clerance of that hard to track issue due to bad user behavior of dunst for users who haent read all code/manual/whatever. but probably  i am than using the wrong notification deamon problem's that the corner of low resorce but intuitiv usable software is very limited... Or with outer wourds i should upgrade my system or better buy a new one but thats to exp.

but sorry i am misguiding this comment, again, but äh, sorry, what was it yes:

thanks for all your help and keep up this good worl

**Comment by infirit** [comment]
>haent read all code/manual/whatever

Dunst is very poorly documented indeed and from the looks of it somewhat unmaintained.

>thanks for all your help

Your welcome 😄
