### ISSUE TITLE
Bluetooth will not stay disabled

### ISSUE THREAD

**Issue by nightsky30** [blueman-project/blueman#682]
Bluetooth is enabled every time I boot and log in to my system, even when I've disabled it previously.  It does not seem to save/acknowledge the disabled setting.

blueman:  2.0.4-1ubuntu2
BlueZ:  5.37-0ubuntu5
Distribution:  Ubuntu 16.04.2 LTS
Desktop environment:  XFCE 4.12.2

**Comment by infirit** [comment]
Bluemans power-manager plugin auto powers the adapter. To disable open the plugin dialog, find PowerManager and disable ``Auto power-on``.

**Comment by nightsky30** [comment]
I wasn't aware of that plugin.  I guess I just expected the last state as of system shutdown to be remembered at startup.

Thanks!
