### ISSUE TITLE
feature request: accept all files (obex push)

### ISSUE THREAD

**Issue by treaki** [blueman-project/blueman#69]
Hi,

i would appreciate if you could add an option to accept all files send to the computer by obex push, not only them send from trusted devices. Therefore the files should be saved in a folder structure like this:
bluman_recived_files
- recive.log
- XX:XX:XX:XX:XX:XX (bluetooth id)
  - date_filename.ext

thanks

**Comment by infirit** [comment]
I understand the need to unconditionally accept files. And I think doing a dir/file formatting language that can be customized by the user is needed. But..

Can you explain the use case for the receive log?

**Comment by treaki** [comment]
hi infirit, to integrate it into  an "kind of public accessible interactive kiosk system" where people can drop files using bluetooth. Another daemon is reading the log file created by the obex push service, like tail -f, and is doing some stuff if events take place...

but in general i would like that every pice of software running on my box is generating logs at any relevant event that i can use for analyzing the system history. Nothing as important as receiving files using bluetooth should be unnoticeable and if we have a unintended receive mode we need a log file (in my opinion)...

regards treaki

**Comment by cschramm** [comment]
Closing as 8 years have passed without any progress, this seems like a rather specific use case to me and I don't really see it happening to be honest.
