### ISSUE TITLE
Grammar/spelling issue - 'Setup New Device' should be 'Set Up New Device' in all translations

### ISSUE THREAD

**Issue by slvr32** [blueman-project/blueman#692]
Incorrect...

Setup New Device

Correct...

Set Up New Device

'Setup' is a noun or adjective, 'set up' is a verb, and the verb is what you should be using here, e.g.

How did you manage to get the headphones set up to work correctly?

I followed the setup instructions and set up the new device to work with my computer.

That's a really nice setup!

I grabbed the blueman-2.1.alpha1 source release, and the suggested corrections are as follows...

All instances of 'Setup New Device' (in menus and translations) should become 'Set Up New Device'.

The 'Setup...' menu items and translations are ok, since those are appropriate as nouns, if you take the 'Setup...' menu choice to mean that you want to go look at the 'Setup (details)'.

aclocal.m4 should have 'Set up a source with many dependencies...'

~/blueman-2.1.alpha1
$ find . -type f | xargs grep Setup
./blueman/plugins/applet/StandardItems.py:        self.new_dev = create_menuitem(_("_Setup New Device") + "...", get_icon("document-new", 16))
./blueman/main/Adapter.py:        # Setup dialog
./blueman/gui/manager/ManagerDeviceMenu.py:        item = create_menuitem(_("_Setup..."), get_icon("document-properties", 16))
./po/af.po:msgid "Setup..."
./po/af.po:msgid "_Setup..."
./po/af.po:msgid "_Setup New Device"
./po/sr.po:msgid "Setup..."
./po/sr.po:msgid "_Setup..."
./po/sr.po:msgid "_Setup New Device"
./po/nl.po:msgid "Setup..."
./po/nl.po:msgid "_Setup..."
./po/nl.po:msgid "_Setup New Device"
./po/hu.po:msgid "Setup..."
./po/hu.po:msgid "_Setup..."
./po/hu.po:msgid "_Setup New Device"
./po/nds.po:msgid "Setup..."
./po/nds.po:msgid "_Setup..."
./po/nds.po:msgid "_Setup New Device"
./po/hi.po:msgid "Setup..."
./po/hi.po:msgid "_Setup..."
./po/hi.po:msgid "_Setup New Device"
./po/zh_HK.po:msgid "Setup..."
./po/zh_HK.po:msgid "_Setup..."
./po/zh_HK.po:msgid "_Setup New Device"
./po/gl.po:msgid "Setup..."
./po/gl.po:msgid "_Setup..."
./po/gl.po:msgid "_Setup New Device"
./po/bg.po:msgid "Setup..."
./po/bg.po:msgid "_Setup..."
./po/bg.po:msgid "_Setup New Device"
./po/ro.po:msgid "Setup..."
./po/ro.po:msgid "_Setup..."
./po/ro.po:msgid "_Setup New Device"
./po/ast.po:msgid "Setup..."
./po/ast.po:msgid "_Setup..."
./po/ast.po:msgid "_Setup New Device"
./po/da.po:msgid "Setup..."
./po/da.po:msgid "_Setup..."
./po/da.po:msgid "_Setup New Device"
./po/lt.po:msgid "Setup..."
./po/lt.po:msgid "_Setup..."
./po/lt.po:msgid "_Setup New Device"
./po/ca.po:msgid "Setup..."
./po/ca.po:msgid "_Setup..."
./po/ca.po:msgid "_Setup New Device"
./po/en_GB.po:msgid "Setup..."
./po/en_GB.po:msgstr "Setup..."
./po/en_GB.po:msgid "_Setup..."
./po/en_GB.po:msgstr "_Setup..."
./po/en_GB.po:msgid "_Setup New Device"
./po/en_GB.po:msgstr "_Setup New Device"
./po/en_AU.po:msgid "Setup..."
./po/en_AU.po:msgstr "Setup..."
./po/en_AU.po:msgid "_Setup..."
./po/en_AU.po:msgstr "_Setup..."
./po/en_AU.po:msgid "_Setup New Device"
./po/en_AU.po:msgstr "_Setup New Device"
./po/fr.po:msgid "Setup..."
./po/fr.po:msgid "_Setup..."
./po/fr.po:msgid "_Setup New Device"
./po/uk.po:msgid "Setup..."
./po/uk.po:msgid "_Setup..."
./po/uk.po:msgid "_Setup New Device"
./po/ta.po:msgid "Setup..."
./po/ta.po:msgid "_Setup..."
./po/ta.po:msgid "_Setup New Device"
./po/fi.po:msgid "Setup..."
./po/fi.po:msgid "_Setup..."
./po/fi.po:msgid "_Setup New Device"
./po/sw.po:msgid "Setup..."
./po/sw.po:msgid "_Setup..."
./po/sw.po:msgid "_Setup New Device"
./po/sk.po:msgid "Setup..."
./po/sk.po:msgid "_Setup..."
./po/sk.po:msgid "_Setup New Device"
./po/hr.po:msgid "Setup..."
./po/hr.po:msgid "_Setup..."
./po/hr.po:msgid "_Setup New Device"
./po/mk.po:msgid "Setup..."
./po/mk.po:msgid "_Setup..."
./po/mk.po:msgid "_Setup New Device"
./po/he.po:msgid "Setup..."
./po/he.po:msgid "_Setup..."
./po/he.po:msgid "_Setup New Device"
./po/mr.po:msgid "Setup..."
./po/mr.po:msgid "_Setup..."
./po/mr.po:msgid "_Setup New Device"
./po/pt.po:msgid "Setup..."
./po/pt.po:msgid "_Setup..."
./po/pt.po:msgid "_Setup New Device"
./po/ms.po:msgid "Setup..."
./po/ms.po:msgid "_Setup..."
./po/ms.po:msgid "_Setup New Device"
./po/id.po:msgid "Setup..."
./po/id.po:msgstr "Setup..."
./po/id.po:msgid "_Setup..."
./po/id.po:msgstr "_Setup..."
./po/id.po:msgid "_Setup New Device"
./po/id.po:msgstr "_Setup Perangkat Baru"
./po/ja.po:msgid "Setup..."
./po/ja.po:msgid "_Setup..."
./po/ja.po:msgid "_Setup New Device"
./po/ko.po:msgid "Setup..."
./po/ko.po:msgid "_Setup..."
./po/ko.po:msgid "_Setup New Device"
./po/cy.po:msgid "Setup..."
./po/cy.po:msgid "_Setup..."
./po/cy.po:msgid "_Setup New Device"
./po/et.po:msgid "Setup..."
./po/et.po:msgid "_Setup..."
./po/et.po:msgid "_Setup New Device"
./po/sq.po:msgid "Setup..."
./po/sq.po:msgid "_Setup..."
./po/sq.po:msgid "_Setup New Device"
./po/de.po:msgid "Setup..."
./po/de.po:msgid "_Setup..."
./po/de.po:msgid "_Setup New Device"
./po/kk.po:msgid "Setup..."
./po/kk.po:msgid "_Setup..."
./po/kk.po:msgid "_Setup New Device"
./po/es.po:msgid "Setup..."
./po/es.po:msgid "_Setup..."
./po/es.po:msgid "_Setup New Device"
./po/pt_BR.po:msgid "Setup..."
./po/pt_BR.po:msgid "_Setup..."
./po/pt_BR.po:msgid "_Setup New Device"
./po/fa.po:msgid "Setup..."
./po/fa.po:msgid "_Setup..."
./po/fa.po:msgid "_Setup New Device"
./po/be.po:msgid "Setup..."
./po/be.po:msgid "_Setup..."
./po/be.po:msgid "_Setup New Device"
./po/sv.po:msgid "Setup..."
./po/sv.po:msgid "_Setup..."
./po/sv.po:msgid "_Setup New Device"
./po/sl.po:msgid "Setup..."
./po/sl.po:msgid "_Setup..."
./po/sl.po:msgid "_Setup New Device"
./po/el.po:msgid "Setup..."
./po/el.po:msgid "_Setup..."
./po/el.po:msgid "_Setup New Device"
./po/ar.po:msgid "Setup..."
./po/ar.po:msgid "_Setup..."
./po/ar.po:msgid "_Setup New Device"
./po/vi.po:msgid "Setup..."
./po/vi.po:msgid "_Setup..."
./po/vi.po:msgid "_Setup New Device"
./po/tr.po:msgid "Setup..."
./po/tr.po:msgid "_Setup..."
./po/tr.po:msgid "_Setup New Device"
./po/ru.po:msgid "Setup..."
./po/ru.po:msgid "_Setup..."
./po/ru.po:msgid "_Setup New Device"
./po/bs.po:msgid "Setup..."
./po/bs.po:msgid "_Setup..."
./po/bs.po:msgid "_Setup New Device"
./po/cs.po:msgid "Setup..."
./po/cs.po:msgid "_Setup..."
./po/cs.po:msgid "_Setup New Device"
./po/am.po:msgid "Setup..."
./po/am.po:msgid "_Setup..."
./po/am.po:msgid "_Setup New Device"
./po/eu.po:msgid "Setup..."
./po/eu.po:msgid "_Setup..."
./po/eu.po:msgid "_Setup New Device"
./po/zh_CN.po:msgid "Setup..."
./po/zh_CN.po:msgid "_Setup..."
./po/zh_CN.po:msgid "_Setup New Device"
./po/it.po:msgid "Setup..."
./po/it.po:msgid "_Setup..."
./po/it.po:msgid "_Setup New Device"
./po/nb.po:msgid "Setup..."
./po/nb.po:msgid "_Setup..."
./po/nb.po:msgid "_Setup New Device"
./po/pl.po:msgid "Setup..."
./po/pl.po:msgid "_Setup..."
./po/pl.po:msgid "_Setup New Device"
./po/lv.po:msgid "Setup..."
./po/lv.po:msgid "_Setup..."
./po/lv.po:msgid "_Setup New Device"
./po/zh_TW.po:msgid "Setup..."
./po/zh_TW.po:msgid "_Setup..."
./po/zh_TW.po:msgid "_Setup New Device"
./aclocal.m4:    # Setup a source with many dependencies, because some compilers
./autom4te.cache/traces.0:    # Setup a source with many dependencies, because some compilers
./autom4te.cache/output.1:    # Setup a source with many dependencies, because some compilers
./autom4te.cache/output.0:    # Setup a source with many dependencies, because some compilers
./configure:    # Setup a source with many dependencies, because some compilers
./data/ui/manager-main.ui:            <property name="label" translatable="yes" comments="translators: toolbar item: keep it as short as possible">Setup...</property>

**Comment by cschramm** [comment]
Thanks. I just did a search & replace for that.
