### ISSUE TITLE
Headset connection fails. "DBusNotAvailableError"

### ISSUE THREAD

**Issue by vasilis74** [blueman-project/blueman#693]
Hello
I try to connect a **Dell mini 9** netbook to a **Nokia BH-310** bluetooth handsfree.
I tried both **headset** and **handsfree** connection, they give the following message:
_Connection Failed: blueman.bluez.errors.DBusNotAvailableError: Operation currently not available_
When I run the **Set up device**, I get the message:
_Device added succsessfuly, but failed to connect_.
Can someone help?

**Comment by infirit** [comment]
Most problems related to bluetooth audio on linux are solved by following the sugestions from https://github.com/blueman-project/blueman/wiki/Troubleshooting#a2dp-audio-device-paired-but-fails-to-connect. If you still have problems make sue to read https://github.com/blueman-project/blueman/wiki/Troubleshooting#reporting-a-bug--asking-for-support
