### ISSUE TITLE
Do not change places in top bar of GNOME Shell

### ISSUE THREAD

**Issue by PanderMusubi** [blueman-project/blueman#697]
When the status of Bluetooth changes (on or off) the icon in the top bar of GNOME Shell changes places, see also attached screenshots (please ignore the pink around the sound icon). Please let it remain on the same position as this is less disturbing for the user.

![screenshot from 2017-05-12 12-01-58](https://cloud.githubusercontent.com/assets/198964/25993723/408ba234-370b-11e7-8e73-de85b82151a1.png)

This was reported for blueman version 2.0.4-1ubuntu2

**Comment by cschramm** [comment]
The one below is not our logo so I suppose it's not blueman at all.

**Comment by PanderMusubi** [comment]
Well, if you click on it, you get blueman. :-)

**Comment by cschramm** [comment]
Looks like GNOME Shell does not maintain the position of applications then. I don't think there's anything we can do about that.

**Comment by PanderMusubi** [comment]
Other application do remain in place. I think the change of icon might be the cause of it.

**Comment by cschramm** [comment]
I'd file a bug against `gnome-shell` and await the reply.
