### ISSUE TITLE
Name full website url in about dialog

### ISSUE THREAD

**Issue by PanderMusubi** [blueman-project/blueman#698]
Please name full website url in about dialog. See also attached screenshot. Some people want to see the url without having to create unwanted HTTP traffic.

![screenshot from 2017-05-12 12-07-59](https://cloud.githubusercontent.com/assets/198964/25993878/e513def2-370b-11e7-9f7c-85cda21e28be.png)

Also change in all static strings in the source code and documentation "GTK based" to "GTK-based".

**Comment by cschramm** [comment]
You can right-click and copy it, no?

**Comment by PanderMusubi** [comment]
Yes, I see that now. I would not expect that. But url look nicer IMHO.

**Comment by infirit** [comment]
I care very little how it looks but we can do the below. Objections @cschramm?

![afbeelding](https://cloud.githubusercontent.com/assets/3465730/26254907/67c9c030-3cb8-11e7-9e21-a162f9908562.png)

**Comment by cschramm** [comment]
Fine for me. 🙂
