### ISSUE TITLE
Blueman fails to start on Fedora Rawhide x86_64 blueman.constants missing...

### ISSUE THREAD

**Issue by tonyabc** [blueman-project/blueman#71]
I have compiled 1.23 on a Fedora 21 (Rawhide) build using the mate desktop and blueman fails to start with a blueman.constants missing error (below), no errors during autogen or make (I can supply the full build output if required).

Ideas?

Jul  7 01:37:58 banana python: detected unhandled Python exception in '/usr/local/bin/blueman-applet'
Jul  7 01:37:59 banana abrt-server: Executable '/usr/local/bin/blueman-applet' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Jul  7 01:37:59 banana abrt-server: 'post-create' on '/var/tmp/abrt/Python-2014-07-07-01:37:59-2046' exited with 1
Jul  7 01:37:59 banana abrt-server: Deleting problem directory '/var/tmp/abrt/Python-2014-07-07-01:37:59-2046'
Jul  7 01:37:59 banana /etc/gdm/Xsession: Traceback (most recent call last):
Jul  7 01:37:59 banana /etc/gdm/Xsession: File "/usr/local/bin/blueman-applet", line 9, in <module>
Jul  7 01:37:59 banana /etc/gdm/Xsession: from blueman.Constants import *
Jul  7 01:37:59 banana /etc/gdm/Xsession: ImportError: No module named blueman.Constants
Jul  7 01:38:00 banana /etc/gdm/Xsession: Initializing caja-open-terminal extension

**Comment by norpol** [comment]
Hi! FYI: `./configure --prefix=/usr` made it for me. At least when I `make install` it.
