### ISSUE TITLE
bluetooth connect problem

### ISSUE THREAD

**Issue by ziyou226** [blueman-project/blueman#710]
blueman-applet:3.0.2
linux mint:18.1  cinnamon 64-bit

Hi, I really need your help .
Earlier I let bleachbit delete some packages related with bluetooth,
now my laptop cannt connect to my bluetooth soundbox,
but blueman can find it in the list,
when try to connect ,words will show :
 blueman.bluez.errors.DBusFailedError: No such file or directory

**Comment by infirit** [comment]
Most of the time the problem is missing bluetooth pulseaudio package, see https://wiki.debian.org/BluetoothUser/a2dp for the details.

**Comment by ziyou226** [comment]
thank you
