### ISSUE TITLE
Message: Network Manager failed to activate the connection

### ISSUE THREAD

**Issue by foggy67** [blueman-project/blueman#722]
![capture du 2017-07-05 16-55-02](https://user-images.githubusercontent.com/29923817/27870550-6badc2b8-61a3-11e7-92a4-0be84dd2c76e.png)

Hello
When pairing with my Samsung Galaxy Ace 4 to get the Internet connection from the PC, the message above appear.
Audio sharing to play an audio file from my smartphone works very well. Only the Internet link fails to set up.
Is this a bug?
If I let Blueman managing the PAN and the DUN, I get the message "input/output error"
Is that also a bug?

Here is a log file with the error message:
![capture du 2017-07-05 17-16-36](https://user-images.githubusercontent.com/29923817/27871382-d1d8c522-61a5-11e7-8eb0-4990e4a74214.png)

Thank you.

**Comment by parkerlreed** [comment]
NetworkManager also isn't working for me. It instantly drops connection even if I only do it from within NetworkManager.

The bnep0 interface devices gets created, never used, and I can manually run dhcpcd on it afterwards and it works fine.

````
Jul 06 11:35:20 inspiron NetworkManager[814]: <info>  [1499355320.7857] bluez: use BlueZ version 5
Jul 06 11:35:20 inspiron NetworkManager[814]: <info>  [1499355320.7870] manager: startup complete
Jul 06 11:35:20 inspiron NetworkManager[814]: <info>  [1499355320.7978] supplicant: wpa_supplicant running
Jul 06 11:35:20 inspiron NetworkManager[814]: <info>  [1499355320.8359] keyfile: add connection in-memory (31c96844-8303-4c7a-a1c2-dfc168b6bb37,"Nexus 5X Network")
Jul 06 11:35:20 inspiron NetworkManager[814]: <info>  [1499355320.8401] bluez: BT device Nexus 5X (A0:91:69:95:88:84) added (NAP)
Jul 06 11:35:20 inspiron NetworkManager[814]: <info>  [1499355320.8424] manager: (A0:91:69:95:88:84): new Bluetooth device (/org/freedesktop/NetworkManager/Devices/3)
Jul 06 11:35:20 inspiron NetworkManager[814]: <info>  [1499355320.8432] device (A0:91:69:95:88:84): state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
Jul 06 11:35:20 inspiron NetworkManager[814]: <info>  [1499355320.8560] device (A0:91:69:95:88:84): state change: unavailable -> disconnected (reason 'none') [20 30 0]
Jul 06 11:37:37 inspiron NetworkManager[814]: <info>  [1499355457.7779] device (A0:91:69:95:88:84): Activation: starting connection 'Nexus 5X Network' (31c96844-8303-4c7a-a1c2-dfc168b6bb37)
Jul 06 11:37:37 inspiron NetworkManager[814]: <info>  [1499355457.7782] audit: op="connection-activate" uuid="31c96844-8303-4c7a-a1c2-dfc168b6bb37" name="Nexus 5X Network" pid=682 uid=1000 result="success"
Jul 06 11:37:37 inspiron NetworkManager[814]: <info>  [1499355457.7787] device (A0:91:69:95:88:84): state change: disconnected -> prepare (reason 'none') [30 40 0]
Jul 06 11:37:37 inspiron NetworkManager[814]: <info>  [1499355457.7792] manager: NetworkManager state is now CONNECTING
Jul 06 11:37:37 inspiron NetworkManager[814]: <info>  [1499355457.7803] device (A0:91:69:95:88:84): state change: prepare -> config (reason 'none') [40 50 0]
Jul 06 11:37:37 inspiron NetworkManager[814]: <warn>  [1499355457.7870] device (A0:91:69:95:88:84): Error connecting with bluez: GDBus.Error:org.bluez.Error.Failed: Operation already in progress
Jul 06 11:37:37 inspiron NetworkManager[814]: <info>  [1499355457.7871] device (A0:91:69:95:88:84): state change: config -> failed (reason 'bluetooth-failed') [50 120 44]
Jul 06 11:37:37 inspiron NetworkManager[814]: <info>  [1499355457.7875] manager: NetworkManager state is now DISCONNECTED
Jul 06 11:37:37 inspiron NetworkManager[814]: <warn>  [1499355457.7889] device (A0:91:69:95:88:84): Activation: failed for connection 'Nexus 5X Network'
Jul 06 11:37:37 inspiron NetworkManager[814]: <info>  [1499355457.8193] device (A0:91:69:95:88:84): state change: failed -> disconnected (reason 'none') [120 30 0]
Jul 06 11:37:45 inspiron NetworkManager[814]: <info>  [1499355465.1218] device (A0:91:69:95:88:84): Activation: starting connection 'Nexus 5X Network' (31c96844-8303-4c7a-a1c2-dfc168b6bb37)
Jul 06 11:37:45 inspiron NetworkManager[814]: <info>  [1499355465.1222] audit: op="connection-activate" uuid="31c96844-8303-4c7a-a1c2-dfc168b6bb37" name="Nexus 5X Network" pid=682 uid=1000 result="success"
Jul 06 11:37:45 inspiron NetworkManager[814]: <info>  [1499355465.1228] device (A0:91:69:95:88:84): state change: disconnected -> prepare (reason 'none') [30 40 0]
Jul 06 11:37:45 inspiron NetworkManager[814]: <info>  [1499355465.1233] manager: NetworkManager state is now CONNECTING
Jul 06 11:37:45 inspiron NetworkManager[814]: <info>  [1499355465.1244] device (A0:91:69:95:88:84): state change: prepare -> config (reason 'none') [40 50 0]
Jul 06 11:37:46 inspiron NetworkManager[814]: <info>  [1499355466.6565] device (A0:91:69:95:88:84): Activation: (bluetooth) Stage 2 of 5 (Device Configure) successful. Will connect via PAN.
Jul 06 11:37:46 inspiron NetworkManager[814]: <info>  [1499355466.6572] device (A0:91:69:95:88:84): state change: config -> ip-config (reason 'none') [50 70 0]
Jul 06 11:37:46 inspiron NetworkManager[814]: <info>  [1499355466.6631] dhcp4 (bnep0): activation: beginning transaction (timeout in 45 seconds)
Jul 06 11:37:46 inspiron NetworkManager[814]: ((src/platform/nm-platform.c:2650)): assertion '<dropped>' failed
Jul 06 11:37:46 inspiron NetworkManager[814]: g_array_sort_with_data: assertion 'array != NULL' failed
Jul 06 11:37:46 inspiron systemd[1]: NetworkManager.service: Main process exited, code=dumped, status=11/SEGV
Jul 06 11:37:46 inspiron systemd[1]: NetworkManager.service: Unit entered failed state.
Jul 06 11:37:46 inspiron systemd[1]: NetworkManager.service: Failed with result 'core-dump'.
Jul 06 11:37:46 inspiron systemd[1]: NetworkManager.service: Service hold-off time over, scheduling restart.
Jul 06 11:37:46 inspiron systemd[1]: Stopped Network Manager.
Jul 06 11:37:46 inspiron systemd[1]: Starting Network Manager...
````

NetworkManager seems to fail, then crash ad restart.

**Comment by foggy67** [comment]
Thank you for your explanation, I am not alone dealing with that trouble :)
Can anybody solve these regressions or bugs? May be the package maintainer?

**Comment by infirit** [comment]
Confirmed, something wonky is going on but have not checked if we are at fault.

**Comment by infirit** [comment]
NetworkManager crashes with the following dbus call as well and with blueman not running. If folks are running into this file a bug report with your distro please.

```
$ gdbus call -y -d "org.freedesktop.NetworkManager" -o "/org/freedesktop/NetworkManager" -m "org.freedesktop.NetworkManager.ActivateConnection" "/org/freedesktop/NetworkManager/Settings/5" "/org/freedesktop/NetworkManager/Devices/6" "/"
```

**Comment by infirit** [comment]
Should be fixed with NetworkManager 1.8.2, https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/NEWS?h=nm-1-8

**Comment by foggy67** [comment]
Hello
Here is the result of the gbus command on my system:
damien@damien-Lenovo-G70-80:~$ gdbus call -y -d "org.freedesktop.NetworkManager" -o "/org/freedesktop/NetworkManager" -m "org.freedesktop.NetworkManager.ActivateConnection" "/org/freedesktop/NetworkManager/Settings/5" "/org/freedesktop/NetworkManager/Devices/6" "/"
Erreur : GDBus.Error:org.freedesktop.NetworkManager.UnknownConnection: Connection could not be found.
(According to introspection data, you need to pass 'ooo')

I have Network Manager 1.2.6 on my system.

**Comment by infirit** [comment]
re-opening as the the @foggy67 actually has a different problem than me and @parkerlreed have.

@foggy67, that command line is from my machine and the object paths most likely are different for you.

Instead can you please follow https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging and provide the logs for __both__ ``blueman-applet`` and ``blueman-manager``.

**Comment by foggy67** [comment]
Hi,
Here is the log for Blueman-applet, when I try to pair my 2 devices to get the internet connection from the PC:

damien@damien-Lenovo-G70-80:~$ blueman-applet --log-level debug
blueman-applet version 2.0.4 starting
Stale PID, overwriting
_________
Load (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:60)
['StandardItems', 'NMDUNSupport', 'RecentConns', 'SerialManager', 'GameControllerWakelock', 'Headset', 'AppIndicator', 'AuthAgent', 'ExitItem', 'ShowConnected', 'NetUsage', 'PPPSupport', 'NMPANSupport', 'KillSwitch', 'DiscvManager', 'Networking', 'TransferService', 'DhcpClient', 'PowerManager', 'Menu', 'DBusService', 'StatusIcon'] 
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
_________
get_interface_version (/usr/lib/python3/dist-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 5 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Menu.Menu'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'> 
_________
update_menuitems (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:123)
warning: Adapter is None 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DBusService.DBusService'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NMPANSupport.NMPANSupport'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.TransferService.TransferService'> 
_________
get_interface_version (/usr/lib/python3/dist-packages/blueman/bluez/obex/Base.py:20)
Detected BlueZ integrated obexd 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NetUsage.NetUsage'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AppIndicator.AppIndicator'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Networking.Networking'> 
_________
load_nap_settings (/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py:36)
Loading NAP settings 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ExitItem.ExitItem'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Headset.Headset'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
_________
io_event (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
killswitch registered 1 
_________
io_event (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
State: True 
_________
UpdatePowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False 
foff False 
on True 
current state True 
new state True 
_________
io_event (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
killswitch registered 2 
_________
io_event (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
State: True 
_________
UpdatePowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False 
foff False 
on True 
current state True 
new state True 
_________
_on_obex_owner_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/TransferService.py:172)
obex owner changed: :1.71 
_________
on_dbus_name_owner_change (/usr/bin/blueman-applet:95)
org.bluez owner changed to :1.1 
_________
set_nap (/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py:65)
set nap True 
_________
__init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
caching initial properties 
_________
__init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
caching initial properties 
_________
__init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
caching initial properties 
_________
initialize (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:144)
rebuilding menu 
_________
register_agent (/usr/lib/python3/dist-packages/blueman/plugins/applet/AuthAgent.py:63)
Registering agent 
_________
enumerate_connections (/usr/lib/python3/dist-packages/blueman/plugins/applet/ShowConnected.py:53)
Found 1 existing connections 
_________
on_register_failed (/usr/lib/python3/dist-packages/blueman/bluez/obex/AgentManager.py:21)
/org/blueman/obex_agent org.bluez.obex.Error.AlreadyExists: Agent already exists 
_________
on_adapter_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:96)
prop Class 1966348 
_________
on_adapter_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:96)
prop UUIDs dbus.Array([dbus.String('00001801-0000-1000-8000-00805f9b34fb'), dbus.String('0000110e-0000-1000-8000-00805f9b34fb'), dbus.String('00001106-0000-1000-8000-00805f9b34fb'), dbus.String('00001800-0000-1000-8000-00805f9b34fb'), dbus.String('00001105-0000-1000-8000-00805f9b34fb'), dbus.String('00001200-0000-1000-8000-00805f9b34fb'), dbus.String('0000110c-0000-1000-8000-00805f9b34fb'), dbus.String('00001104-0000-1000-8000-00805f9b34fb'), dbus.String('0000110b-0000-1000-8000-00805f9b34fb'), dbus.String('0000110a-0000-1000-8000-00805f9b34fb'), dbus.String('00005005-0000-1000-8000-0002ee000001'), dbus.String('00001116-0000-1000-8000-00805f9b34fb'), dbus.String('00001133-0000-1000-8000-00805f9b34fb'), dbus.String('0000112f-0000-1000-8000-00805f9b34fb'), dbus.String('00001132-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1) 
_________
RequestPowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:131)
Requesting True 
_________
on_power_state_change_requested (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:118)
True 
_________
UpdatePowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False 
foff False 
on True 
current state True 
new state True 
_________
check (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:119)
callbacks done 
_________
set_adapter_state (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:90)
True 
blueman-manager version 2.0.4 starting
Stale PID, overwriting
_________
__init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
caching initial properties 
_________
notify (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:239)
<Device.Device object at 0x7febfb344708 (blueman+main+Device+Device at 0x25aa280)> <blueman.services.NetworkAccessPoint.NetworkAccessPoint object at 0x7febfb346a90> 00001116-0000-1000-8000-00805f9b34fb 
_________
__del__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:72)
deleting device /org/bluez/hci0/dev_08_EC_A9_67_04_91 
_________
Destroy (/usr/lib/python3/dist-packages/blueman/main/Device.py:94)
invalidating device /org/bluez/hci0/dev_08_EC_A9_67_04_91 
_________
initialize (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:144)
rebuilding menu 
_________
on_nm_device_added (/usr/lib/python3/dist-packages/blueman/plugins/applet/NMPANSupport.py:63)
/org/freedesktop/NetworkManager/Devices/8 
_________
on_nma_new_connection (/usr/lib/python3/dist-packages/blueman/plugins/applet/NMPANSupport.py:69)
/org/freedesktop/NetworkManager/Settings/8 
_________
init_connection (/usr/lib/python3/dist-packages/blueman/plugins/applet/NMPANSupport.py:75)
activating /org/freedesktop/NetworkManager/Settings/8 /org/freedesktop/NetworkManager/Devices/8 
_________
on_device_state (/usr/lib/python3/dist-packages/blueman/plugins/applet/NMPANSupport.py:97)
state= 30 oldstate= 20 reason= 0 
_________
on_device_state (/usr/lib/python3/dist-packages/blueman/plugins/applet/NMPANSupport.py:97)
state= 40 oldstate= 30 reason= 0 
_________
on_device_state (/usr/lib/python3/dist-packages/blueman/plugins/applet/NMPANSupport.py:97)
state= 50 oldstate= 40 reason= 0 
_________
on_network_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/NetUsage.py:374)
Connected 1 /org/bluez/hci0/dev_08_EC_A9_67_04_91 
_________
on_network_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/NetUsage.py:374)
UUID 00001116-0000-1000-8000-00805f9b34fb /org/bluez/hci0/dev_08_EC_A9_67_04_91 
_________
on_network_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/NetUsage.py:374)
Interface bnep0 /org/bluez/hci0/dev_08_EC_A9_67_04_91 
_________
__init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
caching initial properties 
_________
on_device_state (/usr/lib/python3/dist-packages/blueman/plugins/applet/NMPANSupport.py:97)
state= 70 oldstate= 50 reason= 0 
_________
on_network_property_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/NetUsage.py:374)
Connected 0 /org/bluez/hci0/dev_08_EC_A9_67_04_91 
_________
on_device_state (/usr/lib/python3/dist-packages/blueman/plugins/applet/NMPANSupport.py:97)
state= 120 oldstate= 70 reason= 5 
/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerProgressbar.py:165: Warning: Source ID 1061 was not found when attempting to remove it
  GObject.source_remove(self.gsource)

Here is the log file for Blueman-manager under the same conditions as above:

damien@damien-Lenovo-G70-80:~$ blueman-manager --log-file debug
_________
Load (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:60)
['PulseAudioProfile', 'Services'] 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.manager.Services.Services'> 
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.manager.PulseAudioProfile.PulseAudioProfile'> 
_________
pa_context_event (/usr/lib/python3/dist-packages/blueman/main/PulseAudioUtils.py:341)
1 
blueman-manager version 2.0.4 starting
Stale PID, overwriting
_________
pa_context_event (/usr/lib/python3/dist-packages/blueman/main/PulseAudioUtils.py:341)
2 
_________
on_bluez_name_owner_changed (/usr/bin/blueman-manager:96)
org.bluez owner changed to  :1.1 
_________
get_interface_version (/usr/lib/python3/dist-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 5 
_________
SetAdapter (/usr/lib/python3/dist-packages/blueman/gui/DeviceList.py:271)
 
_________
on_adapter_changed (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerToolbar.py:83)
toolbar adapter /org/bluez/hci0 
_________
__init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
caching initial properties 
_________
add_device (/usr/lib/python3/dist-packages/blueman/gui/DeviceList.py:317)
adding new device 
_________
do_cache (/usr/lib/python3/dist-packages/blueman/gui/DeviceList.py:496)
Caching new device B0:47:BF:44:09:03 
_________
row_update_event (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Fake False 
_________
row_update_event (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Trusted 0 
_________
row_update_event (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Paired 1 
_________
__init__ (/usr/lib/python3/dist-packages/blueman/main/Device.py:26)
caching initial properties 
_________
add_device (/usr/lib/python3/dist-packages/blueman/gui/DeviceList.py:317)
adding new device 
_________
do_cache (/usr/lib/python3/dist-packages/blueman/gui/DeviceList.py:496)
Caching new device 08:EC:A9:67:04:91 
_________
row_update_event (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Fake False 
_________
row_update_event (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Trusted 1 
_________
row_update_event (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Paired 1 
_________
monitor_power_levels (/usr/lib/python3/dist-packages/blueman/gui/DeviceList.py:185)
starting monitor 
_________
level_setup_event (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceList.py:325)
animating up 
_________
Generate (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:173)
 SM-G318H 
_________
pa_context_event (/usr/lib/python3/dist-packages/blueman/main/PulseAudioUtils.py:341)
3 
_________
pa_context_event (/usr/lib/python3/dist-packages/blueman/main/PulseAudioUtils.py:341)
4 
_________
on_pa_ready (/usr/lib/python3/dist-packages/blueman/plugins/manager/PulseAudioProfile.py:29)
connected 
_________
<lambda> (/usr/lib/python3/dist-packages/blueman/main/PulseAudioUtils.py:353)
1 
_________
Generate (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:173)
 SM-G318H 
_________
Generate (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:173)
SM-G357FZ 
_________
Generate (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:173)
SM-G357FZ 
_________
set_op (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:85)
op: regenerating instance <ManagerDeviceMenu.ManagerDeviceMenu object at 0x7f36fcc5daf8 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x2061340)> 
_________
set_op (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:85)
op: regenerating instance <ManagerDeviceMenu.ManagerDeviceMenu object at 0x7f36f60fc9d8 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x2061a90)> 
_________
unset_op (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:99)
op: regenerating instance <ManagerDeviceMenu.ManagerDeviceMenu object at 0x7f36fcc5daf8 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x2061340)> 
_________
Generate (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:173)
SM-G357FZ 
_________
unset_op (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:99)
op: regenerating instance <ManagerDeviceMenu.ManagerDeviceMenu object at 0x7f36f60fc9d8 (blueman+gui+manager+ManagerDeviceMenu+ManagerDeviceMenu at 0x2061a90)> 
_________
fail (/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerDeviceMenu.py:124)
fail org.freedesktop.DBus.Python.dbus.exceptions.DBusException: Network Manager Failed to activate the connection 
/usr/lib/python3/dist-packages/blueman/gui/manager/ManagerProgressbar.py:165: Warning: Source ID 821 was not found when attempting to remove it
  GObject.source_remove(self.gsource)


May those logs help you....
