### ISSUE TITLE
E1 headset pairs but do not connect

### ISSUE THREAD

**Issue by mitcoes** [blueman-project/blueman#741]
It works with Android, and in this same computer with MS WOS 10.
The Adapter is ORICO BTA-403
The error is: Connection Failed: blueman.bluez.errors.DBusFailedError: Protocol not available...

**Comment by infirit** [comment]
Most likely missing pulseaudio, see https://github.com/blueman-project/blueman/wiki/Troubleshooting#a2dp-audio-device-paired-but-fails-to-connect
