### ISSUE TITLE
Systray icon misaligned in Arch Linux

### ISSUE THREAD

**Issue by Hacksaurus** [blueman-project/blueman#750]
I was just wondering if this is an issue pertaining to my icon theme or this is a bug with bluman... But it seems to be some sort of misalignment in the bluetooth icon...

Examples:
![screenshot_2017-08-15_08-14-31](https://user-images.githubusercontent.com/24832107/29345279-8df2cdea-81f2-11e7-85ef-efec6eb34a41.png)
![screenshot_2017-08-15_08-14-00](https://user-images.githubusercontent.com/24832107/29345280-8df3907c-81f2-11e7-8601-33fc5bce8954.png)

From these 2 perspectives it seems like that blueman is causing the trouble...

Thanks for any help!

**Comment by cschramm** [comment]
You mean it is not centered but shifted to the left a little bit?

That is not our icon. It comes from some icon theme.

I've listed icon themes that contain icons for blueman and are included in Ubuntu yakkety in https://github.com/blueman-project/blueman/issues/696#issuecomment-301047681.

**Comment by Hacksaurus** [comment]
Oh, I'm sorry I have the icon pack "Numix-Circle"

**Comment by cschramm** [comment]
My guess is that you're seeing https://github.com/numixproject/numix-icon-theme/blob/master/Numix/22/panel/bluetooth-active.svg, so it's not the icon itself that's off.

Are you using the AppIndicator plugin (check if a left click opens the menu (app indicator) or the manager window (otherwise))?

**Comment by infirit** [comment]
It look like the numix icon is 18x22 which could explain it not aligning properly. Our default icons are 22x22.

in my quick test it shows the same behaviour in the classic tray and appindicator.

**Comment by Hacksaurus** [comment]
@cschramm Whenever I click the menu, it opens the manager...

**Comment by cschramm** [comment]
Looks like an issue in the Numix icon theme. All icons I checked in https://github.com/numixproject/numix-icon-theme/tree/master/Numix/22/panel are rectangular except the bluetooth ones (to which the blueman ones link to). I'd create an issue there, @Hacksaurus.

**Comment by Hacksaurus** [comment]
Ok got it! Thanks for the help!
