### ISSUE TITLE
Appindicator Colour

### ISSUE THREAD

**Issue by nimrod86** [blueman-project/blueman#756]
Probably a very trivial issue, but I don't seem to be able to change the colour of the applet icon in the task bar. I assume this is controlled by the plugin "appindicator" as when I disable I lose the icon, but the configure button in the plugins menu isn't clickable. Is there a way to change the icon to a blue colour to make it stand out on a grey/black task bar?

**Comment by cschramm** [comment]
The `AppIndicator` plugin does not have any configuration. Our blueman icon actually *is* blue. You seem to have a monochrome icon theme that overrides it (e.g. Numix).
