### ISSUE TITLE
Debian 9

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#758]
I am currently checking blueman on it and ifconfig is not installed and we fail to configure.

The simplest option is to add net-tools as dep but porting to using the ``ip`` command should be pretty easy. Either way we need to fix blueman in debian.

**Comment by infirit** [comment]
#759 adds ip for using network configuration.

**Comment by MisterShivers** [comment]
I connected my phone to my bluetooth using blueman and it connected just fine but after 3 reformatts I am not able to see the bluetooth after making it discoverable when i scan on my phone
