### ISSUE TITLE
Can not pair certain devices in GUI

### ISSUE THREAD

**Issue by sup2069** [blueman-project/blueman#762]
Using the GUI to pair an Iphone 7 Plus with auto pair, and setup GUI, ends in with an "unsuccessful pair". One must use bluetoothctl's pair command in terminal to receive the pair code prompt, allowing for a then successful pair. 

GUI lacks this functionality, or is not working as intended.

blueman: 2.0.4
BlueZ: 5.45
Distribution: Debian 9 (stretch)
Desktop environment: Mate

Report tool debug upload
[log.txt](https://github.com/blueman-project/blueman/files/1254006/log.txt)

url
https://gist.github.com/anonymous/4262d4491984981ba30692cf43ba5e2a

**Comment by cschramm** [comment]
Hi, I just added https://github.com/blueman-project/blueman/wiki/Troubleshooting#pairing-fails-on-the-remote-devices-side-wihout-a-pairing-dialog-showing for that case. You've already done the `bluetoothctl` step. Please try the python snippet and see what happens.

Please confirm that you have the package `mate-notification-daemon` and your `libnotify4` is 0.7.7.

**Comment by sup2069** [comment]
Thanks for the prompt reply! I already have `mate-notification-daemon` and `libnotify4` (0.7.7-2) installed. Ran the python snippet and got the test notification to popup. 
![screenshot at 2017-08-27 12-20-51](https://user-images.githubusercontent.com/14266320/29752822-4dddbc18-8b22-11e7-9d01-993c09dd9654.png)

**Comment by cschramm** [comment]
Strange. This is the interesting part from your log:

```
[1mRequestConfirmation[0m (/usr/lib/python3/dist-packages/blueman/main/applet/BluezAgent.py:205)
Agent.RequestConfirmation 
```

It shows that blueman does get the pairing request from BlueZ. The code at that point is:

```
        dprint("Agent.RequestConfirmation")
        alias = self.get_device_alias(device)
        notify_message = _("Pairing request for:") + "\n%s" % alias
        if passkey:
            notify_message += "\n" + _("Confirm value for authentication:") + " <b>%s</b>" % passkey
        actions = [["confirm", _("Confirm")], ["deny", _("Deny")]]

        self.n = Notification("Bluetooth", notify_message, 0, actions, on_confirm_action,
                              pixbuf=get_icon("blueman", 48), status_icon=self.status_icon)
```

So it should lead directly to the notification that you just tested successfully.

Maybe the `(blueman-applet:6417): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed` points to some issue (@infitit: Any idea?).

There are only two points where your test differs: It does not use an icon or provide position hints. To  test the icon you can do:

```
from blueman.gui.Notification import Notification
from blueman.Functions import get_icon
Notification("Title", "Message", 0, [["action1", _("Action 1")], ["action2", _("Action 2")]], pixbuf=get_icon("blueman", 48))
```

To test if the position hints are the problem, you can edit /usr/lib/python3/dist-packages/blueman/main/applet/BluezAgent.py. Remove the `status_icon` argument from line 222 so that it is just `pixbuf=get_icon("blueman", 48))`. Then restart `blueman-applet` and try pairing again.

**Comment by infirit** [comment]
>Maybe the ```(blueman-applet:6417): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed``` points to some issue (@infitit: Any idea?).

its harmless and you can ignore that. Its AppIndicator not having a place to put its indicators and being annoying about it.

**Comment by sup2069** [comment]
> To test if the position hints are the problem, you can edit /usr/lib/python3/dist-packages/blueman/main/applet/BluezAgent.py. Remove the status_icon argument from line 222 so that it is just pixbuf=get_icon("blueman", 48)). Then restart blueman-applet and try pairing again.


Success! 

![screenshot at 2017-08-28 11-00-29](https://user-images.githubusercontent.com/14266320/29784202-68372540-8be0-11e7-8f03-f00b90f9c03e.png)

**Comment by infirit** [comment]
Disabling AppIndicator plugin should also workaround this. For some reason get_geometry is way off when in this situation and we display the notification off screen.

**Comment by cschramm** [comment]
@infirit: What exactly is "this situation"? Notifications work fine for me with AppIndicator on Xfce with xfce4-notifyd (might very well be that it just ignores the position hints).

**Comment by infirit** [comment]
So when it is enabled it gives me x and y like this,
```blueman-applet 19.51.41 WARNING  StatusIcon:46 geometry  : Got garbage x 330320972 or y 32766 value```. Considering my screen is 1920x1080 x and y are not even close.

However, just looked into this a bit more. AppIndicator actually provides a fallback StatusIcon so we probably should just move things over. If you don't mind, for 2.0 I'll prepare a PR that checks x and y against the screen size and always return something sane. In my quick tests using zero seems to work ok.

**Comment by infirit** [comment]
Workaround to try, https://github.com/infirit/blueman/commit/f7aa1fe5f3cbe3d2c9bb949df3bc7ee3c0910d1a

**Comment by sup2069** [comment]
> Workaround to try, infirit/blueman@f7aa1fe

I reversed cschramm's edit to `/usr/lib/python3/dist-packages/blueman/main/applet/BluezAgent.py` and made the edits to `blueman/gui/Notification.py`.

Success! The only noticeable change is that the notification is now on the left instead of the right. I will report back once I reboot. 

![screenshot at 2017-08-28 20-29-07](https://user-images.githubusercontent.com/14266320/29802394-091cf574-8c32-11e7-907c-cde07afc949f.png)

**Comment by sup2069** [comment]
Rebooted the computer, GUI pair successful again.
