### ISSUE TITLE
Device dialog hangs - power monitor error - PPA for 2.0.4+ commits?

### ISSUE THREAD

**Issue by dkebler** [blueman-project/blueman#770]
blueman: 2.0.4
BlueZ: 5.37
Distribution:  16.04
Desktop environment: unbuntu-mate on arm chip

The tray applet launches fine but the `setup new device` and `Devices` dialogs crash.  (they actually worked when ubuntu-mate was initially installed but later system updates have caused this issue)

If I start from the cli  blueman-manager I get the error below.

If I use bluetoothctl I have no trouble discovering, pairing, and connecting to any BT device.

I see there has been 642 commits since release 2.0.4.  I see no point in tracking down this issue until I have loaded something not so stale as 2.0.4 which was relased before even bluez 5+  But...I can't find any ppa for blueman.  I don't currently have a setup for compiling for ARM so hoping someone is doing this already.    Even finding the ARM binary for 2.1.alpha1 would be an improvement.

error when running blueman-manager from CLI
```
monitor_power_levels (/usr/lib/python3/dist-packages/blueman/gui/DeviceList.py:185)
starting monitor 
*** Error in `/usr/bin/python3': free(): invalid next size (fast): 0x000000000107b3b0 ***
Aborted (core dumped)
```

**Comment by cschramm** [comment]
Might be a bug in the Cython version that was used when building the package (I suppose you're using the official Ubuntu binary package?). Could you send the core dump?

> finding the ARM binary for 2.1.alpha1 would be an improvement.

https://packages.debian.org/experimental/blueman#pdownload
