### ISSUE TITLE
Support for Rii Bluetooth RT-MWK02+

### ISSUE THREAD

**Issue by APGRoboCop** [blueman-project/blueman#784]
blueman: 2.0.4-1+b4
BlueZ: 5.43-2+rpt1+deb9u1
Distribution: Raspbian GNU/Linux 9 (stretch)
Desktop environment: PIXEL

Hello I'm trying to connect my BlueTooth Keyboard to my Raspberry Pi SBC but it seems like it won't pair up properly. I did try this Keyboard on my Kodi and it seems to work alright, even though I had to blow and clean my BlueTooth Dongle to check if it works or not. This Keyboard is new but I don't know if Blueman got a pairing problem with my Keyboard. Please help.

**Comment by cschramm** [comment]
Please check https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging and provide a log with that process.
