### ISSUE TITLE
Blueman removed from EPEL

### ISSUE THREAD

**Issue by rothgar** [blueman-project/blueman#786]
Distribution: CentOS 7

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

It appears blueman was removed from the EPEL 7 repositiory. What is the recommended way to install blueman on CentOS and RHEL distributions?

**Comment by cschramm** [comment]
Unfortunately https://apps.fedoraproject.org/packages/blueman/overview/ looks like you're right. It's not in EPEL. I cannot find a prove though that it's been removed and why.

Did you try just downloading and installing one of the Fedora RPM files?

**Comment by leigh123linux** [comment]
FTR EPEL repo never had blueman

https://koji.fedoraproject.org/koji/packageinfo?packageID=8707

I imported it but never built it

https://src.fedoraproject.org/cgit/rpms/blueman.git/log/?h=epel7

**Comment by cschramm** [comment]
Doesn't https://admin.fedoraproject.org/pkgdb/package/rpms/blueman/ say that it is / has been in "Fedora EPEL 7"? 🤔

**Comment by leigh123linux** [comment]
No, it's means I applied for a epel7 branch for git and koji

**Comment by cschramm** [comment]
I see. Thanks for clarifying.
