### ISSUE TITLE
Sony wireless keyboard, Model no. CECH-ZKB1GB cannot connect

### ISSUE THREAD

**Issue by a34fm** [blueman-project/blueman#787]
blueman: 1.23-git201403102151-1ubuntu1
BlueZ: 4.101-0ubuntu13.3
Distribution: Kernel 4.4.0-70-generic
Desktop environment: Linux Mint 17.3 Cinnamon 64-bit

My keyboard is recognized but failed to connect.

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

**Comment by cschramm** [comment]
Please provide the debug log from blueman-applet.

**Comment by a34fm** [comment]
Excuse me but I don't know where to find the debug lob.

**Comment by cschramm** [comment]
See the debugging section on the troubleshooting page you read earlier.
