### ISSUE TITLE
Bluetooth gets actived automatically upon system reboot

### ISSUE THREAD

**Issue by Titumeer** [blueman-project/blueman#794]
blueman: 2.0.4-1ubuntu3
BlueZ: 5.46-0ubuntu3
Distribution: Ubuntu 17.10(Xubuntu)
Desktop environment: Xfce

Here's the full log-
https://pastebin.com/fqTwpqWV
Steps to reproduce: Turn Bluetooth off through blueman-applet while system is turned on. Reboot the system. Bluetooth will be tuned on.

**Comment by cschramm** [comment]
Turning bluetooth off in blueman-applet should enable a software killswitch for bluetooth. Check `sudo rfkill list bluetooth`. It should show something like
```
0: tpacpi_bluetooth_sw: Bluetooth
	Soft blocked: yes
	Hard blocked: no
```
Disable the autostart of blueman-applet for your desktop environment. Then reboot and check if the killswitch is still blocked. If it's not, something else on your system is switching it. I'd first have a look in a terminal before logging in on the desktop, to see if it's related to the desktop session.
