### ISSUE TITLE
i want pairing without auth

### ISSUE THREAD

**Issue by gaiyamega** [blueman-project/blueman#795]
i tried to paring with my smartphone to OrangePi board. ubuntu 16.04

but authentication screen always showed up

i want.. i mean like bluetooth speaker. headless.. what should i do?

i don't want to see {authorize service (yes/no)}

please help

**Comment by cschramm** [comment]
Did you try marking the device as trusted?

**Comment by gaiyamega** [comment]
i mean, I do not want to have a trust screen when I use any device.

**Comment by cschramm** [comment]
You should not get one if you mark the device as trusted (you can do that in `blueman-manager` or also `bluetoothctl`) before connecting.
