### ISSUE TITLE
 Blueman (bluetooth) applet/tray icon is out of proportion

### ISSUE THREAD

**Issue by jebeld17** [blueman-project/blueman#796]
[Launchpad bug link](https://bugs.launchpad.net/ubuntu/+source/blueman/+bug/1734801)

The applet/tray icon for the "blueman-applet" appears out-of-proportion when no devices are currently connected and bluetooth is on.

Please see the screenshot attached.

ProblemType: Bug
DistroRelease: Ubuntu 17.10
Package: blueman 2.0.4-1ubuntu3
ProcVersionSignature: Ubuntu 4.13.0-17.20-lowlatency 4.13.8
Uname: Linux 4.13.0-17-lowlatency x86_64
ApportVersion: 2.20.7-0ubuntu3.5
Architecture: amd64
CurrentDesktop: ubuntu:GNOME
Date: Mon Nov 27 22:58:16 2017
ProcEnviron:
 TERM=xterm
 PATH=(custom, no user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/bin/bash
SourcePackage: blueman
UpgradeStatus: No upgrade log present (probably fresh install)
![screenshot from 2017-11-27 23-00-09](https://user-images.githubusercontent.com/9492083/33302027-53e37c0e-d3c7-11e7-8012-c417f4339bef.png)

**Comment by cschramm** [comment]
That's not blueman's icon. It's one of https://packages.ubuntu.com/search?searchon=contents&keywords=blueman-active&mode=filename&suite=artful&arch=any, most probably numix's icon. They recently fixed that, see https://github.com/numixproject/numix-icon-theme/issues/1235.
