### ISSUE TITLE
new 2.1 snapshot release?

### ISSUE THREAD

**Issue by petefwalter** [blueman-project/blueman#798]
Can you do a new 2.1 snapshot release, 2.1.alpha2 or so, please? The last 2.1 snapshot is quite old and broken and would be great to get a newer snapshot into Fedora.

**Comment by cschramm** [comment]
I just created milestone [2.1.alpha2](https://github.com/blueman-project/blueman/milestone/3) as I'd like to get some small fixes in. @infirit: Anything to add there?

**Comment by infirit** [comment]
Nothing to add. Pretty busy atm but I'll poke at that obex issue this weekend.

**Comment by infirit** [comment]
I updated the CHANGELOG just now with all the changes since alpha 1. Please check if I missed anything.

**Comment by cschramm** [comment]
And it's done. 🙂

**Comment by petefwalter** [comment]
Thanks!
