### ISSUE TITLE
wait_for_adapter broken?

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#802]
It checks for [!= "00:00:00:00:00:00"](https://github.com/blueman-project/blueman/blob/0dd077a9e926ba6f105693a75a95e83084c5f521/blueman/Functions.py#L101) is always true for me at least since BlueZ5. It may have been a leftover from BlueZ4

Does anyone else see "00:00:00:00:00:00" with Bluez5? If not I'll drop it as it then serves little purpose.

**Comment by cschramm** [comment]
Same here. Most probably a leftover, yes.

**Comment by infirit** [comment]
wait_for_adapters was removed, closing.
