### ISSUE TITLE
Bluetooth speaker (client) disconnected after reboot

### ISSUE THREAD

**Issue by hannesrapp** [blueman-project/blueman#803]
Hello,

After a system reboot, my bluetooth speaker is always disconnected. In blueman-manager devices menu, the speaker is all of the following: VISIBLE, PAIRED and TRUSTED.  In my startup apps, blueman-applet is included.

To connect a device after reboot, I just open device menu in blueman manager and follow the "setup" procedure which now starts at step 4 "Connect" phase. This works without any issues. I want to avoid having to follow this procedure every time I do a system reboot. If there's anything else that must be done for a persistent connection, please let me know. If theres a command line alternative to this procedure, that would be acceptable as a workaround (can include in startup).

Regards,
Hannes

+++

blueman: 2.0.4 Blueman-manager
BlueZ: 5.46
Distribution: Xubuntu 17.10
Desktop environment: XFCE4

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by cschramm** [comment]
A right click on the device should give you a "connect" entry you can use.

A CLI automation would be something like `echo 'connect YO:UR:DE:VI:CE:ID' | bluetoothctl`.

There is a ticket for an auto-connect feature in blueman but it's currently not in the pipeline: #239 (also see the discussion in https://github.com/blueman-project/blueman/issues/775#issuecomment-333956546).

**Comment by hannesrapp** [comment]
thx @cschramm
