### ISSUE TITLE
Manjaro bluetooth. I can't send audio files from my mobile to laptop but I can send documents

### ISSUE THREAD

**Issue by take5or1** [blueman-project/blueman#809]
I installed the xfce manjaro last verions.
I have problems with the bluetooth. I can send files but not audio from laptop to mobile 
any solution?

**Comment by cschramm** [comment]
https://github.com/blueman-project/blueman/wiki/Troubleshooting

**Comment by infirit** [comment]
Go to the link @cschramm provided and post the output of blueman applet run from a terminal. It will show if we actually see the transfer coming in or not and possibly errors.
