### ISSUE TITLE
bueman device list seldom doesnot open in raspbian

### ISSUE THREAD

**Issue by AYANDEY** [blueman-project/blueman#816]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

**Comment by E3V3A** [comment]
What do you mean and what did you do?
