### ISSUE TITLE
ubuntu 17 and altec lansingBT over ear

### ISSUE THREAD

**Issue by JazzMaster** [blueman-project/blueman#823]
device pairs -as a sink- better than before. but disconnects while BT still active. very annoying bug when playing audio- as it should- thru Juk. connects to ps3 but cant stay on long enough to be viably used for similar. I cant test further if a device FW failure or linux bug. device stays connected w ubuntu but gets removed from audio sources list when BT is still active. I touched no buttons on the headset. results in BT connection being dropped and headset going to standby.

**Comment by cschramm** [comment]
Right-click on the device and check the selected audio profile. Also provide the content of the info screen available from the same menu, please.
