### ISSUE TITLE
Bluetooth manager is not responsive

### ISSUE THREAD

**Issue by simJSatw** [blueman-project/blueman#839]
blueman:
BlueZ:
Distribution: Debian
Desktop environment: XFCE

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

When first installed bluez and blueman everything worked perfectly fine. Then I turned the computer off and when started it again everything stopped working. Manager opens up but i cannot click on anything. Every button is now greyed out. Bluetooth adapter app is not working properly either. It whows only 'close' sign and that's it. Sending a pic below. 
![bluetooth-proble](https://user-images.githubusercontent.com/28625611/36066032-ee672f22-0eab-11e8-85f8-2407cf052bb0.png)

**Comment by teja4477** [comment]
same problem in mint 18.2

**Comment by cschramm** [comment]
Please provide the output as described on the Troubleshooting page you read.
