### ISSUE TITLE
Receiving files is broken

### ISSUE THREAD

**Issue by cschramm** [blueman-project/blueman#84]
[Debian #757633](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757633)

Confirmed on my system; wasn't able to find a working version / combination. :worried:

**Comment by landroni** [comment]
Using bluez-4.101 and obex-data-server-0.4.6 and blueman-1.23-git201403102151, I too cannot receive files from an Android phone to a desktop Ubuntu 14.04. 

In `Local services` the Transfer Settings are disabled, and `obex-data-server` is reported as not available. 
![screenshot_2015-03-25_23-33-10](https://cloud.githubusercontent.com/assets/1318567/6836949/5bdd06ce-d347-11e4-902e-411817026f4d.png)

Is there a way to work around this issue? Has it been addressed in the latest alpha releases?

**Comment by cschramm** [comment]
Still open and the most important issue on the way to 2.0.

**Comment by landroni** [comment]
I've now tried alpha2 (using obexd-server as dep): 
https://launchpad.net/~landronimirc/+archive/ubuntu/staging

And funny thing. Receiving files works as expected (once enabled in Local Services). But I can no longer *send* files, getting this error message: 

> obexd not available
> obexd is probably not installed

The 1.99.alpha2 release notes mention: 

> obexd is required for sending files

With Ubuntu in mind, which package exactly do you mean? Is it still `obex-data-server`, or now `obexd-server` ?

**Comment by cschramm** [comment]
You need obexd-client >= 0.47 (unfortunately I think there is no such deb package) for BlueZ 4 or bluez-obexd for BlueZ 5.

**Comment by landroni** [comment]
Indeed so. Does this make blueman 2.0 incompatible with Ubuntu?

**Comment by cschramm** [comment]
1.99~alpha2-1 ([review version](http://mentors.debian.net/debian/pool/main/b/blueman/)) depends on `obexd-client (>= 0.47) | bluez-obexd` which is not satisfiable in current Ubuntu vivid. Anyway, it looks like BlueZ 5 and thus bluez-obexd will make it into the next release ([blueprint](https://blueprints.launchpad.net/ubuntu/+spec/desktop-v-bluez5), [bug](https://bugs.launchpad.net/ubuntu/+source/bluez/+bug/1162781)).

Concerning the topic: If you have any idea what made receiving files work for you, please let us know.

**Comment by landroni** [comment]
I very honestly don't know. It was working nicely, then I embarked on extensive testing (installing one package at a time---`obexd-server`, `obex-data-server`, `obexd-client`---and restarting Bluetooth and Blueman), and now receiving files doesn't work anymore. And I cannot find the sweet-spot where it was working, but it was certainly working...  I don't know what's going on.

Does Blueman leave any logs of any kind?

**Comment by cschramm** [comment]
> Does Blueman leave any logs of any kind?

Error output will normally be written to ~/.xsession-errors. Other than that, no.

> I managed to hack obexd-client 0.48 into a .deb, and installed on my system, and now Sending files works indeed with alpha2. But I had to tweak the packaging because of failing tests, so I'm not sure if it's a good idea to put it on a PPA...

There are also some versions available which have been in Debian jessie before the migration to BlueZ 5: http://snapshot.debian.org/package/obexd/.

**Comment by landroni** [comment]
Nothing interesting in `~/.xsession-errors`. Better logging would be useful here (say, a Log window like in Linphone), as even when receiving files is failing it's clear that the phone and the desktop are connecting successfully via Bluetooth (phone says "connected" and Blueman icon becomes all greenish) before the sending itself fails... 

Nice find for the packaging. I'll look into that.

**Comment by cschramm** [comment]
For debugging you can look at the stdout of blueman-applet, see the FAQ file / GitHub Wiki.

**Comment by cschramm** [comment]
The issue with BlueZ 5 discussed here is a problem with obex-data-server and BlueZ 5. It can be fixed by changing the configuration files of both of those components.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757633#81 for details.

**Comment by jod35fan** [comment]
Here is what i have done in Jessie to get latest sources of blueman, obex-data-server and bluez5 to receive file from a phone as normal user.
1. add --compat flag to bluetooth.service file in bluez5 sources and run configure --help to set systemd directories to /etc/systemd/system:
[Unit]
Description=Bluetooth service
Documentation=man:bluetoothd(8)
Requires=network.target

[Service]
Type=dbus
BusName=org.bluez
ExecStart=/usr/libexec/bluetooth/bluetoothd --compat
Restart=on-failure
RestartSec=5

#NotifyAccess=main
#WatchdogSec=10
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
LimitNPROC=1

[Install]
WantedBy=multi-user.target
Alias=dbus-org.bluez.service

2 edit sdpd-server.c to set more access rights to /var/run/sdp:
chmod(SDP_UNIX_PATH, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH);chmod(SDP_UNIX_PATH, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH);

3. run make install as root and then enable bluez:
systemctl daemon-reload
systemctl enable bluetooth.service
systemctl start bluetooth.service

4.Go to obex-data-server sources and cp obex-data-server.conf /etc/dbus-1/system.d/ after make install. You can also use existing packages but be sure to copy that file.

5. Now you can use the latest blueman. It does not save user settings an I need to pair after every reboot, any ideas how to fix this? Also obexd connection is not currently working, it might be same kind of a configuration file fixing.

**Comment by cschramm** [comment]
@jod35fan:

> It does not save user settings

What user settings?

> I need to pair after every reboot, any ideas how to fix this?

So after rebooting you do not see the device until you start a discovery?

> Also obexd connection is not currently working, it might be same kind of a configuration file fixing.

 So sending files is broken for you? Do you have bluez-obexd? The only issue I know concerning sending files is reported by @juanitotc in #218, but he has a weird system, so I doubt you're having the same problem. :wink:

**Comment by juanitotc** [comment]
I might have a "weird system" (does that mean not gnome?), but I compiled bluez-5.28 in a normal way and it did not install a dbus service file to start the obexd.

If you paste the contents of your obexd dbus service file I can create one to suit and test.

**Comment by cschramm** [comment]
By "weird system" I mean everything seems to be compiled by yourself, there are a lot of /usr/local paths, and some symlinking to squashfs targets. I don't mean that in any negative way, "weird system" just reads "the opposite of Linux Mint" here. :wink: 

Lets keep your obexd issue in #218 to not get lost completely.

**Comment by juanitotc** [comment]
Sorry, I was a little frustrated at trying and failing to get gnome-3.12.x or 3.14.x to work (and the debug output is no help at all).

I'll switch back to #218

**Comment by landroni** [comment]
Re https://github.com/blueman-project/blueman/issues/84#issuecomment-87270984 

"Concerning the topic: If you have any idea what made receiving files work for you, please let us know."

OK, right now receiving files from an Android device works. Is there anything in particular that could help you (logs, config files, etc.)? 

For reference, I'm using Bluez 4: 
bluez-4.101 and obex-data-server-0.4.6 and blueman-1.99~alpha2

**Comment by cschramm** [comment]
@landroni So it is working for you from time to time? As you are the only user reporting issues with receiving files with BlueZ 4, I don't want to dig deeper if you're happy. :wink: 

If it does not work we'll need the output from blueman-applet (see [FAQ file](https://github.com/blueman-project/blueman/blob/master/FAQ) / [GitHub Wiki](https://github.com/blueman-project/blueman/wiki/Troubleshooting)).

**Comment by landroni** [comment]
@cschramm After restart, it seems to be working without much trouble (there is an issue, but i'll report that separately). 

As for the Ubuntu packaging, I've got both obexd 0.48 and blueman alpha2 compiled on my PPA: 
https://launchpad.net/~landronimirc/+archive/ubuntu/staging

Would you like me to upload the builds at the official PPA?  
https://launchpad.net/~blueman

**Comment by cschramm** [comment]
There's an official alpha2 deb package which will make it to Debian unstable soon. There's also an official obexd-client 0.48 deb package in the Debian archive.

The blueman Launchpad project is abandoned and I do not even have access to the PPA, sorry.

**Comment by cschramm** [comment]
I'll close as the BlueZ5 issue is just about configuration (obex-data-server and BlueZ), so it's more a Debian than an upstream problem.

In any case, the obexd transition (#16) is ongoing and will fix this nevertheless.

**Comment by walmis** [comment]
@cschramm @landroni I have added you to the launchpad.net/~blueman team page.

**Comment by landroni** [comment]
@walmis Thanks. I've now uploaded alpha2 for Trusty and Utopic to the PPA: 
https://launchpad.net/~blueman/+archive/ubuntu/ppa
