### ISSUE TITLE
[SOLVED] Can't find any device using blueman (HP notebook)

### ISSUE THREAD

**Issue by jpantao** [blueman-project/blueman#855]
blueman: 2.0.4
BlueZ: 5
Distribution: Xubunto 17.10
Desktop environment: XFCE 4.12

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

I just bought a Bluetooth mouse and when i tried to connect it to my laptop i found that i can't find any device. At first I thought it was the mouse, then i tried to connect the mouse to a lenovo thinkpad x230 with the same exact distro and, in the lenovo, i can find and pair the mouse without any problem.
Can anyone help?
Thanks

**Comment by jpantao** [comment]
Already solved

**Comment by parkerlreed** [comment]
Please comment what solved it. It helps others who might have the same issue.

**Comment by jpantao** [comment]
After some research what solved my problem was:

I ran: lspci -knn | grep Net -A2 

the output was:
05:00.0 Network controller [0280]: Broadcom Limited BCM43142 802.11b/g/n [14e4:4365] (rev 01)
	Subsystem: Hewlett-Packard Company BCM43142 802.11b/g/n [103c:804a]
	Kernel driver in use: wl
Then I searched for BCM43142 and eventually got to: 
https://github.com/winterheart/broadcom-bt-firmware/tree/master/brcm

From there I just download the right file and since Im in Xubunto (thunar is the file manager in Xubunto) i ran: sudo thunar
then i went to /lib/firmware/brcm and moved the file i download to this directory and changed the name to BDC.hcd.

After this I was able to find all bluetooth devices without any problem.

I Hope this helps.

**Comment by dhuacon** [comment]
> After some research what solved my problem was:
> 
> I ran: lspci -knn | grep Net -A2
> 
> the output was:
> 05:00.0 Network controller [0280]: Broadcom Limited BCM43142 802.11b/g/n [14e4:4365] (rev 01)
> Subsystem: Hewlett-Packard Company BCM43142 802.11b/g/n [103c:804a]
> Kernel driver in use: wl
> Then I searched for BCM43142 and eventually got to:
> https://github.com/winterheart/broadcom-bt-firmware/tree/master/brcm
> 
> From there I just download the right file and since Im in Xubunto (thunar is the file manager in Xubunto) I ran: sudo thunar
> then i went to /lib/firmware/brcm and moved the file i download to this directory and changed the name to BCM.hcd
> 
> After this I was able to find all bluetooth devices without any problem.
> 
> I Hope this helps.

Run:
lsusb | grep -i bluetooth
So you know the model of your bluetooth device.
