### ISSUE TITLE
Blueman does not connect to Bluetooth service

### ISSUE THREAD

**Issue by finanalyst** [blueman-project/blueman#857]
blueman: 2.0.4
BlueZ: 5.45
Distribution: Pop! OS ( Ubuntu 17.10 )
Desktop environment: Gnome

* [x ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

I am trying to connect a bluetooth optical mouse (qualcom chipset). Connection works after cold reboot. But Bluetooth is unaccessible after suspend/resume.

After cold reboot, Bluetooth is available and blueman-manager acts as expected and shows all devices.  
After suspend and resume, blueman-manager either (a) generates a window with no bluetooth, or (b) generates a new window asking for Bluetooth to be enabled. After clicking on 'Enable Bluetooth' button, 1) blueman-manager freezes completely, or 2) returns to a screen with no devices.

In looking for a way to turn on Bluetooth after suspend/resume, Google indicates that the Blueman utility handles reconnection. That is why I have been trying blueman-manager.

Failure to find a running Bluetooth service (see below) by Blueman and freezing after clicking on a provided button seems odd.

The problem seems to be in Bluez not Blueman, but Blueman could provide diagnostics. See for example the end of the terminal output of blueman-manager --loglevel debug in Paste (link below). The output indicates BlueZ 5 is connected, but there is no adapter. This response could be provided by blueman. 

Output from various utitlities given in https://pastebin.com/ETZTNnHB , and a screenshot showing the blank Blueman screen over a terminal screen that shows systemctl status bluetooth indicates that Bluetooth is running.

I tried to use blueman-report , but found that the time for performing the action was too short to be useful. There is no documentation I could find about how to use this tool. blueman-report --help provides no information.

It would be helpful if someone could provide a link to a way to restart bluetoothd so that after a resume I could manually get bluetooth working again.

I have been looking for a solution to this problem for several days. I am wondering what to do next.

**Comment by BraveLilToaster** [comment]
I am also experiencing the same issue with blueman after suspend. It works fine after I shutdown my machine and start it up again.
