### ISSUE TITLE
Suggest to use HTML details element rather than external services like pastebin or gist

### ISSUE THREAD

**Issue by krichter722** [blueman-project/blueman#871]
blueman: ---
BlueZ: ---
Distribution: ---
Desktop environment: ---

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

The [HTML details element](https://www.w3schools.com/tags/tag_details.asp) solves the problem of unreadable reports well and has the advantage over pastebin or gist to keep the information at one place without the risk of expiration or unavailability of the service.

**Comment by infirit** [comment]
Markdown and github do not support it so we'll have to do with gist or a pastebin. People can these days attach a text file so we could add that as a suggestion but besides that we can't use it.

It is a good suggestion so perhaps you can raise this with the github folks as a feature request.
