### ISSUE TITLE
My raspberrypi3 has established bluetooth connection to my iphone6s, however I am unable to play any music on my mobile.HDMI connection between TV and Raspberrypi is working well barring music on mobile. Please help

### ISSUE THREAD

**Issue by rameshsabnis** [blueman-project/blueman#885]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

**Comment by cschramm** [comment]
Please check the troubleshooting page and provide a log to see what's going on.

**Comment by infirit** [comment]
Closing, when details are provided we can reopen.
