### ISSUE TITLE
no adapter found

### ISSUE THREAD

**Issue by KambhaktIshQ** [blueman-project/blueman#888]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

**Comment by KambhaktIshQ** [comment]
![screenshot from 2018-06-17 13-10-01](https://user-images.githubusercontent.com/37856911/41505881-d561750e-722f-11e8-8be3-ace627b54409.png)

**Comment by cschramm** [comment]
Check https://github.com/blueman-project/blueman/wiki/Troubleshooting#reporting-a-bug--asking-for-support and https://github.com/blueman-project/blueman/wiki/Troubleshooting#no-adapter-or-not-able-to-turn-on-bluetooth.

**Comment by Taariqq** [comment]
Same issue here. "no device connected" Even though when I plug the device into usb my bluetooth status goes to "on".

**Comment by infirit** [comment]
@Taariqq, see the links @cschramm posted.

And I don't understand what you mean with ```Even though when I plug the device into usb my bluetooth status goes to "on".```.
