### ISSUE TITLE
Pairing Passphrase Prompt Broken

### ISSUE THREAD

**Issue by Teknocrat** [blueman-project/blueman#89]
When I attempt to pair my phone with my laptop the prompt for passphrase matching never appears..

```
(blueman-manager:29175): GLib-GIO-CRITICAL **: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/main/PluginManager.py", line 206, in Run
    ret = getattr(inst, function)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/blueman/plugins/manager/Services.py", line 39, in on_request_menu_items
    manager_menu.Signals.Handle("bluez", device, manager_menu.service_property_changed, "PropertyChanged")
  File "/usr/lib64/python2.7/site-packages/blueman/main/SignalTracker.py", line 36, in Handle
    obj.handle_signal(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBlueZInterface.py", line 57, in handle_signal
    self._handle_signal(wrapper, 'PropertiesChanged', interface, self.get_object_path(), **kwargs)
  File "/usr/lib64/python2.7/site-packages/blueman/bluez/PropertiesBlueZInterface.py", line 33, in _handle_signal
    self.get_bus().add_signal_receiver(handler, signal, interface, 'org.bluez', obj_path, **kwargs)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 157, in add_signal_receiver
    watch = self.watch_name_owner(bus_name, callback)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 373, in watch_name_owner
    return NameOwnerWatch(self, bus_name, callback)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 80, in __init__
    arg0=bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 160, in add_signal_receiver
    self.add_match_string(str(match))
```

**Comment by cschramm** [comment]
I think the relevant data we have is this:

````
RequestConfirmation (/usr/lib64/python2.7/site-packages/blueman/main/applet/BluezAgent.py:185)
Agent.RequestConfirmation 
org.bluez.Error.AuthenticationFailed: Authentication Failed
````

I guess it takes some time before the last line appears as it's probably triggered by some timeout, right?

What notification daemon are you using?

Please open a python shell and type

````
from blueman.gui.Notification import Notification
Notification("Bluetooth", "Message", actions=[["test", "Test"]])
````

to see what happens.

**Comment by shiznix** [comment]
Hi, having the same issue here.
I use notify-osd notification daemon as used by Ubuntu and blueman fails to display a notification for pairing passphrase prompt.
For testing I uninstalled notify-osd and installed notification-daemon.
This resulted in a pairing passphrase prompt but as soon as my mouse cursor touches the notification bubble it disappears with the following error in terminal:
(blueman-applet): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

The only way the passphrase prompt notification will work is if I'm in a Gnome session (gnome-shell has it's own notification daemon built-in).

Would it be possible to have the passphrase prompt be just a standard window ?
In this way you won't have to maintain support for all the different notification daemons and each of their quirks.

**Comment by cschramm** [comment]
We have a fallback and since notify-osd reports not to support actions (although it has a similar fallback built in to actually support actions) that fallback is used. Unfortunately our fallback is broken. :grin: 

@infirit @stefano-k I need a little help with GTK / instrospection here. We need to fix `blueman.gui.Notification.NotificationDialog("Title", "Message")`. The first issue is just a missing `from gi.repository import GObject`, but then I get an error regarding the flags property. I found it [in the documentation](https://developer.gnome.org/gtk3/stable/GtkMessageDialog.html#gtk-message-dialog-new), but obviously our usage through introspection is wrong.

**Comment by infirit** [comment]
Try replacing ``GObject.GObject.__init__`` with ``Gtk.MessageDialog.__init__``

**Comment by cschramm** [comment]
Works. :smiley: 

Fixed that.

If your issue is different, @Teknocrat, just re-open.

**Comment by shiznix** [comment]
Works great! Thanks for the fix :)
