### ISSUE TITLE
I can't connect to my android phone with my acer notebook ubuntu installed

### ISSUE THREAD

**Issue by masud78** [blueman-project/blueman#892]
blueman:
BlueZ:
Distribution:
Desktop environment:

*ACER aspire E5-471
UBUNTU 18.04 LTS INSTALLED.
i can't connect to my phone.both my phone and notebook have built-in bluetooth radio.

**Comment by infirit** [comment]
Check https://github.com/blueman-project/blueman/wiki/Troubleshooting#reporting-a-bug--asking-for-support and https://github.com/blueman-project/blueman/wiki/Troubleshooting#no-adapter-or-not-able-to-turn-on-bluetooth.

**Comment by infirit** [comment]
Closing, if you still have problems please read above links and provide more info.
