### ISSUE TITLE
ConnMan integration

### ISSUE THREAD

**Issue by progandy** [blueman-project/blueman#90]
The Killswitch plugin does not work nicely with connman. I think a proper implementation would be a new alternative plugin that uses the connman api to enable/disable bluetooth instead of using rfkill directly.
net.connman.Manager -> call GetTechnologies()
net.connman.Technology -> get/set Powered property
net.connman.Technology -> watch PropertyChanged signal

**Comment by infirit** [comment]
After some patching to have connman not crash with iptables 1.6 I have connman running on gentoo. I'll probably most likely will have a go adding this in the coming weeks or so.

**Comment by infirit** [comment]
Here is a patch that works for me when using connman, https://github.com/infirit/blueman/commit/153d233892c74c4aab80d602ca6722de956525f2

I have not tested it when connman is not running but I'll have that done before merging to master.

@progandy, can you try it out?

**Comment by infirit** [comment]
Ignore the previous message please (deleted).

**Comment by infirit** [comment]
I have something working on gentoo with #689 against master, please test. Connman is a bit unstable for me here so I am very interested in feedback how it works for others.
