### ISSUE TITLE
Failed to apply network settings - Dbus

### ISSUE THREAD

**Issue by mrpewpew** [blueman-project/blueman#913]
blueman: 2.0.6
BlueZ: 5.50-3
Distribution: Arch Linux
Desktop environment: no DE, just using i3wm

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

After updating linux kernel to 4.18 and rebooting, a window appeared with the message : 
`Failed to apply network settings - You might not be able to connect to the Bluetooth network via this machine`

The exception is : 
`org.freedesktop.Dbus.Python.dbus.exceptions.DbusException: Not authorized`

Any idea how to fix it ?

**Comment by infirit** [comment]
See #912

**Comment by mrpewpew** [comment]
Yes thank you, it worked !

**Comment by JayeHorn** [comment]
> Yes thank you, it worked !

How did you get this to work?
