### ISSUE TITLE
create directory

### ISSUE THREAD

**Issue by Hinnawy** [blueman-project/blueman#914]
blueman:
BlueZ:
Distribution: UBUNTU 18.04
Desktop environment:Lenovo-Z50-70

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow

I lost the directory for receiving downloads. Trying to configure it using blueman-services I  do not know how to complete the  task. I was only prompted to use blueman services by a message repeatedly appears every time I start the computer.

**Comment by infirit** [comment]
Not sure what you tried but you can run ``blueman-services`` from a terminal. Or you can open ``blueman-manager`` and go to the ``view`` menu. The last option is click on the blueman status icon.

It should open the below window and on the Transfer tab you can configure it.

![image](https://user-images.githubusercontent.com/3465730/44628652-42e56400-a944-11e8-941b-a0e470501104.png)

**Comment by Hinnawy** [comment]
This is what I discovered and have already done. Thank you.
