### ISSUE TITLE
My blueman does not want to connect to my headset  in audio only in service I get sound only when I connect please help?

### ISSUE THREAD

**Issue by Midget0020** [blueman-project/blueman#917]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
There is not enough information to even start. See https://github.com/blueman-project/blueman/wiki/Troubleshooting for some guidance on asking for help and some suggestions to resolve some common problems.
