### ISSUE TITLE
Authentication promts at Gnome-manjaro version for standard users

### ISSUE THREAD

**Issue by UbuntuTarnow** [blueman-project/blueman#919]
blueman:
BlueZ:
Distribution:Manjaro 17 latest version
Desktop environment:Gnome

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.  Problem solved but should not be like this after install
I have installed newest version of Manajro-Gnome on two computers and after creating standard accounts, when I log into standard accounts it ask for authentication required for blueman twice.  This happens every single time a standard user logins into account.  It asks for admin password.  This is by default from fresh install.  Had to go and add the new standard users to group wheel to get rid of the prompt at startup.  To me this s a bug creating a new standard account should put the user into the wheel account or blueman should be modified so it does not do that on standard account the way it is.  A standard account user should just login like normally with no prompts for admin password.  This only has started happeing after updates a while back.
<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
See #912
