### ISSUE TITLE
Xbox One Wireless Controller Not Connecting/Looping.

### ISSUE THREAD

**Issue by Hilol1000** [blueman-project/blueman#920]
blueman: 2.05-1ubuntu1
BlueZ: 5.48-0ubuntu3.1
Distribution: Ubuntu Mate 18.04.1 LTS
Desktop environment: MATE

My controller is looping connecting and disconnecting.

How to reproduce the bug.
1. Go into the devices menu.
2. Turn on the Xbox One controller and enter pairing mode.
3. Search for devices.
4. Pair with controller.
5. Exit pairing mode on the controller
6. It loops connecting and disconnecting. 

'blueman-applet --loglevel debug' gave me this.
https://gist.github.com/Hilol1000/a54ba0c17b4e208688280e4b43f12f2c

'bluetoothctl list' Tells me that it is looping connecting and disconnecting.
https://gist.github.com/Hilol1000/9178c90b9e740b36059eb36a629c0183

**Comment by infirit** [comment]
Is the device trusted? If not try trusting it.

What happens if you remove the device and then use ``bluetoothctl`` to pair, trust and connect?

There is likely not much we can do here. Looking on the internets it seems the xbox one controller is supported in the kernel but does not  work well for everyone. There is also https://xboxdrv.gitlab.io/ which looks like a nice alternative.

**Comment by Hilol1000** [comment]
I have tried trusting the device in Blueman however i still get the same error.

Using bluetoothctl to pair, trust and connect gave me the same looping connecting and disconnecting issue.
https://gist.github.com/Hilol1000/2522eb669af279da13ed1e4f9aca9294

Even with the xboxdrv driver installed it is still looping connecting and disconnecting.

I think my xbox controller is working fine because when i connect it to my samsung S8 it works fine.

Thanks for trying to help me.

**Comment by cschramm** [comment]
You have to look for the issue in `bluetoothd`, i.e. check the syslog for any information about the connection failure and if that's not enough restart `bluetoothd` with the `-d` switch.
