### ISSUE TITLE
blueman-applet does not show icon tray when launched on startup.

### ISSUE THREAD

**Issue by rprs** [blueman-project/blueman#924]
blueman: 2.0.4
BlueZ: 5.3.7
Distribution: Ubuntu 16.04.5 LTS
Desktop environment: i3

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Using i3, blueman-applet does not show an icon on the system tray when launched on startup. Disabling blueman-applet from launch on startup and launching it manually (from terminal) makes icon tray show up. My guess is there is something about launching it on startup that messes things up.

Repro steps:
- modify ~/.i3/config to add the following line:
  `exec --no-startup-id blueman-applet # Bluetooth Manager`
- reboot computer.

Expected:
- blueman-applet icon on system tray.

Actual:
- blueman-applet not on system tray.
- running `blueman-applet` on terminal gives this output:
  `There is an instance already running`

Other things I tried:
Try to run blueman-applet after no icon was on tray (blueman-applet was set to run on startup).
- `blueman-applet`
- `killall blueman-applet`
- `blueman-applet`
output: https://pastebin.com/VYcD9MF6
Icon tray did show up on second `blueman-applet` command.

Disable blueman-applet from launch on startup, then run it manually.
- `blueman-applet`
output same as normal (third command in https://pastebin.com/VYcD9MF6)
Icon tray did show up.

Try running with --loglevel_debug when launch on startup
- modify ~/.i3/config to add the following line:
  `exec --no-startup-id blueman-applet --loglevel debug > ~/.blueman-output`
- reboot computer.
Same behavior and output as before.

**Comment by cschramm** [comment]
I just tried with blueman versions 2.0.6, 2.1.alpha2 and a recent snapshot with and without the AppIndicator plugin enabled and it worked fine for every configuration. Note that the `exec` line is the only enty in my config file though. Maybe you have some issue in conjuction with other configuration?
