### ISSUE TITLE
Bluetooth cannot detect any device

### ISSUE THREAD

**Issue by jouva6** [blueman-project/blueman#928]
blueman:
BlueZ:
Distribution:
Desktop environment: ubuntu 18

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
See https://github.com/blueman-project/blueman/wiki/Troubleshooting on how to ask for help.

**Comment by rohitspatil** [comment]
my device uses Ubuntu 16.04 lte .Bluetooth of this device does not show any other device on search bar.this device also does not found any other device.my  Bluetooth version  blueman-applet version 2.0.4
