### ISSUE TITLE
feature request: only connect to one audio profile

### ISSUE THREAD

**Issue by treakiandroid** [blueman-project/blueman#931]
i have successfully connected my Bluetooth loudspeaker system using blueman-manager. After installing the required modules and restarting pulse audio it was working ;)
but it is now connected to three profiles:

Headset
Handsfree
Audio sink

but i only need the last one, all others i really dont need. The problem i have is that sometimes the audio brakes apart do to bad connection quality which is quite annoying while enjoining your favorite music. 

So could you add a way to disconnect from all unneeded services but only use the one you need to limit the required bandwidth?

thanks a lot in advance and keep up the good work

**Comment by infirit** [comment]
Closing, we can't control this.
