### ISSUE TITLE
Recognize the audio headset Taotronics TT-BH22

### ISSUE THREAD

**Issue by stephane-couget** [blueman-project/blueman#933]
blueman: 2.0.4-1ubuntu2
BlueZ:
Distribution: linuxMint19
Desktop environment: MATE

I would want to make recognize the bluetooth audio headset Taotronics TT-BH22, you have an idea?

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
What's the problem?
