### ISSUE TITLE
Sony SRS-XB30 Bluetooth Speaker Won't Pair And Connect With Blueman Manager

### ISSUE THREAD

**Issue by DavidASmith072** [blueman-project/blueman#937]
I have a problem connecting my Sony SRS-XB30 Bluetooth Speaker using Blueman Bluetooth Manager in OpenSUSE Leap 42.3 on my desktop computer. About a week ago it would connect fine without a problem. However, since then there was a few software updates through SUSE on-line and Bluedevil5 was replaced with Blueman Manager and it had problems re-pairing with the SRS-XB30 bluetooth speaker. The following is my basic information:

blueman: Version 2.0.6-2.3.1
BlueZ: Version 5.41-6.1
Distribution: OpenSUSE Leap 42.3 64bit
Desktop environment: Plasma KDE Version 5.8.7-2.1

At first the problem was pairing the SRS-XB30 with the Blueman Manager because the SRS-XB30 expected to be paired with a PIN value of 0000, which the Blueman Manager never prompted for a PIN value directly on the Desktop screen but through the Plasma KDE Notifications. By the time I clicked on Notifications and then clicked on Enter Authority and the PIN prompt window finally appears the time has expired for me to enter the 0000 PIN value. However, when I finally got PIN value entered and the SRS-XB30 device paired with the bluetoothctl text command, there is still another problem with getting the SRS-XB30 device connected. The following indicates the problem:

```
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]# pair B8:D5:0B:25:AA:4C
Attempting to pair with B8:D5:0B:25:AA:4C
[CHG] Device B8:D5:0B:25:AA:4C Paired: yes
Pairing successful
[CHG] Device B8:D5:0B:25:AA:4C Connected: yes
[CHG] Device B8:D5:0B:25:AA:4C Connected: no
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]# list-attributes B8:D5:0B:25:AA:4C
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]# info B8:D5:0B:25:AA:4C
Device B8:D5:0B:25:AA:4C
        Name: SRS-XB30
        Alias: SRS-XB30
        Class: 0x240414
        Icon: audio-card
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: yes
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]# connect B8:D5:0B:25:AA:4C
Attempting to connect to B8:D5:0B:25:AA:4C
[CHG] Device B8:D5:0B:25:AA:4C Connected: yes
[CHG] Device B8:D5:0B:25:AA:4C Modalias: bluetooth:v0039p1582d2203
[CHG] Device B8:D5:0B:25:AA:4C UUIDs: 00000000-deca-fade-deca-deafdecacaff
[CHG] Device B8:D5:0B:25:AA:4C UUIDs: 00001108-0000-1000-8000-00805f9b34fb
[CHG] Device B8:D5:0B:25:AA:4C UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device B8:D5:0B:25:AA:4C UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device B8:D5:0B:25:AA:4C UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device B8:D5:0B:25:AA:4C UUIDs: 0000111e-0000-1000-8000-00805f9b34fb
[CHG] Device B8:D5:0B:25:AA:4C UUIDs: 00001200-0000-1000-8000-00805f9b34fb
Failed to connect: org.bluez.Error.Failed
[CHG] Device B8:D5:0B:25:AA:4C Connected: no
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]# connect B8:D5:0B:25:AA:4C
Attempting to connect to B8:D5:0B:25:AA:4C
Failed to connect: org.bluez.Error.Failed
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]#
```

However, when I go back using the Blueman Manager GUI, I now see the following:

![blueman-manager-6 0 2-srs-xb30-04](https://user-images.githubusercontent.com/923798/47624082-acbded80-daee-11e8-8542-8f2de2354b80.png)

When I click on the "More" button, the following information is shown:

![blueman-manager-6 0 2-srs-xb30-05](https://user-images.githubusercontent.com/923798/47624103-e55dc700-daee-11e8-8c0e-87bb6cdfc6f3.png)

From what I understand from this error message displayed, it looks like the DBus support for the blueman.bluez Bluetooth Stack is missing the protocol for the Sony SRS-XB30 loudspeaker device, which is odd because the SRS-XB30 device was working fine prior to the OpenSUSE Leap 42.3 update on-line from SUSE. Can anyone correct this problem with the DBus data base?

Thank you,

David A. Smith

**Comment by DavidASmith072** [comment]
The following is additional screen snapshots of the results from the Plasma KDE bluetooth manager:

![blueman-manager-6 0 2-srs-xb30-01](https://user-images.githubusercontent.com/923798/47624581-8ac76980-daf4-11e8-91e2-1572e84d5fa5.png)
![blueman-manager-6 0 2-srs-xb30-02](https://user-images.githubusercontent.com/923798/47624600-a2065700-daf4-11e8-8cd2-57a1fe6ab56f.png)
![blueman-manager-6 0 2-srs-xb30-03](https://user-images.githubusercontent.com/923798/47624613-ba767180-daf4-11e8-91e6-c639b99f3ebe.png)
![blueman-manager-6 0 2-srs-xb30-04](https://user-images.githubusercontent.com/923798/47624621-d0843200-daf4-11e8-978e-d5498ee090c3.png)
![blueman-manager-6 0 2-srs-xb30-05](https://user-images.githubusercontent.com/923798/47624630-e7c31f80-daf4-11e8-84d9-c42bc24d2df7.png)

David A. Smith

**Comment by cschramm** [comment]
Hi David, the error seems like you're missing [pulseaudio-module-bluetooth](https://software.opensuse.org/package/pulseaudio-module-bluetooth).

**Comment by DavidASmith072** [comment]
I just installed the pulseaudio-module-bluetooth for OpenSUSE Leap 42.3 and repaired the SRS-XB30 device but it didn't fix the connection failure of the SRS-XB30 device with the Blueman Manager. The following screen snap shots is  what happens:

![blueman-manager-6 0 2-srs-xb30-06](https://user-images.githubusercontent.com/923798/47688464-c6793680-dbbb-11e8-9c2e-4496607fe9ca.png)

When I initiate the pairing of the SRS-XB30 device, I click on the + button in the Blueman Manager window, which brings up the bluetooth device scanning window and the SRS-XB30 device is detected. Then I click on the SRS-XB30 device icon and then click on the Manual PIN option and  enter 0000 for the pin  number and then click on Next, which does pair the device.

![blueman-manager-6 0 2-srs-xb30-08](https://user-images.githubusercontent.com/923798/47690998-c6326880-dbc6-11e8-8724-98abc36f04fb.png)

However, for some reason the rest of the setup process for the SRS-XB30 device fails but the device is added to the bluetooth device list of the Blueman Manager with the SRS-XB30 paired. When I click on Restart the wizard, the SRS-XB30 device is no longer found in the bluetooth scanning because it has been already paired. If I click on Close, the following appears:

![blueman-manager-6 0 2-srs-xb30-09](https://user-images.githubusercontent.com/923798/47691361-2544ad00-dbc8-11e8-9cc2-ba8ba48f8cec.png)

If I click on the SRS-XB30 device icon in the bluetooth device list, it displays the current status of the SRS-XB30 device as being Trusted and not Blocked. However, if I click on Connect, a notification message appears, saying; "The SRS-XB30 bluetooth device has failed to connect."

If I run the bluetoothctl text-based utility and do the following:

```
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]# paired-devices
Device 90:7F:61:11:47:52 ThinkPad Compact Bluetooth Keyboard with TrackPoint
Device B8:D5:0B:25:AA:4C SRS-XB30
[CHG] Device B8:D5:0B:25:AA:4C Connected: yes
[CHG] Device B8:D5:0B:25:AA:4C Connected: no
[CHG] Device B8:D5:0B:25:AA:4C Connected: yes
[CHG] Device B8:D5:0B:25:AA:4C Connected: no
[CHG] Device B8:D5:0B:25:AA:4C Connected: yes
[CHG] Device B8:D5:0B:25:AA:4C Connected: no
[CHG] Device B8:D5:0B:25:AA:4C Connected: yes
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]# info B8:D5:0B:25:AA:4C
Device B8:D5:0B:25:AA:4C
        Name: SRS-XB30
        Alias: SRS-XB30
        Class: 0x240414
        Icon: audio-card
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: yes
        LegacyPairing: no
        UUID: Vendor specific           (00000000-deca-fade-deca-deafdecacaff)
        UUID: Headset                   (00001108-0000-1000-8000-00805f9b34fb)
        UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
        UUID: Handsfree                 (0000111e-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        Modalias: bluetooth:v0039p1582d2203
[CHG] Device B8:D5:0B:25:AA:4C Connected: no
[CHG] Device B8:D5:0B:25:AA:4C Connected: yes
[CHG] Device B8:D5:0B:25:AA:4C Connected: no
[ThinkPad Compact Bluetooth Keyboard with TrackPoint]#
```
This is puzzling to what's wrong. However, the pulseaudio-module-bluetooth version that I installed is version 9.0-8.1 and the reason why I asked this is because the link you gave me in your previous comment took me to the download.opensuse.org web site where a direct install link is and it has a path repository error, because when I installed it, the following warning message appeared:

`"An error occurred during repository initialization. [http-download.opensuse.org-ba4934ed|http://download.opensuse.org/ports/update/leap/42.3/] Valid metadata not found at specified URL History: - [http-download.opensuse.org-ba4934ed|http://download.opensuse.org/ports/update/leap/42.3/] Repository type can't be determined."`

I am not sure if this repository is correct for the current port updates because it wasn't directed to the OSS directory path, therefor it didn't work at first until I corrected it at my end. I would assume what I did was correct otherwise the repository for installing the pulseaudio-module-bluetooth wouldn't been able to be installed?

Thank you,

David A. Smith

**Comment by cschramm** [comment]
Hi David, the screenshots you posted do not seem to show blueman.

So you installed `pulseaudio-module-bluetooth`. Do you still get the `Protocol not available` message in blueman or what's the current situation?

**Comment by DavidASmith072** [comment]
After all this, I finally had to reinstall the whole bluetooth software system from the OpenSUSE Leap 42.3 packman repository and then it finally found the Protocol and connected with the Sony SRS-XB30 Bluetooth Speaker. Some file must had gotten corrupted but it's working reliably now.

Thank you all for your help in troubleshooting this bluetooth, "Protocol not available" issue.

David A. Smith

**Comment by DavidASmith072** [comment]
Blueman "Protocol not available" issue solved!

David A. Smith
