### ISSUE TITLE
problem in Ubuntu 

### ISSUE THREAD

**Issue by rohitspatil** [blueman-project/blueman#938]
blueman:
BlueZ:
Distribution:
Desktop environment:

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

my device uses Ubuntu 16.04 lte .Bluetooth of this device does not show any other device on search bar.this device also does not found any other device.my  Bluetooth version  blueman-applet version 2.0.4

**Comment by cschramm** [comment]
Please see the troubleshooting page.
