### ISSUE TITLE
Installing on Solus, Cairo is not required to install

### ISSUE THREAD

**Issue by armandg** [blueman-project/blueman#942]
blueman: 2.0.6
BlueZ:
Distribution: Linux Solus 4.19.2-99.current #1 SMP PREEMPT Tue Nov 20 16:47:35 UTC 2018 x86_64 GNU/Linux
Desktop environment: i3 version 4.15.0.1 (03-13-2018)

Just a heads up that when running blueman after installing it I got an ImportError saying that my Python  2.7 couldn't find cairo. Fixed by installing the cairo package from eopkg in Solus.

I'm not sure if this is a blueman-area or the distro's area, so giving it a shot here first. Let me know if I should pass this on to Solus developers instead.

**Comment by infirit** [comment]
It is in the distribution realm, please file a report with the solus folks. (py)Cairo is a runtime dep so we do not check for it at build time. We do have it listed in the dependencies list on [1]. Closing but feel free to comment further if more info/help is required :smiley: 

[1] https://github.com/blueman-project/blueman/blob/master/Dependencies.md
