### ISSUE TITLE
Local service share network connection leads to dnsmasq / dhpcd failed to start

### ISSUE THREAD

**Issue by Dantali0n** [blueman-project/blueman#943]
blueman: 2.0.6
BlueZ: 5.50
Distribution: Manjaro 18
Desktop environment: xfce 4.12

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

```
Nov 27 10:10:40 XXX dnsmasq[3664]: FAILED to start up
Nov 27 10:10:40 XXX dnsmasq[3664]: failed to create listening socket for 127.0.0.1: Address already in use
Nov 27 10:10:40 XXX org.blueman.Mechanism[702]: dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use
Nov 27 10:10:40 XXX blueman-mechanism[1717]: Return code 0
```

Because a running instance of dnsmasq is already bound to 127.0.0.1:53 the share network service fails to start dnsmasq / dhcpd as it to wants to bind to 127.0.0.1:53. Since the share network service allows to specify the address range that it is going to use I think it is possible to pass this on to dnsmasq / dhpcd. This would prevent the service from having to bind localhost and it could then instead only bind the network range it needs to listen to, for instance 10.42.0.1:53. 

Being able to run a local dnscache alongside sharing my network connection over bluetooth would be a great feature for me.

**Comment by infirit** [comment]
I don't like the idea of interfering with other system services like that. It may be an idea to have an option "Advanced, I know what I'm doing and will promise to keep both bits if it breaks" and have the user configure it themselves.

**Comment by Dantali0n** [comment]
In my opinion the current implementation is already interfering with system services as enabling the share network connection option in local services will launch an instance of dnsmasq or dhcpd.

I would consider launching such a service to share the network connection as a necessary evil as it would probably be quite impractical to implement dns & dhcp in bluemon without such a third-party service.

**Comment by cschramm** [comment]
We don't need the DNS service, do we? So adding `--port 0`, which turns it off, should avoid the error and give all choices to the user.

You says it'd be the same for `dhcpd` but as far as I know there's no DNS server included there, so it should not try to bind to 53. :thinking:

**Comment by infirit** [comment]
@Dantali0n, What I mean is that I don't like interfering with dnsmasq started by the user or networkmanager. This will cause problems for which I don't want to be responsible.

@cschramm I rather see networkmanager manage this which it can but requires pretty large refactor. I have a issue open for this #866.

**Comment by infirit** [comment]
@Dantali0n 10.174.71.0 is not a valid ipv4 so it failed, dnsmasq appears to accept this but dhcpd not (anymore?).  To be sure, do you get this with blueman 2.0 or 2.1 (master)?

**Comment by infirit** [comment]
Dug into the error some more. It appears dhcpd looks for an ip in the range and then starts the server. If for some reason the bridge pan1 is not yet ready it will fail with the above. If dhcpd is started before the bridge is even created then that explains the error. Otherwise it may be a timing issue..

I put a commit to disable dns in dnsmasq for the time being. It works for me but let us know if this fixes the original reported problem. commit https://github.com/blueman-project/blueman/pull/954/commits/58adc4198a153120135556a434ea0f56d7e28f9e

**Comment by Dantali0n** [comment]
Thanks, that works the service now starts and my bluetooth connected devices get dhcp leases. Though, I can not send packets to other networks & because of that can't contact a dns server. Seems something goes wrong with bridging the network adapters. Of course this is a different issue but I still wanted to address this to create awareness.

I would consider this issue resolved.
