### ISSUE TITLE
blueman connects to audio service after network manager fails to connect to PAN

### ISSUE THREAD

**Issue by treaki** [blueman-project/blueman#946]
for the version see my previews issue #945

i have done some more with bluetooth and blueman today, i have set up network manager to connect to my phones internet connecting using my thinkpad not using wifi but bluetooth, wich is much better for battery usage and (i think but are not 100% sure, is there a bluetooth scanner that can dig up invisible devices?) privacy concerns...

the only problem is that my phones os refuses the connection from my thinkpad after any reboot, and gives some anoying popup. Because its operating system is for noobs (it -dummies in german) there is no rotten way to whitelist my thinkpad on my phone. so every time taking my phone out of the pocket can be a bit anoying. But even worse is, ant thats where debian and blueman come in, is that if network manager fails to connect to the internet using bluetoth, bluez, without i have told it at any time and without any way of stopping it from doing so, connects to my phone using an audio profile...

in this situation i am not able to create another connection to the same device using network manager on debian, so i have to (after i, after long time i was saerching for the root of this disturbence, and found out what cousing it) manually open the bluez manager and disconnect from my pone to be able to connect to the shared internet. ok, i dont reboot my phone any day, but it can get still a bit anoying.

 So please fix this issue so noone runes into this situation again and blames linux in general for it (which happens unfortunattely much to often)

the best way to work arund this in my opinion would be to increase the granulation of the trust level in the bluez backend logics. So can not only trust a particular device but can trust a particular service on a particular device and/or blackist specific services on devices. this should also be done if the software detects a connection try of another (interfering) service less then 3 secouns (or a more) befor...

thanks in advance and keep up the good work

**Comment by cschramm** [comment]
I do not really get the problem.

Version 1:
NM fails to connect to the NAP service of your phone.
blueman then connects to its audio service.

We'd need a protocol (see the troubleshooting page) if that's the case and I don't get why you think a fine grained trust system could help.

Version 2:
NM fails to connect to the NAP service of your phone.
The phone then connects to an audio service of your computer.

If you do *not* mark the device trusted you will get a dialog for that connection and can deny it.
