### ISSUE TITLE
Lubuntu - Bluetooth Pairing_OK - Connection_NOK

### ISSUE THREAD

**Issue by AH40833V** [blueman-project/blueman#953]
blueman:
[Bluetooth_issue - bluetoothd[1153].txt](https://github.com/blueman-project/blueman/files/2640237/Bluetooth_issue.-.bluetoothd.1153.txt)

BlueZ:
![screenshot at 2018-12-03 16-52-53](https://user-images.githubusercontent.com/45266711/49385733-63307600-f71e-11e8-8ede-353ee54cd725.png)

Distribution: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->
Pairing OK
Connection NOK

**Comment by infirit** [comment]
Most problems with a2dp are due to missing packages or some setup. See https://github.com/blueman-project/blueman/wiki/Troubleshooting#a2dp-audio-device-paired-but-fails-to-connect

If you still have problems see https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging and log your attempt to connect to the device.

**Comment by rohoog** [comment]
I think I experience the same issue (fc28-xfce4). This used to work fine, but not anymore probably after updates of bluez/pulseaudio. The BT device (speaker) appears connected, but it fails to be registered with and used by pulseaudio. I don't think it is a blueman issue, but I lack the knowledge of who-does-what-and-who-is-to-blame.

**Comment by rohoog** [comment]
Indeed, that selecting of the audio profile fails as well.

**Comment by michael3638** [comment]
NOT stale. Same issue, beefree os-perixx mouse

**Comment by cschramm** [comment]
Hi @michael3638, we need to see at least the logs as instructed on the troubleshooting page. Also your issue is most probably not the same as "os-perixx mouse" clearly doesn't sound like an audio device. :wink:

**Comment by infirit** [comment]
Michael, this issue is about an audio device not mouse. If you have
problems with a mouse open a new issue and provide the necessary
information as requested in the new issue template.
