### ISSUE TITLE
Blueman asking for user permisions after startup

### ISSUE THREAD

**Issue by rsm-gh** [blueman-project/blueman#959]
blueman: 2.0.6-1
BlueZ: 5.50-3
Distribution: Archlinux
Desktop environment: Xfce4

It makes some updates that after starting XFCE4 (startxfce4), when blueman starts I get the following two dialogs to ask for my permission:

(the first dialog is missing, I'll upload it as soon as possible)

![second_dialog](https://user-images.githubusercontent.com/11134652/49695399-ceed6580-fb9a-11e8-8098-0605a5b19182.png)

Is this something that was made on purpose? How can I set the permission once for all?

Thanks !

**Comment by cschramm** [comment]
#896 https://github.com/blueman-project/blueman/wiki/PolicyKit https://github.com/blueman-project/blueman/releases/tag/2.0.6 #912 #913

There's a 2.0.7 release coming up in #960 for you Arch folks. :slightly_smiling_face:
