### ISSUE TITLE
use nftables in blueman/main/NetConf.py

### ISSUE THREAD

**Issue by debianxfce** [blueman-project/blueman#968]
blueman: git
BlueZ: 5.50
Distribution: Debian Sid
Desktop environment: Xfce

iptables is dropped with dnsmasq and others. You need to convert rules to the nftables format.

**Comment by cschramm** [comment]
What do you mean with dropped? The iptables package is available as usual and will probably not go away in the next few years. Do you mean that it's not getting installed by default in some system configurations? Maintainers could simply add a dependency then. However, the `dnsmasq` package is never installed by default, so I don't really get your point. :thinking:

**Comment by infirit** [comment]
As I understand it its a backend change and packages do not need to make any changes.

Should we check if this change breaks blueman, for sure. Should we move over to using nftables directly, at some point yes, but not right now.
