### ISSUE TITLE
Off by default?

### ISSUE THREAD

**Issue by cw64** [blueman-project/blueman#984]
blueman: 2.0.5
BlueZ: ?
Distribution: ?
Desktop environment: ubuntu bionic 18.04.1 LTS

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Option to set bluetooth to be off by default would be nice. Rather than having to switch it off everytime I use the pc

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
Click plugins in the applet menu, open the settings of the PowerManager plugin and uncheck the respective option. (There's a ticket to promote that setting in #877.)
