### ISSUE TITLE
pactl load-module module-bluetooth-discover. Failure: Module initialisation failed

### ISSUE THREAD

**Issue by RomRomR** [blueman-project/blueman#986]
I have all the necessary software installed (blueman bluez pulseaudio). But bluetooth still wont seek any devices, from the forums i've been to, is probably because the bt discover module fails to start. 

output of pactl list modules | grep blue:

 	Name: module-bluetooth-policy
	module.description = "Policy module to make using bluetooth devices out-of-the-box easier"
 	Name: module-bluetooth-discover
 	Name: module-bluez5-discover

**Comment by infirit** [comment]
We ask for information like distro used, bluez version, logs etc when you open a new issue. We have good reasons for that :wink:.

Now, lets start with point out that the followinf link points to two very complete sources about bluetooth audio. https://github.com/blueman-project/blueman/wiki/Troubleshooting#a2dp-audio-device-paired-but-fails-to-connect

Next, blueman has no influence what pulseaudio does except we allow to change audio profile.

I am happy to help and after you read the two wiki pages we reference in the troubleshooting and you still run into problems make sure you provide at lease the log for blueman-applet as described in https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging. AND at the minimum your distro and version.
