### ISSUE TITLE
Mouse connected, but cursor doesn't move on Rapoo M100

### ISSUE THREAD

**Issue by vlad0337187** [blueman-project/blueman#994]
blueman: 2.0.5
BlueZ: 5.48.0
Distribution: Linux Mint 19.1
Desktop environment: Cinnamon

* [+] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Hello.
Bought a mouse, which has several connections ways - via Bluetooth or USB (radio channel).
It's Rapoo M100 Silent.

I connect it through Blueman or standard system Cinnamon's bluetooth applet - all works.
Reboot system - all works.

When mouse goes to power saving mode (disconnects), and after you press something on it - it connects again.
Mint's bluetooth applet shows it's connected again, mouse's indicator shows the same.
But cursor isn't moved, mouse doesn't work.
As for Blueman, it shows mouse as "unknown" when you connected it first time, mouse works well after this.
After mouse was disconnected and them  reconnected due to power saving - it still shows "Unknown"

Logs with descriptions: https://pastebin.com/5wAHFtU5

On Macbook Pro 2017 system it works as expected.

Not sure it's related to Blueman, but I decided to leave issue here anyway, it's an additional info.
Also will created issue on Mint bugtracker: https://github.com/linuxmint/blueberry/issues/74

If you'll need any additional info, or you'd like to test something - you can use my machine remotely.
Control laptop via TeamViewer and ask me to move\connect mouse via Telegram, for example.

Thank you.

<!--
ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.
->

**Comment by cschramm** [comment]
Definitely not a blueman issue, but let's see where we can get. When I do connect a bluetooth mouse `dmsg` looks like this:

```
hidraw: raw HID events driver (C) Jiri Kosina
Bluetooth: HIDP (Human Interface Emulation) ver 1.2
Bluetooth: HIDP socket layer initialized
hid-generic 0005:046D:B008.0001: unknown main item tag 0x0
input: Bluetooth Laser Travel Mouse Mouse as /devices/pci0000:00/0000:00:14.0/usb2/2-11/2-11:1.0/bluetooth/hci0/hci0:256/0005:046D:B008.0001/input/input22
hid-generic 0005:046D:B008.0001: input,hidraw0: BLUETOOTH HID v3.14 Mouse [Bluetooth Laser Travel Mouse] on e8:b1:fc:41:ad:0b
```

I then end up with a new mouse device (`/dev/input/mouse2` in my case) for which I see output if I `cat` it and move the mouse.

I'd check which of these parts differ in your case.

**Comment by infirit** [comment]
The only thing I can think of is that you do not have the UHID kernel driver enabled/loaded.
